### ISSUE TITLE
[feature]: Document existing environment variables

### ISSUE THREAD

**Issue by simonmicro** [makeplane/plane#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

While a minimalistic instruction set for self-hosting exist, it does not include what can be configured (where).

Yes, there exists the `.env.example`, but who knows what which variable expects... I do NOT expect a whole guide how to e.g. setup a Slack integration, but it would be useful to know what to put where to get it working.

### Why should this be worked on?

To allow simpler self-hosting and evaluation of this software before deployment into production.

_With the current setup I'm not sure, if I really want to self-host this software, nor if it is ready for production use. I've dived into the code to figure out what was going on, but (partially due to my limited knowledge of React) as an ops-guy (and a dev) the code is not documented in any way to allow inference of knowledge needed for proper configuration. In combination with the missing documentation, this is a huge problem!_

**Comment by pablohashescobar** [comment]
Hi @simonmicro, we have documented the usage of each variable in the .env.example file. This should provide clear instructions to help you understand the purpose of each variable. We are closing this issue now. However, if you encounter any further issues or have additional questions, please don't hesitate to reopen the issue. We'll be happy to assist you further. Thank you!
