### ISSUE TITLE
[bug]: docker-compose fails on server with aarch64 architecture

### ISSUE THREAD

**Issue by fabfischer** [makeplane/plane#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

is it possible to run/start plane on a arm64/aarch64 server? When I check out the repository and follow the instructions at https://docs.plane.so/self-hosting, I always get these error messages on my Hetzner CAX21 machine with Docker:

```
planefrontend   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
planefrontend   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
planefrontend   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
planefrontend   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
[...]
planefrontend   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
planefrontend   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
planefrontend   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
planefrontend exited with code 1
```

Server architecture:
```
uname -m
aarch64
```

When I tested it on my ARM64 Mac (M1) it worked without problems - so I assume it is possible to run plane with Docker on ARM machines?

Do you have any ideas what the issue could be?

### Steps to reproduce

1. execute `docker-compose -f docker-compose-hub.yml up` on a machine with aarch64 architecture

### Browser

Other

### Version

Self-hosted

**Comment by fabfischer** [comment]
Okay, I was able to built the images from the Dockerfiles within the repository. 
I will close this issue, because I could "fix" it myself :)

**Comment by mhetrich** [comment]
> Okay, I was able to built the images from the Dockerfiles within the repository. I will close this issue, because I could "fix" it myself :)

I have the same error, how did you fix it?

**Comment by mhetrich** [comment]
> 

Got it fixed myself by running:
# docker-compose -f docker-compose.yml up

Instead of running:
docker-compose -f docker-compose-hub.yml up

**Comment by viseshrp** [comment]
Thanks @mhetrich 
Also, that is basically just `docker compose up`
