### ISSUE TITLE
[bug]: Removing a user from a workspace does not remove them from the projects

### ISSUE THREAD

**Issue by dennisrahmen** [makeplane/plane#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I remove a user from my workspace the user is still listed in the individual projects.

### Steps to reproduce

1. Add user to workspace
2. Add user to project
3. Remove user from workspace
4. Look in to the projects members

### Browser

Google Chrome

### Version

Cloud

**Comment by pablohashescobar** [comment]
This is issue has been already fixed and promoted to master.
