### ISSUE TITLE
[bug]: Lists are not sorted

### ISSUE THREAD

**Issue by dennisrahmen** [makeplane/plane#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It appears that lists are not sorted, but rather the entries are displayed as they are listed in the database. Some List may also be sorted by the last update, which is not ideal in most cases.

I would expect that most lists are alphabetically sorted except in specific cases, for instance the last updated issues.

This is particular noticeable on the projects page as well as the navigation on the left with all the projects. Having my projects jumping around leads to me always needing to search for them rather than remembering that it is at the bottom or top of the navigation.

Sorting by last updated may be desirable in some cases/lists, so a sorting option could be added. For example, in the navigation on the same row as the "Project" or "Favorites" text a icon to change the sorting.

### Steps to reproduce

1. Create multiple projects
2. Update them
3. The project list in the navigation will be changing the order as well as the order on the project page

### Browser

Google Chrome

### Version

Cloud

**Comment by vihar** [comment]
Thanks @dennisrahmen, we'll pick this up soon.

**Comment by dennisrahmen** [comment]
This is also related to the Upcoming & Overdue Issues on the dashboard.
They should be sorted by due date.

**Comment by dakshesh14** [comment]
This issue will be fixed once https://github.com/makeplane/plane/pull/1122 is merged.

**Comment by rhea0110** [comment]
Hey @dennisrahmen, we are delighted to inform you that we have already fixed this issue, and it is now live on our website.

Thank you!
