### ISSUE TITLE
[bug]: Dropdowns cut of the text to early

### ISSUE THREAD

**Issue by dennisrahmen** [makeplane/plane#1078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The text in for example the module selection dropdown cuts of to early:
![Bildschirmfoto 2023-05-19 um 11 57 08](https://github.com/makeplane/plane/assets/61705878/2544db0f-e47c-4870-bd20-208543c425d6)

As well as the assigne only shows the first name, which is quite confusing at times:
![Bildschirmfoto 2023-05-19 um 11 56 57](https://github.com/makeplane/plane/assets/61705878/59b42e98-b527-4778-95a4-922be27b8080)

### Steps to reproduce

1. Add multiple members with the same first name
2. Try selecting a specific member from the assignee dropdown.

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @dennisrahmen, we have addressed your issue and made the necessary changes, which are available in this commit #1089. It will be soon available on our website with our latest release. 

Thanks.

**Comment by vihar** [comment]
The new UI looks something like this. 

<img width="341" alt="CleanShot 2023-05-21 at 19 14 43@2x" src="https://github.com/makeplane/plane/assets/16307796/76faa84b-73c4-4b83-8333-fe68c65b8a92">
