### ISSUE TITLE
Mobile menu missing on dashboard page

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The menu is currently missing on the dashboard on the mobile page. I have to switch to the desktop site, select a workspace and switch back to mobile to navigate.

### Steps to reproduce

1. Open plane on any mobile device

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by rhea0110** [comment]
Hey @Quadrubo, 

Thank you for bringing up this issue. We haven't implemented mobile responsiveness for some parts of Plane yet, but we have plans to address it soon. Additionally, we are currently developing a mobile app that will be launched in the near future. In the meantime, if there are any responsiveness-related bugs on the web app, we will prioritize fixing them.

**Comment by kblueberry** [comment]
Hey @Quadrubo, there is PR with fix fir that, link to PR:
https://github.com/makeplane/plane/pull/1374

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
