### ISSUE TITLE
[bug]: Default Credentials Do Not Work

### ISSUE THREAD

**Issue by Alcatraz077** [makeplane/plane#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is similar to Issue #719, but it has been closed. I've followed the quick start guide on the README for docker compose. However, the default credentials do not work. I pulled the current dev branch before creating this issue. 

This is a brand new VM, with current updates and Docker/Docker Compose installed:
OS: Ubuntu 22.04
Docker: 24.0.1
Docker Compose: 2.18.1

The error produced is "Oops! Enter the correct email and password to sign in". 

Network logs from the browser advise that "Response body is not available to scripts (Reason: CORS Failed)".

I'll happily provide any logs needed, please point in the right direction to generate/grab them. I've tried this within Firefox on multiple machines, I'll try Chrome as well and update this issue.

### Steps to reproduce

1. `git clone https://github.com/makeplane/plane`
2. cd into plane directory
3. `./setup.sh localhost `
4. `set -a`
5. `source .env`
6. `set +a`
7. `docker compose -f docker-compose-hub.yml up`
8. Attempt to login with `captain@plane.so` and `password123`
9. Receive the error "Oops! Enter the correct email and password to sign in".

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @Alcatraz077,
Can you please share logs for both frontend and backend container.

**Comment by Alcatraz077** [comment]
Sure, attached.

[plane-frontend.log](https://github.com/makeplane/plane/files/11525299/plane-frontend.log)
[plane-backend.log](https://github.com/makeplane/plane/files/11525300/plane-backend.log)

**Comment by pablohashescobar** [comment]
Hi @Alcatraz077,
Everything looks fine here may I if you are running this in a cloud VM or your own local machine.

**Comment by Alcatraz077** [comment]
I'm running this on a VM that's on my LAN, via esxi 6.7 as the hypervisor.

May 21, 2023 1:44:54 PM pablohashescobar ***@***.***>:

**Comment by pablohashescobar** [comment]
Oh can you provide the IP address of the VM to setup.sh `./setup.sh <VM_IP>` and then please try running the above steps once again.

**Comment by Alcatraz077** [comment]
That seems to have done it, thank you.

**Comment by Alcatraz077** [comment]
Still don't understand why FQDN or short name didn't work...

**Comment by pablohashescobar** [comment]
Hey @Alcatraz077 because localhost may not have resolved to correct IP.

closing this issue.
