### ISSUE TITLE
[bug]: Pressing "Enter" on the login page does not work

### ISSUE THREAD

**Issue by dennisrahmen** [makeplane/plane#1114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The "Enter" key does not trigger the "Send code" button.
Also, I am not sure if it works for the button when I already put in email and code.

Furthermore, the link in the Email just redirects me to the login page to type in my email again, I always have to copy the code over.

### Steps to reproduce

1. Open app.plane.so
2. Type in your email
3. Hit the "Enter" key on your keyboard
4. The email field will be cleared but nothing happens

### Browser

Google Chrome

### Version

Cloud

**Comment by vihar** [comment]
This issue will be fixed once #1121 is merged.

**Comment by rhea0110** [comment]
Hey @dennisrahmen, we are delighted to inform you that we have already fixed this issue, and it is now live on our website.

Thank you!
