### ISSUE TITLE
[bug]: Color of the "Analytics" icon does not match the others

### ISSUE THREAD

**Issue by dennisrahmen** [makeplane/plane#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/makeplane/plane/assets/61705878/5afd5f39-0626-4b8a-b933-5c0d8f8b3768)

### Steps to reproduce

👀

### Browser

Google Chrome

### Version

Cloud

**Comment by anmolsinghbhatia** [comment]
This issue will be fixed once #1120 is merged.

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
