### ISSUE TITLE
[bug]: The "My Issues" page does not save the view settings

### ISSUE THREAD

**Issue by dennisrahmen** [makeplane/plane#1116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I can add additinal information with the view option but does do not get saved.

### Steps to reproduce

1. Go to the "My Issues" page
2. Select other view settings than the default
3. Refresh the page

### Browser

Google Chrome

### Version

Cloud

**Comment by anmolsinghbhatia** [comment]
This issue will be fixed once #1124 is merged.

**Comment by rhea0110** [comment]
Hey @dennisrahmen, we are delighted to inform you that we have already fixed this issue, and it is now live on our website.

Thank you!
