### ISSUE TITLE
[feature]: My issues page, grouping, sorting

### ISSUE THREAD

**Issue by dennisrahmen** [makeplane/plane#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to group the Issues by for example state, project, project and module, ...
Sorting would also be great.

### Why should this be worked on?

To make the "My Issues" page more usable.

**Comment by hifnStudio** [comment]
@rhea0110 Is there any update on this? If not i would love to contribute for this.

**Comment by aaryan610** [comment]
@hifnStudio, we would love for your contribution on this, but this feature has some backend dependency which will be taken care of really soon and we plan to ship sorting and grouping for my issues in our upcoming release.

**Comment by aaryan610** [comment]
This feature has been shipped with our v0.10 release.

**Comment by hifnStudio** [comment]
Is their going to be a calendar view in my issue section?
