### ISSUE TITLE
[bug]: Navbar not responsive to mobile and unable to see toggle in homescreen

### ISSUE THREAD

**Issue by sheggamharshith** [makeplane/plane#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## There are 2 issues 
- Unable to see the toggle button for sidenav in the homescreen in mobile view
- ![image](https://github.com/makeplane/plane/assets/43858219/9a7aa734-0f22-4061-8f9b-95d107704f40)
- Project page is not responsive in the mobile view
- ![image](https://github.com/makeplane/plane/assets/43858219/410f574f-9f29-478e-b32b-3680ba589eab)

The project name in 

### Steps to reproduce

1) Go to home page in mobile. 
2) Go to projects page in mobile 

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @sheggamharshith,

Thank you for bringing up this issue. We haven't implemented mobile responsiveness for some parts of Plane yet, but we have plans to address it soon. Additionally, we are currently developing a mobile app that will be launched in the near future. In the meantime, if there are any responsiveness-related bugs on the web app, we will prioritize fixing them.

**Comment by aaryan610** [comment]
This issue has now been fixed and is live.
