### ISSUE TITLE
[bug]: SECRET_KEYs escaped creating unexpected EOF error

### ISSUE THREAD

**Issue by rpjohnson** [makeplane/plane#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After running the setup script, the SECRET_KEY that was generated ended in a backslash which escaped the final double quotes.

Rerunning the setup script, generates a new SECRET_KEY that is unlikely to end in a backslash again.

### Steps to reproduce

By randomness or by force, make `SECRET_KEY` end with a back slash

```
root@plane:~/plane# ./setup.sh 192.168.1.100

root@plane:~/plane# set -a
root@plane:~/plane# source .env
-bash: .env: line 23: unexpected EOF while looking for matching `"'
-bash: .env: line 24: syntax error: unexpected end of file

root@plane:~/plane# cat .env
# Replace with your instance Public IP
NEXT_PUBLIC_EXTRA_IMAGE_DOMAINS=
NEXT_PUBLIC_GOOGLE_CLIENTID=""
NEXT_PUBLIC_GITHUB_APP_NAME=""
NEXT_PUBLIC_GITHUB_ID=""
NEXT_PUBLIC_SENTRY_DSN=""
NEXT_PUBLIC_ENABLE_OAUTH=0
NEXT_PUBLIC_ENABLE_SENTRY=0
NEXT_PUBLIC_ENABLE_SESSION_RECORDER=0
NEXT_PUBLIC_TRACK_EVENTS=0
NEXT_PUBLIC_SLACK_CLIENT_ID=""
EMAIL_HOST=""
EMAIL_HOST_USER=""
EMAIL_HOST_PASSWORD=""
AWS_REGION=""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_S3_BUCKET_NAME=""
OPENAI_API_KEY=""
GPT_ENGINE=""
NEXT_PUBLIC_API_BASE_URL=http://192.168.1.100

SECRET_KEY="_O+EQR_h+N55hUYM7N?-dy7(=H+EkqLrhB0swb$y,:#EJbl)O\"
```

This can be fixed by running the setup script again.
```
root@plane:~/plane# ./setup.sh 192.168.1.100
root@plane:~/plane# set -a
root@plane:~/plane# source .env
root@plane:~/plane# set +a
root@plane:~/plane#
```

### Browser

Other

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hello @rpjohnson, could you kindly provide some additional information about the operating system you are currently using?

**Comment by pablohashescobar** [comment]
Thanks for reporting this updated the script to only generate hexadecimal values #1133
