### ISSUE TITLE
[feature]: change password 

### ISSUE THREAD

**Issue by require-dev** [makeplane/plane#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add ability for users to change their password from their profile

### Why should this be worked on?

Feature required for security and for locking down the default user account, as currently there is no "global" user management available.

**Comment by markskram** [comment]
+1 this is the first thing I wanted to do after logging in.

Here are ideas for it:
- Essential: Allow any user to change their password from the Profile screen
- Strong Nice to have: Require the default user "captain@plane.so" to change the password immediately after logging in. Don't want to leave the default password in there.
- Would be Neat: Generate a unique default password to avoid insecure default password being available publicly. (Similar to how WordPress generates a unique password during setup.)

**Comment by markskram** [comment]
Related to https://github.com/makeplane/plane/issues/1131

**Comment by Pdzly** [comment]
> +1 this is the first thing I wanted to do after logging in.
> 
> Here are ideas for it:
> 
>     * Essential: Allow any user to change their password from the Profile screen
> 
>     * Strong Nice to have: Require the default user "[captain@plane.so](mailto:captain@plane.so)" to change the password immediately after logging in. Don't want to leave the default password in there.
> 
>     * Would be Neat: Generate a unique default password to avoid insecure default password being available publicly. (Similar to how WordPress generates a unique password during setup.)

I would rather just dont have a default user. Because everyone can immediatly sign up.

**Comment by Pdzly** [comment]
To help for the first time setup i created this https://github.com/makeplane/plane/issues/1195

**Comment by rhea0110** [comment]
Hey @require-dev, thank you for your valuable suggestion. We have already planned to implement it soon, and we will keep you updated on the progress.

Thank you!

**Comment by vihar** [comment]
Sorry for the late follow-up on this. We’ve shipped an option to change the password on self-hosted instances under Profile > Preferences > Security.

![CleanShot 2024-07-01 at 16 27 51@2x](https://github.com/makeplane/plane/assets/16307796/3628f439-20bb-4cac-a49c-6b0f98177a7e)
