### ISSUE TITLE
[feature]: disable signup

### ISSUE THREAD

**Issue by require-dev** [makeplane/plane#1139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As an administrator of a self-hosted instance I want the ability to disable sign-up by everyone

### Why should this be worked on?

I don't want everyone to be able to sign-up and create a workspace and use my self-hosting instance resources.

**Comment by Pdzly** [comment]
I could imagine to make it 3 ways:
- Public 
- Invite Only ( Only with invite permissions )
- Private/Closed ( No one can join or be invited )

**Comment by require-dev** [comment]
Closing this in favor of #779 (duplicate)
