### ISSUE TITLE
[bug]: Invitiation email appending http:// to https:// url

### ISSUE THREAD

**Issue by coltondick** [makeplane/plane#1161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I invite new users to my plane instance the invitation url is malformed.

```http://https//plane.example.com/workspace-member-invitation/f420e4d4-4bae-4e1c-aab1-933b82b1f6d6?email=user@example.com```

### Steps to reproduce

```
curl https://raw.githubusercontent.com/makeplane/plane/develop/docker-compose-hub.yml --output docker-compose.yml
curl https://raw.githubusercontent.com/makeplane/plane/develop/setup.sh --output setup.sh
chmod +x setup.sh
./setup.sh https://plane.example.com
set -a
source .env
set +a
docker compose up -d
```

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by roopeshsn** [comment]
H, @coltondick! I would like to work on this!

**Comment by 153957** [comment]
From the example url it seems `:` is missing in the original url schema:
```
http://https//plane.example.com/workspace-…
           ^^       
```

**Comment by eugen-korentsov** [comment]
Same issue with http. ':' is missing. URL in email is http//plane.example.com

**Comment by pablohashescobar** [comment]
Hello @coltondick! We're glad to inform you that the issue you reported has been resolved in the latest Docker setup update. If you encounter any further difficulties or if the problem persists, please don't hesitate to reopen the issue.
