### ISSUE TITLE
[bug]: Quick Start

### ISSUE THREAD

**Issue by PierreSnell** [makeplane/plane#1168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Reading the documentation and readme, I couldn't get plane to start following the docs (and trying stuff on my own too). 

Docker composing everything works fine and the sign in page appears but the credential for a local setup doesn't seem to work (`captain@plane.so` & `password123`). 

![image](https://github.com/makeplane/plane/assets/116119917/7acf6100-d82b-4363-a514-29520e98b91d)

I checked the `.env` and `.env.example` and it's the correct values. 

```
NEXT_PUBLIC_EXTRA_IMAGE_DOMAINS=
NEXT_PUBLIC_GOOGLE_CLIENTID=""
NEXT_PUBLIC_GITHUB_ID=""
NEXT_PUBLIC_GITHUB_APP_NAME=""
NEXT_PUBLIC_SENTRY_DSN=""
NEXT_PUBLIC_ENABLE_OAUTH=0
NEXT_PUBLIC_ENABLE_SENTRY=0
NEXT_PUBLIC_ENABLE_SESSION_RECORDER=0
NEXT_PUBLIC_TRACK_EVENTS=0
NEXT_PUBLIC_SLACK_CLIENT_ID=""
PGUSER="plane"
PGPASSWORD="plane"
PGHOST="plane-db"
PGDATABASE="plane"
EMAIL_HOST="captain@plane.so" # This was empty I tried to add it
EMAIL_HOST_USER="captain" # This was empty I tried to add it
EMAIL_HOST_PASSWORD="password123" # This was empty I tried to add it
EMAIL_PORT=587
EMAIL_FROM="Team Plane <team@mailer.plane.so>"
AWS_REGION=""
AWS_ACCESS_KEY_ID="access-key"
AWS_SECRET_ACCESS_KEY="secret-key"
AWS_S3_BUCKET_NAME="uploads"
FILE_SIZE_LIMIT=5242880
OPENAI_API_KEY=""
GPT_ENGINE=""
GITHUB_CLIENT_SECRET="" # For fetching release notes
DOCKERIZED=1
NGINX_PORT=80
DEFAULT_EMAIL="captain@plane.so"
DEFAULT_PASSWORD="password123"
NEXT_PUBLIC_API_BASE_URL=http://localhost
SECRET_KEY="A long key"
WEB_URL=http://localhost
```

### Why should this be worked on?

To have more users easily try locally this promising solution.

**Comment by Pdzly** [comment]
Isnt this a bug? Not a feature?

**Comment by OvermindDL1** [comment]
Same issue here, unable to login with default email/password.  I have tried changing it to a variety of other things (clearing the volumes as well of course so it fully rebuilds) to no avail.

**Comment by shadowjig** [comment]
I downloaded the latest code today and run all commands in the self hosting documentation and I get the same error when trying to login.  I'm using the latest docker images and the default email and password that's listed in the .env file (which is also the same one listed in the documentation).  I would really like to get this up and running locally to check it out.

**Comment by keremdev** [comment]
If you are installing on the server, you should write ./setup.sh http://<ip-address>.

**Comment by simon-lewis** [comment]
> If you are installing on the server, you should write ./setup.sh http://<ip_address>.
> 
> Access URL: http://<ip_address>:3000

Same problem for me. Ran setup.sh for both domain and IP address. Cannot login with captain@plane.so @ domain, IP address or ipaddress:3000 (I get to the /signin form but entering the default credentials get the prompt "Oops! Enter the correct ....")

**Comment by danielslyman** [comment]
Same here

**Comment by BrettMerrick** [comment]
Check you have nothing else listening on port 8000.
I had another container running on port 8000. Stopping that allowed Plane to use it for it's API and then I could sign in.

**Comment by shadowjig** [comment]
> 

The only thing the setup.sh file does is make a copy of the env.example file and renames it to .env.  It then adds a few variables with their values (based on what you passed in the script as an argument) to the end of the .env file.  It also appears to export the variables, which appears to be for MACs.  Either way the script it unnecessary for a majority of users and could easily be accomplished in a well documented .env file and remove the need for a script.

**Comment by shadowjig** [comment]
> I checked. Still the same issue. I ran both compose files. I will try again on a completely fresh install. May I ask what the point of the .sh files are. It would be way easier and streamlined with other projects if it were just a compose and env file.

The only thing the setup.sh file does is make a copy of the env.example file and renames it to .env. It then adds a few variables with their values (based on what you passed in the script as an argument) to the end of the .env file. It also appears to export the variables, which appears to be for MACs. Either way the script it unnecessary for a majority of users and could easily be accomplished in a well documented .env file and remove the need for a script.

**Comment by pablohashescobar** [comment]
Hi! If you are still experiencing issues with logging in, I want to let you know that we have fixed the bug. You should now be able to log in effortlessly. However, if you are still encountering any problems, please don't hesitate to join our Discord server. You can open a thread there, and we will be more than happy to assist you.
