### ISSUE TITLE
[feature]: All issues view (cross-project views)

### ISSUE THREAD

**Issue by pixelspark** [makeplane/plane#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently Plane has advanced views functionality _within_ projects, as well as a view for 'my issues' across projects. It would be most useful to also have a view of 'all issues in all projects' (visible to me) regardless of being assigned to an issue.

Even better would be to have 'global view' functionality  (i.e. the ability to make global views that show data from multiple projects and save these per-user or globally). 

### Why should this be worked on?

* This is useful for our team to be able to do planning and to manage dependencies across projects
* I suspect this is fairly easy to make because it would basically be the 'my issues' view with a filter removed.
* It fits the Plane philosophy of 'various useful views on the same data' perfectly.

**Comment by rhea0110** [comment]
Hey @pixelspark, thank you for raising the feature request. Our team will brainstorm around it, and we will keep you updated on any developments.

Thanks!

**Comment by mstindia-com** [comment]
Hi @rhea0110, 
A global view will help a lot. Currently, we need to switch between projects to see what's in progress and who is working on what. 
Thanks!

**Comment by sakyork** [comment]
I came here to submit a feature request for the same. Having global views is a MUST for my org if we use Plane. We use Kanban boards and dashboards to maintain saved filters (views) across all projects in Jira. For example, a dashboard where we can see all `alpha` and `beta` bugs filed. Among many others.

**Comment by moshtaghmaveddat** [comment]
I really need this feature and I've been using it in Linear as well.

as a Team lead, I need to have an overview of all the tasks in one place from different perspectives.

Some use cases:

1.
View type: column ---- Group by: Project ---- Sort by: Priority
So I can see the most important tasks of each project.

2.
View type: Gantt
So I can see the overall workload on the team.

3.
View type: column ---- Group by: Assignee ---- Sort by: Priority ---- Filters: some assignees
So I can Track a specific number of team members and their activities.

4.
View type: Calendar ---- Filters: a label or custom field (like release dates or presentation meeting)
So I can track a specific type of event on the calendar which is important to me in all the projects.

**Comment by rhea0110** [comment]
Hey @pixelspark! We have shipped the global views with our latest release, v0.13-dev. Stay tuned for more updates.

**Comment by rhea0110** [comment]
> Hi @rhea0110, A global view will help a lot. Currently, we need to switch between projects to see what's in progress and who is working on what. Thanks!

Hello @mstindia-com! We have shipped the global views with our latest release, v0.13-dev. Stay tuned for more updates.

**Comment by descovi** [comment]
Hello, apologies for reopening this issue. I appreciate the improvements to the "All Issues Panel," but to plan my team's work more effectively, I would like to have a calendar and/or gant view. This would allow me to organize work across projects in a more linear manner. I dont know if it is possible. Thanks in advance

**Comment by mstindia-com** [comment]
Hi @rhea0110 , thanks a lot.
