### ISSUE TITLE
[feature]: translation

### ISSUE THREAD

**Issue by restray** [makeplane/plane#1175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Let the user choose the language they speak fluently.

### Why should this be worked on?

As a project-management app based, this should be a basic feature. It lets the user understand quickly what he sees, and goes faster to the end of what he wants.

This should allows **translators** to easily translate the apps (with `.po` for the back-end notifications and i18n JSON *maybe?* for the front-end).
This shouldn't slow down the developer, they should type in English, then the translators should translates entire sentences.

**Comment by rhea0110** [comment]
Hey @restray, thank you for raising the feature request. Our team will brainstorm around it, and we will keep you updated on any developments.

Thanks!

**Comment by redzumi** [comment]
@rhea0110 hi Rhea! Any news about translation? :)

**Comment by rhea0110** [comment]
Hey @redzumi, just wanted to update you on the progress. As mentioned earlier, our team has been actively brainstorming and will soon begin working on it. Currently, our team is focused on developing features such as inbox, spreadsheets view, timers, and more. We truly appreciate your patience, and we will keep you informed of any updates as we move forward. Thanks again for your understanding!

**Comment by redzumi** [comment]
@rhea0110 Thats awesome! Thank you for keeping me up to date and also for this great project!

**Comment by landonzeng** [comment]
I'm looking at this feature too

**Comment by vihar** [comment]
Thank you to everyone involved in this discussion. We will be addressing this issue shortly. To facilitate smoother communication, we're moving this conversation to the main thread. Please refer, https://github.com/makeplane/plane/issues/2028. 🙏🏻
