### ISSUE TITLE
[feature]: One-click deployment via Railway

### ISSUE THREAD

**Issue by AprilNEA** [makeplane/plane#1177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

One-click deployment support via SaaS platforms such as Railway

It provides all environments including Postgresql Redis, but this may require modifying the dockerfile.

### Why should this be worked on?

This will allow users to quickly deploy an instance, which will help drive the rapid development of the project. 

At the same time, the amount of SaaS elasticity will facilitate cost savings.

Also, any updates can be captured and automatically deployed by the SaaS platform, avoiding the hassle of manual updates.

**Comment by Pdzly** [comment]
Could you make a example deployment  template of plane?

**Comment by Pdzly** [comment]
This similar to https://github.com/makeplane/plane/issues/966

**Comment by rhea0110** [comment]
Hey @AprilNEA, we sincerely appreciate and value your suggestion. Thank you for submitting the feature request. Our team will brainstorm around it, and we will keep you updated on any progress made.

Thanks!

**Comment by vihar** [comment]
One of our community members created a template to deploy Plane on Railway. Sharing the link here: https://railway.app/template/MrCqPF. Shoutout to [Vincenzo Fehring](https://railway.app/u/vin) for doing this. 🎉
