### ISSUE TITLE
[bug]: No image visable after upload

### ISSUE THREAD

**Issue by mainshooter** [makeplane/plane#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When uploading a image using the default setup according to the docs there is no image visable after uploading.

### Steps to reproduce

1. Go to profile
2. Upload avatar image
3. Refresh the page

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Unyxos** [comment]
can reproduce, when checking the network tab, it tries to load using `url` parameter.

Example on my self hosted instance when trying to load my avatar : 
`https://plane.domain.tld/_next/image?url=https%3A%2F%2Fplane.domain.tld%2Fuploads%2Fuser-cfe162aaa60540f8b45b833d87a3f89e-g6uLytzf_400x400.jpg&w=256&q=75`

is failing with HTTP 400 and reason : `"url" parameter is not allowed`

Trying to access directly through https://plane.domain.tld/uploads/user-cfe162aaa60540f8b45b833d87a3f89e-g6uLytzf_400x400.jpg` works perfectly fine

**Comment by pablohashescobar** [comment]
Hello! Thank you for bringing this issue to our attention. I want to assure you that our team is already hard at work addressing it. You'll be glad to know that we have made significant progress, and we anticipate resolving this problem in the upcoming release. We appreciate your patience and understanding as we work to provide a fix.

**Comment by parekhsandip** [comment]
I experienced similar issue on the cloud version where I pasted an image in the issue description but image was niether visible after paste nor uploaded.

**Comment by thanhquang1988** [comment]
Hotfix: 
ssh to docker container by use 

docker exec -it planefrontend sh

Try edit server.js file and add your image domain to config

vi apps/app/server.js

Then restart planefrontend container

**Comment by pablohashescobar** [comment]
Hello! we have made significant updates to the Docker setup, and as a result, we have successfully fixed the bug you reported. We appreciate your patience and understanding throughout this process. Should you encounter any further issues or have any additional feedback, please don't hesitate to let us know by reopening this issue. We're here to assist you further. Thank you for your support!
