### ISSUE TITLE
[bug]: unable to change workspace member role from guest to admin (once user created) 

### ISSUE THREAD

**Issue by rogerrustad** [makeplane/plane#1188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you add a user as a guest viewer to a workspace, you cannot later go and change that user to admin. 

### Steps to reproduce

1. create user on workspace with viewer access
2. try to change viewer role to admin role
3. get error (see below for debug output from Chrome developer tools) 

e.g.

_app-db6675eff8851c2e.js:7
PATCH https://api.plane.so/api/workspaces/firedrill/members/d076cce1-f801-48b6-b8b0-3edc88604694/ 400

### Browser

Google Chrome

### Version

Cloud

**Comment by pablohashescobar** [comment]
Created a PR to fix this #1203
