### ISSUE TITLE
[bug]: Every new user create new workspace

### ISSUE THREAD

**Issue by reski-rukmantiyo** [makeplane/plane#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using following command, username and password always correct.
I follow docs on how to create [self hosted plane](https://docs.plane.so/self-hosting)
```
git clone -b master https://github.com/makeplane/plane && cd plane
./setup.sh http://192.168.10.10
set -a; source .env; set +a;
docker-compose -f docker-compose-hub.yml up
```
Is this correct? or something that i miss?

```
# Frontend
# Extra image domains that need to be added for Next Image
NEXT_PUBLIC_EXTRA_IMAGE_DOMAINS=
# Google Client ID for Google OAuth
NEXT_PUBLIC_GOOGLE_CLIENTID=""
# Github ID for Github OAuth
NEXT_PUBLIC_GITHUB_ID=""
# Github App Name for GitHub Integration
NEXT_PUBLIC_GITHUB_APP_NAME=""
# Sentry DSN for error monitoring
NEXT_PUBLIC_SENTRY_DSN=""
# Enable/Disable OAUTH - default 0 for selfhosted instance
NEXT_PUBLIC_ENABLE_OAUTH=0
# Enable/Disable sentry
NEXT_PUBLIC_ENABLE_SENTRY=0
# Enable/Disable session recording
NEXT_PUBLIC_ENABLE_SESSION_RECORDER=0
# Enable/Disable event tracking
NEXT_PUBLIC_TRACK_EVENTS=0
# Slack for Slack Integration
NEXT_PUBLIC_SLACK_CLIENT_ID=""

# Backend

# Database Settings
PGUSER="plane"
PGPASSWORD="plane"
PGHOST="plane-db"
PGDATABASE="plane"

# Email Settings
EMAIL_HOST=""
EMAIL_HOST_USER=""
EMAIL_HOST_PASSWORD=""
EMAIL_PORT=587
EMAIL_FROM="Team Plane <team@mailer.plane.so>"

# AWS Settings
AWS_REGION=""
AWS_ACCESS_KEY_ID="access-key"
AWS_SECRET_ACCESS_KEY="secret-key"
# Changing this requires change in the nginx.conf for uploads if using minio setup
AWS_S3_BUCKET_NAME="uploads"
# Maximum file upload limit
FILE_SIZE_LIMIT=5242880

# GPT settings
OPENAI_API_KEY=""
GPT_ENGINE=""

# Github
GITHUB_CLIENT_SECRET="" # For fetching release notes

# Settings related to Docker
DOCKERIZED=1

# Nginx Configuration
NGINX_PORT=80

# Default Creds
DEFAULT_EMAIL="captain@plane.so"
DEFAULT_PASSWORD="password123"

# Auto generated and Required that will be generated from setup.sh
NEXT_PUBLIC_API_BASE_URL=http://192.168.10.10
SECRET_KEY="6wxbp8ph2op2qm7t3f03ou8f8nim3win17h21vxv46ooxcumxx"
WEB_URL=http://192.168.10.10
```

### Steps to reproduce

1. Create deployment based on  [self hosted plane](https://docs.plane.so/self-hosting)
2. Login successful deployment with web browser in http://192.168.10.10
3. Every login successful and able to create new workspace

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Pdzly** [comment]
Just to clarify: Everyone can login into user "test" with any password or what do you mean? 

If you mean that everyone can create a Account and create workspaces, this is the currently normal behaviour!

**Comment by reski-rukmantiyo** [comment]
Hi @Pdzly not only test, but asdsadas@asdsa.com with password asdsadsadsa can enter as well.
If this is normal behaviour, why in the docs, should access with captain@plane.so username?

**Comment by Pdzly** [comment]
Its weirdly documented because there is NO usermanagement. you cant even kick people out of this site. or only have it invite only.

**Comment by require-dev** [comment]
#1139 
I think this is relevant

**Comment by reski-rukmantiyo** [comment]
Yes @require-dev just realize that. I thought it was a bug.
