### ISSUE TITLE
Please revert #1189

### ISSUE THREAD

**Issue by Igorgro** [makeplane/plane#1192]
Please revert #1189. `docker-compose` is an older Python compose implementation which is deprecated in flavour of new V2 compose whiuch is implemented in Go and available as docker cli plugin (via `docker compose`).

Source: https://docs.docker.com/compose/migrate/

cc @pablohashescobar

**Comment by pablohashescobar** [comment]
Hi @Igorgro, thank you for the reference. I appreciate it and will take the necessary steps accordingly.

**Comment by pablohashescobar** [comment]
Created a PR #1193

**Comment by pablohashescobar** [comment]
Closing this issue.
