### ISSUE TITLE
[feature]: First Setup "Tutorial"

### ISSUE THREAD

**Issue by Pdzly** [makeplane/plane#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would recommend to have a setup view for the first time visit of the page where the administrator can set some settings ( for example email server, first admin user, set up "About" data and much more

### Why should this be worked on?

This could help on improving the first setup time for a administrator.

**Comment by markskram** [comment]
This is a good option to handle the "First Run" password issue. The main #1138 issue still needs to be handled, which allows any user to change their own password.

**Comment by rhea0110** [comment]
Hey @Pdzly, thank you for raising the feature request. Our team will brainstorm around it, and we will keep you updated on any developments.

Thanks!
