### ISSUE TITLE
[bug]: Self host docker-compose - fresh install - containers not able to connect to each other

### ISSUE THREAD

**Issue by me-abhishekpal** [makeplane/plane#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It is not working on a fresh install too. Not able to change any ports.
It does not connect with either planebackend, planerqworker.

Stuck here

![image](https://github.com/makeplane/plane/assets/2958671/f0be4b79-e589-4fb0-ad02-a8741df3c075)

Please help !

### Steps to reproduce

1. Deploy the self hosted as vanilla via **docker-compose-hub.yml**

### Browser

Google Chrome

### Version

Self-hosted

**Comment by me-abhishekpal** [comment]
No matter what, it does not work with **docker-compose.yml** as well.

**Comment by pablohashescobar** [comment]
Hello, @me-abhishekpal! Could you kindly provide me with the specific branch you're using?

**Comment by pablohashescobar** [comment]
Hello, @me-abhishekpal! you can modify the host port in nginx. Additionally, I suggest removing all port mappings from other containers if its causing errors with your internal system and executing the command `./setup.sh IP:PORT` in the master branch. Before running the setup, it's advisable to delete all container volumes. If you encounter any further difficulties, please don't hesitate to leave a comment or join our Discord community for immediate assistance.

**Comment by me-abhishekpal** [comment]
I did install it on a brand new server bought a couple of days ago, on which only OS and docker was installed prior to plane. So, It can be assured, there is no internal networking mishap happening here. 

I have tried so wiping and reinstalling so many times that it is on the verge of leaving it alone.

I will get back after trying this specific thing !

**Comment by me-abhishekpal** [comment]
Hello again @pablohashescobar 

So, I managed to install and get it running inside my local environment and I have used cloudflare to reverse proxy to a web url for the frontend only. 

Now, there is another issue that I am facing, I checked all the configurations, I do not have localhost anywhere in my setup. 

I have replaced the backend and frontend public URLs from Cloudflare to all of my containers. My backend is running fine the public URL, the frontend is also working fine on the public URL. 

However, the frontend sign in page is hell-bent on going to localhost or internal ip of the server, which I do not have in the container configurations anywhere. 

I have sanitized, shut down the whole stack and brought it back again, but it does not seem to budge.

Need help !

![image](https://github.com/makeplane/plane/assets/2958671/dc35ee74-fca1-414d-bab9-8922f1846906)

**Comment by pablohashescobar** [comment]
Hi @me-abhishekpal just to check are you using `develop` branch or the `master` branch. Also can you please share the logs of both frontend and backend containers.

**Comment by me-abhishekpal** [comment]
I'm using the master **branch**.

I can share the logs, what level logs would you like to have ?

**Comment by pablohashescobar** [comment]
Hi @me-abhishekpal, just the container logs `docker logs [OPTIONS] CONTAINER`

**Comment by me-abhishekpal** [comment]
Hi @pablohashescobar 

The logs were not getting generated as the request was never going to the desired URL. 

Although, I did try debugging, I thoght of starting it over again. 

It works now over cloudflare well, so I am closing this one. 

Thanks for the help and patience. 

I would love to test more as and when required and would posting more bugs or requirenments if needed.

Thanks again !
