### ISSUE TITLE
[bug]: Sign-in toast error when using valid credentials

### ISSUE THREAD

**Issue by Unyxos** [makeplane/plane#1204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When logging in with a valid account created earlier, the UI will still show the sign-in error toast then redirect to workspace a few seconds after

I noticed that at the same time, in the developer console, I have this error : 
```
TypeError: n is not a function
    at index-419658828f00ae69.js:1:8214
```

Indeed, the sign-in request response with http 200

### Steps to reproduce

1. Go to login page
2. Login using valid credentials for an existing account
3. Error toast will show
4. You'll be redirected as you should

### Browser

Google Chrome

### Version

Self-hosted

**Comment by me-abhishekpal** [comment]
Hey @Unyxos 

Can you check in your install is it going to localhost:8000 for api ?

![image](https://github.com/makeplane/plane/assets/2958671/8f265278-164e-4173-9685-33a929c092d8)

Do you have it over any external proxy such as cloudflare?

**Comment by pablohashescobar** [comment]
Hi @Unyxos, I wanted to inform you that we have successfully resolved the issue you reported. The fix has been implemented in our develop branch, and we will be updating the DockerHub builds with the latest changes shortly. Thank you for bringing this to our attention!

**Comment by Unyxos** [comment]
Hey, thanks a lot @pablohashescobar ! :D 

@me-abhishekpal Hey! On my side I configured Plane on a public url so the request is sent to https://plane.domain.tld, I have a nginx reverse proxy in front of the plane docker compose stack that's forwarding everything to Plane's nginx and it's working fine :)

**Comment by Unyxos** [comment]
Not having the issue anymore! Closing :)
