### ISSUE TITLE
[Question] What will be paid? What will be free? etc.....

### ISSUE THREAD

**Issue by Pdzly** [makeplane/plane#1211]
I have seen this question comes up many times in the discord and on github. Because of it i want to make this issue to keep track of what would you want as a perspective of:

* Collaborator
* End-User
and
* Self Hosted
* Cloud

You can elaborate here over what you think?

The current plan would be already here: https://plane.so/pricing

The license is irritating for some when some features are going to be paid only.

**Comment by vihar** [comment]
Hello, @Pdzly! It's still too early for us to provide specific pricing details at the moment. We're actively engaging with the community and gathering feedback to ensure we create the best pricing structure. However, here's a glimpse of what we have so far:

- Our cloud plan will offer free access for up to 1000 issues per user.
- As for the enterprise plan, there won't be any limitations on the number of issues or members. We are also planning to include SSO/SAML on the free tier. However, we're planning to introduce additional enterprise features that will involve pricing. These features include Plane AI, Custom Theming, Granular Access Control, and limitations on integrations (up to two or three, for instance).

Happy to hear the community feedback :)

**Comment by TheDevMinerTV** [comment]
I hope all "Plane Pro" features will be free for the dockerized install because it's honestly a PITA to manage the infrastructure yourself, so the cloudhosting will still benefit from this plan, I think.

**Comment by ccrvlh** [comment]
That's one of the reasons we didn't even spend time with Linear - the restriction based on the number of issue. It basically becomes a trial in disguise. ClickUp had the same logic (tiers based on the number of items), and even as a paid user I found that out the hard way and deleted my account right away. I do hope this goes into the direction of having enterprise-like features as paid (access control, AI, SSO, SAML, etc) rather than actually just having the product only have a trial.

**Comment by vihar** [comment]
Please find details of our Plans on our [pricing page](https://plane.so/pricing).

**Comment by fuzzy76** [comment]
It looks like either a feature is there or not there in a plan, and the only limit now is number of users. That a clear and fair separation between plans. Good, now I'm definitely adding this to my "do a thorough examination for possible use"-list!

**Comment by YelamanKarassay** [comment]
But why if you do self hosting, you still have to pay for the users exceeding 12?

**Comment by fuzzy76** [comment]
You are paying for access to the premium features, as they have been developed for the paid product.

**Comment by steveepreston** [comment]
Can please clearly say about `Community Edition` seats limit?
is there any limits about number of users can signup?
is there any limits about number of users can join a workspace? 
is there any limits about number of users can join a project?
