### ISSUE TITLE
[bug]: yarn install fails on arm docker build

### ISSUE THREAD

**Issue by tajkirkpatrick** [makeplane/plane#1213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I attempt to run the `docker-compose -f docker-compose.yml up` on a arm architecture machine. The plane-web installer step fails at the yarn install. I receive the error logs below:

![image](https://github.com/makeplane/plane/assets/50558516/a60a8f8a-54d5-49bd-b499-9a992102c239)

What I expect is that the docker build process would be able to connect to the url hosting the images .tgz file from registry.yarnpkg.com

### Steps to reproduce

1. Clone the develop branch of the repository with `git clone --depth 1 -b develop https://github.com/makeplane/plane`
2. run `./setup.sh https://<subdomain>.<domain>.xyz`
3. Manually edit the NGINX port in the .env file using `vim .env`
4. Run `docker-compose -f docker-compose.yml up`
5. Observe the error message above.

### Browser

Other

### Version

Self-hosted

**Comment by tajkirkpatrick** [comment]
I'm sure it is also helpful to know that this build issue is not a  encountered on arm when using the master branch's version of the docker-compose.yml file.

**Comment by pablohashescobar** [comment]
Hello @tajkirkpatrick! We wanted to let you know that we have made updates to the Docker setup. Could you please give it another try? We have carefully reviewed the issue you reported, but unfortunately, we were unable to reproduce it on our end. We value your feedback and would greatly appreciate it if you could test it again and let us know if the issue persists. If you need any assistance or have any further questions, please comment here or jump on to our discord. Thank you for your patience and cooperation!

**Comment by tajkirkpatrick** [comment]
Thanks for taking the time to look into my issue @pablohashescobar! On first attempt of pulling the latest develop branch commit I continued to run into the same error.  I am working on getting a proper screen recording for you to possibly see where and how I am possibly running into this issue. In this comment I will give you more specific system information due to me making an assumption that all raspberry pi environments would be the same.

System information:
`uname -a` returns:
`Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux` which very clearly is not arm64 but aarch64, slightly similar but different nonetheless.

`docker -v` returns:
`Docker version 23.0.6, build ef23cbc`

`docker buildx version` returns:
`github.com/docker/buildx v0.10.4 c513d34049e499c53468deac6c4267ee72948f02`

Once again I will work on making a screen recording available which hopefully provides some insight into my issue. I am still pulling the latest develop branch commits while also deleting old images and volumes, and running
`docker-compose -f docker-compose.yml up --build --force-recreate`
