### ISSUE TITLE
[bug]: Gantt view is not correctly aligned. All the issues/Task is aligned on the Created date instead of Start Date/End Date

### ISSUE THREAD

**Issue by surrey81** [makeplane/plane#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

All the issues/Task in the Grantt view is aligned on the Created date instead of Start Date/End Date

### Steps to reproduce

Projects ==> Issues ==> Click on the Grantt view option

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @surrey81, thank you for reporting this issue. We would like to inform you that we have already made improvements to enhance the Gantt view experience. These changes have been incorporated in Pull Request #1112 by one of our engineers. We are currently working on further enhancements and implementing them. We will keep you updated on our progress.

Stay tuned, and thank you!

**Comment by hifnStudio** [comment]
@rhea0110 can you please tell in which release it will be fixed

**Comment by rhea0110** [comment]
Hey @surrey81, we appreciate your inquiry. We are pleased to inform you that our engineers are actively working on stabilizing the Gantt chart feature, and we have planned to ship it with our next release, version 0.9, in a couple of weeks. We will notify you as soon as the release is available. In the meantime, please stay tuned with us!

Thank you.
