### ISSUE TITLE
[bug]: Text falling out of the onboarding card

### ISSUE THREAD

**Issue by Tooluloope** [makeplane/plane#1219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I SEE AN ERROR when I create a workspace, as attached below.

![Screenshot 2023-06-06 at 12 11 53](https://github.com/makeplane/plane/assets/31691737/63cf33ee-6b39-4aaf-8c16-312ebf720dbe)

The error should stay in the Onboarding card.

### Steps to reproduce

1. Go to onboarding
2. On the New Workspace tab
3. Click Create workspace without filling in any input
4. observe the error and part of the form falling out of the card

### Browser

Google Chrome

### Version

Local

**Comment by Tooluloope** [comment]
I'll like to fix this if possible.

**Comment by rhea0110** [comment]
Hey @Tooluloope, thank you for reporting this bug. We are pleased to inform you that one of our engineers has already fixed this issue and raised Pull Request #1225 for it. We will review and merge the code soon onto the develop branch, and it will go live on our website with our latest release.

Thanks!

**Comment by rhea0110** [comment]
Hey @Tooluloope, we're delighted to inform you that we have successfully resolved the bug you reported. It is now live on our website. Thank you for your patience.
