### ISSUE TITLE
[bug]: docker compose hub doesn't work out of the box

### ISSUE THREAD

**Issue by zub0r** [makeplane/plane#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Error response from daemon: pull access denied for makeplane/plane-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### Steps to reproduce

docker compose -f docker-compose-hub.yml up

### Browser

Google Chrome

### Version

Self-hosted

**Comment by ErnieBernie10** [comment]
The proxy is not currently published to docker hub as it was not released yet. If you want to use the docker-compose-hub.yml files you must use a release branch. Check the tags for this.

You can build everything yourself by using the docker-compose.yml file instead.

**Comment by pablohashescobar** [comment]
Hello @zub0r!  The updated Docker setup has been successfully pushed to the master branch, and all the latest images, including the proxy, have been uploaded to Docker Hub. With these changes in place, you should now be able to effortlessly run the setup. If you encounter any issues or have any questions, please feel free to reach out.
