### ISSUE TITLE
[bug]: Wrong email subject when using forgot password

### ISSUE THREAD

**Issue by Unyxos** [makeplane/plane#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On self hosted version, when using the forgot password feature, the email's subject is `Verify your Email!` where I believe it should be something more in line with a password reset flow

right now, it sounds like you just registered even though you've been using your account for some time)

### Steps to reproduce

1. Go to login page
2. Click on forgot password
3. Input & wait for password reset email
4. See email's subject

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Created a PR to fix this #1233
