### ISSUE TITLE
[bug]: When using reset password, user needs to login before inputing new password

### ISSUE THREAD

**Issue by Unyxos** [makeplane/plane#1231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the "reset password" feature, you have to first login into the account before being able to reset password, the reset password form isn't shown otherwise.

The user shouldn't have to login to reset password as the userid & token are supposed to allow the user to access this page and save a new password

(Tried with Chrome, Safari and Firefox)

### Steps to reproduce

1. Create an account
2. Log out and click forgot password
3. Fill email, wait for email
4. In the reset password email, click on the link
![CleanShot 2023-06-06 at 22 40 06@2x](https://github.com/makeplane/plane/assets/11515332/f63cddcc-149a-442e-98fe-5bdcc2872d79)

6. You're redirected to `https://plane.domain.tld/?next_url=/reset-password`
![CleanShot 2023-06-06 at 22 41 28@2x](https://github.com/makeplane/plane/assets/11515332/194f6734-014e-4919-8648-ab7ce348f271)

8. Login (remember : you're not supposed to remember credentials)
9. You're then granted the reset password form
![CleanShot 2023-06-06 at 22 42 09@2x](https://github.com/makeplane/plane/assets/11515332/b9568f95-f452-40a7-9641-a3b903740710)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by aaryan610** [comment]
Hello @Unyxos, thanks for pointing out this crucial bug, we have fixed it with #1238, and is live on the `develop` branch.

**Comment by aaryan610** [comment]
Hello @Unyxos, thanks for pointing out this crucial bug, we have fixed it with #1238 , and is live on the `develop` branch.
