### ISSUE TITLE
[bug]: Workspace Settings upload log Response error :  "Workspace id is required"

### ISSUE THREAD

**Issue by ultimate-smile** [makeplane/plane#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Workspace Settings upload log Response error :  "Workspace id is required"

### Steps to reproduce

Workspace Settings upload log Response error :  "Workspace id is required"

### Browser

Google Chrome

### Version

Cloud

**Comment by pablohashescobar** [comment]
Hello @ultimate-smile, thank you for bringing this issue to our attention. We're happy to inform you that it has been successfully resolved. We're now closing this issue. However, if you encounter any further difficulties or have additional concerns, please don't hesitate to reopen it. We're here to assist you further. Thank you again for your valuable feedback!
