### ISSUE TITLE
[bug]: Unable to change user role at the workspace level

### ISSUE THREAD

**Issue by atom-bhairav** [makeplane/plane#1239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I am on the Workspace settings and click on Members and try to change a user role from Viewer to either Member or Admin, I receive the generic error message "An error has occurred, please try again"

### Steps to reproduce

Go to Workspace
Click on Settings
Click on Members
Find a user with the role of Viewer
Change the user role to Admin

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @atom-bhairav, thank you for bringing up your concern. We would like to clarify the scenario regarding upgrading user roles. In this case, only the admin has the authority to upgrade the roles of lower-level members (Guest, Viewer, Member) to the admin role.

To provide further clarification, the hierarchy of roles is as follows:

1. Admin
2. Member
3. Viewer
4. Guest

For instance, if you hold the Member role, you have the capability to upgrade the roles of Guests and Viewers to the Member role only. However, the admin has the flexibility to upgrade them to any role.

**Comment by atom-bhairav** [comment]
Hi @rhea0110,

I created the workspace so am an admin myself, trying to give another person admin rights.  At the moment I can't upgrade the roles to either Member or Admin.

Regards

**Comment by rhea0110** [comment]
Hey @atom-bhairav, I just wanted to let you know that the changes have already been made in the development branch and they will be live on our website soon.

Thanks!

**Comment by rhea0110** [comment]
Hey @atom-bhairav, we're delighted to inform you that we have successfully resolved the bug you reported. It is now live on our website. Thank you for your patience.
