### ISSUE TITLE
[bug]: Issue Update Modal Not Showing The Description

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Bug
When we want to update any Issue with the modal, **description** is not showing what we've already entered or contains on the object.

## Expectation
Modal should be open with the existing data that we already entered.

### Steps to reproduce

1. Create a workspace
2. Inside the `workspace` create a projects
3. Under the `Projects` (Left Side Bar) Go to `Issues`
4. Create a new issue from the above `Add Issue` button.
5. Click on the more action from the issue that just created.
6. Update with the new data.

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @ChandanJal, thank you for reporting this bug. We acknowledge the issue and assure you that we are actively working on it. We plan to have it resolved and included in one of our upcoming releases.

Thank you!

**Comment by ChandanJal** [comment]
@rhea0110  I've resolved this issue. You can check this https://github.com/makeplane/plane/pull/1249

**Comment by rhea0110** [comment]
Hey @ChandanJal, we appreciate your contribution to Plane. Our engineers will review your code soon and merge it as soon as possible to ensure a smoother experience.

Thank you!

**Comment by rhea0110** [comment]
Hello @ChandanJal! We are thrilled to announce that the issue has been successfully resolved and is now live on app.plane.so as part of our v0.8 dev release. Feel free to check it out now!

Thank you!
