### ISSUE TITLE
[bug]: Non latin letters on project naming

### ISSUE THREAD

**Issue by BayCo** [makeplane/plane#1246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create a new project and the name has non latin letters like (Ç, Ş, Ğ, I, İ, Ö, Ü) the validation gives wrong error
<img width="687" alt="Screenshot 2023-06-07 at 18 32 04" src="https://github.com/makeplane/plane/assets/2808949/d15e52a7-7340-4365-8533-f096ac03cc18">

### Steps to reproduce

1) Go to create a new project
2) Input a name that has non latin letters

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @BayCo, thank you for bringing this issue to our attention. We would like to inform you that currently, our system only supports alphabets. However, we understand the importance of expanding the capabilities, and our engineers will be working on it in the near future.

Thank you!

**Comment by vihar** [comment]
@BayCo, we apologize for the oversight. We will work on this issue shortly. 

cc: @NarayanBavisetti
