### ISSUE TITLE
[bug]: You don't have any projects yet on adding to favorites

### ISSUE THREAD

**Issue by me-abhishekpal** [makeplane/plane#1250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you mark any project to the favourites, it moves from the projects and goes to favorites and shows that You don't have any project yet.

![image](https://github.com/makeplane/plane/assets/2958671/4d9df026-a8aa-4c28-9286-6acf99c52f48)

### Steps to reproduce

1. Add any existing project to Favorites
2. Vanishes from the Project list

![image](https://github.com/makeplane/plane/assets/2958671/527cd89e-ccb2-4bfc-a380-14ca45d5d0d7)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by ChandanJal** [comment]
I guess `Projects` just showing the normal projects. Normal projects are not favorite. The **Favorite** should be inside the `Project` or something so anyone can guess it right, should change the name to **Normal Project**.

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
