### ISSUE TITLE
[bug] No "Analytics" on the left for the self-host version

### ISSUE THREAD

**Issue by klion26** [makeplane/plane#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I run a self-hosted plan, login using the default user. Can't find the "Analytics" on the left after create a new workspace(such as the pic below).

![image](https://github.com/makeplane/plane/assets/1425623/0dea45c1-d50a-4aa3-92f8-9ff04f958567)

### Steps to reproduce

1. run the self-host plane using the pre-build docker image such as the master branch (`docker compose -f docker-compose-hub.yml up -d`)
2. create a new workspace

### Browser

Google Chrome （Mac M1  13.4 (22F66) ）

### Version

Self-hosted

**Comment by Unyxos** [comment]
Hey I think it'll be fixed on the next release, I'm running the develop branch and can see it :)

**Comment by klion26** [comment]
@Unyxos thanks for the reply, will wait the next release and try it again :)
