### ISSUE TITLE
🚀 Feature: change password in self-hosted solution

### ISSUE THREAD

**Issue by RilusMahmud** [makeplane/plane#1258]
Please implement the change password on the self-hosted solution.

**Comment by Pdzly** [comment]
dupe of this https://github.com/makeplane/plane/issues/1138

**Comment by Pdzly** [comment]
Should be fixed on develop branch btw. it could be bugged but it could work

**Comment by RilusMahmud** [comment]
Can you please show me where is the option to change the password? I couldn't find that. Maybe I'm missing something.

**Comment by RilusMahmud** [comment]
Alright. But, what I meant by the change password is to change my own password from the profile page.

**Comment by Pdzly** [comment]
This is still dupe of #1138

**Comment by vihar** [comment]
Sorry for the late follow-up on this. We shipped the option to change the password on our self-hosted instance a few releases back. This can be found under profile > settings > security.​
