### ISSUE TITLE
🚀 [Feature]: Automatically save content typed in pages (just like when creating a new issue)

### ISSUE THREAD

**Issue by yaikohi** [makeplane/plane#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When creating a new page and filling it with content, it doesn't automatically save the content. This feature request is so that it does get automatically saved. 

Should work like this:
1. create a new page
2. create a new title
3. write down the content in the block/body section
4. no need to press `update block` because it would automatically be saved (on keystroke? after clicking outside the textarea DOM element? I don't know what's most optimal)

### Why should this be worked on?

I like using the `pages` feature because it allows me to share information on one platform (issues + information about the project)! But the first time using the `pages` feature I didn't know that I had to press the save button in order for it to be saved so I lost my initial progress the first time I was using it. 

I thought that it would save automatically as this is also the case when you create a new `Issue`.

**Comment by rhea0110** [comment]
Hey @yaikohi, thank you for your suggestion. Our team will brainstorm around it and start working on it soon. We will keep you updated on the progress.

Thanks!

**Comment by Palanikannan1437** [comment]
Hey @yaikohi, we've added this in at https://github.com/makeplane/plane/issues/1261 and improved it more at https://github.com/makeplane/plane/pull/3397. Please upgrade to the latest version to experience the new and improved pages thanks to @henit-chobisa 🙌
