### ISSUE TITLE
[feature]:add support switch app language

### ISSUE THREAD

**Issue by gribanoveu** [makeplane/plane#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add support for switching the application language. Move the translation strings out of the components to a file. Allow the community to translate the application into their languages

### Why should this be worked on?

To expand the app's audience

**Comment by rhea0110** [comment]
Hey @gribanoveu, thank you for your suggestion. Our team will brainstorm around it, and we will keep you updated on any progress made.

Thanks!

**Comment by vihar** [comment]
Thank you, @gribanoveu, for your feature request. We plan to address it soon. For easier communication, we're shifting this conversation to the main thread. Refer, https://github.com/makeplane/plane/issues/2028.
