### ISSUE TITLE
[bug]: Login Issues Consolidation and Analysis

### ISSUE THREAD

**Issue by KairuDeibisu** [makeplane/plane#1272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Summary
Currently, people trying to self-host `Plane` in docker using either [docker-compose-hub.yml](https://github.com/makeplane/plane/blob/develop/docker-compose-hub.yml) or [docker-compose.yml](https://github.com/makeplane/plane/blob/develop/docker-compose.yml) docker compose files, are unable to login at all.

## Bug Reports
List the individual bug reports related to log in issues that have been identified that I believe to be related.

- [ ] #719 
- [ ] #1267
- [ ] #1155

#### Commonalities among Bug Reports
- **Error Message:** All three bug reports share a common error message: “Opps! Enter the correct email address and password to sign in.” This error message is consistently displayed when users attempt to log in.

- **404 Error to API:** Regardless of the self-hosting environment or the specific docker-compose file used, all three bug reports mention encountering a 404 error when the frontend tries to POST to the API. This issue persists across different configurations.

> Note: This issue is **not** related to the password change of the database, as it persists even after clearing all images and volumes.

# Notes

In the worker logs, the Redis address has a trailing / at the end of the URL. I've removed it from line 27, from my docker compose and the issue persists, 

**Before**
```ymal
        plane-api:
                container_name: planebackend
                image: makeplane/plane-backend:latest
                restart: always
                command: ./bin/takeoff

                environment:
                        DJANGO_SETTINGS_MODULE: plane.settings.production
                        DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
                        REDIS_URL: redis://plane-redis:6379/
```

**After**

```yaml
REDIS_URL: redis://plane-redis:6379
```

> Note: Only changed lines are shown

### Steps to reproduce

See attached logs.

![2023-06-10_12-15-22](https://github.com/makeplane/plane/assets/34011041/84619b21-0a8a-4179-b4bd-cf9677fe3b2a)

[docker-compose.txt](https://github.com/makeplane/plane/files/11712828/docker-compose.txt)

[_planefrontend_logs.txt](https://github.com/makeplane/plane/files/11712834/_planefrontend_logs.txt)
[_plane-redis_logs.txt](https://github.com/makeplane/plane/files/11712838/_plane-redis_logs.txt)
[_plane-db_logs.txt](https://github.com/makeplane/plane/files/11712842/_plane-db_logs.txt)
[_plane-minio_logs.txt](https://github.com/makeplane/plane/files/11712843/_plane-minio_logs.txt)
[_planebackend_logs.txt](https://github.com/makeplane/plane/files/11712845/_planebackend_logs.txt)

[_planerqworker_logs.txt](https://github.com/makeplane/plane/files/11712847/_planerqworker_logs.txt) <--SUS

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hello @KairuDeibisu! We sincerely appreciate the detailed report you provided. Before we proceed, could you please confirm if you are currently running the latest images of the plane? Ensuring that you have the most recent versions will help us better understand the context of the issue you're experiencing. Additionally, if possible, it would be helpful if you could expand one of the network logs to display additional information, such as the URL involved. This will assist us in analyzing the problem more effectively. Thank you for your cooperation and valuable input!

**Comment by KairuDeibisu** [comment]
I've attached my docker-compose file to the write-up; however, it may have been lost as it's a lot of info.

I'm currently using `makeplane/plane-frontend:latest`.


[docker-compose.txt](https://github.com/makeplane/plane/files/11712886/docker-compose.txt)

**Comment by pablohashescobar** [comment]
Hello @KairuDeibisu! Thank you for bringing this to our attention. We noticed that you have removed the NGINX container, and based on the network logs, it appears that any requests to the backend with the `/api` endpoint are resulting in a 404 error. It would be extremely helpful if you could provide us with your NGINX configuration as well.

**Comment by KairuDeibisu** [comment]
Sure, let me get that for you, in the meantime, here is a longer video for the network, https://drive.google.com/file/d/1ivgx-RCcIyPWT5fvIFwFDpsDhTWKN1Es/view?usp=drivesdk

**Comment by KairuDeibisu** [comment]
Attached is my nginx Configuration.
[5.txt](https://github.com/makeplane/plane/files/11712899/5.txt)

**Comment by KairuDeibisu** [comment]
Also, as the site is public and online, feel free to go to https://plane.researchsystems.org/ and see what you can find if you feel the need.

**Comment by pablohashescobar** [comment]
Hello @KairuDeibisu! Upon reviewing the provided nginx.conf, it appears that there is no explicit configuration for handling requests to the `/api` endpoint all the requests to `/api` should be forwarded to backend container.

**Comment by KairuDeibisu** [comment]
I don't think I'm the only one who forgot to do this, I'll see if that corrects the issue.

**Comment by KairuDeibisu** [comment]
Adding the following to my nginx configuration resolved all my issues.

I think we should include a note about forwarding the /api route in nginx if you don't use the container provided.

![SNAG-0002](https://github.com/makeplane/plane/assets/34011041/6243f247-84f1-4388-bdef-0c32c98d150d)

**Comment by pablohashescobar** [comment]
Hello @KairuDeibisu! Thank you for bringing this to our attention. We appreciate your feedback and understanding. We will make sure to update the documentation accordingly to include the necessary configuration for handling requests to the `/api`.
