### ISSUE TITLE
[bug]: Change Cover button is missing on self-hosted version

### ISSUE THREAD

**Issue by mikhail-shevtsov-wiregate** [makeplane/plane#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On latest release v0.7.1 when creating new project or editing project `Change Cover` button is missing on self-hosted version.

### Steps to reproduce

1. Go to Projects;
2. Click `Add Project` button;
or
1. Go to Project Settings;

In both cases the button `Change Cover` is Missing

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by ChandanJal** [comment]
Yes, mine also not showing

**Comment by rhea0110** [comment]
Hey @mikhail-shevtsov-wiregate, thank you for reporting this bug. Our engineers have already started working on fixing this issue, and it will be live in some time. We will keep you updated on the progress made.

Thank you!

**Comment by vihar** [comment]
thanks for flagging this, @mikhail-shevtsov-wiregate. this issue is fixed on https://github.com/makeplane/plane/pull/2375.
