### ISSUE TITLE
[bug]: Issue view overflows due to long lines in code blocks

### ISSUE THREAD

**Issue by dmikushin** [makeplane/plane#1275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When issue comment contains very long code line, the issue page overflows the display view (see screenshot attached).
![Screenshot from 2023-06-12 02-15-55](https://github.com/makeplane/plane/assets/5672874/2915a8de-86fa-48c3-96bb-bc8a3b2a9aee)
![Screenshot from 2023-06-12 02-14-52](https://github.com/makeplane/plane/assets/5672874/9ddbc1ac-2f2f-4276-ba26-30852337f4f2)

### Steps to reproduce

1. Create a new issue
2. Add a very long preformatted text into a comment:

```
very very long preformatted code block very very long preformatted code block very very long preformatted code block very very long preformatted code block very very long preformatted code block very very long preformatted code block very very long preformatted code block very very long preformatted code block
```

In GitHub there is a scroll, so it displays normally. But not in Plane.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by kblueberry** [comment]
@dmikushin I couldn't reproduce it, could you add some more details/recored a video of how you reproducing this?

**Comment by dmikushin** [comment]
Hi @kblueberry, please find the video demo attached.
![plane-issue-2023-06-30_12 52 34](https://github.com/makeplane/plane/assets/5672874/7aa2a79a-9d15-4f39-a3f7-53dcd5de9ef4)

**Comment by dmikushin** [comment]
I see that the issue is gone, as of [v0.11-dev](https://github.com/makeplane/plane/tree/v0.11-dev). Therefore closing, thanks!
