### ISSUE TITLE
[bug]: Content Overflow

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Content is getting overflow inside the Import/Export section.

### Steps to reproduce

1. Go to your `Workspace` first.
2. After that click on `Settings`
3. On `Settings` go to `Import/Export` tab.

Like this `Workspace > Settings > Import/Export`

![BUG](https://github.com/makeplane/plane/assets/97095857/446249ba-1061-443b-8e41-b9b6ce016316)

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @ChandanJal, we want to know if you are using it in the mobile, requesting you to please confirm? 


Thank you!

**Comment by rhea0110** [comment]
Hey @ChandanJal, we want to know if you are using it in the mobile, requesting you to please confirm? 


Thank you!

**Comment by ChandanJal** [comment]
@rhea0110 Please check out https://github.com/makeplane/plane/pull/1249 this pull request. All the bugs that I've encountered are solved here.

**Comment by ChandanJal** [comment]
> Hey @ChandanJal, we want to know if you are using it in the mobile, requesting you to please confirm?
> 
> Thank you!

@rhea0110 Please check out https://github.com/makeplane/plane/pull/1249 this pull request. All the bugs that I've encountered are solved here.

**Comment by rhea0110** [comment]
Hey @ChandanJal, once again, thank you for your contribution to Plane. As I mentioned earlier, our team will soon review your code, and we will merge it to enhance the overall experience.

Thanks!

**Comment by vihar** [comment]
This issue is fixed on our latest release (0.14-dev, soon to be promoted to cloud), thanks @ChandanJal for flagging this.
