### ISSUE TITLE
[bug]: Profile Setting Have Too Much Padding

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When opening the `Profile Settings`, it showing too much padding from x and y axis.

### Steps to reproduce

Go to `Profile Setting` on your mobile devices.

### Browser

Google Chrome

### Version

Cloud

**Comment by aaryan610** [comment]
Hello @ChandanJal, thanks for pointing out this design issue, we'll get it fixed asap.

**Comment by aaryan610** [comment]
This issue will be resolved once PR #1335 is merged.
