### ISSUE TITLE
[feature]: PWA support

### ISSUE THREAD

**Issue by kirtan403** [makeplane/plane#1280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

PWA support is a good to have so that we can install it like apps on our phone. For this, need to make current design mobile friendly. Currently it breaks at multiple places. This can be started just by converting it to PWA without offline/notification support. And can be added these features later on.

### Why should this be worked on?

This can eliminate the need of the native app, as most functionalities can be supported via PWA

**Comment by SaadBazaz** [comment]
I prefer PWAs over mobile apps. 

Less maintenance for the open source community, and easy installs for users. Win win.

**Comment by vihar** [comment]
Plane Cloud supports PWAs. We are also launching desktop applications and a mobile app shortly.
