### ISSUE TITLE
[bug]: Breadcrumb Heading Getting Breaks On Mobile 

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we open the issues section on the mobile devices. It's breadcrumb title getting break and top header get destroyed.

### Steps to reproduce

![ISSUS PAGE](https://github.com/makeplane/plane/assets/97095857/344f26d5-2b4b-4413-90d8-be69614cd45c)

### Browser

Google Chrome

### Version

Local

**Comment by rhea0110** [comment]
Hey @ChandanJal, thank you for bringing up this issue. We haven't implemented mobile responsiveness for some parts of Plane yet, but we have plans to address it soon. Additionally, we are currently developing a mobile app that will be launched in the near future. In the meantime, if there are any responsiveness-related bugs on the web app, we will prioritize fixing them.

**Comment by vihar** [comment]
The web app doesn't support mobile views, we are shortly planning to release native mobile applications.
