### ISSUE TITLE
Unable to log in when behind reverse proxy

### ISSUE THREAD

**Issue by Willow6949** [makeplane/plane#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Installation works fine when logging in via IP.
However as soon as I try to log in behind my Nginx Proxy Manager it's not excepting any credentials.

Anything I can do to mitigate this issue? 

### Steps to reproduce

Create a DNS record on your firewall.
Create a Proxy host in NPM
Connect to Plane using your proxy host domain e.g. https://plane.domainexample.com
Login with default credentials.

![image](https://github.com/makeplane/plane/assets/111548844/b508b646-4872-4009-9ebd-c8714efa28ef)

### Browser

Other

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @Willow6949, it would be great if you could also share the network logs. Also just to confirm the proxy should be configured to forward / to plane frontend and /api to plane backend and /uploads/ to plane minio.

**Comment by Willow6949** [comment]
Hi @pablohashescobar I've changed the the proxy locations per your instructions but still no luck to sign in.
I'm not well versed in nginx so I know I'm doing something wrong.
Which network logs would you like to look at?

**Comment by pablohashescobar** [comment]
Hi @Willow6949, it looks like the backend is still not accessible anything to `/api` should be forwarded to the backend container.

**Comment by niltonvasques** [comment]
I'm facing the same problem. Seems that the frontend is attempt to use HTTP instead HTTPS protocol for some reason. Any idea why? In the @Willow6949 screenshots we can also clearly see this behavior. The browser blocks HTTP ajax calls when the   domain is using HTTPS.

**Comment by niltonvasques** [comment]
I figured out the problem. After change the URL you need to rebuild the planefrontend image from scratch, because the URL is hardcoded inside the previos image.

**Comment by pablohashescobar** [comment]
Hi, it is recomended to use the pre-built images using the `docker-compose-hub.yml`. Closing this issue please feel free to re-open if the issue still persists.
