### ISSUE TITLE
[bug]: My Profile page have too much padding on mobile devices.

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you browse to the My Profile page on your mobile browser, It'll give you so much padding from left and right side.
![1686727095500](https://github.com/makeplane/plane/assets/97095857/484c1770-c960-4781-8ff0-96d66d64ac7a)

### Steps to reproduce

1. Login to the plane 
2. Open side bar and click on your profile picture to open `My Profile`

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @ChandanJal, we appreciate your active involvement in the community. As mentioned earlier, regarding issue number 1282 that you opened yesterday, I would like to inform you that we have not yet implemented mobile responsiveness for certain parts of Plane. However, I want to assure you that we have plans to address these issues soon. Our engineers are actively working on resolving the bugs related to responsiveness on the web app. Until then, we sincerely appreciate your patience.

**Comment by aaryan610** [comment]
This issue will be resolved once PR #1335 is merged.
