### ISSUE TITLE
[bug]: 401 error login loop

### ISSUE THREAD

**Issue by Aviortheking** [makeplane/plane#1290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After trying to login I get sent back to the login page

It seems that I can get one authenticated request done to the api but after that I go back to being disconnected

----------
Additionnal infos:

Browser Request logs:
[_planerqworker_logs.txt](https://github.com/makeplane/plane/files/11744133/_planerqworker_logs.txt)

API logs:
[api.log](https://github.com/makeplane/plane/files/11744154/api.log)

the only "error" I see in any logs is this for the frontend
```
2023-06-14T09:34:26.890329433Z Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly 
```

You can try on https://plane.dzeio.com using the defaults

it is self hosted using coolify with the docker being here https://github.com/aviortheking/plane

### Steps to reproduce

1. Login with the defaults ids
2. get sent back to the login screen

### Browser

Mozilla Firefox

### Version

Self-hosted

[Discord forum](https://discord.com/channels/1031547764020084846/1120331795452399636)

**Comment by Jirubizu** [comment]
I have the exact same issue :/ Tried following the guide on the readme, however it just wont let me login using the default

**Comment by pablohashescobar** [comment]
Hi, it would be awesome if you could try the latest version (0.8). Please feel free to comment if you are still facing the issue.

**Comment by orbatschow** [comment]
@pablohashescobar tried with 0.8, can confirm, that the issue still persists

**Comment by calbrecht** [comment]
It seems [SECRET_KEY](https://github.com/makeplane/plane/blob/4ede04d72f25f54a2b6d6a11720e022098a4a4c0/apiserver/plane/settings/common.py#L10) will be regenerated sporadically, if not already present in environment and is used to encode and decode jwt in several places.

**Comment by Aviortheking** [comment]
Yeah it seems to have fixed the issue !

**Comment by orbatschow** [comment]
For me this was indeed caused by a type, setting SECRET_KEY the correct way fixes the issue!

**Comment by quangngoc** [comment]
I have the exact same issue, @orbatschow, how did you fix that?

**Comment by orbatschow** [comment]
@quangngoc I misspelled the SECRET_KEY environment variable itself, so i just fixed the type and then it worked for me.

**Comment by jimhuds** [comment]
Can confirm SECRET_KEY fixed it for me too
