### ISSUE TITLE
[bug]: Scrollbar indicator is showing

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Most of the screen have scrollbar indicator showing. Must hard coded the scroll behavior or something. `Firefox` browser is showing.
![SCROLL_BAR](https://github.com/makeplane/plane/assets/97095857/3ee51c39-2a5e-43be-ad5c-5986b4f8b42a)

### Steps to reproduce

Open your `Plane` on **`Firefox Browser`**

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by kblueberry** [comment]
@ChandanJal I can't reproduce it anymore, I didn't see any useless scrollbars on the sections you highlighted earlier
