### ISSUE TITLE
[bug]: Filters are performing weirdly

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Filter is performing weird.

![FILTER NONE](https://github.com/makeplane/plane/assets/97095857/a8f4b47f-5530-408b-ba19-07be387f4536)

### Steps to reproduce

Go to your issue and try to filter and create your custom views. 

### Browser

Google Chrome

### Version

Cloud

**Comment by aaryan610** [comment]
Hello @ChandanJal, thanks for raising this issue. We're currently working on improving the way we are managing our contexts and hope to fix this asap.

**Comment by aaryan610** [comment]
This issue will be fixed once this #1334 is merged.
