### ISSUE TITLE
[feature]: Minor UI change (Add an arrow button to scroll)

### ISSUE THREAD

**Issue by dineshkumardavanam** [makeplane/plane#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The website when opened by anyone, is a very long website in the beginning, For the people who want to go to the bottom have to scroll through everything, So I am suggesting an arrow feature to the website so that when opened we can have a small arrow button in the bottom right which will take us to the bottom of the screen and then when in bottom come back to the top

Can I get this feature assigned to solve it 

### Why should this be worked on?

For the people to go the carrier pages and social media pages it is getting hard, So this is a feature which can be a beneficial one

![image](https://github.com/makeplane/plane/assets/96611161/93609e23-ce52-4b19-a6fc-95115d0c4e71)

Below we can add a Arrow like this
![image](https://github.com/makeplane/plane/assets/96611161/192ccce2-7f0f-4671-b26c-2dfa45e260b2)

**Comment by vihar** [comment]
Closing this issue. We’ve improved our website. Thanks for the feedback, @dineshkumardavanam.
