### ISSUE TITLE
[bug]: Not Coming out of the dialog box when clicked in the backgroud

### ISSUE THREAD

**Issue by dineshkumardavanam** [makeplane/plane#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we open create issue in the workspace, and when we want to go out we only have to click discard to go out, but when we are clicking the background we are not going out of the dialog box, which is causing highlighting of text if clicked twice

So after this bug fix, we actually have to come out of the dialog box rather than waiting for discard

### Steps to reproduce

1 => click on my issues in the left pane
2 => click on create issue
3=> now try to click on the background just beside the dialog box
4=> Click on discard, We will come out

This should not happen, Would try to solve the bug

### Browser

Google Chrome

### Version

Local

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
