### ISSUE TITLE
[feature]:  Page where you can upload files

### ISSUE THREAD

**Issue by DevNimo** [makeplane/plane#1304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I wish there was a separate page where I could upload files.
I wish there was a function to link issues and file links.

### Why should this be worked on?

After uploading the file, if the file is related to multiple issues, it would be nice if you could link to the issue.
And it looks like I can use it in a "page" by linking it with the uploaded file.

**Comment by rhea0110** [comment]
Hey @DevNimo, we sincerely appreciate and value your suggestion. Thank you for submitting the feature request. Our team will brainstorm around it, and we will keep you updated on any progress made.

Thanks!

**Comment by vihar** [comment]
@DevNimo, we are working on a feature called Drive, where you can manage all your attachments. We’ll open a new thread shortly to understand use cases.
