### ISSUE TITLE
[bug]: Cycle progress showing NaN inside the progress

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we create a new `Cycle`. Inside the all cycle tab progress is showing `NaN %` which is inappropriate. It should be showing the progress how much it done.

![NaN %](https://github.com/makeplane/plane/assets/97095857/5f9415b1-0d37-400a-b366-d4b1088064d7)
 

### Steps to reproduce

1. Go to `Cycle` from `Project`.  Like `Project > Cycle`.
2. If you do not have any `Cycle`, then create a new one.
3. At the `All` cycle tab. You can see the progress is showing `NaN %`

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @ChandanJal, thank you for reporting this bug to us. Our engineers will work on it soon, and we will fix it with our upcoming release.

Thank you!
