### ISSUE TITLE
[bug]: Module progress bar not updating

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you create a module and assign it to an issue, it should update the progress as the issues are updating.

![MODULE NOT UPDATEING](https://github.com/makeplane/plane/assets/97095857/df9b3939-7e53-4b22-89f3-ccd1b053bb62)

### Steps to reproduce

1. Create a `Module`.
2. Create a new `Issue` or inside the new `Issue` update the module to the created module.
3. After assigning `Module` to an `Issue`, change the status of the `Issue`

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @ChandanJal, thank you for reporting this bug to us. Our engineers will work on it soon, and we will fix it with our upcoming release.

Thank you!

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
