### ISSUE TITLE
[bug]: able to remove all the states from a group

### ISSUE THREAD

**Issue by aaryan610** [makeplane/plane#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

According to the current workflow, I see that a project cannot have an empty state group. If I try to delete the last state of any group, it doesn't allow me to do so.

![image](https://github.com/makeplane/plane/assets/65252264/4e200453-6016-429a-ac6d-831464a0de19)

However, there's a loophole I found, the user cannot delete the only state of a group, but they can change the group of that state by using the dropdown menu, like this-

![image](https://github.com/makeplane/plane/assets/65252264/18fd8b0f-017f-4dfe-8e75-97a988e2c3ad)

### Steps to reproduce

1. Go to project settings.
2. Go to the `States` menu.
3. Try changing the group of any state that is the only one in its group.

### Browser

Google Chrome

### Version

Cloud

**Comment by Palanikannan1437** [comment]
Hey @aaryan610, I indeed was able to reproduce this! 

Just so I could confirm it once, could you please clarify what would be the intended ideal workflow?

A possible flow could be on the lines of not allowing the flow to change the "only" state of the group by essentially disabling the dropdown (i.e. by showing the current group's name and showing a message on hover indicating the same) if only a single state is present in the group?

**Comment by aaryan610** [comment]
Hi @Palanikannan1437, that'd be the desired workflow.
