### ISSUE TITLE
[bug]: Unable to navigate via mobile on [workspaceSlug] page

### ISSUE THREAD

**Issue by redzumi** [makeplane/plane#1332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

WorkspaceAuthorizationLayout has noHeader prop, so I can't open drawer to navigate

<img width="230" alt="Снимок экрана 2023-06-20 в 00 50 52" src="https://github.com/makeplane/plane/assets/20846670/2afd385b-e169-40d7-9b52-dc7778328714">

If I misunderstood something in UX, please let me know
PS Thanks for great and opensource service!

### Steps to reproduce

1. Open [workspaceSlug] page via mobile view

### Browser

Google Chrome

### Version

Cloud

**Comment by kblueberry** [comment]
I am new to this project, I would like to take this bug into development, as I see, nobody is working on it, right?
May I ask anybody, is there any design resources which I can rely on?
Thanks in advance

**Comment by redzumi** [comment]
@rhea0110 hi! Pls, help with design for this issue
@kblueberry can fix it, but it's okay, to show navigation header at index page of project?

**Comment by vihar** [comment]
Hello @kblueberry,

Thank you for showing interest in contributing to our project. We're pleased to assign this issue to you!

We currently have a sidebar toggle feature and we're considering how it can be best implemented for mobile screens. Your feedback and insights on this matter would be invaluable.

<img width="1137" alt="CleanShot 2023-06-23 at 00 49 41@2x" src="https://github.com/makeplane/plane/assets/16307796/318a7b07-ddc4-46e7-9c8c-7ab0c9160ffb">

**Comment by kblueberry** [comment]
Hello @vihar , thanks for reply. I was thinking about burger menu, which is expanding/collapsing on icon click, what do you think?

**Comment by redzumi** [comment]
@kblueberry @vihar 
![123](https://github.com/makeplane/plane/assets/20846670/18368fee-a221-4471-b8bc-56b455818af9)
Can we just remove noHeader prop from WorkspacePage component?

**Comment by kblueberry** [comment]
Looks like it could be a decision, and we already see the burger menu working without noHeader prop

**Comment by aaryan610** [comment]
This bug will be fixed, once PR #1389 is merged.

**Comment by redzumi** [comment]
Yea, fixed!
