### ISSUE TITLE
[bug]: Issues jump in Board view while changing state

### ISSUE THREAD

**Issue by Palanikannan1437** [makeplane/plane#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try changing the states of the issues in board view, they jump randomly before getting updated in their new state's column.

Here's a demo reproducing the same,

https://github.com/makeplane/plane/assets/73993394/f57dcde3-5706-480f-897a-7efb6eb1b9d0

- [x]  I am willing to submit a PR

### Steps to reproduce

1. Create Issues
2. Navigate to Board View
3. Change state of Issue

### Browser

Google Chrome

### Version

Cloud

**Comment by aaryan610** [comment]
Thanks for reporting this @Palanikannan1437, we'll look into this issue and try to resolve this asap.

**Comment by Palanikannan1437** [comment]
> Thanks for reporting this @Palanikannan1437, we'll look into this issue and try to resolve this asap.

Sure thing, I'll try to debug this too and come up with a PR 🙌
