### ISSUE TITLE
[feature]: Done is transient state, it shouldn't stay on a kanban board forever

### ISSUE THREAD

**Issue by shadowjig** [makeplane/plane#1343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The Done state is transient.  It shouldn't stay on a kanban board forever.  I suggest allowing the user to pick the period of time after which the done tasks no longer show up on the kanban board.  I would consider creating something like Jira has, which is a version of SQL (they call it JQL) and it's powerful as a user.  A JQL query can be used in boards, views, or even bookmarked queries.

### Why should this be worked on?

If I'm a year into a project, I have a lot of Done tasks, I wouldn't want to continue to see them.

**Comment by rhea0110** [comment]
Hey @shadowjig, we sincerely appreciate and value your suggestion. Thank you for submitting the feature request. Our team will brainstorm around it, and we will keep you updated on any progress made.

Thanks!

**Comment by vihar** [comment]
Sorry for following up late on this. Today, we support the archive feature under `Project Settings > Automations`. You can set a time period for issues in the Done state, and the issues will automatically move to the Archived state from any Done state group.
