### ISSUE TITLE
[feature]: Time tracking

### ISSUE THREAD

**Issue by jstama** [makeplane/plane#1350]
A good feature would be to be able to add time tracking to an issue. Then we can have a sum of the time for issues for modules and cycles

**Comment by torbenraab** [comment]
@jstama Please look at #1184
It would say this issue duplicates the one above

**Comment by rhea0110** [comment]
Hey @jstama, thank you for submitting this feature request. I'm pleased to inform you that we have already begun working on it and expect to release it sometime soon. We will keep you updated on the progress.

Thank you!

**Comment by jstama** [comment]
Yes, this is a duplicate. Thank you for the response. 
I will close the issue

**Comment by weir1** [comment]
Is this implemented?

**Comment by dandry** [comment]
Would also appreciate an update on this :)

**Comment by FEndo** [comment]
This is expected for a long time. and it would make plane today, in my opinion, the best.

**Comment by abrahampo1** [comment]
This one is really game changer for plane upp
