### ISSUE TITLE
[bug]: login codes are receiving very late sometimes it taking longer than the expected time

### ISSUE THREAD

**Issue by Mohanready** [makeplane/plane#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Not working..

### Steps to reproduce

after entering email address we are not receiving verification code immediately.. some times it is taking longer than the expected time 

### Browser

Google Chrome

### Version

Cloud

**Comment by pablohashescobar** [comment]
Hi @Mohanready,

We wanted to inform you about an issue we encountered with our cloud provider, which temporarily caused delays in email delivery. We are pleased to inform you that the problem has been resolved, and the email service is now operating smoothly.

**Comment by aaryan610** [comment]
This issue has been fixed.
