### ISSUE TITLE
[bug]: layout of tabs on Pages is not adaptable to mobile screens 

### ISSUE THREAD

**Issue by kblueberry** [makeplane/plane#1380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

**Problem** 
on mobile screens, tabs are positioned horizontally, but because of huge size, they look like bubbles and morover, its container is not scrollable horizontally. 

<img width="396" alt="Screenshot 2023-06-23 at 19 34 36" src="https://github.com/makeplane/plane/assets/56432889/456134c3-79ae-452e-881b-a28b3b7ac1e8">

### Steps to reproduce

1. Go to 'Pages'
2. Open DevTools & select any of mobile dimensions 
3. Observe the view of pages tabs 

**Expected result:**
position horizontally with wrapping items in a row

### Browser

Google Chrome

### Version

Self-hosted

**Comment by kblueberry** [comment]
There is one more opened PR fo that from me
https://github.com/makeplane/plane/pull/1387

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
