### ISSUE TITLE
[bug]: Context menu is not seen until user scrolls on clicking More button 

### ISSUE THREAD

**Issue by kblueberry** [makeplane/plane#1391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Current behavior**

When I click More actions, I barely see context menu with all actions expanded, to be able to see it, I need to scroll (the video is below)

<img width="980" alt="Screenshot 2023-06-24 at 17 04 19" src="https://github.com/makeplane/plane/assets/56432889/53f4fe82-3337-4651-a0ae-d3e609ca78df">
<img width="959" alt="Screenshot 2023-06-24 at 17 04 43" src="https://github.com/makeplane/plane/assets/56432889/a4fcdace-cd36-4058-a98e-53fa7f52753f">

### **Steps to reproduce**

1. Go to Pages, Recent tab
2. Create a page
3. On the pages list, click More actions on recetly added page
4. Observe the context menu

### Browser

Google Chrome

### Version

Cloud

**Comment by kblueberry** [comment]
I'd like to take it to development

**Comment by Flavsditz** [comment]
This is the same issue as #1301 
In essence is that the popover is being rendered inside a div that has a overflow set to scroll...

**Comment by ChandanJal** [comment]
@kblueberry this issue is resolved https://github.com/makeplane/plane/pull/1395 here. 
I've made a pull request please checkout.

**Comment by rhea0110** [comment]
Hey @kblueberry, this issue has already been fixed and is now live on app.plane.so.

Thanks!
