### ISSUE TITLE
[bug]: A long Issue title or description pushes the components out of screen without even scroll

### ISSUE THREAD

**Issue by faizanjan** [makeplane/plane#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I write a very long Issue Title or Issue Description, It pushes the sidebar out of view. And if we further keep writing then all the content is pushed out of the screen and that too without any horizontal scroll.

I have attached a screencast below

### Steps to reproduce

1. Go to Projects
2. Go to issues
3. Create a new issue with a very long title/description

[Screencast](https://github.com/makeplane/plane/assets/122923000/c66bcd29-5640-4ac7-a88f-2893bc1b6703)

### Browser

Google Chrome

### Version

Cloud

**Comment by aaryan610** [comment]
HI @faizanjan, thanks for bringing this to our attention, we'll try to fix this issue asap.

**Comment by rhea0110** [comment]
Hello @faizanjan! We are thrilled to announce that the issue has been successfully resolved and is now live on app.plane.so as part of our v0.8 dev release. Feel free to check it out now! 

Thank you!
