### ISSUE TITLE
[bug]: application getting crashed

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Go to your `Module` section. It getting crashed
![CRASH](https://github.com/makeplane/plane/assets/97095857/6d56e3d8-2f3b-4a91-b935-1d003c26b90b)

### Steps to reproduce

Create a new `Module` and open the module details page

### Browser

Google Chrome

### Version

Local

**Comment by aaryan610** [comment]
Hi @ChandanJal, have you pulled the latest changes from the `develop` branch?

**Comment by ChandanJal** [comment]
@aaryan610 Yes I've, I think the problem is causing from the **Backend**. It is not giving the required response and missing `distribution`, `members_list`, `workspace_detail` form the response.

**Comment by pablohashescobar** [comment]
Hi @ChandanJal, we checked the local branch and we were unable to replicate the issue.
