### ISSUE TITLE
[bug]: Select label is missing scrollbar in Chrome

### ISSUE THREAD

**Issue by slasktrat** [makeplane/plane#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is no scrollbar visible in the "Select label" dropdown in Chrome. In firefox it is present

### Steps to reproduce

1. Use Chrome
2. Open an issue
3. Click "Select label"

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@slasktrat, sorry for replying late. this issue is fixed on our latest release. if you're still facing this issue, please let us know.
