### ISSUE TITLE
[bug]: issue item overflow

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you open the `Issue` list and open it with the `Waterfall View`. 

![OVER FLOW FILTER](https://github.com/makeplane/plane/assets/97095857/f8a141ce-d2fc-4b6b-97f2-d8a2d9854a45)

### Steps to reproduce

1. Open `Issue`
2. Open it with the `Waterfall View`
3. Filter issues

### Browser

Google Chrome

### Version

Cloud

**Comment by PrashantIndurkar** [comment]
i have checked this issue this issue is solved already.

**Comment by vihar** [comment]
this issue is resolved on our latest release, thanks for flagging.
