### ISSUE TITLE
[feature]: Bulk Add members / invite members in Bulk

### ISSUE THREAD

**Issue by kotasudhakar** [makeplane/plane#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

it is difficult for people with greater than 50 team size to invite each one individually.
if there is a feature to bulk invite/ bulk add people to a workspace (may be using excel sheet) from their email address would be really a time saver and a great help

### Why should this be worked on?

would be really a time saver and a great help

**Comment by rhea0110** [comment]
Hi @kotasudhakar! Thank you for your valuable suggestion. We want to inform you that we have already included it in our roadmap and we are aiming to implement it in one of the upcoming releases in the following months. Your feedback is greatly appreciated, and we look forward to delivering an enhanced experience.

**Comment by kotasudhakar** [comment]
> Hi @kotasudhakar! Thank you for your valuable suggestion. We want to inform you that we have already included it in our roadmap and we are aiming to implement it in one of the upcoming releases in the following months. Your feedback is greatly appreciated, and we look forward to delivering an enhanced experience.

Hi @rhea0110 , thank you for your response. I didn't knew that it was already on the road map. May i know if there is a way i can check the road map? if yes, where can i see that?

**Comment by kotasudhakar** [comment]
@rhea0110 Can you please guide me to the place where the i can the roadmap of this project?

**Comment by rhea0110** [comment]
Hey @kotasudhakar, if you want to stay updated on the tasks and features currently being developed, simply use the v0.9 tag as a filter. We assign this tag to the issues we are actively working on in GitHub, so you can easily track our progress and be in the know about what's coming down the pipeline.

Thankyou!

**Comment by kotasudhakar** [comment]
i believe you are referring to bulk creating issues, this is to INVITE Users in bulk, which i could not see anywhere in the road map. sorry i if missed it. Kindly correct me if i am wrong

**Comment by rhea0110** [comment]
Hello @kotasudhakar, this feature is live on app.plane.so. You have the ability to efficiently add multiple members to a project or workspace all at once.
