### ISSUE TITLE
[bug]: custom theme not changing properly

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you try to customize the them and changing the color it not changing as required.

https://github.com/makeplane/plane/assets/97095857/3458e019-565e-4b32-9c51-418c3bfaca9e

### Steps to reproduce

Customize the them and again change the color.

### Browser

Google Chrome

### Version

Local

**Comment by hifnStudio** [comment]
@ChandanJal I'm using it and it's working perfectly for me i have changed my custom theme many time it takes time but works perfectly. For test you can open plane in two tabs and then on one tab you can change the values for theme and then refresh the other tab you will see the new changes.

**Comment by aaryan610** [comment]
We have restructured our custom theming for a smoother experience, you can check it on- https://app.plane.so
