### ISSUE TITLE
[bug]: Attachments upload error on self-hosted version

### ISSUE THREAD

**Issue by klion26** [makeplane/plane#1440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When upload files as issue attachments, got the following error

![image](https://github.com/makeplane/plane/assets/1425623/12b95071-005b-4bbb-bca5-8898bc857025)

The size of the file is 806KB, tried ".log" and ".txt" suffix.
<img width="770" alt="image" src="https://github.com/makeplane/plane/assets/1425623/fe45830d-924f-4b5c-a58e-4f04d58c6329">

The version of plane is 0.6 in my laptop

![image](https://github.com/makeplane/plane/assets/1425623/d35be507-93d4-4b0a-b684-25954a974e66)

### Steps to reproduce

1. create an issue
2. drag a file to the attachments
![image](https://github.com/makeplane/plane/assets/1425623/c337fe2e-6f0a-4e4a-b8f0-94f1f45d853b)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @klion26 this issue was fixed in the 0.7.1-dev.

**Comment by klion26** [comment]
@pablohashescobar thanks for the quick reply, will try the latest version.
Thanks all the creating the awesome project

**Comment by klion26** [comment]
@pablohashescobar the problem has been resolved by using the latest version. thanks.

But seems user can only drag one file a time, will throw the exception "invalid file type or size(max 5mb)" (such as the pic below), not sure this is the expected behavior

<img width="451" alt="image" src="https://github.com/makeplane/plane/assets/1425623/ae4b500b-e18a-4adf-8d7e-6c7da175b980">

**Comment by sidrxd** [comment]
i am uploading video which is 20 mb .
How can i increase size limit in self hosted version?
