### ISSUE TITLE
[bug]: issue by state doughnut chat overflow legend on mobile

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When opening on the `Mobile` device and visit `Dashboard` the `Issue By State` is overlapping the legends

![GRAPH NOT SHOWING PROPERLY ON MOBILE](https://github.com/makeplane/plane/assets/97095857/419a219e-c530-4093-b5a9-48d981baed9a)

### Steps to reproduce

1. Open `Plane` on mobile device
2. Visit `Dashboard`
3. Scroll to the `Issue By State` section

### Browser

Google Chrome

### Version

Cloud

**Comment by aaryan610** [comment]
This issue will be fixed with #1528.

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
