### ISSUE TITLE
[bug]: High memory/RAM usage with dockerized Plane API 

### ISSUE THREAD

**Issue by whallin** [makeplane/plane#1449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Docker version of the Plane API ([makeplane/plane-backend:latest](https://hub.docker.com/r/makeplane/plane-backend)) uses a high amount of RAM on startup and counting.

The API/back-end container doesn't have any deployment resource limits right now, but with the way things are going, that could change quickly. When the container is first started, the memory usage is set right away to 400-600MB, even though the user hasn't done anything yet.

If you leave the service running and let users interact with the platform—slowly, but sometimes quickly, the RAM usage goes up, but there are no visible signs of garbage collection or anything like that. Is this a possible memory leak or a task that uses a lot of RAM in the API/back-end that might not be optimized?

Our current setup for Plane has no more than 3 registered users, 1 workspace with 4 projects, and only a few created issues. Redis, Postgres, and MinIO resource usage seems fine by their standards. The high amount of memory is only applicable to the Plane back-end Docker image.

I can say for sure that the front-end and worker containers don't have the same problem with using a lot of resources.

**EDIT:** Another theory here; could it be an upstream dependency causing the high memory usage?

### Steps to reproduce

1. Create a Plane instance following the instructions of [Self Hosting | Plane](https://docs.plane.so/self-hosting) & using [docker-compose-hub.yml](https://github.com/makeplane/plane/blob/develop/docker-compose-hub.yml)
2. Start your Plane stack
3. Monitor resource usage during startup & while using your Plane instance

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @whallin, did this started happening after the 0.8 release?

**Comment by whallin** [comment]
> Hi @whallin, did this started happening after the 0.8 release?

Never had time to test it properly on 0.7.x. So, I can only confirm the behavior on 0.8

**Comment by pablohashescobar** [comment]
Hi @whallin, can you check if the `DEBUG value is set to 0 in the `.env`.

**Comment by whallin** [comment]
> Hi @whallin, can you check if the DEBUG value is set to 0 in the `.env`.

The `DEBUG` variable is not present. I suppose it's 0 by default.

**Comment by pablohashescobar** [comment]
Can you try by deleting all the containers, volumes and network and reinitiating the setup again with the latest changes.

**Comment by whallin** [comment]
Fresh install and the resource usage remains high. Not quite sure if there's any profiling I can do for you.

**Comment by kosmoz** [comment]
I have noticed that the worker and backend containers both spawn a lot of processes. 

Both can be reduced by modifying the entrypoint scripts but there's no easy way to do this when using the prebuilt docker images.

**Comment by dkotama** [comment]
can confirm, the api itself taking like 800M memory

**Comment by vihar** [comment]
@pablohashescobar, can you also share the PR here? Thanks.

**Comment by pablohashescobar** [comment]
Sure @vihar, here is the [PR](https://github.com/makeplane/plane/pull/2573) which adds an additional environment variable to the backend container called `GUNICORN_WORKERS` which controls the number of gunicorn workers that will boot up.

**Comment by vihar** [comment]
This PR is now shipped on our latest release, `v0.14-dev`.
