### ISSUE TITLE
[feature]: Support at someone in the discription/comment

### ISSUE THREAD

**Issue by klion26** [makeplane/plane#1450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Want to support at someone in the issue description/comment, and the one who has been at could receive some notification.

### Why should this be worked on?

This can be helpful if some issue need the other to pay attention to.

**Comment by rhea0110** [comment]
Hey @klion26, we sincerely appreciate and value your suggestion. Thank you for submitting the feature request. Our team will brainstorm around it, and we will keep you updated on any progress made.

Thanks!

**Comment by Palanikannan1437** [comment]
Hey @klion26, we've delivered this! Here's a PR from my pal @henit-chobisa here at https://github.com/makeplane/plane/pull/2544. Please consider upgrading to the latest version to try it out!!
