### ISSUE TITLE
[feature]: add repository

### ISSUE THREAD

**Issue by TartanLeGrand** [makeplane/plane#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Deploy each needs docker images to an repository for pull it from an chart helm.

### Why should this be worked on?

Self-hosted with k8s

**Comment by mguptahub** [comment]
@TartanLeGrand

Helm Chart based deployment is available at artifacthub

[![Artifact Hub](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/makeplane)](https://artifacthub.io/packages/search?repo=makeplane)

Closing this issue.

**Comment by TartanLeGrand** [comment]
@mguptahub where we can contribute to the chart ?
