### ISSUE TITLE
[feature]: Add search on Emojis select

### ISSUE THREAD

**Issue by Glassback** [makeplane/plane#1456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

it's very difficult to find the emoji that we're looking for.

The icons are not very necessary and emojis are very small

<img width="251" alt="image" src="https://github.com/makeplane/plane/assets/10955956/9b3b0e54-aa87-4881-9a1d-f12426322276">

### Why should this be worked on?

My proposal is to replace the actual component with https://github.com/missive/emoji-mart

<img width="348" alt="image" src="https://github.com/makeplane/plane/assets/10955956/3fbba69e-274d-4c87-8176-6df97cdb638a">

**Comment by rhea0110** [comment]
Hey @Glassback, thank you for your valuable suggestion. We have already planned to implement it soon, and we will keep you updated on the progress.

Thank you!

**Comment by vihar** [comment]
Sorry for following up late on this issue. We now support search bars on all emoji pickers and have also added support for using icons. Thanks for the suggestion.

![CleanShot 2024-06-29 at 16 17 07@2x](https://github.com/makeplane/plane/assets/16307796/f97dda30-0845-42c5-9cfe-39058e05954d)
![CleanShot 2024-06-29 at 16 17 20@2x](https://github.com/makeplane/plane/assets/16307796/bbd34919-2a23-42f1-85e7-bc0363f56c20)
