### ISSUE TITLE
🚀 Feature: Ticket Estimated time

### ISSUE THREAD

**Issue by strappberry** [makeplane/plane#1462]
We should be able to estimate the time or sprint points in a ticket in order to know the capacity of the team, we should display it in the ticket list (backlog, todo, etc...) and ticket details

![Screenshot 2023-07-04 at 13 10 33](https://github.com/makeplane/plane/assets/54283605/a33f6091-c63b-40c0-bf0e-3f8d8c48a044)
![Screenshot 2023-07-04 at 13 13 02](https://github.com/makeplane/plane/assets/54283605/d99ed5c4-8466-4814-a1e7-664d1ce6f29a)

**Comment by rhea0110** [comment]
Hey @strappberry, thank you for reaching out to us. We are delighted to inform you that the mentioned feature is already available in our application. To access the estimates, follow these steps in Plane:

1. Navigate to Project settings.
2. Within Project settings, go to Estimates.
3. Click on the "Create New Estimate" button.
4. Fill in all the required details in the Create Estimate form and submit it.
5. Once the Estimate is created, click on the 'Use' button to enable it.

To disable the Estimates for a specific project, simply click on the "Disable Estimates" button located on that page.

Thank you!
