### ISSUE TITLE
[bug]: page recent section height

### ISSUE THREAD

**Issue by chandanvc** [makeplane/plane#1480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Inside the `Page` of any `Project` if you are creating multiple `Pages` list is performing weirdly.

https://github.com/makeplane/plane/assets/138677898/8073ed82-1953-4760-9014-b000051c8d48

### Steps to reproduce

1. Go to your `Project`
2. Open the `Pages`
3. Inside the `Recent` tab

Make sure to create as much `Pages` you want so it could get scroll

### Browser

Google Chrome

### Version

Local

**Comment by vihar** [comment]
We completely revamped our pages, thanks for flagging this.
