### ISSUE TITLE
[feature]: Comments/Activity settings

### ISSUE THREAD

**Issue by rascal999** [makeplane/plane#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Love this tool, thank you guys. You made me realise how bad Jira is.

Regarding the Comments/Activity pane, please can you allow us to:

1. Sort the comments/activity pane by date (descending/ascending)
2. Allow us to customise what we see in the pane. Personally, I'd like to be able to view just comments. Most of the space is taken up with messages relating to actions on the ticket.

### Why should this be worked on?

For request 1, it would save individuals scrolling down (potentially a lot) to find the latest activity on tickets.

For request 2, it would save space and allow individuals to see just comments instead of other activity on the ticket.

**Comment by rhea0110** [comment]
Hey @rascal999, we sincerely appreciate and value your suggestion. Thank you for submitting the feature request. Our team will brainstorm around it, and we will keep you updated on any progress made.

Thanks!

**Comment by mstindia-com** [comment]
Hey @rhea0110, 

First thanks a lot for a great tool. Good point by @rascal999, but a better option is to show them in a tab if possible. So we can see comments by default and switch tabs to view activity.

And if you plan to add a way to log hours for a task. Add another tab to this. We are currently using the activity to track how much a task took. Basically using the time difference between when the task goes from 'in progress' to 'done'.

So a way to log time will be a great add-on. Much needed.

**Comment by pushya22** [comment]
@rascal999 both your feature requests have been implemented and live in all versions of Plane.
