### ISSUE TITLE
Changes on ts files not reflecting

### ISSUE THREAD

**Issue by Abhilash-Kishor** [makeplane/plane#1488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have done some changes like changing logos images textual changes on apps/app/pages/index.tsx
some changes at seo-variables.ts but none of the changes are reflecting on my portal any changes suggested ?

### Steps to reproduce

Home Page 

### Browser

Google Chrome

### Version

Self-hosted

**Comment by appinteractive** [comment]
Hey just a couple of dumb question but did you deployed after building it? Or are you running it locally? Using Docker? 

What steps did you follow? 


Just asking those as you did not provide any information on the steps you went through.

**Comment by Abhilash-Kishor** [comment]
I deployed it on an AWS EC2 server using Docker build. After making some UI changes, I stopped the Docker container and ran Docker system prune to ensure all images were deleted. Then, I restarted Docker compose, but the changes did not appear.

**Comment by appinteractive** [comment]
Did you build a new docker container with your changes?

**Comment by vihar** [comment]
Apologies for the delayed response in this thread. We have recently updated our contribution guidelines. Please refer our contribution guidelines: https://github.com/makeplane/plane/blob/preview/CONTRIBUTING.md.
