### ISSUE TITLE
[bug]: page details search label consisting search query

### ISSUE THREAD

**Issue by chandanvc** [makeplane/plane#1489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you search for a `Label` on the `Page Details`, after searching for the label if you just click outside of the modal the search query is remain consist.

### Steps to reproduce

1. Go to any of your `Project` .
2. Inside the `Project` find the `Page` section.
3. Click on any of the `Page` item and open the `Page Details`.
4. To add a `Label` click on the add button.
5. Search for the `Label` that you want to select.
6. After selecting the `Label` click outside the modal to close the modal.
7. Repeat `Step 4`
8. Now you get the bug

### Browser

Google Chrome

### Version

Local

**Comment by anmolsinghbhatia** [comment]
This issue will be fixed with #1610
