### ISSUE TITLE
[bug]: inbox issue activity is not getting track

### ISSUE THREAD

**Issue by chandanvc** [makeplane/plane#1490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Like normal `Issue` the `Issue` inside the `Index` is not getting the tracked all `Comment/Activity`, but when open as a normal `Issue` it working fine.

### Steps to reproduce

1. Go to your `Project`
2. Navigate to the `Issue` and from the header top right click on the `Index`
3. Create new `Issue`
4. Now try to make some changes on the `Issue`

### Browser

Google Chrome

### Version

Local

**Comment by aaryan610** [comment]
This issue has been fixed and is live on https://app.plane.so
