### ISSUE TITLE
[bug]: project menu should be disabled when issues are edited from context menu 

### ISSUE THREAD

**Issue by jamesw** [makeplane/plane#1501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I view issues for a project I click on the three dots menu and choose edit from the three options. I am then presented with an edit window
Select a different project from the currently selected project and update, a red error box appears and the edit form is redrawn blank and the project remains unchanged from the original
![Screenshot from 2023-07-11 15-05-32](https://github.com/makeplane/plane/assets/16945/47c1631b-f86f-418a-a93c-65dadf509ac4)
![Screenshot from 2023-07-11 15-05-20](https://github.com/makeplane/plane/assets/16945/622d493d-c035-46fa-a686-7d2f60581607)
![Screenshot from 2023-07-11 15-04-41](https://github.com/makeplane/plane/assets/16945/018be252-a568-41c1-b79b-d273491fd089)
![Screenshot from 2023-07-11 15-03-23](https://github.com/makeplane/plane/assets/16945/e6a473a8-bae4-4057-b490-5e4429802cb8)

### Steps to reproduce

As described above

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by aaryan610** [comment]
Hi @jamesw, thanks for reporting this issue, we'll try to fix this asap.
