### ISSUE TITLE
[bug]: workspace upload image accepting any king of file

### ISSUE THREAD

**Issue by chandanvc** [makeplane/plane#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to update the `Workspace` default image to a custom one. But the image upload button let me upload other then images file also. This should not be happening as the profile is only to show images files.

### Steps to reproduce

1. Go to your `Workspace`.
2. Go to `Workspace Settings` or just click on the `Settings`  on the sidebar.
3. Update the profile with any kind of file.

`Workspace > Settings`

### Browser

Google Chrome

### Version

Cloud

**Comment by aaryan610** [comment]
This issue has been fixed with v0.10 release.
