### ISSUE TITLE
[bug]: Unable to see OAuth Options on Sign In

### ISSUE THREAD

**Issue by mr-karan** [makeplane/plane#1509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
docker compose -f docker-compose-hub.yml exec plane-web sh
/app $ env | grep OAUTH
NEXT_PUBLIC_ENABLE_OAUTH=1
```

I've configured it to enable OAuth however on the home screen I don't see any option to login via GitHub or Google:

![image](https://github.com/makeplane/plane/assets/5689132/f0da4869-3743-46ed-a7e4-2615005e3f03)
![image](https://github.com/makeplane/plane/assets/5689132/bf1a15a2-bc16-473d-9703-19ed465f1e8c)

### Steps to reproduce

1. Edit `.env` file with:

```
NEXT_PUBLIC_GOOGLE_CLIENTID: "redacted"
NEXT_PUBLIC_ENABLE_OAUTH: "1"
```

2. `docker compose -f docker-compose-hub.yml up` Start the containers.
3. Visit `/sign-up` or `/` and notice that OAuth options are still disabled.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@mr-karan, sorry for the late response on this; we missed it. We've fixed this issue in our latest release by introducing a feature called `god-mode`. More details can be found in our docs: https://docs.plane.so/self-hosting/instance-admin. 

If you're still facing issues or have suggestions to improve the user experience, please reopen this issue and let us know. 🙏🏻
