### ISSUE TITLE
[bug]:  column issues.archived_at does not exist at character 482

### ISSUE THREAD

**Issue by mktelos** [makeplane/plane#1510]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

I am getting this error ' column issues.archived_at does not exist at character 482' on database after setting up plane using docker-compose

### Steps to reproduce

All the containers seems to run fine but cannot login since i am getting a 500 error and after checking the logs i saw  column issues.archived_at does not exist at character 482, it seems the latest db migrations are missing.

### Browser

Google Chrome

### Version

Cloud

**Comment by pablohashescobar** [comment]
Hi @mktelos, this is an error in `deveop` branch, It would be awesome if you could switch to `master` branch and run the project again.
