### ISSUE TITLE
[feature]: make openai API key configurable per user

### ISSUE THREAD

**Issue by mktelos** [makeplane/plane#1511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great if users could customize OpenAI settings and use their own key instead of a shared one. 

### Why should this be worked on?

By having their own API key, users can manage their own usage limits.

**Comment by rhea0110** [comment]
Hey @mktelos, we sincerely appreciate and value your suggestion. Thank you for submitting the feature request. Our team will brainstorm around it, and we will keep you updated on any progress made.

Thanks!

**Comment by vihar** [comment]
@mktelos you can configure your own API keys under `/god-mode`, more docs [here](https://docs.plane.so/self-hosting/govern/instance-admin). Let us know, if you are having any issues configuring this.
