### ISSUE TITLE
[feature]: clean filter in custom search select

### ISSUE THREAD

**Issue by rlscode** [makeplane/plane#1512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello, the custom search select component, if I open it for the first time and filter the content, everything is fine, however, if I open it a second time, it stays with the filter applied and the user does not know or has no vision of the list that is being displayed.

Two posible options for improve the componente, 
- always show the value of the Input in the filter.
- clear the value of the Input when the list is displayed

### Why should this be worked on?

When i have a Issue and i need to assign, i filter the users the first time and everything well 

![image](https://github.com/makeplane/plane/assets/25810274/bb3d763b-9550-4fb6-8eec-68b8dd682887)

But if i open again the list its filter but the user can't see that filter value.

![image](https://github.com/makeplane/plane/assets/25810274/5b9e3da5-085a-4234-b901-5f8f97697403)

i recommend in the Input filter component assign the value of query or clean the value of query when open.
![image](https://github.com/makeplane/plane/assets/25810274/406a3a10-6021-4810-a298-b3fb402aafd0)

**Comment by rhea0110** [comment]
Hey @rlscode, thank you for reporting this to us. We greatly appreciate your feedback. Our dedicated engineers have already begun addressing this issue, as it has been identified as a bug. Rest assured, it will be resolved and included in our upcoming release. We will make sure to keep you informed about the progress we make.

Thank you for your understanding and support!

**Comment by anmolsinghbhatia** [comment]
This issue will be fixed with #1610

**Comment by rhea0110** [comment]
Hey @rlscode, this issue has now been resolved and is live on app.plane.so.
