### ISSUE TITLE
[feature]: Docker installation improvements

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#1516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## The source code is required for the installation.

The current recommended installation method requires the user to clone the source files.

## Portainer / Unraid / etc. compatibility.

Because the installation requires the source code and an additional .env file plane is not compatible with systems like Portainer or Unraid where a single file defines the application.

## Upgrading

Upgrading is currently more complicated than it needs to be because of having to keep track of the changes done to the .env files and the docker compose files.

## My proposed solution:

The recommended installation method should use the prebuilt docker images (as it already is), but should not require the cloning of the source code.
The setup.sh script should not be necessary and should automatically be executed on start of the container to fill the default variables that require random data, e.g. SECRET_KEY.
The .env file is only accessible within the container and not to the user. Variables like the NEXT_PUBLIC_API_BASE_URL and the WEB_URL should be overriden from within the compose file.

### Why should this be worked on?

see above :)

**Comment by Quadrubo** [comment]
This would allow to fix #966 and #1177

**Comment by leikoilja** [comment]
any updates on this? :)

**Comment by pablohashescobar** [comment]
@Nahiiko, the docker setup has been updated and now does not require cloning the entire repository. You can follow the [docs](https://docs.plane.so/self-hosting) for reference.

**Comment by mguptahub** [comment]
@Nahiiko @leikoilja 

To deploy Plane on Portainer, use the 2 files
- [Docker Compose](https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/docker-compose.yml)
- [.env](https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/variables.env)

This is more than sufficient to make it work on portainer

Hope this helps. 

Closing this issue. Feel free to reopen for further support.

**Comment by Quadrubo** [comment]
This issue is not solved. Please reopen it. You don't provide any instructions on how to setup with docker compose in your documentation. The only way to install Plane through your documentation is by using the setup.sh script.

There are also platforms like Unraid which don't use docker compose with .env files but their specialized syntax. They would profit from a single docker compose file made available in the docs, which has all the environment variables filled in without a .env file.

Once there is:

1. docker compose file with environment variables filled in (without the need for .env)
2. documentation on using docker compose instead of the setup.sh script.

I would consider this issue as solved.

**Comment by leikoilja** [comment]
> This issue is not solved. Please reopen it. You don't provide any instructions on how to setup with docker compose in your documentation. The only way to install Plane through your documentation is by using the setup.sh script.
> 
> There are also platforms like Unraid which don't use docker compose with .env files but their specialized syntax. They would profit from a single docker compose file made available in the docs, which has all the environment variables filled in without a .env file.
> 
> Once there is:
> 
> 1. docker compose file with environment variables filled in (without the need for .env)
> 2. documentation on using docker compose instead of the setup.sh script.
> 
> I would consider this issue as solved.

@Quadrubo, i am not sure what more do you need to be able to deploy it using docker.
[This comment](https://github.com/makeplane/plane/issues/1516#issuecomment-1956012692) gives pretty much everything you need, docker-compose file example is enough

**Comment by Quadrubo** [comment]
Did you read my comment?
Everyone who wants to set this up that is not very knowledgeable using docker (which would most likely be people using unraid) need:

1. A docker compose file without the need for a .env (all variables filled in the compose file.
2. Proper documentation **on your website** on how to set this up without the install script.

**Comment by radhakrisri** [comment]
Tend to agree with @Quadrubo here: this definitely needs more information.

I pulled down both docker-compose.yml and .env into a folder and launched with without any changes to .env. When i load up plane.so in a browser, this is what I encounter:

![image](https://github.com/makeplane/plane/assets/125212515/1967e993-6a78-45fd-8bb9-11869b5b9af0)

At this point, its a treasure hunt in the code and documentation to figure what is going wrong. 

More information about what to configure in .env is definitely required. 

Lack of information just makes all the hardwork that went into putting together this docker-compose and .env file, pretty much useless.
