### ISSUE TITLE
Question: Cross-project "blocking" issues?

### ISSUE THREAD

**Issue by knadh** [makeplane/plane#1551]
Hi!

If there are two projects A (Issue1) and B (Issue2), is it possible for A.Issue1 to use B.Issue2 as a "blocking" issue? Currently, this doesn't seem possible on the UI. What is the recommended way for cross-project blocking issues then?

Thank you.

**Comment by knadh** [comment]
Thanks @vihar. Cross-project dependencies are an inevitable reality in all complex systems and orgs.

**Comment by vihar** [comment]
This issue has been resolved on https://github.com/makeplane/plane/pull/1612 and will soon be promoted to the master branch.

**Comment by knadh** [comment]
Great, thank you!
