### ISSUE TITLE
[feature]:  "Identifier must be uppercase text" how can I use V2 , V3, V1-1  as project name ？

### ISSUE THREAD

**Issue by xxaier** [makeplane/plane#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

 "Identifier must be uppercase text" how can I use V2 , V3, V1-1 as project name

**Comment by aaryan610** [comment]
Hi @xxaier, you cannot use anything apart from uppercase letters for your project identifier. However, there's no such restriction for the project name, you can choose any name of your choice, including- `V2 , V3, V1-1`.

**Comment by aaryan610** [comment]
HI @xxaier, we have updated the project identifier to accept uppercase alphabets as well as digits. This update was shipped in our [v0.10](https://github.com/makeplane/plane/releases/tag/v0.10-dev) release.
