### ISSUE TITLE
[bug]: Label color selecting bug

### ISSUE THREAD

**Issue by santidevhmo** [makeplane/plane#1617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I click the color-menu for a new label it doesn't fully display and only 2 colors are shown

### Steps to reproduce

1. Click on any issue for the right-side menu to open
2. Click on +New label
3. Click on the default red color
<img width="1161" alt="Screenshot 2023-07-22 at 12 50 05 p m" src="https://github.com/makeplane/plane/assets/49324282/e0e06f2c-5fd9-43a6-815f-be15b2553aad">

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by aaryan610** [comment]
Hi @santidevhmo, thanks for pointing out this bug, we'll fix this asap with our next release.

**Comment by rhea0110** [comment]
Hey @santidevhmo, this issue has now been resolved and is live on app.plane.so.
