### ISSUE TITLE
[bug]: task state don't update from "in progress" to "test"

### ISSUE THREAD

**Issue by edalkic** [makeplane/plane#1642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i change the state of the task from in progress -> test, don't update. I refresh page and the state of the task is still in progress.

![image](https://github.com/makeplane/plane/assets/61585747/8d410221-13e4-4951-bd29-696f21857c40)

![image](https://github.com/makeplane/plane/assets/61585747/d0713fce-1946-45df-8ace-5fea9b6b05d6)

### Steps to reproduce

1. open the detail page of the task (my task state is in progress at my scenario)
2. click state select box.
3. select "test" state

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hello, @edalkic! Thank you for reporting the bug. We'll fix it soon in one of our upcoming releases.

**Comment by rhea0110** [comment]
Hey @edalkic, this issue has now been resolved and is live on app.plane.so.
