### ISSUE TITLE
[bug]: Unable to select project while creating a new issue from My Issues

### ISSUE THREAD

**Issue by ds201ues** [makeplane/plane#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Unable to select project while creating new issue from My issues.

https://github.com/makeplane/plane/assets/33284199/10feb548-342c-44d8-be51-15f123e4f512

### Steps to reproduce

1. Go to my issues
2. Click on Add Issue
3. In Add Issue box, try selecting a different project
4. Project always defaults to first project. Selected project never displays

### Browser

Google Chrome

### Version

Self-hosted

**Comment by aaryan610** [comment]
HI @ds201ues, this issue will be fixed with PR #1608.

**Comment by aaryan610** [comment]
This issue has been fixed with v0.10 release.
