### ISSUE TITLE
[feature]: add labels from kanban view if there isnt one already

### ISSUE THREAD

**Issue by zdaar** [makeplane/plane#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi, it would be nice if we could add labels on kanban cards that dont have a label already. 
Example :
![image](https://github.com/makeplane/plane/assets/4218386/85b63a63-d4cf-4c07-80a1-eb55ffbb72da)
Can add label because it already has one

![image](https://github.com/makeplane/plane/assets/4218386/778f3567-2604-44c0-a0a6-8a1298faf3d9)
Cannot quick add label because it doesn't already have one

### Why should this be worked on?

Consistent behaviour with other quick-add attributes like Assignee, etc

**Comment by rhea0110** [comment]
Hello, @zdaar! Thank you for the feature request. Our team will work on it soon.
