### ISSUE TITLE
[feature]: Improve UX to add label in the full-view sidebar of an issue

### ISSUE THREAD

**Issue by zdaar** [makeplane/plane#1656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When you open an issue detail and go in the sidebar to add a label it is a poor UX when trying to select a label if you have a lot of them. It is only able to display 4 elements and you have to scroll and cannot filter.

![image](https://github.com/makeplane/plane/assets/4218386/e4b296e7-545c-4a86-a3fd-d3e9399e61e3)

### Why should this be worked on?

It is frustrating to add labels when you have a lot, so this would be a good improvement

**Comment by rhea0110** [comment]
Hello @zdaar! Thank you for the feature request. Our team will work on it soon.
