### ISSUE TITLE
[bug]: onboarding for invited members ask to create a new workspace

### ISSUE THREAD

**Issue by rush-skills** [makeplane/plane#1670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On the current dev version of the self-hosted plane instance,

When I setup a workspace and invite other team members via email (with sign up disabled),

They get an email with a link to the login page, and upon login they are redirected to the onboarding process, where they can enter their Name etc., and on second step, they are asked to create a workspace (although they have been already invited). 

This cause people to create a new (personal) workspace forcefully to use the product, but they should ideally be just asked to join the invited workspace and continue (in step 2). 

### Steps to reproduce

1 . Setup new self-hosted plane instance
2. Login as admin and create a workspace
3. Invite an user to your workspace
4. Click on the invite link/login as the invited user
5. Now you see the onboarding screen
6. (problem) the user now is asked to create a workspace 
6. (solution) the user can choose to join invited workspace and continue (or create new workspace if needed, but shouldn't be forced)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by aaryan610** [comment]
This workflow has been changed with v0.10 release.

**Comment by jmessy919** [comment]
This is still an issue with the latest release. I just experienced it firsthand when showing Plane to a colleague.
