### ISSUE TITLE
[bug]: ai-assistant/HITP/1.0 400

### ISSUE THREAD

**Issue by lyfar** [makeplane/plane#1675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to use the AI assistant I receive the bad request error

172.28.0.8:48610 - "POST /api/workspaces/*****/projects/1£019450-5323-4661-a66a-3
568802035f7/ai-assistant/HITP/1.0' 400

### Steps to reproduce

Create issue
Click AI 
Error appears 

### Browser

Safari

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @lyfar did you add the `OPENAI_API_KEY` in the `.env`.

**Comment by lyfar** [comment]
@pablohashescobar yes I did
OPENAI_API_KEY="KEY"
GPT_ENGINE="gpt-4"

**Comment by lyfar** [comment]
@pablohashescobar ok so I checked discord and redeployed with GPT_ENGINE="text-davinci-003" and it works. Can you add support for gpt-4?

**Comment by pablohashescobar** [comment]
Hi @lyfar, can you share what is the error you are getting from the API from the network tab.

**Comment by lyfar** [comment]
The API endpoints for the chat completion are different for 3.5 and 4 looks like.

**Comment by lyfar** [comment]
Legacy: https://platform.openai.com/docs/api-reference/completions/create
New: https://platform.openai.com/docs/api-reference/chat/create

**Comment by vihar** [comment]
@lyfar, sorry for replying late on this, AI features/ Open AI keys can be configured from the `god-mode` feature, please refer to our docs for more details: https://docs.plane.so/self-hosting/instance-admin
