### ISSUE TITLE
[bug]: user can be removed from workspace even it's the only admin

### ISSUE THREAD

**Issue by rolinbos** [makeplane/plane#1693]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

It's possible to delete the only admin user on a workspace. When there is one other person in the same workspace with the viewer permission this one is not automatically upgraded to admin of this workspace.

### Steps to reproduce

1. Create a workspace
2. delete yourself from the workspace

### Browser

Google Chrome

### Version

Cloud

**Comment by aaryan610** [comment]
This issue has been fixed with v0.10 release.
