### ISSUE TITLE
[bug]: Error response from daemon: driver failed programming external connectivity on endpoint planeproxy listen tcp4 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by klsdfjo** [makeplane/plane#1713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Error response from daemon: driver failed programming external connectivity on endpoint planeproxy (69f168d7d38636afca15109e3355a7f6a62adc0c9271efb23a5c27e040f54a6e): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

### Why should this be worked on?

Error response from daemon: driver failed programming external connectivity on endpoint planeproxy (69f168d7d38636afca15109e3355a7f6a62adc0c9271efb23a5c27e040f54a6e): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

**Comment by pablohashescobar** [comment]
Hi @klsdfjo, you can change the default nginx port from the configuration ` NGINX_PORT`.

**Comment by klsdfjo** [comment]
你好，我已收到你的e-mail，谢谢。

**Comment by slushpuppy** [comment]
Error response from daemon: driver failed programming external connectivity on endpoint planeproxy (5280446e555ebe6d2a6f497a25581fcb9906dd492e93fb0061c63e82420c7385): Error starting userland proxy: listen tcp4 0.0.0.0:8082: bind: address already in use

even after changing the port, this error still appears

**Comment by vihar** [comment]
We have upgraded our self-hosting setup, and the latest version should fix this bug. For more information, documentation at https://docs.plane.so/self-hosting/.
