### ISSUE TITLE
[feature]: is  there any guides to local development

### ISSUE THREAD

**Issue by dgo2dance** [makeplane/plane#1731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

is  there any guides to local development

### Why should this be worked on?

is  there any guides to local development， I would like to contribute to this project.

**Comment by vihar** [comment]
We have extensive documentation at [docs.plane.so](https://docs.plane.so/). For local development, read our contribution guidelines: [CONTRIBUTING.md](https://github.com/makeplane/docs/blob/master/CONTRIBUTING.md).
