### ISSUE TITLE
[bug]: host not found in upstream "planefrontend" in /etc/nginx/nginx.conf:15

### ISSUE THREAD

**Issue by thelazyoxymoron** [makeplane/plane#1775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I upgrade the installation to the latest master, `planeproxy` container throws an error:

`2023/08/02 11:24:46 [emerg] 1#1: host not found in upstream "planefrontend" in /etc/nginx/nginx.conf:15
`

### Steps to reproduce

1. Bring the existing app down `docker compose down`
2. Fetch new images `docker compose --file docker-compose-hub.yml pull`
3. Restart the containers `docker compose --file docker-compose-hub.yml up -d`

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by vihar** [comment]
We have upgraded our self-hosting setup, and the process should now be seamless. For additional information, kindly view our documentation at https://docs.plane.so/self-hosting/.
