### ISSUE TITLE
[bug]: label filter should show something if there is no label

### ISSUE THREAD

**Issue by pankajvc** [makeplane/plane#1779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we would like to filter the `Issues` according to the `Label`. If there is no label then it should show something like there is no label. 

### Steps to reproduce

1. Create a `Project`
2. Go to the `Project` and create a new `Issue` without any label
3. Filter the `Issues` from the header options 
4. Click on the `Label` option

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @pankajvc, thank you for reporting this bug to us. We will get it fixed soon in one of our upcoming releases.

**Comment by pankajvc** [comment]
> Hey @pankajvc, thank you for reporting this bug to us. We will get it fixed soon in one of our upcoming releases.

@rhea0110 I'm working on it and soon I'll make PR request on this issue.

**Comment by rhea0110** [comment]
Hey @pankajvc, this issue has now been resolved and is live on app.plane.so.
