### ISSUE TITLE
[bug]: adding member to project fails

### ISSUE THREAD

**Issue by krakowski** [makeplane/plane#1782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to add a new member to my project, the request fails with error code `400` (`{error: "Something went wrong please try again later"}`). Turning on `DEBUG` shows the following error:

```
plane-db   | 2023-08-03 09:23:50.023 UTC [204] ERROR:  null value in column "sort_order" of relation "project_members" violates not-null constraint
plane-db   | 2023-08-03 09:23:50.023 UTC [204] DETAIL:  Failing row contains (2023-08-03 09:23:50.021662+00, 2023-08-03 09:23:50.021682+00, af1316b2-5196-4e77-84b4-c6bc2d469f87, null, 15, null, b5acda95-08d7-42e7-85b0-707e2fb35d1b, e6711752-0077-462e-95ab-8a472f708e72, null, fdace9e6-b4a6-491f-83d1-bcf611adfd45, {"filters": {"type": null}, "orderBy": "-created_at", "collapsed..., {"filters": {"type": null}, "orderBy": "-created_at", "collapsed..., null, null).
plane-db   | 2023-08-03 09:23:50.023 UTC [204] STATEMENT:  INSERT INTO "project_members" ("created_at", "updated_at", "created_by_id", "updated_by_id", "id", "project_id", "workspace_id", "member_id", "comment", "role", "view_props", "default_props") VALUES ('2023-08-03 09:23:50.021662+00:00'::timestamptz, '2023-08-03 09:23:50.021682+00:00'::timestamptz, NULL, NULL, 'af1316b251964e7784b4c6bc2d469f87'::uuid, 'e67117520077462e95ab8a472f708e72'::uuid, 'fdace9e6b4a6491f83d1bcf611adfd45'::uuid, 'b5acda9508d742e785b0707e2fb35d1b'::uuid, NULL, 15, '{"filters": {"type": null}, "orderBy": "-created_at", "collapsed": true, "issueView": "list", "filterIssue": null, "groupByProperty": null, "showEmptyGroups": true}'::jsonb, '{"filters": {"type": null}, "orderBy": "-created_at", "collapsed": true, "issueView": "list", "filterIssue": null, "groupByProperty": null, "showEmptyGroups": true}'::jsonb) ON CONFLICT DO NOTHING
```

I expect the project member to be added.

### Steps to reproduce

1. Clone the repository and checkout `master` or `v0.9-dev` (both fail)
2. Build containers using `docker compose build`
3. Configure Plane through `.env` file
4. Start Plane using `docker compose up`
5. Create a workspace and a project
6. Invite a new member to the workspace
7. Wait for new member to accept the invitation
8. Add new member to the project

### Browser

Other

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @krakowski, can you check with the pre-built images of 0.11 using the `docker-compose-hub.yml`. This has been fixed closing this issue please feel free to reopen if you are still facing same issue.
