### ISSUE TITLE
[bug]: Clicking escape when using the "Select Parent Issue" search closes create issue modal

### ISSUE THREAD

**Issue by slasktrat** [makeplane/plane#1786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you have the create issue modal open and are using the "Select Parent Issue" search, clicking escape should only abort the parent issue search, but is currently also closing the create issue modal.

### Steps to reproduce

1. Create new issue
2. Click "Select Parent Issue"
3. Click ESC key

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@slasktrat thanks for flagging this, apologies on replying late. we fixed this issue on v0.13-dev, give it a try and let us know if you're still facing issues.
