### ISSUE TITLE
[feature]: restore draft in create issue

### ISSUE THREAD

**Issue by slasktrat** [makeplane/plane#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Store changes temporarly while creating a new issue and add a button to restore the saved changes in case the modal is closed or reset before the issue is submitted

### Why should this be worked on?

There is currently multiple scenarios where all fields are wiped if you click something "wrong" in the "Create issue" modal.

E.g. if you try to change project, toggle "Create more", click "I'm feeling lucky", https://github.com/makeplane/plane/issues/1786, and maybe other. Many scenarios are probably bugs (that will eventually be fixed), but one can still click with the mouse outside the modal or ESC key and the modal will close without any prompt or warning. This can be frustrating if one has already typed title, description and/or other fields and have to start over. It would be great if changes are stored continuously e.g. in session store while creating a new issue .Then if the fields somehow is cleared (either by bug, or by unintended mouse click outside modal etc) it should be a button to restore the previous draft.

**Comment by rhea0110** [comment]
Hey @slasktrat, thank you for the feature request. We will start working on it soon.

**Comment by ddudda174** [comment]
I second this. Also noticed that fields are reset after some changes (as mentioned the "create more"-swich). But there seems to be another scenario where a field gets erased. For example the title will reset after a new issue was created and the create-more-switch has been switched on. That leads to reentering the title text more than once before you notice when you're able to type without erasing.

**Comment by vihar** [comment]
Thank you for the feature request. Draft issues have been included in [v0.13-dev](https://github.com/makeplane/plane/releases/tag/v0.13-dev). Feel free to give it a try, and if there's anything we can do to enhance your experience, please don't hesitate to reach out and let us know.
