### ISSUE TITLE
[feature]: Select module and cycle when creating an issue

### ISSUE THREAD

**Issue by slasktrat** [makeplane/plane#1789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It should be possible to select module and cycle when creating new issues

### Why should this be worked on?

It would improve the product

**Comment by aaryan610** [comment]
Hi @slasktrat, thank you for raising this feature request. Rest assured, we will prioritize this request and work on it as soon as we have the necessary resources and capacity. We appreciate your patience, and please feel free to reach out if you have any further suggestions or questions.
