### ISSUE TITLE
[bug]: self-hosting, when signin using magic email link, then enter non-existent email, it will create a new account despite setting ENABLE_SIGNUP=false

### ISSUE THREAD

**Issue by WilsonLe** [makeplane/plane#1792]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When signin using magic email link, then enter non-existent email, it will create a new account despite setting ENABLE_SIGNUP=false.

### Steps to reproduce

In self-hosting solution, when signin using magic email link, then enter non-existent email, it will create a new account despite setting ENABLE_SIGNUP=false.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by WilsonLe** [comment]
Any updates on this issue? The PR that addresses this is still open.

**Comment by vihar** [comment]
@WilsonLe, we've fixed this issue on our latest release, v0.14-dev. for more details on the solve, we've documented our new onboarding flow, please view them here: https://docs.plane.so/sign-up-sign-in
