### ISSUE TITLE
[bug]: Migrations Error after pulling migration 0042 and 0043

### ISSUE THREAD

**Issue by burenhuu** [makeplane/plane#1864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Backend end is not starting due to migration conflict
planebackend         |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/graph.py", line 60, in raise_error
planebackend         |     raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
planebackend         |   django.db.migrations.exceptions.NodeNotFoundError: Migration db.0043_auto_20230809_1645 dependencies reference nonexistent parent node ('db', '0042_alter_analyticview_created_by_and_more')

### Steps to reproduce

1. docket-compose logs -f
2. In error logs planebackend there is a migration error

### Browser

Google Chrome

### Version

Cloud

**Comment by pablohashescobar** [comment]
Hi @burenhuu, you can switch to master branch and use the pre-built docker images.

**Comment by pablohashescobar** [comment]
Hi @burenhuu, this is resolved in the current master branch it would be awesome if you could re-pull and rerun the migrations. Closing this issue
