### ISSUE TITLE
[bug]: backspace and preformatted text adjacent to lists do not work

### ISSUE THREAD

**Issue by fdr** [makeplane/plane#1867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I backspace on a newline in preformatted text block, it should delete a newline character. In this situation, it does not work:

![image](https://github.com/makeplane/plane/assets/7191/8512ab68-05f7-4ce4-acba-3d8262610054)

### Steps to reproduce

1. type `1.` to create a list. Give it a heading, like "Hello" as in the screenshot.
2. Press "enter" twice to end the list
3. use \`\`\` and then enter to create a preformatted text block
4. Type some non-newline characters into the preformatted block, add some newline characters
5. Try backspace; it doesn't work.

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @fdr! Thank you for reporting this bug. Could you please share a video recording with us?

**Comment by Palanikannan1437** [comment]
Hey @fdr, I tried to reproduce this bug with your steps but sadly am not able to do so, we've improved our Code Blocks recently at https://github.com/makeplane/plane/pull/2745 and these changes will be reflected after the upcoming release 😄, hopefully that fixes this bug...

Could you please check if you're still facing this issue/reproduce it? Thanks!

**Comment by vihar** [comment]
@fdr, we are unable to replicate issue; closing now. Also, several improvements made to rich text editors.
