### ISSUE TITLE
[bug]: Cannot install "@tiptap-pro/extension-unique-id"

### ISSUE THREAD

**Issue by aditipatelpro** [makeplane/plane#1869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to install dependencies using yarn, it throws an unexpected error with the following error message.

> " An unexpected error occurred: "https://registry.tiptap.dev/@tiptap-pro%2fextension-unique-id/-/extension-unique-id-2.1.0.tgz: Request failed \"500 Internal Server Error\".

![image](https://github.com/makeplane/plane/assets/20130692/ee74bc89-f790-4d87-9e74-028a7d849fd6)

 

### Steps to reproduce

Run 

> yarn install

### Browser

Google Chrome

### Version

Local

**Comment by Palanikannan1437** [comment]
Hey @aditipatelpro, we'd have to update our local dev setup instructions, but you'd simply have to signup for Tiptap Pro (which is free) and paste the keys that it gives in a .npmrc file. Please let me know if that works for you, thanks

**Comment by gusutabopb** [comment]
Is there an option to use plane *without* relying on a third-party, non-open-source, non-self-hostable service? I'd take that even if that'd mean losing some features.

Plane advertises itself as an "Open-source, self-hosted project planning tool". I find it odd having to sign for something like TipTap to install it.

**Comment by vihar** [comment]
Plane was indeed in its early stages of development, and during this phase, we have been experimenting with various editors. The use of TipTap was a part of this experimentation process. 

One of the challenges we encountered with TipTap was its reliance on the pro extension, but I want to assure you that we have already addressed this issue. We are continuously working to improve Plane, and your feedback is valuable to us. If you have any more questions or need additional context, please feel free to ask.

More on this PR: https://github.com/makeplane/plane/pull/2209

**Comment by Palanikannan1437** [comment]
@gusutabopb the dependency on TipTap pro extension has been removed now. The dependency was initially used for uniquely identifying nodes in the Editor to track images such that they can be cleared i.e. avoided from piling up in your storage. But we've come a long way from there. 

The algorithm we now use to do this has improved quite a bit now! Now with version `v0.14-dev` , when you remove an image from the Editor, it is "marked" for delete after 7 days unless you do an undo operation anytime before this that brings back the image!

**Comment by Palanikannan1437** [comment]
Hey there @gusutabopb, the dependency on TipTap pro extension has been removed now. The dependency was initially used for uniquely identifying nodes in the Editor to track images such that they can be cleared i.e. avoided from piling up in your storage. But we've come a long way from there. 

The algorithm we now use to do this has improved quite a bit now! Now with version `v0.14-dev` , when you remove an image from the Editor, it is "marked" for delete after 7 days unless you do an undo operation anytime before this that brings back the image!

Here's the PR for the same https://github.com/makeplane/plane/pull/2859
