### ISSUE TITLE
[bug]: Duplicate issue with same issue ID created when adding multiple assignees. 

### ISSUE THREAD

**Issue by vishnus** [makeplane/plane#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create an issue, and assign it to multiple people, the same number of issues get created with the same number of assignees, all with same issue ID. Screenshot:
![image](https://github.com/makeplane/plane/assets/598121/ba3083a1-127b-4e18-a4c6-5b60a7489a09)

The assignees see only 1 issue, but the person who created the issue sees multiple. 

### Steps to reproduce

1. Click on Add Issue 
2. Enter the details
3. Add more than 1 assignees.
4. Check "My issues" page. 

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @vishnus thanks for reporting, PR has been already raised #1882
