### ISSUE TITLE
[feature]: Ability to add someone else as a subscriber

### ISSUE THREAD

**Issue by sakyork** [makeplane/plane#1898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be helpful for someone to be able to add another user as a subscriber. 

### Why should this be worked on?

We currently use the function to add someone as a watcher to tickets without the need to ping them and to keep them in the know on specific issues as planning happens within Jira.

**Comment by rhea0110** [comment]
Hello @sakyork! Thank you for the feature request. Our team will begin working on it soon.

**Comment by vihar** [comment]
This feature is already available on both our cloud and self-hosted versions. Find the subscribe button on the top right of the issue detail page.

![CleanShot 2024-07-03 at 14 00 19@2x](https://github.com/makeplane/plane/assets/16307796/486fda33-d0c8-42c0-8031-a774db08905c)

**Comment by vihar** [comment]
Other users will automatically subscribe if they are mentioned in the issue detail, assigned, or mentioned in the comment.
