### ISSUE TITLE
[bug]: Getting an error during the local installation , docker compose step

### ISSUE THREAD

**Issue by emecas** [makeplane/plane#1912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

~/plane (develop)
$ docker compose up -d
[+] Building 165.8s (23/31)
 => [internal] load .dockerignore                                                                                                                                                                 
0.0s  => => transferring context: 92B                                                                                                                                                                  
0.0s  => [internal] load build definition from Dockerfile.web                                                                                                                                          
0.0s  => => transferring dockerfile: 2.18kB                                                                                                                                                            
0.0s  => [internal] load metadata for docker.io/library/node:18-alpine                                                                                                                                 
0.9s  => [internal] load build context                                                                                                                                                                 
0.2s  => => transferring context: 88.63kB                                                                                                                                                              
0.2s  => [builder 1/6] FROM docker.io/library/node:18-alpine@sha256:3482a20c97e401b56ac50ba8920cc7b5b2022bfc6aa7d4e4c231755770cf892f                                                                   
0.0s  => CACHED [runner  2/12] WORKDIR /app                                                                                                                                                            
0.0s  => CACHED [runner  3/12] RUN addgroup --system --gid 1001 plane                                                                                                                                  
0.0s  => CACHED [runner  4/12] RUN adduser --system --uid 1001 captain                                                                                                                                 
0.0s  => CACHED [builder 2/6] RUN apk add --no-cache libc6-compat                                                                                                                                      
0.0s  => CACHED [builder 3/6] WORKDIR /app                                                                                                                                                             
0.0s  => CACHED [builder 4/6] RUN yarn global add turbo                                                                                                                                                
0.0s  => [builder 5/6] COPY . .                                                                                                                                                                        
0.3s  => [builder 6/6] RUN turbo prune --scope=app --docker                                                                                                                                            
0.8s  => CACHED [installer  4/13] COPY .gitignore .gitignore                                                                                                                                           
0.0s  => CACHED [installer  5/13] COPY --from=builder /app/out/json/ .                                                                                                                                 
0.0s  => CACHED [installer  6/13] COPY --from=builder /app/out/yarn.lock ./yarn.lock                                                                                                                   
0.0s  => CACHED [installer  7/13] RUN yarn install --network-timeout 500000                                                                                                                            
0.0s  => [installer  8/13] COPY --from=builder /app/out/full/ .                                                                                                                                        
0.1s  => [installer  9/13] COPY turbo.json turbo.json                                                                                                                                                  
0.0s  => [installer 10/13] COPY replace-env-vars.sh /usr/local/bin/                                                                                                                                    
0.0s  => [installer 11/13] RUN chmod +x /usr/local/bin/replace-env-vars.sh                                                                                                                             
0.5s  => [installer 12/13] RUN yarn turbo run build --filter=app                                                                                                                                     
162.3s  => ERROR [installer 13/13] RUN /usr/local/bin/replace-env-vars.sh http://NEXT_PUBLIC_WEBAPP_URL_PLACEHOLDER http://localhost:8000                                                                0.6s ------
 > [installer 13/13] RUN /usr/local/bin/replace-env-vars.sh http://NEXT_PUBLIC_WEBAPP_URL_PLACEHOLDER http://localhost:8000:
#0 0.552 /bin/sh: /usr/local/bin/replace-env-vars.sh: not found
------
failed to solve: process "/bin/sh -c /usr/local/bin/replace-env-vars.sh http://NEXT_PUBLIC_WEBAPP_URL_PLACEHOLDER ${NEXT_PUBLIC_API_BASE_URL}" did not complete successfully: exit code: 127

### Steps to reproduce

$ git clone https://github.com/makeplane/plane
Cloning into 'plane'...
remote: Enumerating objects: 30184, done.
remote: Counting objects: 100% (5426/5426), done.
remote: Compressing objects: 100% (1001/1001), done.
Receiving objects: 100% (30184/30184), 32.77 MiB | 6.87 MiB/s, done.sed 24758 eceiving objects: 100% (30184/30184), 31.36 MiB | 6.75 MiB/s

Resolving deltas: 100% (21486/21486), done.
Updating files: 100% (1130/1130), done.

$ cd plane/

~plane (develop)
$ ls

apiserver/  apps/               CONTRIBUTING.md  docker-compose.yml      Dockerfile  LICENSE.txt  package.json  README.md             setup.sh*  turbo.json
app.json    CODE_OF_CONDUCT.md  deploy/          docker-compose-hub.yml  heroku.yml  nginx/       packages/     replace-env-vars.sh*  start.sh*  yarn.lock

~plane (develop)
$ chmod +x setup.sh

~plane (develop)
$ ./setup.sh http://localhost

 Instructions for generating TipTap Pro Extensions Auth Token

 1. Head over to TipTap cloud's Pro Extensions Page, https://collab.tiptap.dev/pro-extensions
 2. Copy the token given to you under the first paragraph, after 'Here it is'

 Please Enter Your TipTap Pro Extensions Authentication Token:  iF+/o2OMzG9pxI4I************************************************************************************************

~plane (develop)
$ docker compose up -d

### Browser

Mozilla Firefox

### Version

Local

**Comment by emecas** [comment]
I have tried master branch as well (#1167) , getting a different error:

    ~plane (master)
    $ docker compose up -d
    [+] Building 388.1s (21/31)
     => [internal] load build definition from Dockerfile.web                                                                                                                                                     
     0.0s  => => transferring dockerfile: 2.18kB                                                                                                                                                                 
     0.0s  => [internal] load .dockerignore                                                                                                                                                                  
    0.0s  => => transferring context: 92B                                                                                                                                                                  
    0.0s  => [internal] load metadata for docker.io/library/node:18-alpine                                                                                                                                 
    2.8s  => [internal] load build context                                                                                                                                                                 
    0.2s  => => transferring context: 2.32MB                                                                                                                                                               
    0.1s  => [builder 1/6] FROM docker.io/library/node:18-    alpine@sha256:3482a20c97e401b56ac50ba8920cc7b5b2022bfc6aa7d4e4c231755770cf892f                                                                   
    0.0s  => CACHED [runner  2/12] WORKDIR /app                                                                                                                                                            
    0.0s  => CACHED [runner  3/12] RUN addgroup --system --gid 1001 plane                                                                                                                                  
    0.0s  => CACHED [runner  4/12] RUN adduser --system --uid 1001 captain                                                                                                                                     
    0.0s  => CACHED [builder 2/6] RUN apk add --no-cache libc6-compat                                                                                                                                      
    0.0s  => CACHED [builder 3/6] WORKDIR /app                                                                                                                                                             
    0.0s  => [installer  4/13] COPY .gitignore .gitignore                                                                                                                                                      
    0.0s  => CACHED [builder 4/6] RUN yarn global add turbo                                                                                                                                                
    0.0s  => [builder 5/6] COPY . .                                                                                                                                                                        
    0.1s  => [builder 6/6] RUN turbo prune --scope=app --docker                                                                                                                                            
    0.7s  => [installer  5/13] COPY --from=builder /app/out/json/ .                                                                                                                                        
    0.0s  => [installer  6/13] COPY --from=builder /app/out/yarn.lock ./yarn.lock                                                                                                                          
    0.0s  => [installer  7/13] RUN yarn install --network-timeout 500000                                                                                                                                 
    268.6s  => [installer  8/13] COPY --from=builder /app/out/full/ .                                                                                                                                        
    0.3s  => [installer  9/13] COPY turbo.json turbo.json                                                                                                                                                  
    0.1s  => [installer 10/13] COPY replace-env-vars.sh /usr/local/bin/                                                                                                                                    
    0.1s  => [installer 11/13] RUN chmod +x /usr/local/bin/replace-env-vars.sh                                                                                                                            
    13.1s  => [installer 12/13] RUN yarn turbo run build --filter=app                                                                                                                                     
    101.8s  => => # app:build:
     => => # app:build: info  - Linting and checking validity of types...
     => => # app:build: The prop value with an expression type of TSNonNullExpression could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this f  => => # ixed immediately.

     => => # app:build: The prop value with an expression type of TSNonNullExpression could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this f  => => # ixed immediately.
failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF

**Comment by pablohashescobar** [comment]
Hi @emecas, can you use the pre-built docker images by running the command `docker compose -f docker-compose-hub.yml up`.

**Comment by kotasudhakar** [comment]
i think i understood the issue here. This is probably because you are running this with different user other than the root or equivalent user with sudo right. generally this path ("/usr/local/bin/") has a restricted access. @pablohashescobar  @vamsi , Is there a reason we are specifically doing this way? (as in copying the file to /usr/local/bin/) and then running it. Can we just do it normally without copying it to that path?

Is yes, i can do necessary changes and raise a PR... (could be my potential first PR😋)

duplicate - #1916

**Comment by pablohashescobar** [comment]
Hello @kotasudhakar, the error isn't caused by the script itself; rather, it's due to the updated tiptap package in the `develop` branch.

**Comment by kotasudhakar** [comment]
> Hello @kotasudhakar, the error isn't caused by the script itself; rather, it's due to the updated tiptap package in the `develop` branch.

Okay @pablohashescobar
