### ISSUE TITLE
[bug]: /bin/sh: can't open '/usr/local/bin/start.sh': Permission denied

### ISSUE THREAD

**Issue by slushpuppy** [makeplane/plane#1916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After running the installation process using either the master/develop branch, frontend refuses to start- all requests leads to 404 error

 docker logs planefrontend
/bin/sh: can't open '/usr/local/bin/start.sh': Permission denied
/bin/sh: can't open '/usr/local/bin/start.sh': Permission denied
/bin/sh: can't open '/usr/local/bin/start.sh': Permission denied
/bin/sh: can't open '/usr/local/bin/start.sh': Permission denied
/bin/sh: can't open '/usr/local/bin/start.sh': Permission denied

### Steps to reproduce

1) Follow installation steps
2) visit browser to receive 404 JSON response
3)  docker logs planefrontend

### Browser

Mozilla Firefox

### Version

Local

**Comment by pablohashescobar** [comment]
Hi @slushpuppy, just to check are you using the `docker-compose-hub.yml` or `docker-compose.yml`.

**Comment by kotasudhakar** [comment]
i think i understood the issue here. This is probably because you are running this with different user other than the root or equivalent user with sudo right. generally this path ("/usr/local/bin/") has a restricted access. @pablohashescobar @vamsi  is there a reason we are specifically doing this way? (as in copying the file to /usr/local/bin/) and then running it. Can we just do it normally without copying it to that path?

Is yes, i can do necessary changes and raise a PR... (could be my potential first PR😋)

**Comment by slushpuppy** [comment]
> Hi @slushpuppy, just to check are you using the `docker-compose-hub.yml` or `docker-compose.yml`.

docker-compose.yml

**Comment by slushpuppy** [comment]
> i think i understood the issue here. This is probably because you are running this with different user other than the root or equivalent user with sudo right. generally this path ("/usr/local/bin/") has a restricted access. @pablohashescobar @vamsi is there a reason we are specifically doing this way? (as in copying the file to /usr/local/bin/) and then running it. Can we just do it normally without copying it to that path?
> 
> Is yes, i can do necessary changes and raise a PR...

Ah, I am using WSL-1 if that helps

**Comment by slushpuppy** [comment]
> i think i understood the issue here. This is probably because you are running this with different user other than the root or equivalent user with sudo right. generally this path ("/usr/local/bin/") has a restricted access. @pablohashescobar @vamsi is there a reason we are specifically doing this way? (as in copying the file to /usr/local/bin/) and then running it. Can we just do it normally without copying it to that path?
> 
> Is yes, i can do necessary changes and raise a PR...

unfortunately no, I am using debian buster as root- docker switches users in containers right tho?

**Comment by kotasudhakar** [comment]
i understand, may i know which user are you using while running the ``` docker compose up ```(not in the container, but at host machine level), is  it the root user at the host machine level??

**Comment by pablohashescobar** [comment]
Hi @slushpuppy, can you check with `docker-compose-hub.yml` .

**Comment by slushpuppy** [comment]
works with docker-compose-hub!
