### ISSUE TITLE
[feature]: I want to add a hover effect and a discord logo in "chat with us in discord" Button

### ISSUE THREAD

**Issue by taqui-786** [makeplane/plane#1924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Sir i want to add a **hover** effect in "chat with us on Discord" button and Discord **logo**

### Why should this be worked on?

Because there is no hover effect on the button and no logo . If there is a discord logo and hover effect then it will improve user experience .

**Comment by abhinav700** [comment]
I would like to work on this issue. Can you please assign it to me? @taqui-786
