### ISSUE TITLE
[bug]: No way to minimize cycle sidebar on mobile

### ISSUE THREAD

**Issue by kabo** [makeplane/plane#1937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I open plane on my android phone and go to a cycle, the button to minimize the cycle sidebar is out of reach, making it unusable.

This is the sidebar I'm referring to
![image](https://github.com/makeplane/plane/assets/357601/bbef185d-dfa0-4958-a854-2bfe02a2c352)

This is the button that becomes unreachable
![image](https://github.com/makeplane/plane/assets/357601/2c741477-c264-4db9-aa23-bcff2035ce99)

### Steps to reproduce

1. go to a cycle on mobile, or just make your window narrow

### Browser

Other

### Version

Cloud

**Comment by rhea0110** [comment]
Hello @kabo! Thank you for reporting this bug to us. We will address it promptly. To provide an even smoother experience, we are in the process of developing a mobile application. Stay tuned for updates!

**Comment by vihar** [comment]
Plane will soon ship native mobile apps, today web version will not support mobile responsivess. Please follow our changelog page for more updates: https://plane.so/changelog.
