### ISSUE TITLE
[bug]: defult login try show this "someting went wrong please try again later of  contact the support team "

### ISSUE THREAD

**Issue by 250121ss** [makeplane/plane#1952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Sometime I will try some time 
 #/same issue and registration same issue 

### Steps to reproduce

Installation completed. But default login not working and sing up not working 

![Annotate-a-local-image](https://github.com/makeplane/plane/assets/108991960/a8153d7e-d12e-4b3f-9d1e-d79ef1f4c991)

### Browser

Google Chrome

### Version

Cloud

**Comment by pablohashescobar** [comment]
Hi @250121ss, can you share your network logs and the logs for both frontend and backend container.

**Comment by 250121ss** [comment]
@pablohashescobar  sure , actually i am using this ip http://3.143.194.0/  address but show this something ip address
![Annotate-a-local-image(1)](https://github.com/makeplane/plane/assets/108991960/968e562f-d195-485e-aed9-308049245737)

**System Logs** file attached  url plz check this   - https://drive.google.com/file/d/1cphZFFhG-soEHPPdy2p8NxCobqZOFKtd/view?usp=sharing

**Docker Log backend attached** 

2023/08/24 02:50:11 [error] 8#8: *154 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "GET /api/users/me/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/users/me/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
103.197.115.186 - - [24/Aug/2023:02:50:11 +0000] "GET /api/users/me/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
103.197.115.186 - - [24/Aug/2023:02:50:14 +0000] "GET /api/users/me/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023/08/24 02:50:14 [error] 8#8: *154 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "GET /api/users/me/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/users/me/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
2023/08/24 02:50:18 [error] 8#8: *156 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "POST /api/sign-in/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/sign-in/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
103.197.115.186 - - [24/Aug/2023:02:50:18 +0000] "POST /api/sign-in/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023/08/24 02:50:37 [error] 8#8: *156 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "GET /api/users/me/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/users/me/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
103.197.115.186 - - [24/Aug/2023:02:50:37 +0000] "GET /api/users/me/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
103.197.115.186 - - [24/Aug/2023:02:50:37 +0000] "POST /api/sign-in/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023/08/24 02:50:37 [error] 8#8: *154 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "POST /api/sign-in/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/sign-in/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
2023/08/24 02:54:10 [error] 8#8: *162 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "GET /api/users/me/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/users/me/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
103.197.115.186 - - [24/Aug/2023:02:54:10 +0000] "GET /api/users/me/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
103.197.115.186 - - [24/Aug/2023:02:54:20 +0000] "GET /api/users/me/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023/08/24 02:54:20 [error] 8#8: *162 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "GET /api/users/me/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/users/me/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
2023/08/24 02:56:55 [error] 8#8: *166 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "GET /api/users/me/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/users/me/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
103.197.115.186 - - [24/Aug/2023:02:56:55 +0000] "GET /api/users/me/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
103.197.115.186 - - [24/Aug/2023:02:56:55 +0000] "POST /api/sign-in/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023/08/24 02:56:55 [error] 8#8: *168 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "POST /api/sign-in/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/sign-in/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
185.254.196.186 - - [24/Aug/2023:03:00:11 +0000] "GET /.env HTTP/1.1" 200 2364 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
185.254.196.186 - - [24/Aug/2023:03:00:11 +0000] "POST / HTTP/1.1" 405 1989 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
103.197.115.186 - - [24/Aug/2023:03:02:17 +0000] "GET /api/users/me/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
103.197.115.186 - - [24/Aug/2023:03:02:17 +0000] "POST /api/sign-in/ HTTP/1.1" 502 559 "http://3.143.194.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
2023/08/24 03:02:17 [error] 8#8: *175 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "GET /api/users/me/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/users/me/", host: "3.143.194.0", referrer: "http://3.143.194.0/"
2023/08/24 03:02:17 [error] 8#8: *177 connect() failed (113: Host is unreachable) while connecting to upstream, client: 103.197.115.186, server: , request: "POST /api/sign-in/ HTTP/1.1", upstream: "http://172.18.0.5:8000/api/sign-in/", host: "3.143.194.0", referrer: "http://3.143.194.0/"

**Frontend i don't know** 
i am using only this github https://github.com/makeplane/plane

**Comment by 250121ss** [comment]
any Updated.

**Comment by iwanmikhajlov** [comment]
Got the same problem

**Comment by vihar** [comment]
We have upgraded our self-hosting setup, and the process should now be seamless. For additional information, kindly refer our documentation at https://docs.plane.so/self-hosting/. If you're still facing the issue on the new version, please let us know.
