### ISSUE TITLE
[bug]: Changing the port causes sign up to fail

### ISSUE THREAD

**Issue by pouria-ariafar** [makeplane/plane#1960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I installed the latest version on this date and if we don't change the port, everything is fine, but when the port is changed in the .env file, for example, it becomes 6080 or any other port. It is no longer possible to join and plane gives an error.
<img src="https://i.imgur.com/HqkaAQN.png" alt="enter image description here">

### Steps to reproduce

1: git clone --depth 1 -b master https://github.com/makeplane/plane.git && cd plane
2: ./setup.sh http://<your_ip|domain_name>
4: nano .env (Only NGINX_POR port is changed)
4: docker compose -f docker-compose-hub.yml up -d

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @SardarDelha, after changing the PORT you may have to also change the `NEXT_PUBLIC_API_BASE_URL` and the `WEB_URL`.

**Comment by pablohashescobar** [comment]
Hi @SardarDelha you are correct the PORT should be added to the values.
