### ISSUE TITLE
[bug] Image uploads fail with 400 error 

### ISSUE THREAD

**Issue by leikoilja** [makeplane/plane#1964]
Plane stack version: 
[v0.11-dev](https://github.com/makeplane/plane/releases/tag/v0.11-dev) but issue has been seen on v0.10 as well

I get an error:
![image](https://github.com/makeplane/plane/assets/10655107/367910c9-19e6-4694-8a23-90000ff426df)

when trying to add any images to issues.

No additional logs are seen on either backend or frontend containers, but `network` tab shows error 400 with response:
```
{"error":"Something went wrong please try again later"}
```
backend container simply logs:
```
172.31.0.1:39878 - "POST /api/workspaces/test/projects/2d8dda48-53ce-4e54-8fe3-136e8783685a/issues/299f6389-ddfc-4e97-9274-94d42ca1995c/issue-attachments/ HTTP/1.1" 400
```

double checked image formats and sizes, tried with both .jpg and .png, files sizes are under 1MB
![image](https://user-images.githubusercontent.com/10655107/262901888-87769f1b-f65e-45b5-8a84-5db9195e3817.png)

p.s. i do use s3 storage (minio) and set all the credentials right on the env variables

_Originally posted by @leikoilja in https://github.com/makeplane/plane/issues/1716#issuecomment-1657231768_

**Comment by NarayanBavisetti** [comment]
Hey @leikoilja, this issue is fixed in our release 0.14

**Comment by leikoilja** [comment]
Yay, thank you, @NarayanBavisetti, for the update. Will try testing it some time soon.
Shall we close this issue?

**Comment by NarayanBavisetti** [comment]
Yes sure.
