### ISSUE TITLE
[bug]: planefrontend Illegal instruction

### ISSUE THREAD

**Issue by MyWay** [makeplane/plane#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

+ echo 'Starting Plane Frontend..'
Starting Plane Frontend..
+ node apps/app/server.js
Illegal instruction (core dumped)

### Steps to reproduce

```
docker compose up -d
```
This happened after updating to the latest version, before it was working.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @MyWay just to confirm are you in the latest `master` branch ?

**Comment by MyWay** [comment]
> Hi @MyWay just to confirm are you in the latest `master` branch ?

Hi! I'm using latest from docker.

**Comment by pablohashescobar** [comment]
Hi @MyWay, can you pull the updated code also from github for the 0.11-dev there have been changes in the `docker-compose-hub.yml` file.

**Comment by amunrarara** [comment]
Cheers, I'm having the same issue. I've just pulled the repo for the first time, assured I'm on the master branch, and run `docker compose -f docker-compose-hub.yml up` with a clean setup. The `web` workspace is continually throwing: 

```
web                    | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
web                    | Illegal instruction
```

**Comment by vihar** [comment]
@amunrarara, apologies for the late reply. are you still seeing this issue?

**Comment by MyWay** [comment]
I updated it using latest codebase, but I get a generic yarn error with SIGILL.

**Comment by pablohashescobar** [comment]
Can you try removing all the plane containers and restarting all the containers.

**Comment by MyWay** [comment]
Same:

```
371.0 web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
679.3 web:build: info  - Creating an optimized production build...
703.8 web:build: error Command failed with signal "SIGILL".
703.8 web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
705.0 web:build: ERROR: command finished with error: command (/app/web) yarn run build exited (1)
705.0 web#build: command (/app/web) yarn run build exited (1)
705.0 
705.0  Tasks:    5 successful, 6 total
705.0 Cached:    0 cached, 6 total
705.0   Time:    11m38.592s 
705.0 Failed:    web#build
705.0 
705.1  ERROR  run failed: command  exited (1)
709.0 error Command failed with exit code 1.
709.2 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn turbo run build --filter=web" did not complete successfully: exit code: 1
```

**Comment by vihar** [comment]
@MyWay we have upgraded our self-hosting setup, and the process should now be seamless. Can you upgrade to the latest version, [v0.14-dev](https://github.com/makeplane/plane/releases/tag/v0.14-dev) and see if the issue still persists. thanks.
