### ISSUE TITLE
[feature]: ARM64 docker images

### ISSUE THREAD

**Issue by viseshrp** [makeplane/plane#1989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There are no ARM 64 images of plane. Self hosting steps fail if run on ARM machines like a Raspberry pi 4B. 

### Why should this be worked on?

Docker compose fails on ARM machines. Extend support to a broader audience?

**Comment by kotasudhakar** [comment]
this is actually quite helpful, can someone please work on this arm64 based docker images

**Comment by j3mu5** [comment]
I join this and kindly ask for an image for a raspberry pi 4 or 5

**Comment by viseshrp** [comment]
I have moved on to other open source tools (https://github.com/plankanban/planka if anyone is interested) due to the lack of support here. Thanks for triaging this, I guess.

**Comment by TheiLLeniumStudios** [comment]
This is still needed. We've transitioned our workloads to ARM based machines and almost every other tool supports multi-arch. It would be great if we can have multi-arch images for Plane as well

**Comment by MrMarans** [comment]
Yeah its really sad. I would love to install it on a pi so I can use it with any device in my network all the time.
