### ISSUE TITLE
[bug]: self-host Export issues to a CSV file. Failed

### ISSUE THREAD

**Issue by GeekWorkCode** [makeplane/plane#1990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

self-host Export issues to a CSV file. Failed

### Steps to reproduce

1、Export now 2、Previous Exports  click Refresh status   3、Export to CSV Failed

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @GeekWorkCode, thanks for reporting the bug we are working on a fix.
