### ISSUE TITLE
Tiptap: "error": "Something went wrong!"

### ISSUE THREAD

**Issue by dmikushin** [makeplane/plane#1991]
Currently, Tiptap is broken, and building `v0.11-dev` Docker container from source is not possible:

```
error An unexpected error occurred: "https://registry.tiptap.dev/@tiptap-pro%2fextension-unique-id/-/extension-unique-id-2.1.0.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install --network-timeout 500000' returned a non-zero code: 1
ERROR: Service 'plane-web' failed to build
```

Accessing `https://registry.tiptap.dev/@tiptap-pro%2fextension-unique-id/-/extension-unique-id-2.1.0.tgz` in the browser gives:

```
{
  "error": "Something went wrong!"
}
```

Looks like their service is unreliable and should be replaced.

**Comment by tyleraharrison** [comment]
I'm having the same issue, is TipTap required to function? Kind of defeats the whole self-hosted thing...

**Comment by dmikushin** [comment]
This stupid thing is gone in `0.13-dev`
