### ISSUE TITLE
[bug]: Date picker select is always off by one day

### ISSUE THREAD

**Issue by tyleraharrison** [makeplane/plane#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I select an end date, it sets the date to the day prior than the one I selected

Currently running `v0.11.0-dev`

### Steps to reproduce

1. Create an issue
2. Select an end date
3. Check the end date selected

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by tyleraharrison** [comment]
Additionally, the `PATCH` request looks correct but the UI is showing otherwise:
![image](https://github.com/makeplane/plane/assets/16725119/1d370cc2-20a8-4c87-b197-f1ec07ce8a05)

It looks like even the `GET` is pulling the correct date:
![image](https://github.com/makeplane/plane/assets/16725119/2e546c26-5d86-42ce-8a7f-976dd6873710)

But here is the UI:
![image](https://github.com/makeplane/plane/assets/16725119/aa1ee99e-31f6-4f7f-8f6e-980e125de698)

**Comment by tyleraharrison** [comment]
I've got a feeling this is because of how getDate() works with timezones, it mandates UTC and I live in CST.

**Comment by kripainc** [comment]
Similar issue with hosted version as well. 
Both the start and end date not working as expected when setting up or updating a project's Cycle. ie. Selecting 22nd Sep on date picker results in setting 21st Sep. It's very likely due to TZ - I'm testing this from NYC timezone.

**Comment by gicellamare** [comment]
Similar issue here, using GMT-3 timezone

**Comment by vihar** [comment]
Related to https://github.com/makeplane/plane/issues/3074, closing this issue to continue conversation on the new thread.
