### ISSUE TITLE
[bug]: plane sends requests on every keystroke

### ISSUE THREAD

**Issue by Thunderbottom** [makeplane/plane#1998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Whenever someone tries to create an issue by attaching 2 (or more) images and then starts typing content, Plane starts sending (failing) requests with every keystroke. This only happens when 2 or more images are attached to the issue.

Here's the image of the network tab, not sure if it'll be helpful:

![image](https://github.com/makeplane/plane/assets/11243138/8a1769dd-9400-490a-bc2b-b3e5dcee5ac9)

### Steps to reproduce

1. Create a new issue
2. Attach multiple images to the issue
3. Start typing in the textbox

You'll notice in the network tab (and even console) that Plane sends a `DELETE` request every time a key is pressed. This shouldn't be happening, since a 1000-word issue will result in a 1000 requests being attempted.

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by aaryan610** [comment]
Hi @Thunderbottom, apologies for the inconvenience. But can you let me know what you mean by attachment, is it the issue attachments, or uploading a file to the rich text editor?

**Comment by Palanikannan1437** [comment]
@Thunderbottom, thanks for reporting this, I'll have a look at this and fix it!

Until then as a temporary workaround, you can create an Issue (with multiple images, etc) without adding a description in the modal while creating it, but after navigating to the Issue😄

Thanks so much for the network tab image, definitely super helpful 🙌
