### ISSUE TITLE
[bug]: Migration error

### ISSUE THREAD

**Issue by torbenraab** [makeplane/plane#2025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I want to start the application from the current develop branch there is an migration error regarding the two issues #2009 and #2006 which use the same migration number.

I really want to test my PR but I can't get it running

### Steps to reproduce

1. Clone the repo
2. Start the application from the docker-compose.yml not the docker-compose-hub.yml

### Browser

Google Chrome

### Version

Self-hosted

**Comment by NarayanBavisetti** [comment]
Hi @torbenraab thank you for reporting this, we will be fixing the migrations as soon as possible. Until then you can run 
`python manage.py makemigrations --merge` to make a new migration file which will be a merge of both file and then you can test your PR.

**Comment by torbenraab** [comment]
Fixed in #2044
