### ISSUE TITLE
 Long titles for modules, task are not visible in the grid view.

### ISSUE THREAD

**Issue by nandansn** [makeplane/plane#2031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Long title are hidden in the grid view, if we provide tool tip while hovering the mouse over the title it would be really helpful.

### Why should this be worked on?

For pleasant usability experience
![Screenshot 2023-08-31 141218](https://github.com/makeplane/plane/assets/23096457/30de7d3e-b223-4b30-a22a-9f8d5cde6da2)

**Comment by rhea0110** [comment]
Hello @nandansn, thank you for the feature request and suggestion. Our team will be working on it soon.

**Comment by mikecanann** [comment]
![image](https://github.com/makeplane/plane/assets/1325633/eb8ef555-3332-4a05-8eed-a8ccd22ebdec)

Looks like this issue should be closed

**Comment by srinivaspendem** [comment]
This is resolved 

> ![image](https://private-user-images.githubusercontent.com/1325633/326099041-eb8ef555-3332-4a05-8eed-a8ccd22ebdec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mjk2MDcsIm5iZiI6MTcxNTkyOTMwNywicGF0aCI6Ii8xMzI1NjMzLzMyNjA5OTA0MS1lYjhlZjU1NS0zMzMyLTRhMDUtOGVlZC1hOGNjZDIyZWJkZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMDcwMTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVkODg0YWJmYzY4Y2Y5ZTBkNTBlMzAwNTNjMDAxZjQ1YWEzMTU3OWViNzRiYTJlNTY2MzIyZTdjYjI1NDVjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ME1XKcZtaJDfAFR_v9GrRjo0MFPR-gXDBA3L7qhyih0)
> 
> Looks like this issue should be closed
