### ISSUE TITLE
[bug]: Dragging a task card temporarily creates a duplicate of it, after which the card cannot be moved at all.

### ISSUE THREAD

**Issue by AlinaSelivanova** [makeplane/plane#2034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Dragging a task card temporarily creates a duplicate of it, after which the card cannot be moved at all.
I expect that when a card is dragged, if it hasn't reached the next column, the card will return to its previous stage. Without creating a duplicate card. And I can move the cards repeatedly

### Steps to reproduce

1. Create a bug card
2. move the card, but so that it does not reach the indicated column

https://github.com/makeplane/plane/assets/83757237/2588c285-86f7-4a1c-bf4e-5678350e5f14

### Browser

Google Chrome

### Version

Self-hosted

**Comment by chahmedejaz** [comment]
Hey @rhea0110 - I'd love to work on this, can you please assign it to me?

**Comment by vihar** [comment]
@AlinaSelivanova, this issue is fixed on our latest release, please upgrade (https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x). If you're still facing this issue, please let us know.
