### ISSUE TITLE
[feature]: Add ability to close/complete a project

### ISSUE THREAD

**Issue by mindofbeholder** [makeplane/plane#2040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow the ability to "complete" a project so that it no longer appears in my sidebar/metrics but I can still pull it up as an archive for reference if I ever need to pull any of those details back.

### Why should this be worked on?

Projects do eventually complete. At that point it is no longer useful to have it referenced in my metrics or dashboards, but it is nice to be able to look back at the completed issues/pages for future reference in case another project is started with that customer or decision points/actions are called into question later.

**Comment by rhea0110** [comment]
Hey @mindofbeholder! Thank you for the feature request. Our team will be working on it in the near future.

**Comment by JemjinOraho** [comment]
Looking forward to this addition.

**Comment by nickproud** [comment]
This is a big feature. I would want this for sure. At the moment if I finish a project the only thing I can do is delete it if I don't want to see it on my list anymore. Makes things messy!

**Comment by JemjinOraho** [comment]
> This is a big feature. I would want this for sure. At the moment if I finish a project the only thing I can do is delete it if I don't want to see it on my list anymore. Makes things messy!

Yes and a way to archive completed projects for historical review or reference is important.
Maybe a project needs to even be put to archive before deleting as a "safety" feature against accidental deletion.
just my 2 cents on it.

**Comment by CH-JMurray** [comment]
Closing and archiving of projects will be a pretty critical function to our team.  While I don't see Plane marketed as a knowledgebase platform, being able to reference notes and work done while keeping the workspace clean is important.

**Comment by srinivaspendem** [comment]
Hello folks, the archive project feature is live on Plane now to archive the project once it's completed or not being worked on.
