### ISSUE TITLE
[feature]: Display Plane version on Planeweb Dashboard

### ISSUE THREAD

**Issue by Glassback** [makeplane/plane#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When updating Plane, not possible to see on the dashboard if the version changed.

We can add the version on the footer, something like that:

![image](https://github.com/makeplane/plane/assets/10955956/772294ac-4d90-4237-93f8-becbfa4a6bc5)

### Why should this be worked on?

Need to know if our update is successfull.

**Comment by vihar** [comment]
Hey @Glassback this is a great feature request, we'll take this up and ship shortly.

**Comment by vihar** [comment]
Self-hosted users can see their running version by hovering over the plan badge. Attaching the image for reference.

![Screenshot 2024-07-03 at 6 52 22 PM](https://github.com/makeplane/plane/assets/16307796/b3c1dbbc-710b-4d7b-98a4-3f6f0f76ec08)
