### ISSUE TITLE
[feature]: Add "Mark all as read" under notification

### ISSUE THREAD

**Issue by christensen** [makeplane/plane#2107]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

Add button that marks all notifications as read.

### Why should this be worked on?

Clicking "Mark as read" over and over on every single notification gets old quickly.

**Comment by rhea0110** [comment]
Hey @christensen! Thank you for the feature request. I'd like to inform you that this feature has already been included in our latest v0.12-dev release and is now live on app.plane.so.
