### ISSUE TITLE
[bug]: Issue to login after update from 0.11 to 0.12.1

### ISSUE THREAD

**Issue by TheZoker** [makeplane/plane#2152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Since updating from 0.11 to 0.12.1 I can't login anymore. 

Here are the changes I did to my compose file after update:
1. Change `plane-worker` image to `plane-backend`
2. Add `plane-deploy` (also see this github issue #2151 )
3. Change the frontend command form `/usr/local/bin/start.sh apps/app/server.js app` to `/usr/local/bin/start.sh web/server.js web`

Now when I try to login, I get this error:
![image](https://github.com/makeplane/plane/assets/1368405/653f49db-3fd0-4fc4-b2c1-eda5e895a118)

In my console, it shows the following error:
![image](https://github.com/makeplane/plane/assets/1368405/d97aff24-cabb-454c-8aa1-0d02742f9b7b)

The strange thing is, that all this worked in version 0.11 but not with version 0.12

Am I missing a config? 

Which .env is responsible for the /api url? The `NEXT_PUBLIC_API_BASE_URL` is set correctly within my `.env` file to my plane domain

### Steps to reproduce

1. Update from 0.11 to 0.12
2. Try to login

### Browser

Google Chrome

### Version

Self-hosted

**Comment by TheZoker** [comment]
Could be related / fixed by #2135

**Comment by pablohashescobar** [comment]
Hi @TheZoker thanks for reporting this. we are working on updating our docker setup and we will fix this soon.
