### ISSUE TITLE
[feature]: Create tasks by email 

### ISSUE THREAD

**Issue by nick03019** [makeplane/plane#2163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This feature would allow users to send or forward an email to a project-specific email address. On receipt, Plane would create a new task, use the email subject line as the title, and place the body of the email in the description section. An added bonus would be the ability to set start and due dates automatically (e.g., start date = the day the task is created and due date = 14 days after the task is created).

### Why should this be worked on?

I work within higher education disability services. We receive the vast majority of our inquiries and requests via email. This feature would negate the need to manually create tasks after receiving an email. For example, we have a form that receives a lot of traffic. We receive an email for each submission. This feature would allow us to set up a mailbox rule to have email automatically forwarded into a Plane project, thereby automatically creating the tasks we need.

**Comment by rhea0110** [comment]
Hey @nick03019, currently, you cannot create issues using email, but we will be introducing Chrome extensions soon that will help in creating issues from any website. We will keep the community updated once it is available.

Thanks!

**Comment by vihar** [comment]
This feature will be part of our higher-tier plans. Please refer to Email Intake on our pricing page.
