### ISSUE TITLE
[bug]: The first letter of each line will be automatically confirmed into the input box with Chinese input

### ISSUE THREAD

**Issue by SeptemberHX** [makeplane/plane#2164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the description input box of the issue, when the input method is Chinese, the first letter of each line will be automatically confirmed into the input box without waiting for input method suggestions or phrases.

For example: When I want to input `nihao` for words `你好`, the first character `n` is automatically inserted like the `enter` is pressed:

![2023-09-13 09 19 35](https://github.com/makeplane/plane/assets/18042424/4184337b-95bc-4252-9016-4fc702ea4d0d)

### Steps to reproduce

1. Change to Chinese Input, open plane on **Edge Browser**
    * It works fine with Safari
2. create a new issue, and random type something in the description

### Browser

Other

### Version

Self-hosted

**Comment by rhea0110** [comment]
Hey @SeptemberHX! Thank you for your valuable suggestion. We are working on improving the experience of using the editor on our platform.

Stay tuned with us for more exciting updates on the editor.

**Comment by Palanikannan1437** [comment]
Hey @SeptemberHX, thanks for bringing this up, this is interesting....not sure about the tool you're using for completions, maybe that's causing some interference, could you please point me to this extension/tool?

It'd help us debug this much better, thanks 🙌

**Comment by SeptemberHX** [comment]
> Hey @SeptemberHX, thanks for bringing this up, this is interesting....not sure about the tool you're using for completions, maybe that's causing some interference, could you please point me to this extension/tool?
> 
> It'd help us debug this much better, thanks 🙌

I tested with the default chinese-input-method on macOS and Sougou Pinyin, and both of them have this problem:
* macOS 11.3
* Edge 119.0.2151.72
* Sougou Pinyin 6.14

**Comment by strongwer** [comment]
the same situation

**Comment by Palanikannan1437** [comment]
Hey @SeptemberHX and @strongwer, should be fixed in the next release!

https://github.com/makeplane/plane/assets/73993394/c2c1aab2-ca33-4369-801d-870106c4d109

**Comment by vihar** [comment]
@SeptemberHX, this issue is fixed. Please upgrade to the latest version v0.14-dev. Docs here, https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x.
