### ISSUE TITLE
[bug]: Drag and dropping a card takes 5-10 seconds on Firefox (instant on Chrome)

### ISSUE THREAD

**Issue by olivierlambert** [makeplane/plane#2174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When drag'n'dropping a card from a row to another, it takes 5 to 10 seconds to be done in Firefox, while it's instant on Chrome. Did the comparison with the 2 browsers opened on the same instance.

### Steps to reproduce

1. Go in the Views list
2. Use a Kanban view
3. Drag n drop a card from a row to another

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by rhea0110** [comment]
Hey @olivierlambert! Thanks for reporting this bug to us. We will work on it soon and include it in one of our upcoming releases.

**Comment by vihar** [comment]
@olivierlambert, we've introduced substantial changes to our Kanban layout. To benefit from these new features and address this bug, please upgrade to the latest version, `v0.14-dev`.

Docs at, https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x

**Comment by olivierlambert** [comment]
Testing as we speak, thank you very much!
