### ISSUE TITLE
[feature]: Can I help make a Russian translation?

### ISSUE THREAD

**Issue by DenisVASI9** [makeplane/plane#2178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

If you use some package for interface translation, translators from our company could send you a Russian translation. It would be much easier for our employees to use your product.

### Why should this be worked on?

I think translation into many languages is helpful in general. We can also translate into Serbian.

**Comment by gfviegas** [comment]
I'd gladly help translating to portuguese as well.

Maybe create `.po` files?

**Comment by vihar** [comment]
Thank you, @DenisVASI9 and @gfviegas, for your interest in contributing. We are planning to address this issue soon, moving this conversation to main thread for easy communication. 

#2028

**Comment by Magniveo** [comment]
Look fork https://github.com/thomasync/plane/tree/feats-localization
