### ISSUE TITLE
[bug]: Kanban view looses structure on refresh, logout, login, movement to diff page.

### ISSUE THREAD

**Issue by ha-sante** [makeplane/plane#2179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/makeplane/plane/assets/90225652/dcd57a02-eb28-4117-9534-0e86992db447)

I have closed this as you can see.
But when 
- I logout and login again 
- refresh the page or
- move to a diff page

its all reset again and I loose my structure.

### Steps to reproduce

1. Do the regular, projects, tasks etc
2. Change your view to kanban
3. Logout, login, refresh, go to diff page

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @ha-sante! Thank you for reporting this bug. We will fix it and include the fix in one of our upcoming releases.

**Comment by vihar** [comment]
@olivierlambert, we've introduced substantial changes to our Kanban layout. To benefit from these new features and address this bug, please upgrade to the latest version, v0.14-dev.

Docs at, https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x

**Comment by ha-sante** [comment]
Seen thr change! Thanks, and appreciate you guys 👍
