### ISSUE TITLE
[feature]: Slash command: callout

### ISSUE THREAD

**Issue by happyDemon** [makeplane/plane#2183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

`/callout` To generate a textblock with a colored background (optionally set an icon).

https://redgregory.notion.site/Callout-1163474c7cbb41fa9e1b41ec01c6fcd6
https://confluence.atlassian.com/doc/info-tip-note-and-warning-macros-51872369.html

### Why should this be worked on?

Both notion & JIRA have this, it's a good way of adding noticeable context to a page.

Let's say you add a red call out with a warning sign -> makes it clear there's a warning about something on the ticket/page

also works for blue/info sign, other variants serve their own purpose.

You could either:
- offer presets (info, warning, danger, success)
- Allow users to choose color (and optionally an icon)

**Comment by rhea0110** [comment]
Hello @happyDemon! Thank you for your feature request. We already have it on our roadmap, and we will be working on it soon.

**Comment by vihar** [comment]
This feature is shipped in our v0.24.0 release. Find the release notes [here](https://github.com/makeplane/plane/releases/tag/v0.24.0).

![CleanShot 2024-12-01 at 15 41 08@2x](https://github.com/user-attachments/assets/eda44464-cd29-4983-b40d-6d6274f1ef5a)
