### ISSUE TITLE
[bug]: Due Date selects previous day

### ISSUE THREAD

**Issue by gicellamare** [makeplane/plane#2204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i select a due date for an issue, it is automatically selecting the day before i selected. Example: I want to select today (2023-09-18) as due date for an issue. By selecting today it automatically mark the due date as yesterday (2023-09-17)

### Steps to reproduce

1. Enable Time Zone
2. Enter an issue
3. Select a due date

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hello @gicellamare! Thank you for reporting this bug to us. To debug this issue, I request you to please share a video demonstrating the steps to reproduce this problem.

**Comment by Nabhag8848** [comment]
Hey! Looks like its duplicate:
- #1992

**Comment by gicellamare** [comment]
Thanks for letting me know NabhagResolving the issue that I’ve created to avoid duplications  From: Nabhag Motivaras ***@***.***>Date: Tuesday, 19 September 2023 09:56To: makeplane/plane ***@***.***>Cc: Giovanni Cellamare Neto ***@***.***>, Mention ***@***.***>Subject: Re: [makeplane/plane] [bug]: Due Date selects previous day (Issue #2204)Hey! Looks like its duplicate:#1992—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by gicellamare** [comment]
Thanks for letting me know Nabhag

Closing this issue to avoid duplications
