### ISSUE TITLE
[feature]: Support making Documents

### ISSUE THREAD

**Issue by kk-rishang** [makeplane/plane#2205]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Summary

Clickup and Jira have support to make documents for the org which is helpful for other team members this will be useful here as well Click

### Why should this be worked on?

Good to have

**Comment by rhea0110** [comment]
Hello @kk-rishang! Thank you for the feature request. We will work on it in the near future.

**Comment by sriramveeraghanta** [comment]
Hello @kk-rishang ,

As requested by a lot of community folks we are working on a document editor which supports a bunch of features, you can see it here #2784 . Also as you requested we will come up with a strategy for bringing in pages at workspace level as well. We will let you know once the release is out, Your feedback is greatly valued.

**Comment by Palanikannan1437** [comment]
@kk-rishang we've got you covered and shipped Pages in our latest release!!

Please consider upgrading to [v0.14.2](https://github.com/makeplane/plane/pull/3230) and try it out, would love to have your feedback on it 😄
