### ISSUE TITLE
[bug]: (minor) Favicon missing from self-hosted instances

### ISSUE THREAD

**Issue by jimhuds** [makeplane/plane#2206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Favicon doesn't appear on any self-hosted version I've tried so far. Looks like /favicon/[filename.ico] doesn't exist/can't be reached. Not sure if this causes any other issues aside from the visual.

### Steps to reproduce

As described above

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
This has been resolved now
