### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by b4s36t4** [makeplane/plane#2216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to contribute to plane. But it's hard to setup things locally. I read the entire `README.md` and `CONTRIBUTING.md` but it was not that helpful. There was no mention of how to configure environment variables (setup.sh) exists.

As a developer I want to setup things locally because of testing purposes but the guides here are using docker which is not great for development purposes. Maybe a good guide on how to setup the project locally for contributing purposes would help future developers to get started easily.

Maybe like a guide with all steps including `perquisites`, installing requirements for `apiserver`. What is `space` repo and what `web` repo documenting this all would be so much helpful.

If already there's a document please share it :)

### Steps to reproduce

NA

### Browser

Google Chrome

### Version

Local

**Comment by vihar** [comment]
@thomasync, sorry for following up late on this issue. We’ve now updated our docs and contribution guidelines extensively. Please open this thread if you are still experiencing any difficulties setting up Plane.
