### ISSUE TITLE
[bug]: Text is not erased when it is deleted via backspace, del if the text is selected

### ISSUE THREAD

**Issue by AlinaSelivanova** [makeplane/plane#2220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

if you highlight text and press Backspace or Del, the text will be deleted, and then if you continue writing it will come back

### Steps to reproduce

1. Open the bug creation screen
2. write some text
3. highlight this text
4. press the backspace or del key
5. keep writing

https://github.com/makeplane/plane/assets/83757237/b4449caa-eddc-4d7a-9e7a-38681e02c1c2

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Palanikannan1437** [comment]
Hey there @AlinaSelivanova, this should be fixed with https://github.com/makeplane/plane/pull/2530 in the upcoming release 🙌. You can see it resolved in the upcoming release ✈️

**Comment by prathamjagga** [comment]
I'm unable to replicate this issue.

**Comment by Palanikannan1437** [comment]
> I'm unable to replicate this issue.
> 

That's awesome then 🙌
