### ISSUE TITLE
[feature]: internationalization

### ISSUE THREAD

**Issue by AkiraVoid** [makeplane/plane#2222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The UI of Plane needs to be internationalized to provide a world-wide user experience.

### Why should this be worked on?

An app such as Plane will be used in many groups which are from separate countries. Although English is widely used in Internet world, we do need it to be localized to enable our employees or contributors as much as possible. As a suggestion, I recommend Plane team use a internationalization platform which supports people outside the team to co-operate in translation, such as Crowdin. And I am very pleasant to offer my help in translating English to Chinese or Japanese.

**Comment by rhea0110** [comment]
Hey @AkiraVoid! Thank you for the feature request. Our team will work on it in the future.

**Comment by vihar** [comment]
Thanks @AkiraVoid for your patience, we are picking this issue shortly. 

Moving this conversation to, https://github.com/makeplane/plane/issues/2028.

**Comment by vihar** [comment]
Thanks @AkiraVoid for your patience, we are picking this issue shortly. 

Moving this conversation to, https://github.com/makeplane/plane/issues/2028.
