### ISSUE TITLE
[bug]: issue calendar view not properly display all tasks

### ISSUE THREAD

**Issue by pillai-alexander** [makeplane/plane#2274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I have added issues that include either/both start dates and due dates, not all issues are shown on the calendar view nor are those that are shown in the correct day. For example, issues with a start and due date of September 27 are shown in the box for September 26, while other issues (with due dates later than September 27) are not shown at all. I am unsure if this has something to do with the bug related to selecting dates being one off of the desired date ( [bug]: Date picker select is always off by one day #1992 ).

### Steps to reproduce

1. Create new task with start and due date set to "tomorrow" (in my case Set 27).
2. Create another task with a due date that is later than "tomorrow"
3. Select calendar view

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by chanchala** [comment]
I can replicate this issue too. When the 28th is selected as the `due date` or `start date`, it is consequently converted and registered as the 27th.

**Comment by rhea0110** [comment]
Hello @pillai-alexander! We have fixed the issue and is now live with our new release, v0.13-dev.
