### ISSUE TITLE
[bug]: plane\apiserver\.env: The system cannot find the file specified. [Windows]

### ISSUE THREAD

**Issue by xstortionist** [makeplane/plane#2286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Perhaps I'm doing something wrong, very likely because I'm severely ADHD and dyslexic. Perhaps someone can point and laugh at me while telling what I need to do to get this running in docker on windows.

When I run these commands (powershell, cmd, don't matter...)

> git clone git@github.com:makeplane/plane.git
> cd plane
> ./setup.sh
> docker compose up -d
> yarn install
> yarn dev

I get the following errors:

> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"AWS_SECRET_ACCESS_KEY\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"AWS_ACCESS_KEY_ID\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"AWS_ACCESS_KEY_ID\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"AWS_SECRET_ACCESS_KEY\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"AWS_S3_BUCKET_NAME\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"AWS_S3_BUCKET_NAME\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"PGUSER\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"PGDATABASE\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"PGPASSWORD\" variable is not set. Defaulting to a blank string."
> time="2023-09-27T18:07:18-04:00" level=warning msg="The \"NGINX_PORT\" variable is not set. Defaulting to a blank string."
> Failed to load ...plane\apiserver\.env: open ...plane\apiserver\.env: The system cannot find the file specified.

### [Update] Attempted through Dev Env Results Below

> Preparing to clone inside a volume
> Installing credential helpers... 
> done
> Cloning into '/com.docker.devenvironments.code'...
> Detecting main repo language...
> Migration: no config.json detected
> Migration: no .docker/docker-compose.yaml detected
> loading project: open ...\plane\repository\apiserver\.env: The system cannot find the file specified.

### Steps to reproduce

1. go to IDE and input commands from current behavior description above
2. yell at computer for an hour straight until your wife asks "what are you doing?!?!?"
3. tell her to mind her own business
4. get errors in "current behavior" description above
5. thank you

### Browser

Google Chrome

### Version

Local

**Comment by vihar** [comment]
@xstortionist, apologies for the oversight. we've recently launched a new version that includes a straightforward self-hosting setup. docs: https://docs.plane.so/self-hosting/docker-compose for more details.

if you continue to encounter any difficulties, please don't hesitate to inform us, and we will promptly reopen the issue.
