### ISSUE TITLE
Invitation email contains localhost in invitation link. [bug]: 

### ISSUE THREAD

**Issue by SumonT2** [makeplane/plane#2329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While inviting someone to workspace, the invitee got link like http://localhost/xxxxxxxxxxxxxxxxx

### Steps to reproduce

Member invited from WorkSpace member area.

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @SumonT2, invitation urls are generated using the `WEB_URL` environment variable can you check your `WEB_URL`.

**Comment by SumonT2** [comment]
Hi @pablohashescobar , I don't find ```WEB_URL``` in ```.env``` file. I have also checked ```setup.sh``` file, there's no instruction to create ```WEB_URL```. Could you please advice should I manually input ```WEB_URL``` and which ```.env``` file should contain ```WEB_URL```?

**Comment by SumonT2** [comment]
Hello @pablohashescobar , Thanks for the walk-through. I have added ```WEB_URL="http://mydomain.com"``` in ```apiserver/.env```.

Could you please update the ```apiserver/.env.example``' and add the lines?.
```
# Email Redirection URL
WEB_URL="http://localhost"
```
