### ISSUE TITLE
[bug]: Profile page wrong label

### ISSUE THREAD

**Issue by luis-cruzt** [makeplane/plane#2342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I enter on the My Account section it says 'Update project' it should be something like 'Update profile'
<img width="686" alt="image" src="https://github.com/makeplane/plane/assets/55716036/03197756-22b0-44b2-a8d7-0a8d2ef5bc51">

### Steps to reproduce

1. Go to Workspace Settings
2. Click on 'My Account'
3. Click on 'Profile'
4. See the 

### Browser

Google Chrome

### Version

Cloud

**Comment by rhea0110** [comment]
Hello @luis-cruzt! Thank you for reporting this bug to us. We will get it fixed soon.
