### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by sooyoung** [makeplane/plane#2379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When entering an email address for a new invitee the "invalid email" validation gets triggered if there is trailing OR leading whitespace. 

Desired behaviour would be to auto-trim all whitespace and then perform validation.

### Steps to reproduce

Go to invite new member, enter a valid email address with a trailing space. 

### Browser

Google Chrome

### Version

Self-hosted

**Comment by rhea0110** [comment]
Hey @sooyoung! Thank you for reporting this bug to us. We will fix it soon.

**Comment by PrashantIndurkar** [comment]
Hi @rhea0110,
i would like to work on this issue 
Thank you :)

**Comment by vihar** [comment]
hey @PrashantIndurkar, you can pick this issue. let us know if you have any issues setting up our code base.

**Comment by PrashantIndurkar** [comment]
oh looks like @ousszizou already fixed this issue

**Comment by sooyoung** [comment]
Great when can we test?
