### ISSUE TITLE
Login form not showing 

### ISSUE THREAD

**Issue by imran-stacklearner** [makeplane/plane#2392]
![Screenshot_20231006-004454.png](https://github.com/makeplane/plane/assets/141145172/4715b91f-cac8-4418-940d-93e35ee863fc)

**Comment by Kyrluckechuck** [comment]
Looks to be the same issue as https://github.com/makeplane/plane/issues/2395, and a comment in that thread posted a workaround (reverting to a previous version)

**Comment by vihar** [comment]
We've upgraded our set-up for self-hosting and this issue should be fixed on our latest release. [Upgrade guide](https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x).

Please re-open this issue if you're still having trouble. Thanks.
