### ISSUE TITLE
[bug]:  Group by in projects unexpected behavior

### ISSUE THREAD

**Issue by twilighty-abhi** [makeplane/plane#2393]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When I try to change the _group by_ to _none_  after grouping by any option available, the change does not reflect in the view.

### Steps to reproduce

While in any specific project:
1. Go to Display > Group by
2. change the group to anything other than _none_
3. Now try to change back to _none_ 
4. **It won't work.**

Potential solution:
* Click on reset to defaults button, and it returns back to normal

### Browser

Google Chrome

### Version

Cloud

**Comment by ousszizou** [comment]
I tried to reproduce the steps you've outlined, but I noticed that the "none" option is not available in the "Group by" dropdown.

![DemoCreatorSnap_2023-10-06 07-13-34](https://github.com/makeplane/plane/assets/26632567/64a7f278-01e0-47da-928a-ad2d50b4cf26)

**Comment by twilighty-abhi** [comment]
I just checked, and there is the none option there still
![image](https://github.com/makeplane/plane/assets/79564956/c4bca05b-4a11-4d33-bf2e-46b6be21a4ab)

**Comment by ousszizou** [comment]
Ah, my bad! Just checked again and you're right, the "none" option is there. I was in the Kanban layout, so I didn't see it at first. Switched to the List layout and there it was. Thanks for pointing it out! 👍

I'm going to look into fixing this issue.

**Comment by pushya22** [comment]
This issue is now resolved.
