### ISSUE TITLE
[bug]: Sign in to Plane not showing any login form So i can login

### ISSUE THREAD

**Issue by imran-stacklearner** [makeplane/plane#2395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/makeplane/plane/assets/141145172/66d736a5-778c-4832-b9c4-5a670e411103)

### Steps to reproduce

Go to home page it not showing login page

### Browser

Google Chrome

### Version

Self-hosted

**Comment by guennoun53** [comment]
I had the same issue with makeplane/plane-frontend:v0.13.2-dev, but I switched back to the makeplane/plane-frontend:v0.13-dev

**Comment by didemkkaslan** [comment]
How? inside docker compose?


<img width="887" alt="Screenshot 2023-10-07 at 12 34 49" src="https://github.com/makeplane/plane/assets/106841409/e9381536-54e0-460b-9cd5-4dd73b3c5d51">

**Comment by srinivaspendem** [comment]
We've made updates to our authentication setup. To implement these changes, you can add the following variables in your apiserver/.env file:

ENABLE_EMAIL_PASSWORD="1"
ENABLE_MAGIC_LINK_LOGIN="0"
GOOGLE_CLIENT_ID=""
These updates are reflected in our [Release notes](https://github.com/makeplane/plane/releases/tag/v0.13.2-dev) and [documentation](https://docs.plane.so/self-hosting). You can also refer to apiserver/.env.example for guidance.

**Comment by codevski** [comment]
> I had the same issue with makeplane/plane-frontend:v0.13.2-dev, but I switched back to the makeplane/plane-frontend:v0.13-dev

Can confirm rolling back to 0.13 works. Latest frontend is bugged and doesnt show login for fresh installs.

**Comment by dikkini** [comment]
same issue

**Comment by vihar** [comment]
We've upgraded our set-up for self-hosting and this issue should be fixed on our latest release. [Upgrade guide](https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x). 

Please re-open this issue if you're still having trouble. Thanks.
