### ISSUE TITLE
[bug]: can't delete new created issues

### ISSUE THREAD

**Issue by guennoun53** [makeplane/plane#2401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When attempting to delete a recently created issue using the system, the action does not execute as expected; the issue is not deleted. Upon utilizing developer tools to delve deeper into the problem and examining the container logs for additional insight, it is observed that a 500 (Internal Server Error) is returned in response to the delete request.

PS: deleting uploaded pictures works without any problem
<img width="1751" alt="issue" src="https://github.com/makeplane/plane/assets/145984612/9685dffc-ca86-4ec7-8b4c-983227a0f5e8">
and elso there is an error for the redis url as  the expected value is rediss:// (ssl connection) and not redis://
<img width="1059" alt="Bildschirmfoto 2023-10-09 um 12 51 07" src="https://github.com/makeplane/plane/assets/145984612/a417fefa-360e-4d2e-93d5-6aa1e64b6955">

ValueError:
SSL connection parameters have been provided but the specified URL scheme is redis://. A Redis SSL connection URL should use the scheme rediss://.

### Steps to reproduce

The scenario involves a migration from software version 0.10 to version v0.13.2-dev. 

Key Components:

Source Version: 0.10
Target Version: v0.13.2-dev
Database: External PostgreSQL
Cache: External Redis
Storage: External Minio

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @guennoun53, can you check the db migrations or check the logs for the backend container it seems there is an error on issue delete. Also the issue related to redis is due to updated settings file for selfhosted users you can check the value of `apiserver/.env` for the variable `DJANGO_SETTINGS_MODULE`.

**Comment by guennoun53** [comment]
As I am deploying plane in Kubernetes, i checked the value again 
 I did the drill with the migration from "manage.py makemigrations and manage.py migrate"

 The value are as they should be.
export DJANGO_SETTINGS_MODULE='plane.settings.production'
export DOCKERIZED='1'
 
  I checked the code as well, and I was thinking that there is something with the redis.py file

**Comment by guennoun53** [comment]
Thanks for your reply @pablohashescobar 
As I am deploying plane in Kubernetes, I checked the value again
I did the drill with the migration from "manage.py makemigrations and manage.py migrate"

The value are as they should be.
export DJANGO_SETTINGS_MODULE='plane.settings.production'
export DOCKERIZED='1'

I checked the code as well, and I was thinking that there is something with the redis.py file

**Comment by pablohashescobar** [comment]
Got it @guennoun53, can you check the error while deleting the issues.

**Comment by guennoun53** [comment]
In Plane, like the web interface, it doesn't show anything it just stay the same
<img width="775" alt="Bildschirmfoto 2023-10-09 um 14 17 56" src="https://github.com/makeplane/plane/assets/145984612/21261fe4-208f-4824-aa56-83fe639fea35">

The errors I could get using the developer tools and looking in the container logs are the following 

<img width="934" alt="Bildschirmfoto 2023-10-09 um 14 20 07" src="https://github.com/makeplane/plane/assets/145984612/b5eb732b-a0e5-401c-926d-cf4369d1d621">

 SSL connection parameters have been provided but the specified URL scheme is redis://. A Redis SSL connection URL should use the scheme rediss://.
 
<img width="1044" alt="Bildschirmfoto 2023-10-09 um 14 15 22" src="https://github.com/makeplane/plane/assets/145984612/973c6df8-c468-4a83-9a66-c311f0fa6f4c">

**Comment by pablohashescobar** [comment]
@guennoun53 are you using the pre-built images or building images in local?

**Comment by guennoun53** [comment]
i am using the pre-build images from docker hub 
makeplane/plane-backend:v0.13-dev for api 
makeplane/plane-frontend:v0.13-dev for  frontend 
makeplane/plane-space:v0.13.2-dev

**Comment by guennoun53** [comment]
@pablohashescobar any update relating this issue ?

**Comment by pablohashescobar** [comment]
Hi @guennoun53 can you stop all the containers delete all the containers and repull and restart Plane again.

**Comment by guennoun53** [comment]
It did work :thumbsup: , thanks for the help

**Comment by pablohashescobar** [comment]
Closing this issue as it is resolved.
