### ISSUE TITLE
[bug]: Online website unavailable

### ISSUE THREAD

**Issue by bitbreakr** [makeplane/plane#2428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://plane.so is unavailable and looks like it is not parked anymore

### Steps to reproduce

http://plane.so not https

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hi @bitbreakr 
We encountered some issues with our Cloud version, but I'm pleased to inform you that we have resolved them. We apologize for any inconvenience this may have caused and appreciate your understanding. If you have any further questions or concerns, please feel free to reach out.
