### ISSUE TITLE
[bug]: Estimate option missing in issue display settings

### ISSUE THREAD

**Issue by TheZoker** [makeplane/plane#2457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I can set different options for the display settings within the issue view. The `Estimate` option is missing and I'm not able to hide that column from the table:

![image](https://github.com/makeplane/plane/assets/1368405/ebe541f2-10d3-4403-9824-53aa191da726)

### Steps to reproduce

1. Create project
2. Go to issue page
3. Select `Spreadsheet Layout`
4. Try to hide estimate column

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hello @TheZoker,

Thank you for reporting a bug. We appreciate your input, and we will address this issue in our upcoming release.
