### ISSUE TITLE
[bug]: haven't sign-up link in docker-compose-hub.yml

### ISSUE THREAD

**Issue by maxim317** [makeplane/plane#2467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i use self-hosted version (v.0.13.2)
when i start `docker compose docker-compose.yml` - new user can sign-up by following the link ***/sign-up under login block

when i start `docker compose docker-compose-hub.yml` - users don't see link ***/sign-up under login block

### Steps to reproduce

Docker compose
Self-host

### Browser

Other

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @maxim317,

We've identified and resolved the error you encountered in version `0.13.2`. The fix is currently available in our [develop branch](https://github.com/makeplane/plane/tree/develop) on GitHub. We'll also be updating our Docker images with this fix shortly. Stay tuned!

**Comment by manishg3** [comment]
Hello @maxim317 

For Self-hosting, you should be using `docker-compose-hub.yml` only. If you want users to do self-signup, you must configure SMTP. This is required to validate email.

**Comment by pablohashescobar** [comment]
Hi @maxim317, this issue should be fixed on latest release [0.14.1-dev](https://github.com/makeplane/plane/releases/tag/v0.14.1-dev). Let us know if you are still facing this issue.
