### ISSUE TITLE
[bug]: cycle view on mobile phone not readable because of cycle lane

### ISSUE THREAD

**Issue by Maurice-Bijl** [makeplane/plane#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I go to the cycle view on the mobile version the information view of the cycle cannot be hidden. Therefore the issues are not visible.

### Steps to reproduce

On desktop version:
1 go to a board
2 click on cycles
3 create cycle
4 add some issues to the cycle

Then on mobile version: 
1 go to board
2 go to cycles
3 click on the cycle you created
4 now you See a big area with sprint info which cannot be hidden.

### Browser

Other

### Version

Cloud

**Comment by vihar** [comment]
Plane will soon ship native mobile apps, today web version will not support mobile responsivess. Please follow our changelog page for more updates: https://plane.so/changelog.
