### ISSUE TITLE
[bug]: No assignee icon on cycle has not showing

### ISSUE THREAD

**Issue by wachirapohn** [makeplane/plane#2489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I access to cycle menu. Icon picture is not showing as below
![image](https://github.com/makeplane/plane/assets/145309221/89f521d2-7342-4a35-9f68-6e38df008b59)

Then I've checking on HTML it's call /user.png as a hard code
<img width="376" alt="image" src="https://github.com/makeplane/plane/assets/145309221/72eabebf-fd45-43f7-92c2-b22e8952db3f">
(Maybe is here?)
![image](https://github.com/makeplane/plane/assets/145309221/ba81b912-8614-4f30-8513-4f0cb133b7b5)

Form Debug it's send HTTP GET to https://[domain]/user.png But file "user.png" doesn't exist there

So, I've to workaround setting my reverse proxy if having GET at path /user.png traffic will force redirect picture that I've manually uploaded. And It's working fine
<img width="1030" alt="image" src="https://github.com/makeplane/plane/assets/145309221/713cf3af-f7ed-4bf0-8812-68ecb57b4f3a">
![image](https://github.com/makeplane/plane/assets/145309221/39a71876-e716-4b2a-a6bd-feee98f7185d)
 
Please, Find the root cause for this issue or how can I fix this issue permanently?

Thank you.

### Steps to reproduce

1. Go to menu cycle and look at the Other Information
2. No assignee icon has shown
3. look at the HTTP logs
4. workaround to force redirect traffic to get static user.png icon

### Browser

Google Chrome

### Version

Self-hosted

**Comment by aaryan610** [comment]
Hi @wachirapohn, thanks for reporting this issue, we'll make sure to fix it with our upcoming release.

**Comment by vihar** [comment]
@aaryan610, can you check if this issue still persists? thanks.

**Comment by vihar** [comment]
thank you for flagging this @wachirapohn, this issue is now fixed on our latest release. please let us know if this still persists.
