### ISSUE TITLE
[bug]: kanban cards duplication issue when dragging and dropping

### ISSUE THREAD

**Issue by saurabhcoded** [makeplane/plane#2513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. When i do drag and drop a card in same grid it just makes a two copy of it and the old one removes in a while.
2. Drag and Drop shows so many issues while dragging it often times not get selected , I am Using Firefox

### Steps to reproduce

1. Use FireFox Browser
2. Go to projects
3. Add two or more issues
4. Try Dragging and drop within same card
5. You will see some times your card not get selected or you will be having copy of same for a while
[ezgif.com-video-to-gif.webm](https://github.com/makeplane/plane/assets/79370686/c862efd3-7a1a-4ea7-9aff-03298cf087c6)

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by aaryan610** [comment]
Hi @saurabhcoded, thanks for reporting this issue. We are on the way of revamping our entire Kanban board, this issue will be fixed with it.

**Comment by ddudda174** [comment]
Already mentioned in #2243 (in comments). Also use a subject/title for issues!

**Comment by saurabhcoded** [comment]
@ddudda174 ok

**Comment by vihar** [comment]
@saurabhcoded, this issue has already been fixed in the [develop](https://github.com/makeplane/plane/tree/develop) branch. It will be resolved in the cloud with our next release.

**Comment by vihar** [comment]
We've introduced substantial changes to our Kanban layout. To benefit from these new features and address this bug, please upgrade to the latest version, `v0.14-dev`.
