### ISSUE TITLE
[feature]: allow attachments from issue peek view

### ISSUE THREAD

**Issue by gillbates** [makeplane/plane#2515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As plane already supports images and minio, can we also add other documents as well?

### Why should this be worked on?

In real world project managements, there are many documents other than image files there ... please add this support.

**Comment by aaryan610** [comment]
Hi @gillbates, you can attach any kind of a document to an issue.

Go to an issue details page, where you'll find a section titled Attachments-

<img width="815" alt="image" src="https://github.com/makeplane/plane/assets/65252264/b28d9ba2-c485-4080-94fe-5b057f1d5a44">

You can upload any kind of attachment here.

**Comment by gillbates** [comment]
![CleanShot 2023-10-23 at 08 32 07@2x](https://github.com/makeplane/plane/assets/783547/030368c8-d61b-4544-94ac-ffa2c6103542)

seemed not there? the latest version with self hosted docker compose

**Comment by NarayanBavisetti** [comment]
@gillbates , to upload attachments, please ensure you open the issue fully instead of using peek mode. To do this, click on the middle icon among the three toggle buttons at the top of the screen.

**Comment by gillbates** [comment]
> @gillbates , to upload attachments, please ensure you open the issue fully instead of using peek mode. To do this, click on the middle icon among the three buttons at the top of the screen.

ah ... got u.. thx @NarayanBavisetti 
this ux maybe later optimized ... as user wont even notice this attachment in normal peek mode.

**Comment by vihar** [comment]
@gillbates, we have revised the issue based on the discussions, and it appears that this operation is expensive in terms of UX. We will make efforts to identify a workaround and address this matter in the near future. In the meantime, please note that attachments will only be accessible on the issue detail screen.

cc: @srinivaspendem, @sriramveeraghanta

**Comment by danbtl** [comment]
Another :+1:  from me for this issue: The attachment section is very hard to find. It wasn't obvious to me that you could open the issue from peek mode to reveal the attachments.

**Comment by srinivaspendem** [comment]
Hey @danbtl @gillbates, just wanted to let you know that we've implemented the attachment feature in the peak overview in PR #3956.
