### ISSUE TITLE
Release v0.12

### ISSUE THREAD

**Issue by frank-lenormand** [makeplane/plane#2519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I see that the milestone for v0.12.x is complete:

https://github.com/makeplane/plane/milestone/1

I’ve been looking forward to trying out a new version of Plane, but I cannot see any v0.12.

Several development intermediary versions have been released both for v0.12 and v0.13, are there still blocking issues that gate the release of v0.12? Maybe you plan on releasing v0.13 directly?

Note that I self-host Plane and rely on the Docker images.

Thanks!

### Why should this be worked on?

Transparency of the workflow and current objectives.

**Comment by ddudda174** [comment]
Well, as of the [releases](https://github.com/makeplane/plane/tags) 0.13-2 is currently running, and also the [docs for self deployment](https://docs.plane.so/self-hosting) include 0.13-2 changes:

![image](https://github.com/makeplane/plane/assets/67892761/dc851b4e-6c6b-4056-bf97-c8fdfb2edb96)

So what are you exactly complaining about?

**Comment by frank-lenormand** [comment]
There are no stable releases that can be seen in the tags of the associated Docker images:

https://hub.docker.com/r/makeplane/plane-backend/tags

The last one was for v0.11.

Or did you not read my message at all?

**Comment by ddudda174** [comment]
Yeah that's my fault, didn't realise that you mean the stable versions, probably overread that.

Well this Tool ist still pretty new and has no 1.x.x Version yet, I guess we have to go with dev-versions so far.

**Comment by frank-lenormand** [comment]
Hi team,

Any updates on this?

I’d just like to know if I should keep waiting for a v0.12, seeing that v0.13.x-dev is already being worked on.

CC @rhea0110

**Comment by vihar** [comment]
Hello @frank-lenormand, I'm slightly confused. The [v0.12-dev](https://github.com/makeplane/plane/releases/tag/v0.12-dev) version is already available. Are you searching for something specific? If you are looking at Docker Hub, here's the link: [Docker Hub Image](https://hub.docker.com/layers/makeplane/plane-backend/develop/images/sha256-6a62daa3f7bc419b3929600fdc0b65bc1e0af6c226d3c6c1660558fe3c56e9fd?context=explore). Currently, our team is working on the 0.14-dev release.

We typically share updates through our [Discord](https://discord.com/channels/1031547764020084846/1053268986449633390), [changelog](https://plane.so/changelog), and GitHub. How can we improve our communication to make it better? If you have any suggestions, please let us know.

**Comment by frank-lenormand** [comment]
There is no **STABLE** release for v0.12. All previous versions had one, so obviously something changed and I still don’t know what it is.

![2023-11-15_09-54](https://github.com/makeplane/plane/assets/131158759/ae0e7aed-91a3-41c3-930c-1606cd32c427)

**Comment by vihar** [comment]
I understand now. Previously, we didn't use the dev tag on our Docker. However, until the 1.0 release, we will continue using the dev tag, as the platform is becoming increasingly stable with each release. Going forward, we'll align our tags with those used on [GitHub](https://github.com/makeplane/plane/tags). Thank you for flagging this; we will improve our release communications in the future.

**Comment by frank-lenormand** [comment]
Thanks for the quick reply.

Just so I’m sure: if the Docker image tags align with the ones on Github, that *does* mean that these images can be considered frozen, and don’t need to be pulled regularly (like say a `develop` tagged image), correct?

**Comment by vihar** [comment]
You're correct, the tags will align with the release and you need to only re-pull when there is a new release.

**Comment by frank-lenormand** [comment]
Thank you for all the information!
