### ISSUE TITLE
[feature]: Replace Old Twitter Icon with New Twitter Icon

### ISSUE THREAD

**Issue by hemant14050** [makeplane/plane#2520]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Description:
- Our website's frontend at https://plane.so/ currently uses an outdated Twitter icon.

## Screenshot
- Current Logo
- ![image](https://github.com/makeplane/plane/assets/112842857/0181b943-41e4-4c7a-8a59-c536155c6cc1)

### Why should this be worked on?

- To maintain a modern and cohesive design, we need to replace the old Twitter icon with the new one provided by Twitter's official branding guidelines. 
- This update is essential to keep our website visually appealing and up-to-date with the latest design standards.

**Comment by hemant14050** [comment]
Please assign it to me.
I would like to work on it. ⚡

**Comment by abhaystoic** [comment]
Good point. But I don't think that this is the repo for the website.

**Comment by hemant14050** [comment]
Okay, I think it was my misunderstanding. I am new to open source.
I will close the issue.
Thanks.
