### ISSUE TITLE
[bug]: Can't upload attachments, always more than 5Mb on self-hosted server

### ISSUE THREAD

**Issue by mregni** [makeplane/plane#2529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to add an image to the description box it will load inifitly. In the browser console the call to `/api/workspaces/uping/file-assets/` return "File too large. Size should not exceed 5 MB.". That is strange because the image itself is only 468kB in size (see second screenshot)

![image](https://github.com/makeplane/plane/assets/22617019/6f198d28-8d17-4ede-b1df-abaf4686df6f)
![image](https://github.com/makeplane/plane/assets/22617019/95bc395e-30a9-4ed8-be76-1a1e7b071836)

When I try to upload an attachment I get a nice error toaster with the same message.
![image](https://github.com/makeplane/plane/assets/22617019/8f9e4503-2201-44be-8211-b378bf791beb)

Any idea how this could be possible? I enabled debug logging but can't find much
```
POST - /api/workspaces/uping/file-assets/ of Queries: 1
GET - /api/workspaces/xxxxxxxxx/projects/983fc856-7f9e-4ffa-901b-7cd8d22b421d/issues/9b9f6656-d89a-42a6-a07d-1d1d5618f782/history/ of Queries: 4
172.32.0.19:33576 - "GET /api/workspaces/xxxxxxx/projects/983fc856-7f9e-4ffa-901b-7cd8d22b421d/issues/9b9f6656-d89a-42a6-a07d-1d1d5618f782/history/ HTTP/1.1" 200
Bad Request: /api/workspaces/uping/file-assets/
172.32.0.19:33526 - "POST /api/workspaces/uping/file-assets/ HTTP/1.1" 400
```

Ow, I'm running version v0.13.2 in docker with docker-compose.

### Steps to reproduce

1. Create a new issue
2. Add attachment or drag file in description box
3. File to large error is returned (see screenshots above)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by mregni** [comment]
Not sure if it's related, but I have the same issue while uploading a profile picture for my user or for workspace as well.

**Comment by vihar** [comment]
Sorry you're facing this issue. This seems like a bug. @pablohashescobar will be shortly fixing this issue.

**Comment by pablohashescobar** [comment]
Hey @mregni, this should be fixed in the current latest version. Let us know if you are still finding this issue.

**Comment by truongnat** [comment]
i pull last code and it still error, can not upload
