### ISSUE TITLE
[bug]: File Upload issue . Same as https://github.com/makeplane/plane/issues/814

### ISSUE THREAD

**Issue by utkarshwealthy** [makeplane/plane#2536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to upload any file in the size limit that I have set for any file it says, "Something Went Wrong"
<img width="333" alt="image" src="https://github.com/makeplane/plane/assets/133212876/8fc24324-67a1-44ca-b69e-0969183e6523">
As you can see in this image.

I'm using the latest version 0.13.2-dev and have even tried checking my resources and the URL I have specified, everything seems correct.

### Steps to reproduce

1. Go to the any ticket created on plane tool.
2. Navigate to the file upload section.
3. Select a file that falls within the size limit.
4. Click the "Upload" button.
5. Observe the error message: "Something Went Wrong."

### Browser

Google Chrome

### Version

Self-hosted

**Comment by utkarshwealthy** [comment]
Hello @venplane  @rhea0110 , Any update on this, as this is a crucial feature which just stopped working.

**Comment by manishg3** [comment]
Hello @utkarshwealthy 
We are looking into this and will revert asap.

**Comment by aaryan610** [comment]
Hi @utkarshwealthy, we have fixed this bug and plan to ship it with the next release, you can see the progress here- #2868. Thanks for your patience.

**Comment by vihar** [comment]
the [release is out](https://github.com/makeplane/plane/releases/tag/v0.14-dev), this issue should now be fixed. if you're still facing the trouble, please let us know.

**Comment by utkarshwealthy** [comment]
Hey @vihar @aaryan610 ,
The image upload issue is not working
<img width="758" alt="image" src="https://github.com/makeplane/plane/assets/133212876/b1ac0903-89d4-413b-b942-87ecb43f8eed">
We have already checked the user as well by manually uploading a file, and it is working fine ( has complete access to the specific bucket).

**Comment by utkarshwealthy** [comment]
Hi @mguptahub @aaryan610  @vihar , any update here?

**Comment by SingHar** [comment]
Hi

Facing the same issue. Is there any resolution yet?

**Comment by fqazi-gencloud** [comment]
Hi
Facing the same issue of image not uploading , Is there any resolution yet?
