### ISSUE TITLE
[bug]: sign-up not working

### ISSUE THREAD

**Issue by twilight74** [makeplane/plane#2542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

hi

i run docker-compose-hub.yml and there is no sing-up link in home page 
and when go to <my-domain-name>/sing-up , it show that """Not Authorized!""" 

help me if you can run it

### Steps to reproduce

Docker compose
Self-host

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by kyborq** [comment]
https://github.com/makeplane/plane?tab=readme-ov-file#%EF%B8%8F-quick-start-with-docker-compose

Basically it says: "You can use the default email address and password for your first captain@plane login.so, and the password is 123."

**Comment by twilight74** [comment]
yes , but i want to sign up for new users, how can i do this?

**Comment by kyborq** [comment]
Just go to the workspace settings and find invite collaborators button

**Comment by twilight74** [comment]
So, how can someone register without being invited?
I just look for a button like the link in docker-compose-hub.yml ,  to click and register.
(It is in docker-compose-hub.yml but not in docker_-compose.yml)

**Comment by vihar** [comment]
Related to https://github.com/makeplane/plane/issues/1131, closing this issue to keep the conversation on one thread.
