### ISSUE TITLE
[bug]: Line-spacing, double enter copy/paste output

### ISSUE THREAD

**Issue by t-AIR-e** [makeplane/plane#2550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I copy/paste from - chatgpt to an issue
I have this weird formatting issue that I can not resolve by highlighting the text again and selecting /text or /code.

I have to manually backspace and then hit enter again to remove the weird line-spacing.

![image](https://github.com/makeplane/plane/assets/19786399/a4fd0eb6-0834-4600-9f62-bcfbea8a032e)

### Steps to reproduce

1: Ask chatgpt for a markdown file directory 
2: copy - paste to issue

![image](https://github.com/makeplane/plane/assets/19786399/b03a993d-5c01-4779-a2d3-cc4a3b01f3e2)

### Browser

Google Chrome

### Version

Local

**Comment by Palanikannan1437** [comment]
Hey there @TEA-AIR-E, markdown formats varies a lot across editors, would it be possible to copy paste the markdown here on github.

We could work on fixing the spacing issue between the text nodes if that's what you'd want, but some input text that I can test with would be of great help, cheers!

**Comment by TEA-AIR-E** [comment]
> Hey there @TEA-AIR-E, markdown formats varies a lot across editors, would it be possible to copy paste the markdown here on github.
> 
> We could work on fixing the spacing issue between the text nodes if that's what you'd want, but some input text that I can test with would be of great help, cheers!

Sure
Here's how it looks like from chatGPT

![image](https://github.com/makeplane/plane/assets/19786399/5cbfa7d5-c7d4-4ef2-964f-07e9d2f27619)

`snake_game_demo
├── server
│ ├── api
│ │ ├── game
│ │ └── scores
│ ├── database
│ ├── app.ts
│ └── .env
│
├── client
│ ├── components
│ │ ├── Snake
│ │ ├── Food
│ │ └── ScoreBoard
│ ├── styles
│ ├── app.tsx
│ └── package.json
│
└── README.md`

Here's how it's formatted when pasted into an issue. (CTRL+SHIFT+V)

`snake_game_demo

├── server

│ ├── api

│ │ ├── game

│ │ └── scores

│ ├── database

│ ├── app.ts

│ └── .env

│

├── client

│ ├── components

│ │ ├── Snake

│ │ ├── Food

│ │ └── ScoreBoard

│ ├── styles

│ ├── app.tsx

│ └── package.json

│

└── [[README.md](http://readme.md/)](http://README.md)`

![image](https://github.com/makeplane/plane/assets/19786399/9e6eabc5-a665-4aa2-97d4-71b23a62afab)

**Comment by Palanikannan1437** [comment]
Thanks, will look into this and get back to you on this...

**Comment by vihar** [comment]
@t-AIR-e, thanks for spotting this. @Palanikannan1437 has resolved the issue. If you are still facing any problems, please let us know.​
