### ISSUE TITLE
[bug]: Cannot Export issue on Plane self-hosted

### ISSUE THREAD

**Issue by wachirapohn** [makeplane/plane#2568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

From issue #1990 I've the same issue
My Environment:
OS: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Platform: Linux
Arch: x64
Docker: True
Plane version: v0.13.2-dev

<img width="1264" alt="image" src="https://github.com/makeplane/plane/assets/145309221/8d0b53aa-6516-4839-aa97-0f953c581d09">

### Steps to reproduce

Export issue and it's failed. But it's show Export Successful
<img width="833" alt="image" src="https://github.com/makeplane/plane/assets/145309221/ab017ee1-e797-4952-8367-72b1e99a7d70">

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@pablohashescobar, can you debug this issue?

**Comment by wachirapohn** [comment]
[plane-docker-logs.zip](https://github.com/makeplane/plane/files/13434432/plane-docker-logs.zip)

docker logs here

**Comment by pablohashescobar** [comment]
Thanks for the logs @wachirapohn  I will check this internally and revert back.

**Comment by pablohashescobar** [comment]
This is a bug on our latest build due to a misconfigured setting variable we have fixed this in the develop branch we will pushing this soon. Attaching the [PR](https://github.com/makeplane/plane/pull/2816) here for reference.

**Comment by pablohashescobar** [comment]
Hi @wachirapohn, this should be fixed on our latest release. Closing this issue feel free to reopen the issue if you are still seeing the error.
