### ISSUE TITLE
[bug]: 🚨 Urgent: Plan.so Mobile View - Sidebar Issue Renders App Unusable 😩

### ISSUE THREAD

**Issue by yasin172** [makeplane/plane#2613]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current behavior

I am encountering a critical sidebar issue on the mobile version of Plan.so, which renders the app practically unusable on my mobile device. The problem stems from non-scrollable sidebars that occupy too much screen space. This issue needs immediate attention as the site has become almost non-functional for many users on mobile devices.

### Steps to reproduce

https://github.com/makeplane/plane/assets/81102121/8d975406-a1cf-46ac-b297-9cec4c981bc3

Proposed Solution:

Make sidebars scrollable and hideable,
Add necessary icons to improve the user interface.
Benefits:

Allows users to work more efficiently on mobile devices,
Optimizes the use of Plan.so in the mobile environment,
Increases user satisfaction and engagement with the site.
Attachments:

A video detailing the usability issues in the mobile view.
Environment Info:

Browser: Google Chrome Latest mobile version
Operating System: iOS Latest version for iPhone 11

### Browser

Google Chrome

### Version

Cloud

**Comment by vinaybadgujar102** [comment]
hey @vihar can i take this issue?

**Comment by vihar** [comment]
@yasin172, today Plane is not optimized for mobile usage. We are currently working on making the web interface more mobile-friendly and also developing native applications. Please follow our [changelog](https://plane.so/changelog) for further updates on these improvements.
