### ISSUE TITLE
Trying Plane

### ISSUE THREAD

**Issue by Julian-Dumitrascu** [makeplane/plane#2644]
I found your software some time ago. I don't remember when. I may have created [this space](app.plane.so/sol).
I'd like to use software more helpful than Atlassian Work and Height. You say Plane is better. I'd like to try it.
I've just tried to create this space. Plane responded: "Workspace URL is already taken!"
Did I create this space?
a. Yes.
Let me use it!
b. No.
I'll choose another URL.

**Comment by vihar** [comment]
@Julian-Dumitrascu, Workspace URLs are unique, so I hope you have chosen an available name for your workspace. If you encounter any errors or issues, please inform us. We will consider this issue closed for now.
