### ISSUE TITLE
[bug]: newly added cycle doesnt appear unlelss the page is manually reloaded

### ISSUE THREAD

**Issue by AbhiShake1** [makeplane/plane#2666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i add a new cycle, it doesnt appear until we manually reload the page

https://github.com/makeplane/plane/assets/40654066/eefe8485-dc12-4614-86ea-6bc652ddcda3

### Steps to reproduce

1. Go to cycles page
2. Create new cycle, submit the form

**(i am in develop branch)**
**(this only happens when creating the first cycle)**

### Browser

Mozilla Firefox

### Version

Local

**Comment by vihar** [comment]
Hello @AbhiShake1, we have identified the issue and a solution is underway. In the meantime, could you please inform us of the specific plane version you are using? This information will assist us in resolving the problem more quickly. Thanks.

**Comment by AbhiShake1** [comment]
> Hello @AbhiShake1, we have identified the issue and a solution is underway. In the meantime, could you please inform us of the specific plane version you are using? This information will assist us in resolving the problem more quickly. Thanks.

Hello, its happening on the develop branch (just checked, still exists). I had sent a PR, not sure if its optimal but it fixes the issue. https://github.com/makeplane/plane/pull/2673

**Comment by vihar** [comment]
Thanks for the PR @AbhiShake1. We'll review the PR and get back to you on this shortly.

**Comment by vihar** [comment]
thanks @AbhiShake1 for your contribution 🙏🏻 , this PR is now on our latest release. 🍰

**Comment by AbhiShake1** [comment]
Thanks @vihar . It means alot. Looking forward to utilizing and contributing more to this awesome project
