### ISSUE TITLE
[feature]: Users should be logged in for longer and have to enter passwords less frequently

### ISSUE THREAD

**Issue by j3mu5** [makeplane/plane#2711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

On my self-hosted instance (version: v0.13.2) I have to log in several times a day (desktop and mobile), for example after restarting the PC. The site should be usable for longer without the need to log in.

### Why should this be worked on?

The need to log in repeatedly leads to frustration among users, as this is perceived as an effort and an unnecessary step. People often take the easiest route and therefore prefer to have to enter their login details infrequently. Prominent examples are Google and Amazon - passwords only need to be re-entered for security-relevant actions.

**Comment by vihar** [comment]
Hello @j3mu5, it appears you're encountering a frustrating issue. It seems to be related to the authentication layer. We will check if this is also occurring in our self-hosted instance. In the meantime, could you share your opinion on the ideal duration for an authentication token's validity? Additionally, what other authentication methods would you suggest for a password-free experience? We would appreciate your insights.

**Comment by abhiraj-ku** [comment]
Yes, i think "Remember me " would be a good option with around a month of maybe two validity time . Because each time the session expires (which in this case is not even a day i guess )you have to click the link or fill the code manually which degrades the user experience.

**Comment by vihar** [comment]
We have extended the session duration to persist for 30 days in our latest release. Additionally, we are actively working on implementing user-friendly authentication options like Passkeys. We will keep the community informed about our progress.

cc: @srinivaspendem, let's work on PRD for auth options.
