### ISSUE TITLE
[bug]: Submit login form on Enter key without requesting email for login code

### ISSUE THREAD

**Issue by t-AIR-e** [makeplane/plane#2766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Issue happens when I enter my email and password in the login form and press the 'Enter' key. 

Currently, this action activates the field for entering an email address to receive a login code. 
Expectation: pressing 'Enter' after filling in the login form should directly submit the form and initiate the login process, without prompting for an email to send a login code.

This is only relevant if login magic link login is enabled.

![image](https://github.com/makeplane/plane/assets/19786399/68cdad22-ea95-434b-9231-066c17361fa4)

### Steps to reproduce

Enable magic link
Enter email address
Enter password
Press enter

### Browser

Google Chrome

### Version

Local

**Comment by vihar** [comment]
@TEA-AIR-E, thanks for flagging this! You're absolutely right – pressing 'Enter' should smoothly transition you to where you need to be, no detours. You can expect a more intuitive and direct experience with our next update.

Are there any other features you're keen on seeing? Maybe something like passkeys or a 'stay logged in' option for a week? Let us know your thoughts!

**Comment by Vivek7038** [comment]
can i fix this and raise a pr for this

**Comment by vihar** [comment]
@Vivek7038, absolutely! If you encounter any hiccups with the setup, let us know on [Discord](https://discord.com/invite/A92xrEGCge).

**Comment by prathamjagga** [comment]
Looking into it. Thanks for reporting.

**Comment by srinivaspendem** [comment]
With our current UI/UX, this issue has been resolved. Please update to the latest version if you encounter any persisting issues.
