### ISSUE TITLE
[bug]: Table controls should be displayed directly below the table

### ISSUE THREAD

**Issue by j3mu5** [makeplane/plane#2811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently the controls for adding / removing lines of a table are displayed at the very bottom of an issue. This is a problem if there is a lot after the table. Could you move the table control so that it appears directly below the table?
![Unbenannt](https://github.com/makeplane/plane/assets/50756558/60c39aa2-2490-4a7b-8f6b-23cbbf827f1e)

### Steps to reproduce

1. Create Table
2. Click in Table

### Browser

Google Chrome

### Version

Self-hosted

**Comment by sriramveeraghanta** [comment]
Thank you for bringing this issue to our attention. Our team has successfully identified the issue, and a fix is work in progress already. You can see it resolved in the upcoming release.

**Comment by Palanikannan1437** [comment]
Hey @j3mu5, the above bug is solved with https://github.com/makeplane/plane/pull/2596 🙌

Hopefully you'd like the new approach much better 😄

**Comment by Palanikannan1437** [comment]
Glad you liked it!

>  When selecting the colour for a column, I think it would be better if the header stayed in its own, separate colour (in the example video this would be blue). This helps to maintain the visual demarcation of the header.

That totally makes sense, thanks for bringing it up, will try to get it up soon! (Hopefully in this release ✌️)

**Comment by Palanikannan1437** [comment]
Hey @j3mu5, we've made these changes now! Please upgrade to our latest version and you'll be able to see these changes ✌️
