### ISSUE TITLE
[feature]: Display : Group by module

### ISSUE THREAD

**Issue by marcungeschikts** [makeplane/plane#2863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

**What:**
- Be able to group the issues by Module in all the view (except Modules view) 
- Display cards separated by an horizontal swimlane containing the module name
- Enable hiding cards of a module with a toggle button  

**How:**
- When selecting the display button (top right), then the "group by" selection, add the module option

**Where:** 
- Everywhere except the Modules view(Issues,Cycles,Views)
- For all the layout type

### Why should this be worked on?

Use case not covered: 
It will avoid to open all the modules view when the user, want to quickly have an overview of many Modules at the same time

**Comment by vihar** [comment]
@marcungeschikts, sorry for replying late. We will pick this up shortly in our upcoming releases.

**Comment by agnarok** [comment]
any updates about this `enhancement`? If needed i could help in the development :)

**Comment by marcungeschikts** [comment]
Done in 0.16.
![image](https://github.com/makeplane/plane/assets/74183327/006ab95d-af5e-4a6d-8387-d3d9b3762d26)
I close this ticket.
Thanks a lot 🙏🏻
