### ISSUE TITLE
[feature]: Filters : Add Modules as a filter

### ISSUE THREAD

**Issue by marcungeschikts** [makeplane/plane#2864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Following [feature]: Display : Group by module #2863

**What:**
- Be able to filter the issues by Module in all the view (except Modules view) 

**How:**
- When selecting the Filters button , add the module selection to be able to select more than one module

**Where:** 
- Everywhere except the Modules view(Issues,Cycles,Views)
- For all the layout type

### Why should this be worked on?

Use Case:
For big dev team/ big software, with many modules, you may want to look only some specific modules (UIs  or backend modules)

**Comment by vihar** [comment]
@vinaybadgujar102, are you still available to pick this issue? Let us know, thanks.

**Comment by vinaybadgujar102** [comment]
@vihar I'm currently occupied and won't be able to work on this issue at the moment

**Comment by marcungeschikts** [comment]
Done in 0.16
![image](https://github.com/makeplane/plane/assets/74183327/330f0101-4b82-4e04-9023-3ec6333ea73b)
I close this ticket.

Thanks a lot 🙏🏻
