### ISSUE TITLE
[feature]:Additional Custom Fields for Issues

### ISSUE THREAD

**Issue by marcungeschikts** [makeplane/plane#2865]
### Discussed in https://github.com/orgs/makeplane/discussions/2649

Why:
All projects management are different and need customization.
Lot of  the project management software( Jira, Trello, Wekan, Focalboard,...) have already this feature.

**Comment by olivierlambert** [comment]
Indeed, that's a pretty interesting feature!

**Comment by cgallay** [comment]
Any update on this feature?

**Comment by cheery550** [comment]
+1, for this feature

**Comment by Novined** [comment]
+1

**Comment by nguyenquanghieu2000d** [comment]
+1

**Comment by techspawn** [comment]
+1

**Comment by mmospanenko** [comment]
Any chances to increase priority?) I believe that this is the main blocker for most teams before moving to Plane ;)

**Comment by danielcolgan** [comment]
Agree, the most requested in our teams. 🎤 ⬇️

**Comment by moiz994** [comment]
+1000!!!

**Comment by erickhaendel** [comment]
release date? Extremely important functionality for workload management.

**Comment by vcscroll** [comment]
up, +1

**Comment by kidzblvck** [comment]
+1

**Comment by iqbalpb** [comment]
+1

**Comment by danielcolgan** [comment]
@sriramveeraghanta please give us your opinion on this issue.

**Comment by Killbunny** [comment]
+1

**Comment by marcungeschikts** [comment]
Any explanation as to why this issue was closed?

**Comment by vihar** [comment]
this feature is in works, we'll take the discussion here, [github.com/orgs/makeplane/discussions/2649](https://github.com/orgs/makeplane/discussions/2649)

**Comment by mmospanenko** [comment]
thanks, just leave few words or link before closing :)
