### ISSUE TITLE
[feature]: Filter by Cycles and modules

### ISSUE THREAD

**Issue by pmig** [makeplane/plane#2887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It is currently not possible to create views with a custom cycle or module filter.

### Why should this be worked on?

E.g. it is not possible to find all open issues that are not yet assigned to a cycle

**Comment by vihar** [comment]
@pmig, currently this feature is unavailable, but it's a fantastic suggestion. Could you provide more details about your use case? From what I gather, you're looking to generate multiple boards using specific attributes from the cycles and modules.

Regarding the challenge of identifying unassigned open issues in a cycle, I understand. Are there any other specific aspects that could enhance the user experience? 

For instance, our views are currently global. If we were to implement filters, where would be the best place to display them? Should they be integrated within cycles, or should we add cycle names as tags to views created based on these filters?

**Comment by pmig** [comment]
We organize our tickets in cycles and would love to find open tickets that do not belong to a cycle yet - let's say a general backlog. In addition we would like to see all tickets from a specific module of a current cycle. I think this functionality is super crucial.

**Comment by marcungeschikts** [comment]
FYI: Already mentionned in #2864 for modules.

**Comment by marcungeschikts** [comment]
Done in 0.16
![image](https://github.com/makeplane/plane/assets/74183327/eb59d807-4d19-4765-9119-e931ec4561c9)
@pmig: I let you close this ticket.

Thansks a lot tp Plane team 🙏🏻
