### ISSUE TITLE
[bug]: priority sorting is broken

### ISSUE THREAD

**Issue by pmig** [makeplane/plane#2916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When organizing tickets in cycles and working in the Kanban view tickets are sorted by priority. (but alphabetically and not actual priority)

sort oder:

high
low
medium
none
urgent

### Correct behavior:

urgent
high
medium
low
none

### Steps to reproduce

Open Kanban view and give tickets priorities

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@pmig, we are currently redesigning the layout of our entire Kanban board for improved performance. This issue has already been addressed and resolved on https://github.com/makeplane/plane/pull/2941. The fix will be included in the upcoming 0.14-dev release. We will update you as soon as the release is available.

**Comment by kotasudhakar** [comment]
I guess this ticket can be closed then

**Comment by pushya22** [comment]
#3141 This is fixed in this PR
