### ISSUE TITLE
[question] If it is self-hosted, why are there imposed limits?

### ISSUE THREAD

**Issue by rondDev** [makeplane/plane#2951]
I haven't read too deep into the product, although I was considering running it for myself. What I am curious about is why there are imposed limits?

**Comment by TEA-AIR-E** [comment]
![image](https://github.com/makeplane/plane/assets/19786399/79cf2b74-ce15-4403-8f5e-d564f78bd39c)
The free-cloud plane.so plan has limits, because resources cost money and then there's self-hosted plans w/ no limits.

I'm curious, what limits are you talking about?
BTW you should really post discussions in the discussion tab not in the issues tab.

**Comment by rondDev** [comment]
> I'm curious, what limits are you talking about?

I could not for the life of me find the little "self-hosted" toggle. That's my bad. Apologies.

**Comment by TEA-AIR-E** [comment]
No worries- Yeah I was like there ain't no way, so I double checked.

**Comment by etaxi341** [comment]
> ![image](https://private-user-images.githubusercontent.com/19786399/287120025-79cf2b74-ce15-4403-8f5e-d564f78bd39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjc4ODEsIm5iZiI6MTcwNTA2NzU4MSwicGF0aCI6Ii8xOTc4NjM5OS8yODcxMjAwMjUtNzljZjJiNzQtY2UxNS00NDAzLThmNWUtZDU2NGY3OGJkMzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEzNTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YTBmNGRkODRkYjg4MjBmZDYzMjgzMWYxOGY5MjM1Yzg5NDM0YjljYTQ5ZGIyMzZiNDJhNjA5ODllOTQ0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZTlTwaYXX4TZHVMtpAPZLX1MoGfWDG-5R1PiDiwI_6M) The free-cloud plane.so plan has limits, because resources cost money and then there's self-hosted plans w/ no limits.
> 
> I'm curious, what limits are you talking about? BTW you should really post discussions in the discussion tab not in the issues tab.

What happened to this pricing page? I cannot find it. Only a contact formula... In the screenshot it still said "Free forever". Did they undo that?

**Comment by octavian-regatun** [comment]
So, cycles feature is not available on self-hosted?

**Comment by chimit** [comment]
It looks like now self-hosted is really limited:

<img width="1040" alt="image" src="https://github.com/makeplane/plane/assets/839349/bca65264-7925-47f2-8d44-aa48f8a935a7">

**Comment by theparthacus** [comment]
> It looks like now self-hosted is really limited:
> 
> <img alt="image" width="1040" src="https://private-user-images.githubusercontent.com/839349/326693749-bca65264-7925-47f2-8d44-aa48f8a935a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTI3MDksIm5iZiI6MTcxNTAxMjQwOSwicGF0aCI6Ii84MzkzNDkvMzI2NjkzNzQ5LWJjYTY1MjY0LTc5MjUtNDdmMi04ZDQ0LWFhNDhmOGE5MzVhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNjIwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTdlZTdmNTNhYjM4NTllMmVlYzc1YzQ3ZjgzZTc3NjkwMTFiNjYzOGFlNmEyNjBmNTNhMWI1ZTk0YzkwMDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D6X0FaBG6b3q0e0_Vl_k7JvrmtMtFE-DUCRVDNRuBB4">

[this comment](https://github.com/makeplane/plane/issues/4095#issuecomment-2096395499) should clarify there isn't an artificial limit imposed by us. if you have questions, @chimit, continue there, please.

**Comment by HRNPH** [comment]
# Now it is actually, More limited? (CE is already cool enough but i think this presentation kinda confuse ppl)
<img width="1072" height="741" alt="Image" src="https://github.com/user-attachments/assets/f91ed2ef-e576-484e-baaf-6f07d88bd17d" />

I'm fine with buying Selfhost with more features offering, a premium that actually worthwhile not out of frustration.
but seat-base SaaS pricing model when i managed my own infras?

I would like one time buy for premium with unlimited seat, or maybe monthly as let's said 100$ but no user limit.
I don't think the limit that infrastructure wise did not cost you is, in good faith a good idea.

it is marketed for early adopter like devs, tech lead, and whatever se/pm so this limit will always seems unreasonable from my perspective.
