### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by siunus** [makeplane/plane#2975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

3 weeks using Plane, but suddenly an error like this occurs.
I don't know what to do, this error appeared after I successfully logged in.
I have added many issues related to my work.
The same thing happens in other browsers.

![image](https://github.com/makeplane/plane/assets/42384452/44bca84c-a1dc-4384-9539-8f28eaf14068)

### Steps to reproduce

On the login page it looks normal.
After successfully logging in this error appears.

Don't know what version of Plane. I installed it on November 11 on an Ubuntu server.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by siunus** [comment]
How to see the log?
I don't see anything wrong here after I successfully logged in.

.

![image](https://github.com/makeplane/plane/assets/42384452/3ff7d25f-6ed8-4583-b031-e44efcdf4f0d)

**Comment by vihar** [comment]
@siunus, can you upgrade to `v0.14-dev`, and see if the issue still persists? 

Docs for upgrading, https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x

**Comment by siunus** [comment]
I have found the solution in the previous version, sorry for not sending the update here.

To fix it, go to DevTools > Application > Local Storage > choose site > Delete theme record, or change the value to light as default. Then refresh the page.

----

The error lines

![Screenshot from 2023-12-12 23-00-07](https://github.com/makeplane/plane/assets/42384452/c2bca8c4-4ee3-43d3-9c77-b4e15c4edc36)

![Screenshot from 2023-12-12 23-00-40](https://github.com/makeplane/plane/assets/42384452/4ac28cf7-bb95-41a0-aa46-63737c4a9d8d)

Local Storage

![Screenshot from 2023-12-12 23-02-47](https://github.com/makeplane/plane/assets/42384452/32caeb69-10d9-47a5-b95b-865846163914)

**Comment by shaheemMPM** [comment]
I have also experienced this issue. As mentioned in #3143, I was navigating away after choosing a custom theme without hitting save. The problem didn't occur immediately upon navigating away from the custom theme preference; it was working fine until I tried to change the workplace. Here's a screenshot of what's going on. As you can see, I'm not on the self-hosted version but on the organization-hosted version.

![Screenshot 2023-12-25 at 18 25 02](https://github.com/makeplane/plane/assets/32431322/64130cde-e2c0-4d10-a209-86ecd5d21ae6)

**Comment by srinivaspendem** [comment]
This issue has already been fixed. Please upgrade to the latest version to avoid encountering this issue.
