### ISSUE TITLE
[bug]: Theme preference not persisted through different sessions

### ISSUE THREAD

**Issue by cy4n1c** [makeplane/plane#3047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I select a theme, it is applied properly. After logging out and logging back in, the theme is set to `System Preference`.
I expect the chosen theme to be applied every time I log in.

### Steps to reproduce

1. Navigate to `{Workspace URL}/me/profile/preferences` page
2. Set theme to Light or Dark (the theme is applied properly)
4. Log out
5. Log in via magic link (the theme is reset to `System Preference`)

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by vihar** [comment]
@cy4n1c, thank you for flagging this issue. This is already a known bug. It will be addressed in https://github.com/makeplane/plane/pull/2455/files, which will be included in the next release (`v0.14-dev`).

**Comment by cy4n1c** [comment]
The bug is still present after the update. It looks like it's triggered only when magic link is used for signing in.
If password from the email is used, the theme is applied correctly.

**Comment by vihar** [comment]
@cy4n1c, sorry you're still seeing this issue. we'll debug this and push a patch shortly.

**Comment by srinivaspendem** [comment]
This issue has been resolved and no longer exists in our current version.
