### ISSUE TITLE
correct license should be stated in the documentation quick start page

### ISSUE THREAD

**Issue by ymolists** [makeplane/plane#3048]
Hi Team

`Plane is open-sourced under Apache-2.0, and currently, .. `

The above is from the [quick-start page](https://docs.plane.so/quick-start) should this be corrected ? or the license is meant to be changed ? which one is correct ?

Regards

**Comment by vihar** [comment]
we are so sorry it's taken us this long to get back to you and for a sensitive matter as this. just, we are a very small team and its difficult to get to everything in time. no excuse, though.

thank you so much for reporting this. we have now fixed this to AGPL, which is our correct license. this has always been the case and is reflected in the `LICENSE.txt` file in our primary repo `plane`.
