### ISSUE TITLE
[bug]: Date Input in Gantt is off by one day. 

### ISSUE THREAD

**Issue by KarloDerEchte** [makeplane/plane#3074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

As you can see, the start day that has been set via the Gantt Diagram is off by one day in the Issue Peek View.

![image](https://github.com/makeplane/plane/assets/41088744/4dc30026-6564-4a07-9301-498a9cb93883)

![image](https://github.com/makeplane/plane/assets/41088744/b5cd4075-1509-4e91-8344-7e1299a9cf8e)

This issue still exists in master and in 0.14-dev.

### Steps to reproduce

1. Go to Issues
2. Create a New Issue
3. Switch to gantt view
4. Move date via Drag and Drop
5. Look at the Issue Peek overview and see that it is off by one day.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
Thank you for bringing this to our attention, @KarloDerEchte. It appears to be a bug. 

Is this happening with every `Issue` in your project, or just for a few? Additionally, does this fix the issue with responsiveness? Please provide us with this information; it will assist us in resolving the problem.

cc: @aaryan610

**Comment by KarloDerEchte** [comment]
If I change the size of the page, the issue persists. Both 0.13 and 0.14(dev branch). If you mean that with responsiveness.

**Comment by roguefalcon** [comment]
I'm seeing the off by one date issue in several places in the software.  For example if I pick December 12th as the Start Date in the Spreadsheet View for a Cycle it will pick December 11th.

**Comment by vihar** [comment]
thanks @roguefalcon and @KarloDerEchte, this should help us debug. we'll work on a fix shortly.

**Comment by vihar** [comment]
@luis-cruzt, @kripainc, @tyleraharrison moving our conversation here from https://github.com/makeplane/plane/issues/1992. We are shortly working on a fix for this, we'll update on this shortly.

**Comment by tyleraharrison** [comment]
> .

Awesome, looking forward to it

**Comment by tyleraharrison** [comment]
> @luis-cruzt, @kripainc, @tyleraharrison moving our conversation here from https://github.com/makeplane/plane/issues/1992. We are shortly working on a fix for this, we'll update on this shortly. 

Awesome, looking forward to it

**Comment by jordan-zimmitti-newmile** [comment]
Hi, glad to see this is being worked on as every date picker seems to be off by one day (exp. selecting Dec 14 shows Dec 13 circled)

That being said just wanted to say how much I love plane so far. This is an amazing project so far and I am excited to see its growth!

**Comment by KarloDerEchte** [comment]
What's the status of this issue?

**Comment by pablohashescobar** [comment]
@KarloDerEchte, what version are you using I tried the same in the latest version and was unable to replicate it.

**Comment by KarloDerEchte** [comment]
> @KarloDerEchte, what version are you using I tried the same in the latest version and was unable to replicate it.

I am currently on the latest docker image version.

**Comment by pablohashescobar** [comment]
@KarloDerEchte, will check this with the team once and update.

**Comment by KarloDerEchte** [comment]
Thank you!

**Comment by Huuuze** [comment]
> @KarloDerEchte, will check this with the team once and update.

We're using 0.14.0 and the issue exists.

**Comment by psi-chuffine** [comment]
I can see in the request to the server, the date I select is sent but the UI displays the incorrect date.
![image](https://github.com/makeplane/plane/assets/76532245/cd9f2a0b-3784-40d3-af22-4e2ce6ecf96a)

When editing from the modules screen, the display is off by two and the message sent is off by one. 
![image](https://github.com/makeplane/plane/assets/76532245/385c60a0-0a96-408f-8a3d-ae09b8b81f78)

This may stem from a [challenge of the JS Date library.](https://dev.to/zachgoll/a-complete-guide-to-javascript-dates-and-why-your-date-is-off-by-1-day-fi1)

**Comment by KarloDerEchte** [comment]
Seems to be fixed in 0.16
