### ISSUE TITLE
[bug]: self host deployment failing

### ISSUE THREAD

**Issue by LukeHagar** [makeplane/plane#3077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Following the self-host instructions here: https://docs.plane.so/self-hosting

Everything works normally at first, but when I get to run the docker-compose command, there seems to be an issue with the docker-compose file that is giving me the below error.

![image](https://github.com/makeplane/plane/assets/5702154/b550e6c5-4be2-46af-9bb3-6cf60f248296)

I don't know if there is a step I missed, or if the script did not run correctly or what, I noticed there was no output from the setup.sh file when run, but on inspection that seems to be expected.

### Steps to reproduce

Follow the self-host instructions I suppose, this is occurring on a brand new Ubuntu server VM

### Browser

Other

### Version

Self-hosted

**Comment by Nizar-Almshantaf** [comment]
I was facing the same issue on my old VPS, and after updating docker to the latest version solved this issue.

**Comment by mguptahub** [comment]
@LukeHagar - can you please check the updated [self hosting docs](https://docs.plane.so/self-hosting/docker-compose)

**Comment by LukeHagar** [comment]
@mguptahub, Those docs are fantastic!

Thank you so much for sharing. With those super clean `docker-compose.yaml` and `.env` files I was able to deploy the app in my existing docker environment no sweat.
