### ISSUE TITLE
[bug]: Unable to create workspace in the onboarding stage

### ISSUE THREAD

**Issue by Nizar-Almshantaf** [makeplane/plane#3078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I created a fresh VPS from digital ocean with Ubuntu 23 and followed the steps for self-hosted version, I only changed the default credentials & chatgpt key in the .env files. docker is not showing any error during the installation but after that when I login using my creds and try to create a work space I get this error in the image below 
![image](https://github.com/makeplane/plane/assets/91416945/0fc8ba4f-2da5-462e-bb2a-183613f5fc84)
after that when I try to create a workspace with the same name I get this error 
![image](https://github.com/makeplane/plane/assets/91416945/38a0adf2-3dfd-4723-9007-252eb926471b)
and here is the docker logs
![image](https://github.com/makeplane/plane/assets/91416945/462b35fb-fbcc-4d44-8ba7-491f573874a3)

### Steps to reproduce

1. git clone --depth 1 -b master https://github.com/makeplane/plane.git && cd plane
2. ./setup.sh
3. change default credentials & add chatgpt key in the .env file
4. docker compose -f docker-compose-hub.yml up
5. open website & enter onboarding
6. toast error shows on top right

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@Nizar-Almshantaf this looks like an old bug, can you upgrade to our latest docker images and reproduce this issue?

**Comment by Nizar-Almshantaf** [comment]
After wiping everything (docker containers/images/volumes/network) and pulling the latest code from the master branch, I am no longer facing the issue.
@vihar Thanks.
