### ISSUE TITLE
[bug]:  Issue is not draggable after drop back

### ISSUE THREAD

**Issue by stylessh** [makeplane/plane#3083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you drop the issue back on the original column, drag is disabled and can't be used anymore. Also a duplicate issue appears for second.

https://github.com/makeplane/plane/assets/45767683/72d123ae-c96b-410e-b856-474f46a0cbdb

### Steps to reproduce

1. Go to issue tab.
2. Select Kanban layout.
3. Drag an issue and go back to the original colum.

### Browser

Google Chrome

### Version

Cloud

**Comment by vihar** [comment]
thanks for flagging this, @stylessh. this issue is fixed on our latest release, it's available on self-hosted version, and will be soon pushed to cloud.
