### ISSUE TITLE
[bug]: page contents aren't saved

### ISSUE THREAD

**Issue by notpushkin** [makeplane/plane#3120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create a new page in a project, it appears to save contents but actually doesn't.

### Steps to reproduce

1. Create a new page
2. Type something in the editor
3. _Saving..._ indicator appears, then changes to _Saved_, but no network requests are actually made
4. Reload page. Page title is saved but contents are gone

No errors in the console either, which is weird 🤔 

I'm using a custom [Docker Swarm based setup](https://gist.github.com/notpushkin/1e515addde258995f1e26e0f099afb22), but everything else seems to work fine so I don't think this is the cause.

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by henit-chobisa** [comment]
Hey @notpushkin, thank you so much for opening the issue and helping us making plane better. I believe you would be glad to know that, we have already resolved this issue and you'll soon see a PR for this, mostly before EOD. ✌🏼

**Comment by Palanikannan1437** [comment]
Hey @notpushkin, I've raised [this PR](https://github.com/makeplane/plane/pull/3203) that should be fixing this bug 🙌

Thanks so much for opening this issue and letting us know!
