### ISSUE TITLE
[bug]: self-hosted: setup.sh: docker compose does not exist on ubuntu 23.10. Use docker-compose instead.

### ISSUE THREAD

**Issue by corbolais** [makeplane/plane#3124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to install a self-hosted plane instance using `./setup.sh` -> "1" (install) fails due to the `docker compose` command being unavailable on Ubuntu 23.10 and earlier (most likely).

Solution: replace `docker compose` with `docker-compose`.

### Steps to reproduce

On Ubuntu 23.10, install latest docker debs and start the self-hosted installation procedure as given in https://docs.plane.so/self-hosting/docker-compose .

### Browser

Google Chrome

### Version

Self-hosted

**Comment by mguptahub** [comment]
Hello @corbolais 

Let me validating on ubuntu 23.10 and get back to you.

**Comment by mguptahub** [comment]
@corbolais 

We have tried the same setup on 23.10 as per docs,  `docker compose ...` worked perfectly fine

**Comment by corbolais** [comment]
Hi @mguptahub 
with my Ubuntu 23.10 installation there is no such thing. Maybe account for that in your scripts? Defensive programming, check for binary availablitiy and have a fallback.
Cheers
