### ISSUE TITLE
[bug]: Choosing custom theme and navigating away from preferences results in client side error, unrecoverable

### ISSUE THREAD

**Issue by genox** [makeplane/plane#3143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a clean test install of plane@latest. Clicking around to see what is possible, I clicked on Preference, Themes and selected the custom theme option. Then I navigated away without saving anything and got an error pointing to this code:

```
o = (e, t) => {
                var r;
                let n = null === (r = document) || void 0 === r ? void 0 : r.querySelector("[data-theme='custom']"),
                    o = e.split(",");
                o.push(t ? "dark" : "light");
                let a = i(o[0]),
                    s = i(o[1]),
```

The error refers to `e.split` being undefined.

Now, no matter which route I try to go to, I get a client side exception and I can't reset the theme setting. So I am basically locked out of my account.

### Steps to reproduce

1. Clean install
2. > User preferences > Theme options
3. Select custom theme
4. Navigate away without changing or saving anything
5. See client side exception

### Browser

Safari

### Version

Self-hosted

**Comment by siunus** [comment]
No need to perform a Clean Install. The solution is here #2975

I have also experienced it.

**Comment by genox** [comment]
I will do that, thanks for linking.
