### ISSUE TITLE
[bug]: In god-mode, the empty fields are filled with "". v0.14

### ISSUE THREAD

**Issue by Dev-A-Line** [makeplane/plane#3158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In god-mode, the empty fields are filled with "". 

![image](https://github.com/makeplane/plane/assets/14335460/a8846bc3-263a-4aa6-bfd8-ba7623212e5f)

### Steps to reproduce

To obtain authorization, just go to http://[IP-ADDRESS]:[PORT]/god-mode/authorization

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
@Dev-A-Line, thanks for reporting this bug we will take this up in the upcoming release.

**Comment by srinivaspendem** [comment]
Hey @Dev-A-Line, just a heads up: this issue is no longer persistent in our current version. If you're still encountering it, please update to the latest version.
