### ISSUE TITLE
[bug]: Your plane instance isn't ready yet

### ISSUE THREAD

**Issue by dskovac** [makeplane/plane#3173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After following the instructions listed on https://docs.plane.so/self-hosting/docker-compose, I am able to run Plane using my domain/IP address, but it only shows static image of a plane saying "Your Plane instance isn't ready yet
Ask your Instance Admin to complete set-up first."

All containers are up and running without any errors. Please help!

### Steps to reproduce

1. Follow self hosted manual
2. Install the latest build
3. Start the containers
4. Open web browser

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Dev-A-Line** [comment]
I managed to get this running by installing v0.13 according to the instructions and then making migrations to v0.14. And then the /god-mode page starts working

https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x

**Comment by dskovac** [comment]
Thanks @thefiredragon this has solved it... And I have lost half a day going through containers and environments trying to figure out whats wrong :) 

Thanks to @Dev-A-Line  as well :)

**Comment by ekopras18** [comment]
> add to your url of your instance http://x.x.x.x/god-mode

thanks

**Comment by Gictorbit** [comment]
> add to your url of your instance http://x.x.x.x/god-mode

how can I do that?

**Comment by dskovac** [comment]
@Gictorbit just type in your browser bar the name or the IP address of your instance and add manually **/god-mode**

http://x.x.x.x/god-mode

**Comment by respect17** [comment]
> add to your url of your instance http://x.x.x.x/god-mode

Thanks a lot, it worked for me!
