### ISSUE TITLE
[bug]: New States anywhere, it is added to the end. v0.14

### ISSUE THREAD

**Issue by Dev-A-Line** [makeplane/plane#3176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you add States anywhere, it is added to the end and cannot be moved.

### Steps to reproduce

Create States.
![image](https://github.com/makeplane/plane/assets/14335460/367ae870-9ae7-45d0-9ab5-1d5050c08601)
Go to Kunban submission and there are 2 problems. The first one is that there is no horizontal scrolling and the second one is that all new states are placed at the end of the list and cannot be moved.
![image](https://github.com/makeplane/plane/assets/14335460/cb9d47df-03f9-4827-8723-baac833fa2a5)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
Thank you for flagging this, @Dev-A-Line. We will soon implement a patch to address and resolve this issue.

**Comment by srinivaspendem** [comment]
Hey @Dev-A-Line, This issue has been resolved with the 0.14.2 release. If you're still experiencing it, please update to the latest version.
