### ISSUE TITLE
[bug]: Github Import will not allow me to select project

### ISSUE THREAD

**Issue by Jon-Schneider** [makeplane/plane#3197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've connected Github with the goal of importing the issues from my project repo to try out Plane (limiting the access to just the project with the issues). Unfortunately I cannot continue past the Select Repository option.

I attempted to Uninstall the Github integration and reattempt while allowing access to all my repos but uninstall does not work.

This repros for me in both Chrome and Safari.

![Screenshot 2023-12-19 at 10 28 01 AM](https://github.com/makeplane/plane/assets/2467701/67841947-3d00-4bc3-b0e1-e60aa9e96382)
![Screenshot 2023-12-19 at 10 28 07 AM](https://github.com/makeplane/plane/assets/2467701/0fd45b61-5b37-487c-86aa-433c9a4685b1)

### Steps to reproduce

1. Connect Github integration
2. Attempt to import issues

### Browser

Google Chrome

### Version

Cloud

**Comment by andremourasantos** [comment]
(Same comment as in #3244)
I have the same issue... I'm on Version: v0.14.0 (cloud).

I've got some issues logged on the console upon opening up the Integrations Settings on my project:
![Integrations Settings on my project](https://github.com/makeplane/plane/assets/92397834/a6a1aded-7394-4e35-b54a-58f84244288b)


While accessing the Import Settings on the Workspace page, I got some other errors too:
![Import Settings on the Workspace page](https://github.com/makeplane/plane/assets/92397834/27b2c1da-ba09-43e5-a534-d3c54d4823f3)


The current integrations seem to be working just fine, but I cannot add new ones...

**Comment by vihar** [comment]
Sorry for the inconvenience. We've identified the issue and will shortly raise a pull request to fix this. 

cc: @sriramveeraghanta, @pablohashescobar, @aaryan610.

**Comment by vihar** [comment]
The issue has been resolved in our `v0.15-dev` release. Thank you for flagging this.
