### ISSUE TITLE
[bug]: Cannot link issues

### ISSUE THREAD

**Issue by athornfam2** [makeplane/plane#3199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I can't seem to link parent and child issues together under the self-hosted v0.14.0 application. 

### Steps to reproduce

Create 2 or more issues, Select the child issue, attempt to link to a parent issue. The click goes through but the issue isn't linked to the parent

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@athornfam2, thanks for flagging this. I've noticed the bug only in peek mode. When adding a parent issue on the issue detail page, everything works fine, as far as I can tell. Correct me if I'm wrong. We'll be shipping a PR to fix the peek mode issue shortly.

**Comment by pushya22** [comment]
#3228 This issue is resolved with this PR
