### ISSUE TITLE
[bug]: description_stripped not returned in API

### ISSUE THREAD

**Issue by tonyeggers** [makeplane/plane#3212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When calling API endpoint /api/v1/workspaces/:slug/projects/:project_id/issues/:issue_id/ for an issue, the description_stripped field is not returned.

### Steps to reproduce

1. Install local development
2. using master branch (just for checking things out with current stable version)
3. using Docker Desktop on Windows
4. Open port for localhost:8000
5. Able to retrieve specific issue successfully using issues endpoint
6. Description_stripped field is not returned
7. Using "fields" parameter works with other fields (e.g. description_html), but not description_stripped

### Browser

Google Chrome

### Version

Local

### Related (Possible)
https://github.com/makeplane/plane/pull/2970/commits/2ece8bceac9dfbb5963734acefe8bf11d2a394a0  (tested removing description_stripped from the exclusions allowed field to be returned)

**Comment by NarayanBavisetti** [comment]
Hey @tonyeggers , regarding the external APIs, we're currently only providing description_html and not description_stripped. Could you share how having this data format might be beneficial for your specific needs or workflow?

**Comment by tonyeggers** [comment]
Hi @NarayanBavisetti , I don't think it's a big deal because I can strip/clean after pulling the data. However, reasons for having clean text with HTML include reporting, analytics (.e.g. sentiment), training, LLM processing, etc.

**Comment by NarayanBavisetti** [comment]
Hi @tonyeggers ,

Thank you for your response and insights into the data format. As of now, we're exclusively providing the description_html. I'll definitely bring up your points and discuss the potential benefits of incorporating the clean text format with my team.

**Comment by tonyeggers** [comment]
Thanks @NarayanBavisetti.
