### ISSUE TITLE
[bug]: failed to upload an image in 0.14 self-hosted version

### ISSUE THREAD

**Issue by taorensayweee** [makeplane/plane#3216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

failed to upload an image in 0.14 self-hosted version

### Steps to reproduce

17031487534204](https://github.com/makeplane/plane/assets/92711117/97523d4c-9054-4713-bbf8-4fbaaee64f13)

### Browser

Google Chrome

### Version
self-hosted

**Comment by Dev-A-Line** [comment]
https://github.com/makeplane/plane/issues/3208   A similar issue has already been created I solved it by connecting a domain, but if you put ip it defaults to localhost

**Comment by vihar** [comment]
@taorensayweee closing this issue, we will shortly fix this one. Moving the conversation to main thread, #3208.
