### ISSUE TITLE
[bug]: Cannot add a parent for an already created issue 

### ISSUE THREAD

**Issue by Bahaatbb** [makeplane/plane#3236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I click on an already created issue to add a parent for it, it opens the parent issue select modal in which I choose an issue, But then it doesn't add it and the modal disappears (giving the feeling it was added).
<img width="567" alt="Screenshot 2023-12-22 at 19 31 26" src="https://github.com/makeplane/plane/assets/60551967/7ed483d4-4f90-4df7-8cc1-3653edcb0727">

**Note**: after careful testing, it seems like the click outside event is being triggered and both modals (the main issue modal and the select parent modal) are closing, meaning if you choose a parent issue using only the arrow keys it will work perfectly. 

### Steps to reproduce

1. Create two issues with no parent 
2. Click on one of the issues 
3. Click on add parent  
4. Recheck the issue

### Browser

Google Chrome

### Version

Local

**Comment by romainds-tech** [comment]
I got the same issue

**Comment by pablohashescobar** [comment]
Thank you for highlighting this issue. It appears to occur specifically in the peak view. Could you please let us know if you've experienced this problem in any other views as well?

**Comment by kdanet** [comment]
I confirm that the problem is exactly when clicking with the mouse when the modal window is open.
If you select with keyboard, arrows and enter, everything is fine

**Comment by vihar** [comment]
This issue is resolved on our latest release. Please upgrade to the latest version if you're self-hosting. Thank you for flagging this.
