### ISSUE TITLE
[bug]: patch issue state returns invalid UUID

### ISSUE THREAD

**Issue by tonyeggers** [makeplane/plane#3238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Attempting to update issue state using API returns invalid UUID. Correcting filter for UUID then causes failure with filter lookup due to context not being passed.  Issue is with serializer code in apiserver/plane/api/serializers/issue.py for UUID failure, and then context not being set in patch method in apiserver/plane/api/views/issue.py.

### Steps to reproduce

1) Install local development version
2) Get API Key
3) Issue patch for issue state
4) failure due to UUID 
5) Resolve UUID, issue then failure for relevant project requirement

### Browser

Google Chrome

### Version

Local

**Comment by NarayanBavisetti** [comment]
Hey @tonyeggers , thanks for pointing this out, this issue is been fixed in the PR #3259
