### ISSUE TITLE
[bug]: Fail to start: "gpgdecryption failed: No secret key"

### ISSUE THREAD

**Issue by BoyanXu** [makeplane/plane#3241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

System: Arch Linux, x86

Fail to `2) Start` with setup.sh

### Steps to reproduce

```
Select a Action you want to perform:
   1) Install
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) Exit

Action [2]: 1


Installing on /home/.../plane-selfhost/plane-app

Latest version is now available for you to use

In case of Upgrade, your new setting file is available as 'variables-upgrade.env'. Please compare and set the required values in '.env 'file.


Select a Action you want to perform:
   1) Install
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) Exit

Action [2]: 2

[+] Running 0/0
 ⠋ space Pulling                                                                                                                    0.0s 
error getting credentials - err: exit status 1, out: `exit status 2: gpg: public key decryption failed: No secret key
gpg: decryption failed: No secret key`
```

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@BoyanXu, is this your first time installing a plane on a Linux machine, or are you attempting to upgrade your instance? @mguptahub will shortly assist you with this.

**Comment by mguptahub** [comment]
@BoyanXu  as of now we build amd64 images only. We are working in cross platform images which should be out sometime Feb ‘24

**Comment by BoyanXu** [comment]
Thanks for reaching out.

I was attempting to upgrade my instance with the `setup.sh`. 

Previously, I manage my instance with docker-compose.yml, and things work well.

If this is not a common issue for most users, then I'll simply try again later.
