### ISSUE TITLE
Web container deployment error "/usr/local/bin/start.sh": stat /usr/local/bin/start.sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by halil-bugol** [makeplane/plane#3242]
I integrated an SSO application into the web interface. Next, I tried to compile it with dockerfile.dev located under the Web folder. The compilation completed successfully, but I get the following error. I just want to image the web. Then, the image that I tested locally as a test deployment. I want to deploy it remotely on a different Plane that I set up with Helm.

`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/start.sh": stat /usr/local/bin/start.sh: no such file or directory: unknown`

After receiving the error, I tried to create an image with Dockerfile.web, but I get the following error during image creation.

```
21.92 web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
21.93 web:build: error Command failed with exit code 1.
21.93 web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21.94 web:build: ERROR: command finished with error: command (/app/web) /tmp/yarn--1703456772769-0.08211509966452724/yarn run build exited (1)
21.94 web#build: command (/app/web) /tmp/yarn--1703456772769-0.08211509966452724/yarn run build exited (1)
21.95
21.95  Tasks:    7 successful, 8 total
21.95 Cached:    0 cached, 8 total
21.95   Time:    21.568s
21.95 Failed:    web#build
21.95
21.95  ERROR  run failed: command  exited (1)
21.96 error Command failed with exit code 1.
21.97 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile.web:32
--------------------
  30 |     ENV NEXT_PUBLIC_DEPLOY_URL=$NEXT_PUBLIC_DEPLOY_URL
  31 |
  32 | >>> RUN yarn turbo run build --filter=web
  33 |
  34 |     FROM node:18-alpine AS runner
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn turbo run build --filter=web" did not complete successfully: exit code: 1
```

**Comment by halil-bugol** [comment]
ping @sriramveeraghanta

**Comment by mguptahub** [comment]
Hello @halil-bugol 

Here are few things i need to know
- branch name on which you made the changes
-  steps you followed to create image

As per your message, it appears that you are not able to create the docker image of your web folder.

**Comment by halil-bugol** [comment]
> Hello @halil-bugol
> 
> Here are few things i need to know
> 
> * branch name on which you made the changes
> * steps you followed to create image
> 
> As per your message, it appears that you are not able to create the docker image of your web folder.

@mguptahub 

Branch Name: preview
Image Creation Steps:
1) run setup.sh in main folder
2) run docker image build -f /web/Dockerfile.web -t web-test .

**Comment by sriramveeraghanta** [comment]
Hello @halil-bugol, 

I have tried building the web docker file, as you mentioned. I didn't find any issue on preview branch. Can you take a pull from the preview branch and try building it again?

**Comment by halil-bugol** [comment]
@sriramveeraghanta I made a mistake. Sorry. Can you try it in Develop Branch?

**Comment by sriramveeraghanta** [comment]
`develop` is an unstable branch where multiple developers are pushing the code to it and testing a bunch of upcoming feature and bugfixes. I suggest you to try using the `master` branch which contains the stable changes we shipped in the last release or you can check `preview` branch which contains some bugfixes and feature we are going to ship in the next release.

**Comment by halil-bugol** [comment]
I will try it on the master and let you know.

**Comment by halil-bugol** [comment]
I passed the master branch and tried again. I found a few syntax errors. After fixing these it worked. Should I open PR?


/web/components/modules/modules-list-view.tsx  // line 99
```
primaryButton={
            isEditingAllowed
              ? {
                  icon: <Plus className="h-4 w-4" />,
                  text: "Build your first module",
                  onClick: () => commandPaletteStore.toggleCreateModuleModal(true),
                }
              **: null // I updated it to undefined**
          }
          disabled={!isEditingAllowed}
        />
      )}
```

/web/components/views/views-list.tsx  // line 86
```
primaryButton={
            isEditingAllowed
              ? {
                  icon: <Plus size={14} strokeWidth={2} />,
                  text: "Build your first view",
                  onClick: () => commandPaletteStore.toggleCreateViewModal(true),
                }
              **: null // I updated it to undefined**
          }
          disabled={!isEditingAllowed}
        />
      )}
```

**Comment by sriramveeraghanta** [comment]
> I passed the master branch and tried again. I found a few syntax errors. After fixing these it worked. Should I open PR?
> 
> /web/components/modules/modules-list-view.tsx // line 99
> 
> ```
> primaryButton={
>             isEditingAllowed
>               ? {
>                   icon: <Plus className="h-4 w-4" />,
>                   text: "Build your first module",
>                   onClick: () => commandPaletteStore.toggleCreateModuleModal(true),
>                 }
>               **: null // I updated it to undefined**
>           }
>           disabled={!isEditingAllowed}
>         />
>       )}
> ```
> 
> /web/components/views/views-list.tsx // line 86
> 
> ```
> primaryButton={
>             isEditingAllowed
>               ? {
>                   icon: <Plus size={14} strokeWidth={2} />,
>                   text: "Build your first view",
>                   onClick: () => commandPaletteStore.toggleCreateViewModal(true),
>                 }
>               **: null // I updated it to undefined**
>           }
>           disabled={!isEditingAllowed}
>         />
>       )}
> ```

I have verified the current changes in the master branch and tried building `web`. Seems like everything is fine to me. If you are still facing any issues, please feel free to create a pull request, our internal team will review it and get it merged as soon as possible.
