### ISSUE TITLE
[bug]: The content of the article in pages is not always saved. v0.14

### ISSUE THREAD

**Issue by Dev-A-Line** [makeplane/plane#3253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The content of the article in pages is not always saved. The title of the article is created, but the content disappears and there is no possibility to press the save button.After trying to insert data into the corner, a save message appears, but no save occurs. You can check this by going up a level higher in pages and going to the article again

### Steps to reproduce

1.Open the project and go to pages
2.Create an article
3.Attempt to enter or paste text data

### Browser

Google Chrome

### Version

Self-hosted

**Comment by henit-chobisa** [comment]
Hey there @Dev-A-Line, thanks for creating the issue. Can you please help me with the version of plane you're using?

**Comment by Dev-A-Line** [comment]
> Hey there @Dev-A-Line, thanks for creating the issue. Can you please help me with the version of plane you're using?

v0.14.0

**Comment by Palanikannan1437** [comment]
Hey there @Dev-A-Line, this should be fixed with https://github.com/makeplane/plane/pull/3203

Please consider upgrading to v0.14.2 🙌
