### ISSUE TITLE
[bug]: Unable to view the uploaded file in the issue  

### ISSUE THREAD

**Issue by kapoorabhish** [makeplane/plane#3255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,
I have installed the self hosted with S3 compatible service provided by E2E.
When I attach a file in the issue it's uploaded successfully but the in the browser it shows loading indefinitely.

![Screenshot 2023-12-26 175531](https://github.com/makeplane/plane/assets/4546754/57f48c91-4a4b-4f07-938d-de8c1251f7e9)

I can see the file in the S3.

Below are the settings in for S3 in the .env
```
USE_MINIO=0
AWS_REGION=
AWS_ACCESS_KEY_ID="key-id"
AWS_SECRET_ACCESS_KEY="access-key"
AWS_S3_ENDPOINT_URL="https://objectstore.e2enetworks.net"
AWS_S3_BUCKET_NAME="planeso-files"
```

Also, while start up I am getting the below error for S3. Which I am not able to understand why do we need to allow Public access. Further the upload is still working despite the error.
![image](https://github.com/makeplane/plane/assets/4546754/cbd7f0cd-a460-4b2c-a57b-1ac378ad085b)

I request if you could help me figure out the issue.

### Steps to reproduce

1. Install the self hosted Plane So on Docker.
2. Configure the required setting in .env
3. Try to create an issue and attach a file.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
@kapoorabhish, can you check if the provided bucket is public.

**Comment by Souravpakhira** [comment]
Can I work on this issue we can even add ACL to the object while uploading to s3 without making whole s3 bucket public

**Comment by kapoorabhish** [comment]
@pablohashescobar Could you please explain me why do we need to make the bucket Public?
It is supposed to store the sensitive organization's data.

**Comment by Souravpakhira** [comment]
if bucket is not public than you cannot access the object of that bucket unless you generate pre-signed URL. But there's a workaround to this issue. We can make the object public through ACL without making the whole bucket public

**Comment by kapoorabhish** [comment]
Could you please explain how could that be achieved?

**Comment by pushya22** [comment]
Hi @kapoorabhish closing the issue for now, please re-open if the issue persists
