### ISSUE TITLE
[bug]: Can't add a link in a ticket

### ISSUE THREAD

**Issue by petergerdes** [makeplane/plane#3272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I want to add a link to a ticket the dialog disappears when clicking anywhere.

### Steps to reproduce

1. Open a ticket (or create new one).
2. Click on 'new' next to 'links'.
3. Click on 'Enter title' (for example).
4. Dialog disappears.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by andremourasantos** [comment]
I'd the same issue @petergerdes, but I got a way to deal with it, at least for the time being: just use tab to add the link and the title. If you click anywhere, the dialog will close, but using tab it'll work fine.

Also, if you open the issue in the "big view" (that one with all the options), it works just fine, it's just for that side-open view. I don't know why, though...

**Comment by abidkhan484** [comment]
I just tried but couldn't regenerate the issue. Probably, it's been fixed. @pablohashescobar

**Comment by andremourasantos** [comment]
Yes, it's working again! I just tested it.

**Comment by abidkhan484** [comment]
> Yes, it's working again! I just tested it.

Can you please close the issue 🙂
