### ISSUE TITLE
[bug]: Navigation not accessible on screens < 767px

### ISSUE THREAD

**Issue by tillkoll** [makeplane/plane#3282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

No navigation is accessible when opening the dashboard or any other page on a small screen (width < 767px). 
Nothing is happening, when clicking on "Dashboard" or the icon on the upper left side.

![image](https://github.com/makeplane/plane/assets/65401722/b679fb79-da90-48f0-b108-1bc0c452b7b2)

### Steps to reproduce

1. Open Dashboard or any other page
2. Resize window to any width smaller than 767px or open on a mobile device

Tested on Chrome, Firefox and Chrome Mobile

### Browser

Google Chrome

### Version

Self-hosted

**Comment by sriramveeraghanta** [comment]
Hello @tillkoll , 

We haven't optimised plane web screens for smaller devices as of now. However, there is a plan to address this issue in upcoming releases. This means that improvements and adjustments will be made to ensure a smoother and more user-friendly experience for individuals accessing the web application on tablets and mobile devices.
