### ISSUE TITLE
[bug]: Ticket can't be a parent to multiple tickets

### ISSUE THREAD

**Issue by petergerdes** [makeplane/plane#3285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I add a ticket as Parent to a ticket, another ticket can't have that same parent (it's not visible in the list). I think a ticket a ticket should be able to have several children. When opening a parent and add subtickets it does allow for multiple children.

### Steps to reproduce

1. Open a ticket
2. Add a parent ticket (ticket MVP-2)
3. Close ticket
4. Open a different ticket
5. Add a parent ticket
6. Ticket MVP-2 is not visible in the list

### Browser

Google Chrome

### Version

Self-hosted

**Comment by etaxi341** [comment]
@pushya-plane and @srinivaspendem Can you have a look at this ticket? I think this was unnoticed because you were not automatically assigned to this issue.

**Comment by srinivaspendem** [comment]
Thank you for bringing this to our attention. We are resolving this as I am typing this message. It will be resolved with our upcoming release.
