### ISSUE TITLE
[bug]: "Issues closed by you" graph on Dashboard does not update info

### ISSUE THREAD

**Issue by andremourasantos** [makeplane/plane#3291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I change the selected month on the "Issues closed by you" graph in the Dashboard, the graph updates as expected, but if I change the selected month back again, it won't update the graph.

See video below:
[Screen recording 2023-12-30 17.39.18.webm](https://github.com/makeplane/plane/assets/92397834/6850e12b-5608-44bd-a439-1dd66efe9031)

I find out that if you minimize the tab, and then reopens it, the graph is updated with the correct information.

See video below:
[Screen recording 2023-12-30 17.42.59.webm](https://github.com/makeplane/plane/assets/92397834/cf732cfd-ae70-4c2f-8d8d-8f6f32c154c5)

I didn't get anything logged into the console, link and error or something like that.

### Steps to reproduce

1. Go to the Dashboard view;
2. Change the month on the "Issues closed by you" graph's selector;
3. See the change take effect as expected;
4. Change the month back to the previous one selected;
5. See the change doesn't take effect;
6. Minimize the tab;
7. Open the tab again;
8. See the change take effect immediately.

### Browser

Google Chrome

### Version

Cloud

**Comment by vihar** [comment]
@andremourasantos, we're currently making several improvements to our dashboards. Soon, we'll be introducing customizable widgets where you can configure the data you want to see. For now, we've removed the 'issues closed by you' metric. Thank you for bringing this to our attention.
