### ISSUE TITLE
[bug]: i have set all issues status to completed but the analytics still shows task are pending

### ISSUE THREAD

**Issue by vneet2057** [makeplane/plane#3293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when i set the task status to completed then the analytics shall show the task to be completed but i see task are still on pending

### Steps to reproduce

go to project>issues 
create a task and set the task to completed and check the specific project analytics

### Browser

Google Chrome

### Version

Cloud

**Comment by gladium-software** [comment]
Hey. I concur that the analytics view doesn't seem to be working as expected.

Using a recent cycle I can see several issues:

- Progress bar colours are incorrect. In the screenshot below, the line chart in Progress shows a small (pink) "Completed" but a large (green) Cancelled. However, there are 20 completed and 2 Cancelled Features.
- Assignees % is incorrect as everything is assigned to me so I would expect to see 100%
- Chart in the bottom right shows there's 0 Pending Issues but the chart is showing about 9 outstanding. However, the pending is correct as there's nothing outstanding.

<img width="1067" alt="Screenshot 2023-12-31 at 14 27 54" src="https://github.com/makeplane/plane/assets/53213228/f405384d-43be-4f26-a15c-efd0d5202c6f">

**Comment by pushya22** [comment]
Hi, This issue is now resolved.
