### ISSUE TITLE
[bug]: Can add a new Issue from Issues category

### ISSUE THREAD

**Issue by Marounda** [makeplane/plane#3294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i try to create a new issue from the bottom of a list, i get an error "
![Screenshot_219](https://github.com/makeplane/plane/assets/16967465/6e7eb253-74ec-4d88-abc3-f433344944c3)
But it's ot with the button on top right of the page

### Steps to reproduce

create a new issue from the bottom of a list
![Screenshot_219](https://github.com/makeplane/plane/assets/16967465/6e7eb253-74ec-4d88-abc3-f433344944c3)
But it's ot with the button on top right of the page

### Browser

Mozilla Firefox

### Version

Local

**Comment by abidkhan484** [comment]
> It may be the error occurred due to the failure of the dispatch queue to the worker.

Just tried to regenerate it and seems like the issue does not exist right now. 

@pablohashescobar how to initiate a proposal to close an issue.
