### ISSUE TITLE
[bug]: Create issue, using AI doesn't work

### ISSUE THREAD

**Issue by Marounda** [makeplane/plane#3295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i try to use AI to create an issue, i have this error 
![Screenshot_220](https://github.com/makeplane/plane/assets/16967465/7f2a5fe0-bb99-4f72-9bd2-c0ce8f281932)
i've well added the api key and configure with god mode

### Steps to reproduce

go to new issue, click on "AI" button, and reproduce this error
![Screenshot_220](https://github.com/makeplane/plane/assets/16967465/9917ffed-9b5c-4df3-b7a9-5e54b4d78c0f)

### Browser

Mozilla Firefox

### Version

Local

**Comment by vihar** [comment]
@Marounda, thanks for flagging this. We'll fix this soon, and let you know. Please note that our AI features are still in `dev` mode. We'll soon share more updates on this.

**Comment by srinivaspendem** [comment]
Hey @Marounda, This issue has been resolved in our latest version. If you're still experiencing it, please update to the latest version.
