### ISSUE TITLE
[bug]: NGNIX proxy misbehaving

### ISSUE THREAD

**Issue by divyanshchahar** [makeplane/plane#3297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NGNIX proxy is having the following issues:
1. It redirects the user from `http://localhost` to `https://localhost`, this is problematic because plane is running on `http://localhost`
2. Upon inspecting the logs of the NGNIX's docker container the following message was encountered      **2024/01/02 07:33:18 [emerg] 1#1: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/nginx.conf:22
nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /etc/nginx/nginx.conf:22**

### Steps to reproduce

1. Stop all docker containers
2. Remove the NGNIX reverse proxy image which is usually named as `plane-proxy`
3. Rebuild the project with `docker compose -f docker-compose-local.yml up -d` command
4. Check logs of the the docker container running reverse proxy (usually `plane-proxy-1`)

### Browser

Mozilla Firefox

### Version

Local

**Comment by abidkhan484** [comment]
This line is occuring the below error for `evnsubst` [shared in this line](https://github.com/makeplane/plane/blob/preview/nginx/env.sh#L3).

`invalid number of arguments in "proxy_set_header" directive in /etc/nginx/nginx.conf`
 
[This is the case](https://github.com/makeplane/plane/pull/3296/commits/969038792cd5d17497e85b5d36786cb25a2baf24) you are getting the error

Any better solution for assigning the variable with `envsubst` is highly appreciated.

**Comment by Arvin-Zi** [comment]
@abidkhan484  hey have you found the solution for this? i appreciate your help

**Comment by abidkhan484** [comment]
[here is the solution](https://github.com/makeplane/plane/pull/3296/commits/969038792cd5d17497e85b5d36786cb25a2baf24)

**Comment by Arvin-Zi** [comment]
@abidkhan484 Yeah i tried that to  add the "empty" bit, but still when im dockering it up the same error is happening

**Comment by abidkhan484** [comment]
It can be due to caching, try removing cache.

**Comment by mguptahub** [comment]
this is no more an issue. closing it.
