### ISSUE TITLE
[bug]: GITHUB_CLIENT_SECRET declared twice

### ISSUE THREAD

**Issue by divyanshchahar** [makeplane/plane#3299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`./apiserver/env.example` declares `GITHUB_CLIENT_SECRET` at two places within the same file i.e. line number 20 and 43. This could lead to future misconfiguration.

### Steps to reproduce

1. Just look at the above mentioned file

### Browser

Mozilla Firefox

### Version

Local

**Comment by abidkhan484** [comment]
`GITHUB_CLIENT_ID` is also declared twice in lines [18 and 19](https://github.com/makeplane/plane/blob/preview/apiserver/.env.example#L19)
