### ISSUE TITLE
[bug]: Cycle value does not display when editing an issue

### ISSUE THREAD

**Issue by Huuuze** [makeplane/plane#3304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I edit an issue that contains a Cycle value, the Cycle value does not display in the pop-up.

### Steps to reproduce

1. Select the Issues link in a Project.
2. From the List Layout, click the ellipsis button ("...") on the far right that corresponds to an issue with a Cycle value. 
3. Select "Edit Issue". A pop-up displaying the issue will appear.

The pop-up does not display the Cycle value. It's blank. The images below demonstrate the bug.

![Screenshot 2024-01-02 at 3 42 00 PM](https://github.com/makeplane/plane/assets/192399/522f4f14-9d39-4021-9012-7bdb98a0c356)
![Screenshot 2024-01-02 at 3 42 26 PM](https://github.com/makeplane/plane/assets/192399/769c5eda-f342-4021-9567-8ccb0e892184)

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pushya22** [comment]
This issue is now resolved.
