### ISSUE TITLE
[bug]: Installation on selfhost

### ISSUE THREAD

**Issue by Sarank015** [makeplane/plane#3324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

For installing this plane, I had followed the instructions given in the official webste for selfhosting.
![plane](https://github.com/makeplane/plane/assets/142474635/f50d7570-6025-4a87-8189-a998ad9bfb52)

### Steps to reproduce

1. I want to install selfhost plane, but it's not installed.
2. Please provide me steps to install and configure it.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @Sarank015 I apologise that you ran into trouble while installing plane. The screenshot is not that helpful, can you tell which all steps did you complete?

**Comment by Sarank015** [comment]
I had followed these steps

mkdir plane-selfhost

cd plane-selfhost

curl -fsSL -o setup.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh

chmod +x setup.sh

./setup.sh

I had followed this document for installation
https://docs.plane.so/self-hosting/docker-compose

**Comment by Sarank015** [comment]
![plane2](https://github.com/makeplane/plane/assets/142474635/8c8a6ddb-3583-4cc6-8a22-acde1cf8a29c)

**Comment by srinivaspendem** [comment]
Please access the /god-mode to configure the instance. Once the configuration is complete, your instance will be up and running.

**Comment by Sarank015** [comment]
Hi @srinivaspendem, I had installed the selfhosted version with docker-compose. I can't able to configure god mode.
I followed this document for installation https://docs.plane.so/self-hosting/docker-compose

**Comment by srinivaspendem** [comment]
Could you please let us know about the challenges you are encountering while setting up the god mode?

**Comment by patricklubach** [comment]
@srinivaspendem please add a note to the setup page that you have to continue on the [Instance admin and God Mode](https://docs.plane.so/instance-admin) page after the initial setup. Otherwise users get confused at first sight when testing plane initially.

**Comment by shubhamlohar8** [comment]
I had followed these steps

mkdir plane-selfhost

cd plane-selfhost

curl -fsSL -o setup.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh

chmod +x setup.sh

./setup.sh


I can't redirect to /god-mode 

please help

**Comment by vihar** [comment]
We’ve tested our self-hosting setup. Please follow these steps [from our docs](https://docs.plane.so/self-hosting/methods/docker-compose). If you are having issues, please raise a support request on our [Discord](https://discord.com/invite/A92xrEGCge), and our engineers will help you set up Plane on your infrastructure.
