### ISSUE TITLE
[feature]: Support external links in Pages content

### ISSUE THREAD

**Issue by benr77** [makeplane/plane#3334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Unless I am mistaken, there is no way to create a link to an external page or document when editing content in Pages.

### Why should this be worked on?

Any useful document is likely to need references to external resources. Having a "link" button on the toolbar is an expected feature.

I would also have thought that this could be enabled by simply setting the configuration in the editor package.

**Comment by henit-chobisa** [comment]
Hey there @benr77, thank you so much for opening this issue. I wanted to let you know that I am working on both link preview and also link addition, which will be shipped in the next version of plane. 

For now if you want to add a link to the text, you can just copy the link that you want to add, make a selection to the text, where you want to add a link and paste. You will be able to see that the link is now attached with the text. 

We will be adding a link button soon, as you suggested like Link previews in the below PR

**Comment by benr77** [comment]
OK understood. Thanks for the speedy response and the explanation!
