### ISSUE TITLE
[bug]: After paste a rectangular image on issue description body the resize feature does not work properly

### ISSUE THREAD

**Issue by Marinofull** [makeplane/plane#3345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After paste a rectangular image on issue description body the resize behaves "weird":
- When trying to resize to decrease it goes slower than the mouse moves;
- When trying to resize to increase it goes faster than the mouse move;
This makes hard to reach de desired size.

https://github.com/makeplane/plane/assets/4636436/6c19d75e-6c6d-4140-9435-a0e91351267e

It is expected  to follow the mouse moves like it does for a square image.

### Steps to reproduce

1. Open an issue;
2. Click to fill the body description and paste an image;
3. Try to resize, when it is squared it works great, when it is rectangular it goes crazy
4. 
https://github.com/makeplane/plane/assets/4636436/6c19d75e-6c6d-4140-9435-a0e91351267e

### Browser

Google Chrome

### Version

Self-hosted, 0.15.0

**Comment by srinivaspendem** [comment]
Hey @Marinofull, This issue has been resolved. If you're still encountering it, please update to our latest version.
