### ISSUE TITLE
[bug]: NGINX proxy container not starting

### ISSUE THREAD

**Issue by benaissazaki** [makeplane/plane#3357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I cloned the project on my machine by following exactly the [steps ](https://github.com/makeplane/plane?tab=readme-ov-file#steps) in README.

All containers start and work correctly except plane-proxy.

This is what `docker logs plane-proxy-1` outputs:
`2024/01/11 17:08:40 [emerg] 1#1: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/nginx.conf:22
2024-01-11T17:08:40.609447860Z nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /etc/nginx/nginx.conf:22`

### Steps to reproduce

1. Clone the code locally using `git clone https://github.com/makeplane/plane.git`
2. Switch to the code folder `cd plane`
3. Open terminal and run `./setup.sh`
4. Run the docker command to initiate various services `docker compose -f docker-compose-local.yml up -d`
5. Run `docker run ps` which outputs:
![image](https://github.com/makeplane/plane/assets/33980130/15bfe008-f703-4c34-9091-55ce323c6b62)
6. Run `docker logs plane-proxy-1` which outputs:
![image](https://github.com/makeplane/plane/assets/33980130/154da6cf-e29f-47cd-baca-3780977d762f)

### Browser

Other

### Version

Local

**Comment by mguptahub** [comment]
Not sure if you are still facing this issue. 

In case you are, then kindly share the log by running `docker logs plane-proxy-1`

**Comment by benaissazaki** [comment]
> Not sure if you are still facing this issue.
> 
> In case you are, then kindly share the log by running `docker logs plane-proxy-1`

I just retried it (after reinstalling the containers) and unfortunately it still persists with the same error logs as in my original message.

**Comment by abidkhan484** [comment]
closed #3296

**Comment by mguptahub** [comment]
closing this issue (refer: PR #3296)
