### ISSUE TITLE
[question]: Pricing disappeared

### ISSUE THREAD

**Issue by etaxi341** [makeplane/plane#3364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello Makeplane.
I really love your project.
I started using it in December and only because it has a free tier.
On the website it said "free forever" (https://web.archive.org/web/20231220090732/https://plane.so/pricing)

Now you removed this page and added a contact formula.

What does this mean? Will everyone that uses the free tier be left on old versions and can't update because we would have to pay?
This would be a really sad ending for this amazing project.

Thank you for your feedback.

Greetings
Maximilian

### Why should this be worked on?

Keep the project alive

**Comment by theparthacus** [comment]
not at all. we are talking to our potential customers using the form on the page and being an early-stage start-up, we didn't want confusion between the Free and early-adopter paid plans. we are also building a new site, so sometime in February, you will see the Free, the Pro, and the Custom plans.

you are fine. continue using Plane and let us know for what use cases so we can build for them.

**Comment by etaxi341** [comment]
Thank you so much :)
Keep up the great work!
