### ISSUE TITLE
[bug]: Display and Layout change impacts all views(Issues, Cycles, Modules and Views) 

### ISSUE THREAD

**Issue by marcungeschikts** [makeplane/plane#3365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In a project, when I change the layout or the display, it changes it for all the views (Issues, Cycles, Modules and Views) of the same project ( the other project are not impacted).

![image](https://github.com/makeplane/plane/assets/74183327/42060594-71d6-4d81-89c8-aae8154c276b)

### Steps to reproduce

1. Go into Issues view
2. Change the layout or/and the dislpay
3. Go in another view like Cycle
4 Select a Cycle
5. The Cycle view  has the same layout than the Issues view.
6. Change again the layout or/and the dislpay
7. Go back to Issues view
8. The Issues view  has the same layout than the Cycle view.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pushya22** [comment]
This issue is now fixed
