### ISSUE TITLE
[bug]: Selfhost installation problem - unknown shorthand flag: 'd' in -d

### ISSUE THREAD

**Issue by Abraka** [makeplane/plane#3367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

mkdir plane-selfhost
cd plane-selfhost/
curl -fsSL -o setup.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh
chmod +x setup.sh
sudo  ./setup.sh 

[sudo] password for ubuntu: 

Select a Action you want to perform:
   1) Install
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) Exit

Action [2]: 2

unknown shorthand flag: 'd' in -d
See 'docker --help'.

...dead end.
How do I solve this?

### Steps to reproduce

.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
`-d` is used for running the setup in detach mode. Can you please tell the system configuration you are running this @Abraka and also do you have docker and docker compose pre installed.

**Comment by Abraka** [comment]
Im trying installation on Ubuntu 22.04.3 LTS. Docker and docker compose are installed. One thing, there is not "docker compose" but rather docker-compose command...

**Comment by Abraka** [comment]
solution: apt install docker-compose-v2
