### ISSUE TITLE
[bug]: [self-managed]: How to completly remove/delete user ?

### ISSUE THREAD

**Issue by Zebnastien** [makeplane/plane#3373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I can remove a user from Workspaces, but I can't delete his plane.so account totally.
I could not find how to do so in the official documentation.
How to totally delete a user from self-managed instance ?

### Steps to reproduce

Try to remove user account from self managed instance.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by theparthacus** [comment]
a little confused. do you mean their plane.so account, which would be the case if they signed up on app.plane.so, or their self-managed instance's account, which wouldn't be a plane.so account? if the latter, you should be able to delete them once you have removed them from all projects on your self-managed instance and turned their account into an orphan. if you cant' seem to do that, please tell us what the status of the user is and if they are an instance admin for your instance.

**Comment by Zebnastien** [comment]
Thanks,

I am in a self-managed instance. So I understand once removed from all projects/workspaces, I can consider my user deleted.
Thank you for your answer.

**Comment by theparthacus** [comment]
you should be able to delete them from your instance entirely, too. @sriramveeraghanta, could you help with steps to this?

**Comment by AbsurdlySuspicious** [comment]
I'm interested in steps to remove a user from self-hosted instance too. It seems like there's no UI for user management at all, even on /god-mode page. 

Also, users who deactivated their account themselves only are only marked as inactive and are not removed, they can simply login again and re-activate their account, so I don't even see a way to completely remove (or at least block) a user, considering there's a lot of foreign keys in db and no ON CASCADE rules, so you can't even DELETE them

**Comment by HRNPH** [comment]
(self-managed) I'm also encounter the issue that I can't completely deleted the user, it count as deactivated instead

**Comment by hadifarnoud** [comment]
this is confusing and cumbersome. I must be allowed to delete/block a user from workspace settings. deleting them from each project is a hassle

**Comment by sriramveeraghanta** [comment]
> (self-managed) I'm also encounter the issue that I can't completely deleted the user, it count as deactivated instead

Yes. By removing the user from the workspace their workspace membership will be suspended. We are still keeping as part of the workspace for audit purposes.

**Comment by zliebersbach** [comment]
> We are working on the Instance level user management

Can this ticket be reopened until then?

**Comment by rprechelt** [comment]
I would second this feature. Since users can reactivate "suspended" accounts, there is no ability to actually remove a user from the Plane platform when self-hosted.
