### ISSUE TITLE
[bug]: When opening a child-issue card the parent task field is displayed as undefined-undefined

### ISSUE THREAD

**Issue by kdanet** [makeplane/plane#3374]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When I open a task card that is linked to a parent task, the first few seconds I see "Parent: undefined-undefined".
Detected on app.plane.so

### Steps to reproduce

1. Two created issues. (child and parent)
2. Open child issue
3. Pay attention to the "Parent" field

<img width="444" alt="image" src="https://github.com/makeplane/plane/assets/40200052/8864bb03-be7b-47d8-8dbb-2b235279b6a1">

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
@kdanet does this only happen for the first few seconds or is "undefined-undefined" shown all the time for you in the parent field?

**Comment by kdanet** [comment]
@srinivaspendem It only happens in the first few seconds

**Comment by srinivaspendem** [comment]
Hey @kdanet, just a heads up: we've fixed this issue. If you're still experiencing it, please let us know.
