### ISSUE TITLE
[bug]: When an User applies some filter in the Cycle board, all users are affected

### ISSUE THREAD

**Issue by niltonvasques** [makeplane/plane#3431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When any user of the system applies any filter in the Cycle board, all others users receives this filter. 

This bug is causing a racing condition in our team, because every hour the board receives another filter, applied by some team member.

The expected behavior should be the filter only applied to the user that applied it. 

Global filters is a nice idea, but should be allowed only to managers.

### Steps to reproduce

1. Go to cycle kanban board
2. Filter by assignee
3. Log in with another user
4. Go to cycle kanban board
5. Check if the board is filtered

### Browser

Google Chrome

### Version

Self-hosted

**Comment by sriramveeraghanta** [comment]
We are addressing this issue in the upcoming release. Currently, our cycle filters are stored globally, impacting the cycle issues view for everyone who accesses the cycles. In the upcoming release, we will be saving this information in a user-specific table, resolving the issue. 

You find the new endpoint here. 
https://github.com/makeplane/plane/blob/preview/apiserver/plane/app/urls/cycle.py#L88

**Comment by srinivaspendem** [comment]
Hey @niltonvasques, just wanted to inform you that this issue has been resolved. If you're still facing it, please update to our latest version.
