### ISSUE TITLE
[bug]: Gantt start and due date not correct compare to issue view

### ISSUE THREAD

**Issue by nic0dk** [makeplane/plane#3438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

self-hosted version 0.14-2 also a problem on 0.14 - when viewing Grantt i always have date offset +1 compare to what the issue is set to.

### Steps to reproduce

1. go issue main view 
2. select Gantt view
3. find issue and open it to compare set date with grantt date

![image](https://github.com/makeplane/plane/assets/14346463/176a5ea1-1e27-4a7a-86ee-b93f01b6d6b9)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Huuuze** [comment]
I cited this same bug (dates showing +1 days) -- and noted the fix -- here:

https://github.com/makeplane/plane/issues/3305

Hoping for a fix in the next release, @nic0dk, @srinivaspendem, @aaryan610, or @pushya-plane. Keep up the great work!

**Comment by KarloDerEchte** [comment]
> I cited this same bug (dates showing +1 days) -- and noted the fix -- here:
> 
> #3305
> 
> Hoping for a fix in the next release, @nic0dk, @srinivaspendem, @aaryan610, or @pushya-plane. Keep up the great work!

#3074

**Comment by Huuuze** [comment]
@nic0dk -- typo in your title change. Gantt not G**r**antt

**Comment by srinivaspendem** [comment]
Hey @Huuuze and @nic0dk, I'm pleased to inform you that this issue has been resolved. Please let us know if you encounter any further difficulties.
