### ISSUE TITLE
[bug]: Incorrect values when using side list to change settings of unselected project

### ISSUE THREAD

**Issue by RikPi** [makeplane/plane#3481]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When a project is selected, if you try to change settings of a different project via the side list, the current project values will be showed even if the navigation hierarchy on top of page shows the correct project.

I am using a self-hosted docker v0.14.0

![Screenshot 2024-01-26 173436](https://github.com/makeplane/plane/assets/42491872/8289e540-e230-43a1-b30d-3e2a2fa0eef5)
Notice how top left the "path" is correct but the data is from the currently selected project.

Great software btw! Keep up the wonderful work! :)

### Steps to reproduce

1. Select a project
2. Go on the project list on the side and click the three dot menu relative to another project
3. Select settings (or just use the normal settings button without selecting that project first
The showed page will show you the settings of the correct project but all the values are from the one that was currently selected, this includes name, ID, icon, description. **Project visibility is instead correctly shown**.

It does not happen all the time, but very frequently

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @RikPi, just an update: this issue has been resolved. Please update to the latest version of Plane if you're still encountering any problems.
