### ISSUE TITLE
[bug]: Commenting as Guest or Viewer

### ISSUE THREAD

**Issue by etaxi341** [makeplane/plane#3512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the PR #1650 it was implemented that guests and viewers can comment.
Sadly the user cannot see the comment section when he does not have member rights.

I have tested that the user with guest rights can comment when he had the member rights on loading the page and got degraded to guest before sending the comment. So it just seems to be an UI bug because the permission in the background works.

### Steps to reproduce

1. Create an Issue in Inbox as Guest
2. Admin accepts Issue
3. Admin has question about issue and comments
4. Creator can't answer because there is no comment input.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
While we are in conversation, this issue is being addressed, and you can expect to receive the update in the 0.15 release.

**Comment by etaxi341** [comment]
Thank you! You guys are amazing!
