### ISSUE TITLE
[feature]: Print Pages as PDF

### ISSUE THREAD

**Issue by Emperor42** [makeplane/plane#3526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow for the printing of pages in a format which could then be more easily distributed outside of Plane and/or saved externally. There seems to be some Open Source projects (ie https://github.com/alanshaw/markdown-pdf) which do this and there are online tools (ie https://www.markdowntopdf.com/)) however it would be nice to have this functionality directly in Plane

### Why should this be worked on?

Using pages allows for documents to be easily generated directly in Plane, however printed copies of these documents need to be converted to a different format before they can be used directly (ie as PDF files) a downloadable or printable version from directly in the Plane software would be helpful if using Pages for document generation capacity.

**Comment by aaryan610** [comment]
Closing this issue, as it is covered by #4738.
