### ISSUE TITLE
[bug]: Upgrading via setup.sh had no effect

### ISSUE THREAD

**Issue by siunus** [makeplane/plane#3529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using Plane self-hosted with current version is `v0.14.0`.
Every time I run `setup.sh` the information appears that a new version is available.
I tried upgrading but nothing happened, the version is still the same.
Is there a special way to upgrade?

### Steps to reproduce

1. Run `setup.sh`
2. Select `5) Upgrade`
3. 
```shell
***** STOPPING SERVICES ****

***** DOWNLOADING LATEST VERSION ****

Latest version is now available for you to use

In case of Upgrade, your new setting file is availabe as 'variables-upgrade.env'. Please compare and set the required values in '.env 'file.

***** PLEASE VALIDATE AND START SERVICES ****
```
4. After comparing `env` file, then `Start`

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hi @siunus, the updates were included in version 0.14, so you might not have seen the version update yet. Soon, you will be able to update to version 0.15, where everything will be sorted.

**Comment by siunus** [comment]
How to update from `0.14` to `0.15` ? I see version 0.15 is already available.
Is there any additional configuration? Because I tried many times but there was no change.

**Comment by srinivaspendem** [comment]
Please execute the following commands in the same folder wherever your existing setup is 

```
curl -fsSL -o setup.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh
chmod +x setup.sh
 ```

**Comment by HiveologieMLData** [comment]
> Please execute the following commands in the same folder wherever your existing setup is
> 
> ```
> curl -fsSL -o setup.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh
> chmod +x setup.sh
> ```

I am also trying to upgrade a self-hosted version of plane from `0.14` to `0.15` with the above setup.sh script, but the script seems to be hitting containers with a non existent 'master' tag on Dockerhub (eg. makeplane/plane-backend:master).
I can see that setup.sh is exporting the APP_RELEASE variable as the BRANCH variable (eg. 'master') at the top of the script
```bash
BRANCH=master
SCRIPT_DIR=$PWD
PLANE_INSTALL_DIR=$PWD/plane-app
export APP_RELEASE=$BRANCH
export DOCKERHUB_USER=makeplane
export PULL_POLICY=always
USE_GLOBAL_IMAGES=1
```

The only function that changes the APP_RELEASE variable is `buildLocalImage()` . 
In my case `buildLocalImage()` is never executed inside `download()` function due to the fact that the `$USE_GLOBAL_IMAGES` variable is set to 1 at the bottom of the script during CPU specific setup (Our server has a `x86_64` CPU )

```bash
# CPU ARCHITECHTURE BASED SETTINGS
ARCH=$(uname -m)
if [ $ARCH == "amd64" ] || [ $ARCH == "x86_64" ];
then
    USE_GLOBAL_IMAGES=1
    DOCKERHUB_USER=makeplane
    PULL_POLICY=always
else
    USE_GLOBAL_IMAGES=0
    DOCKERHUB_USER=myplane
    PULL_POLICY=never
fi
```


Can you please review this and let me know if I am doing something incorrectly on my end, or if I need to make adjustments to any variables in `setup.sh`

**Comment by siunus** [comment]
I do upgrade with new `setup.sh` file, and got this result:

```shell
/home/hco/plane-selfhost# ./setup.sh

Select a Action you want to perform:
   1) Install (x86_64)
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) Exit

Action [2]: 5

***** STOPPING SERVICES ****
[+] Running 11/11
 ✔ Container plane-app-proxy-1        Removed                                                  0.6s 
 ✔ Container plane-app-plane-minio-1  Removed                                                  0.5s 
 ✔ Container plane-app-migrator-1     Removed                                                  0.0s 
 ✔ Container plane-app-beat-worker-1  Removed                                                 10.4s 
 ✔ Container plane-app-space-1        Removed                                                 10.3s 
 ✔ Container plane-app-web-1          Removed                                                 10.2s 
 ✔ Container plane-app-worker-1       Removed                                                 10.3s 
 ✔ Container plane-app-api-1          Removed                                                  1.1s 
 ✔ Container plane-app-plane-redis-1  Removed                                                  0.4s 
 ✔ Container plane-app-plane-db-1     Removed                                                  0.4s 
 ✔ Network plane-app_default          Removed                                                  0.1s 

***** DOWNLOADING LATEST VERSION ****
[+] Pulling 10/10
 ✔ migrator Skipped - Image is already being pulled by api                                     0.0s 
 ✔ worker Skipped - Image is already being pulled by api                                       0.0s 
 ✔ beat-worker Skipped - Image is already being pulled by api                                  0.0s 
 ✔ plane-db Skipped - Image is already present locally                                         0.0s 
 ✔ plane-redis Skipped - Image is already present locally                                      0.0s 
 ✘ proxy Error                                                                                 2.7s 
 ✘ plane-minio Error                                                                           2.7s 
 ✘ api Error                                                                                   2.7s 
 ✘ space Error                                                                                 2.7s 
 ✘ web Error                                                                                   2.7s 
Error response from daemon: manifest for makeplane/plane-backend:master not found: manifest unknown: manifest unknown

Latest version is now available for you to use

In case of Upgrade, your new setting file is availabe as 'variables-upgrade.env'. Please compare and set the required values in '.env 'file.

***** PLEASE VALIDATE AND START SERVICES ****

Select a Action you want to perform:
   1) Install (x86_64)
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) Exit

Action [2]: 
```

---------------------------------------------------

Tried to start again and this happened:
```shell
Select a Action you want to perform:
   1) Install (x86_64)
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) Exit

Action [2]: 2

[+] Running 7/7
 ✘ api Error                                                                                   2.7s 
 ✘ beat-worker Error                                                                           2.7s 
 ✘ worker Error                                                                                2.7s 
 ✘ migrator Error                                                                              2.7s 
 ✘ web Error                                                                                   2.7s 
 ✘ space Error                                                                                 2.7s 
 ✘ proxy Error                                                                                 2.7s 
Error response from daemon: manifest for makeplane/plane-backend:master not found: manifest unknown: manifest unknown

Select a Action you want to perform:
   1) Install (x86_64)
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) Exit

Action [2]:
```

---------------------------------------------

Is my existing data safe? 😱

**Comment by Reloecc** [comment]
So what's the resume of this?

I have download setup.sh from `https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh`
When running as is, it produces error described up here.

I tried replacing $BRANCH with "latest" in setup.sh .. but running 5) Upgrade doesn't upgrade anything; stuck on 0.14.

How to upgrade? Thank you..

**Comment by siunus** [comment]
> Is my existing data safe? 😱

How do I undo this upgrade process?

**Comment by Tropaion** [comment]
Why doesn't the upgrade function use the latest tag for upgrading?
Wouldn't this make way more sense?

**Comment by siunus** [comment]
> How do I undo this upgrade process?

Pinging someone

**Comment by pablohashescobar** [comment]
@Tropaion, the versions aren't upgraded for the latest release this is a bug even if you are running on the latest version it still shows `0.15.1` only we will try to fix it.

**Comment by pablohashescobar** [comment]
@siunus, can you check by reinstalling ?

**Comment by Tropaion** [comment]
@pablohashescobar Any progress about this?

**Comment by pablohashescobar** [comment]
@Tropaion, this should have been fixed can you upgrade then exit through `setup.sh` menu and then again run the `setup.sh` and start the containers you should see the new version.

**Comment by Tropaion** [comment]
@pablohashescobar Thanks, looks like its working. Shouldn't this issue be closed then?

**Comment by pablohashescobar** [comment]
Correct @Tropaion, closing this issue.
