### ISSUE TITLE
[bug]: Completed Sprint burndown chart loses all original information

### ISSUE THREAD

**Issue by Plorenzo** [makeplane/plane#3540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a cycle is completed and are issues that are not done, the usual thing to do is to transfer them to the next cycle, this is called spillover and how much spillover happened in a particular cycle is very useful information. 

The issue is that currently, when a cycle ends and you move the unfinished issues to the next one, the completed cycle burndonwn chart loses al information and only displays the issue count of the NON transfered issues, which is useles. 

<img width="383" alt="Screenshot 2024-02-01 at 22 32 20" src="https://github.com/makeplane/plane/assets/4695692/d95ea5c0-afb4-439a-ac27-ca612bb2ec00">

in the image example shows the complete sprint with 2 issues 1 done and 1 cancelled, but the reality is that the cycle started with more than 30 issues,, so the burndown chart should reflect that, not just remove all spillover. 

Additionally is counting cancelled issue as not completed,which is not correct, but ill open another issue to report that. 

I hope you can take a look at it

### Steps to reproduce

Create cycle and add 30 issues to it 
complete 2 issues 
wait for cycle to end 
create new cycle and transfer all uncompleted issues to it 
go see completed sprint analytics

### Browser

Safari

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
@Plorenzo we are fixing this as part of 0.16 version, planned to go live mid feb

**Comment by srinivaspendem** [comment]
Hey @Plorenzo, We've resolved this issue by taking a snapshot of the analytics when transferring the issues to the new cycle upon completion. This ensures that there's no loss of analytics in the cycle.
