### ISSUE TITLE
[bug]: Cancelled issues counted as incomplete in cycle analytics 

### ISSUE THREAD

**Issue by Plorenzo** [makeplane/plane#3542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

related to https://github.com/makeplane/plane/issues/3540

When a cycle is completed, the analytics shows cancelled issues as not completed, picturing and incorrect view of the cycle 

<img width="383" alt="Screenshot 2024-02-01 at 22 32 20" src="https://github.com/makeplane/plane/assets/4695692/3882ae06-f20f-403d-abe1-7a850569a839">

If I have to issues in a cycle and i complete 1 and cancelled another, this should be Progress 100% done cycle but currently plane marks it as 50%

### Steps to reproduce

Create a cycle 
add 2 issues 
mark 1 as done as 1 as cancel 
wait for cycle to end 
go see cycle analytics it will show 50% instead of 100% 

### Browser

Safari

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @Plorenzo, this issue has been resolved. If you're still experiencing it, please update to the latest version.
