### ISSUE TITLE
[bug]: New issue is always created on current project, ignoring project selector

### ISSUE THREAD

**Issue by Plorenzo** [makeplane/plane#3543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I hit cmd+c to create a issue, the modal comes up then I change the project from the project selector then I create a issue, but the issue never change project and is always created on the project which you are viewing. 

<img width="342" alt="Screenshot 2024-02-01 at 23 24 49" src="https://github.com/makeplane/plane/assets/4695692/3a12985c-77c2-4ed9-88fd-ee583ac29d5e">

the api call is incorrect 
`api/workspaces/someProkect/projects/7582cfb7-5ee9-44b6-99ed-0813c20f7a0c/issues/` that the endpoint and this the payload
```
{
    "id": "c95975bf-107d-417a-8675-1c166d72f010",
    "name": "test 12",
    "state_id": "677242e3-e7bc-4427-bdfe-059f15069c43",
    "description_html": "",
    "sort_order": 585535,
    "completed_at": null,
    "estimate_point": null,
    "priority": "none",
    "start_date": null,
    "target_date": null,
    "sequence_id": 77,
    "project_id": "7582cfb7-5ee9-44b6-99ed-0813c20f7a0c",
    "parent_id": null,
    "cycle_id": null,
    "module_ids": [],
    "label_ids": [],
    "assignee_ids": [],
    "sub_issues_count": 0,
    "created_at": "2024-02-01T16:22:45.160016+01:00",
    "updated_at": "2024-02-01T16:22:45.160038+01:00",
    "created_by": "65994891-2300-42f6-bc98-93c72e78e6d4",
    "updated_by": "65994891-2300-42f6-bc98-93c72e78e6d4",
    "attachment_count": 0,
    "link_count": 0,
    "is_draft": false,
    "archived_at": null
}
```

looks like the project_id is incorrect and using the undelraying project instead of the project in the selector 

### Steps to reproduce

https://github.com/makeplane/plane/assets/4695692/fea72708-a629-4420-aa36-ee4264b86f99

### Browser

Safari

### Version

Self-hosted

**Comment by Plorenzo** [comment]
@anmolsinghbhatia @srinivaspendem this is working as expected now, not sure if you want to keep this open for some reason or expect reporters to close it

**Comment by pushya22** [comment]
Thanks @Plorenzo
