### ISSUE TITLE
[bug]: Sorting column not working in all views in All Issues menu with spreadsheet layout on v0.15.0

### ISSUE THREAD

**Issue by ihkaru** [makeplane/plane#3547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i try to sort date or any other columns, the column wont get sorted.

* ### Sort old to new: 
![image](https://github.com/makeplane/plane/assets/60537437/e3012fe0-af25-4e66-977e-6c3c16acc793)

* ### Sort new to old: 
![image](https://github.com/makeplane/plane/assets/60537437/6fe90328-2283-4f1a-bf49-8e4cad54ea02)

### Steps to reproduce

1. Go to All Issues menu
2. Choose spreadsheet layout
3. Sort any column and see if it gets sorted.

### Browser

Google Chrome

### Version

Cloud

**Comment by rahulramesha** [comment]
This Should be fixed once https://github.com/makeplane/plane/pull/3550 is merged and deployed.

**Comment by ihkaru** [comment]
Thank you,
Will patiently wait for the fix to take effects

**Comment by ihkaru** [comment]
Is there any news about the fix to take effects in the cloud?

**Comment by srinivaspendem** [comment]
Hello @ihkaru, the reported issue has been resolved. Kindly inform us if you are still experiencing any difficulties.

**Comment by ihkaru** [comment]
Thank you very much for your hardwork guys.
Although sorting date column in custom view in all issue menu is not working yet,
its for another issues.

**Comment by rahulramesha** [comment]
@ihkaru thank you for raising this issue. This has been fixed in https://github.com/makeplane/plane/pull/3683
