### ISSUE TITLE
[bug]: Cannot reorder kanban issues in project issues menu on v0.15.0

### ISSUE THREAD

**Issue by ihkaru** [makeplane/plane#3548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When go to project issues, i try to reorder the issue card, it wont get reordered.

### Dragging to reorder issue:
![image](https://github.com/makeplane/plane/assets/60537437/f62b75cc-7e6f-4e16-a87a-a6e9b444d383)

### It wont get reordered:
![image](https://github.com/makeplane/plane/assets/60537437/abe2b56a-6be1-4cf8-8d65-8df97cb99cbf)

### Steps to reproduce

1. Choose any project
2. Go to issues sub menu
3. Activate kanban layout
4. Reorder any issues using mouse drag
5. See if its get reordered, it wont get reordered.

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hi @ihkaru, for sorting the issues, you have to enable the option of manual sorting from the display properties.
<img width="432" alt="Screenshot 2024-02-02 at 11 41 09 AM" src="https://github.com/makeplane/plane/assets/65014795/7d1a5329-e616-4db6-adec-9d0091c6f5bf">

**Comment by ihkaru** [comment]
My bad, thank you very much
