### ISSUE TITLE
[bug]: Cannot reorder modules in GANTT layout 

### ISSUE THREAD

**Issue by adamk22** [makeplane/plane#3551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you reorder modules (with a start and end date) in the GANTT layout, it doesn't update the view (the timeline bars according to the order) and save the reordered state. On refresh it maintains the old/default ordered state.

Somewhat related to https://github.com/makeplane/plane/issues/3548 where issues can be manually reordered if you set the order to 'Manual'. Modules however, do not have this option in GANTT layout.

### Steps to reproduce

1. Go to Modules inside a project
2. Create two or three modules (I also added a start and end date for all modules)
3. Go to Gantt layout
4. Reorder any module
5. The timeline bars won't update according to its order and if you refresh the page maintain its old/default order.

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Thanks for bringing this to my attention @adamk22 we will get it fixed

**Comment by srinivaspendem** [comment]
You will be able to see the update in our 0.16 release. Sorry for any inconvenience caused.
