### ISSUE TITLE
[bug]: double slashes passed to next/router when loading certian endpoints

### ISSUE THREAD

**Issue by resba** [makeplane/plane#3558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

creating a new workspace called 'test2', I go to Workspace Settings and select "Integrations" where I expect to find some UI but instead see a blank page.

Looking at the console log, there are multiple entries of a failure to route:
`Invalid href '/test2//settings/imports' passed to next/router in page: '/[workspaceSlug]/settings/integrations'. Repeated forward-slashes (//) or backslashes \ are not valid in the href.`

### Steps to reproduce

1. Create a new self-hosted instance
2. Create a new workspace, named anything
3. Go to workspace settings, then Integrations
4. No content in the integrations tab will be displayed

### Browser

Google Chrome

### Version

Self-hosted

**Comment by broncha** [comment]
To add to this, I am seeing a lots of permanent redirect from `{workspace}/settings/1/decide/?v....` to `{workspace}/settings/1/decide?v....` and the latter URL returns 404

**Comment by aaryan610** [comment]
Hey @resba, this issue was fixed with #4298. Thanks for reporting it.
