### ISSUE TITLE
[bug]: Forever loading on login

### ISSUE THREAD

**Issue by Julian-Hackenberg** [makeplane/plane#3583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I logged out today and tried to log back in, it just kept loading forever. 
This happened randomly from yesterday to today.

When still logged in everything worked fine, 
but when others tried to log in it apparently broke. 

Im getting error code 500 from the api: 
```bash
plane-app-api-1  | 192.168.80.11:48250 - "GET /api/licenses/instances/ HTTP/1.0" 200
plane-app-api-1  | 192.168.80.11:52210 - "GET /api/users/me/instance-admin/ HTTP/1.0" 401
plane-app-api-1  | 192.168.80.11:52214 - "GET /api/users/me/settings/ HTTP/1.0" 401
plane-app-api-1  | 192.168.80.11:52228 - "GET /api/users/me/workspaces/ HTTP/1.0" 401
plane-app-api-1  | 192.168.80.11:52194 - "GET /api/configs/ HTTP/1.0" 500
plane-app-api-1  | 192.168.80.11:52200 - "GET /api/users/me/ HTTP/1.0" 401
plane-app-api-1  | 192.168.80.11:52234 - "GET /api/configs/ HTTP/1.0" 500
```

### Steps to reproduce

1. Log out
2. Forever loading page
3. ...
4. Profit?

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Julian-Hackenberg** [comment]
I want to extend this, that the sever for some reason is sending the site.manifest.json,,, as html?

from the browser console
```bash

```

**Comment by Julian-Hackenberg** [comment]
Hitting the enpoint `/api/configs` yields:

```json
{
    "error": "Something went wrong please try again later"
}
```

**Comment by Julian-Hackenberg** [comment]
To add to the mystery, this does not happen when the server directly via the IP, only when going through the FQDN via reverse proxy. 

( api/configs error persists tho )

**Comment by dmikushin** [comment]
I have the same problem!

```
api            | GET - /api/instances/ of Queries: 1
api            | 192.168.80.11:41410 - "GET /api/instances/ HTTP/1.0" 200
api            | 
api            | GET - /api/configs/ of Queries: 1
api            | Internal Server Error: /api/configs/
api            | 192.168.80.11:41430 - "GET /api/configs/ HTTP/1.0" 500
api            | GET - /api/users/me/ of Queries: 0
api            | Unauthorized: /api/users/me/
api            | 192.168.80.11:41438 - "GET /api/users/me/ HTTP/1.0" 401
api            | 
api            | GET - /api/configs/ of Queries: 1
api            | Internal Server Error: /api/configs/
api            | 192.168.80.11:41446 - "GET /api/configs/ HTTP/1.0" 500
```

**Comment by dmikushin** [comment]
@Julian-Hackenberg , I think in my case the cause in not the same as yours. But you can follow my steps to figure out:

1.  Login as root into the `api` container and install curl (we will curl from the container directly to avoid problems in the proxy):

```
docker-compose exec -u 0 api bash
apk add curl vim
```

2. Login as user into the `api` container and edit .py file to provide more details about the error:

```
docker-compose exec api bash
fd45674b54a5:/code$ curl api:8000/api/configs
{"error":"Internal error: "}

3. Add exception type to the error reporting everywhere:

```
docker-compose build
```

4. When I login to the `api` and repeat the request, I get:

```
fd45674b54a5:/code$ curl api:8000/api/configs/
{"error":"Unhandled exception: InvalidToken"}
```

So in my case there is some problem with token. Which one of the tokens?.. No idea...

**Comment by Julian-Hackenberg** [comment]
Hey @dmikushin, I don't seem to be able to reproduce your step 3. 

I haven't built it from scratch but am using the published docker image.

I'll try to do that one next!

**Comment by pablohashescobar** [comment]
@Julian-Hackenberg, are you still facing this issue ?
