### ISSUE TITLE
[bug]: Comment Mentions are not working when accessing issues through email notifications 

### ISSUE THREAD

**Issue by HiveologieMLData** [makeplane/plane#3592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When an email notification for comment mentions is sent and the recipient clicks on the 'View Issue" button in the email, the link redirects to the issue, and the user is not able to mention anyone in the comments and typing the '@' character does not open the mention suggestions panel. 

![image](https://github.com/makeplane/plane/assets/138716022/05102fc5-91ab-4a21-8981-45af35fb0d58)

I have tried hard refreshing (Shift+F5) the app after I access it via email notification but the issue persisted, and I have confirmed that the URLs are the same when accessing an issue through both a notification email and the issues dashboard.

There is already a similar PR for notification mentions (https://github.com/makeplane/plane/pull/3573)  it was merged into `develop` branch earlier today, but I don't think that it covers this specific case as we are using the code from `develop` branch for testing 

### Steps to reproduce

We are currently using code from the 'develop' branch for testing. 

Not Working Scenario:
1. Mention a user in a comment on an issue 
2. Go to the email inbox of the mentioned user and click 'View Issue' button
3. Try to mention any user in the comment by typing in a '@' symbol

Working Scenario:

1. Go to the issues dashboard
![image](https://github.com/makeplane/plane/assets/138716022/6e246b96-2b5a-44f3-b4ad-2b1416406624)
2. Double click on an issue and expand it to full-screen mode 
![image](https://github.com/makeplane/plane/assets/138716022/d0f81c68-383d-4434-b784-81cebbc60000)
3. Try to mention any user in the comment by typing in a '@' symbol 
![image](https://github.com/makeplane/plane/assets/138716022/333812fe-5768-43d8-826d-36554731a966)
![image](https://github.com/makeplane/plane/assets/138716022/ee5aee37-bff2-4f46-8b83-b742f4772b0d)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by mitar06** [comment]
@pushya-plane @srinivaspendem hey guys, just following up, do I need to provide any additional information in order to track this bug?

**Comment by HiveologieMLData** [comment]
@pushya-plane @srinivaspendem hi guys, just following up, do I need to supply any additional information in order to track this bug?

**Comment by niltonvasques** [comment]
Same issue is happening here! I think that is not related to email notifications only, the problem happens if we open the ticket URL direct, without navigate until it. 

My guess is that the mentions available users are not fetched in the ticket page, probably they are fetched in the issues screen or main page, thus when we open it directly, the fetch is not executed.

**Comment by etaxi341** [comment]
We are using the release mentioned in your comment. I am not sure if it is caused by the mail redirect. But sometimes when you type "@" no popup appears. Sometimes you just click on a ticket and don't have to ability to mention without refreshing the page

**Comment by etaxi341** [comment]
@srinivaspendem when was this fixed? I still experience this bug. What version fixed this?

**Comment by srinivaspendem** [comment]
Hey @etaxi341, we fixed the mentions in the comments. However, mail redirecting directly to the comment is not part of our current roadmap, which is why the issue has been closed.
