### ISSUE TITLE
[bug]: labels get removed when I updating description

### ISSUE THREAD

**Issue by snaulX** [makeplane/plane#3605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I set labels for the new task, then I update description and labels get removed in the same moment.
![изображение](https://github.com/makeplane/plane/assets/43488179/30ccc945-f9e5-45d8-b93f-0fa5fdbf6301)

### Steps to reproduce

1. Set the labels
2. Update description
3. Get the labels removed

https://github.com/makeplane/plane/assets/43488179/3b9b504a-1bc1-4ab4-ab24-837cfe9c2137

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hi @snaulX, 
I attempted to reproduce the reported issue but was unsuccessful. Could you please provide detailed steps on how to replicate the bug? This will help me better understand the problem and assist you more effectively.

<img width="1103" alt="image" src="https://github.com/makeplane/plane/assets/65014795/3d7c5bb8-24d3-4654-90a7-a63867a31c86">

**Comment by snaulX** [comment]
@srinivaspendem I can add only one thing that is untold: I added issue using "+ New Issue" button in bottom of the issues board.

https://github.com/makeplane/plane/assets/43488179/0e55f4f8-5eaa-43cb-aadd-41ac908ed19b

**Comment by srinivaspendem** [comment]
Hey @snaulX, this issue has been resolved. If you're still facing it, please update to the latest version.
