### ISSUE TITLE
[bug]: Inbox showing incorrect Data with "Viewer" Permissions

### ISSUE THREAD

**Issue by etaxi341** [makeplane/plane#3610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using an Account with "Viewer" Permissions and accessing the Inbox you will experience a Bug:
The Body of the Issue is always the same as the one you opened first.

### Steps to reproduce

1. Enable Inbox Feature for Project
2. Use an Account with "Viewer" Permissions
3. Write 2 Inbox Issues
4. Open one of the Inbox Issues with the "Viewer" user.
5. Click on another Inbox Issue
6. The Text of the Issue stays the same.

Using an Admin Account this Issue does not happen!

### Browser

Google Chrome

### Version

Self-hosted

**Comment by oigeen** [comment]
Experiencing the same bug on Firefox. Each time the error occurs I get the following error in the console.

![image](https://github.com/makeplane/plane/assets/28718181/b4d8b68d-c965-4290-b076-a4f51b475ca2)

Would love to see a fix for this.

**Comment by pushya22** [comment]
Hi @oigeen this issue is fixed with our inbox revamp. Please re-open if you see issue still persists
