### ISSUE TITLE
[bug]: module view, kanban layout, kanban columns do not maintain position

### ISSUE THREAD

**Issue by zackaboyd** [makeplane/plane#3612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In Issues view, kanban columns that are minimized remain minimized when navigating to/away and/or refreshing the page. 

In module view when in kanban layout, the behavior is different: every time the page loads, all kanban columns are expanded

### Steps to reproduce

Go to modules
Select a modules
Enter Kanban Layout
Minimize certain columns
Refresh page
Columns do not remain minimized

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Thanks for raising this @zackaboyd we will fix this soon.

**Comment by zackaboyd** [comment]
This is also true in custom views when in kanban layout
