### ISSUE TITLE
[bug]: priority sort order inverted

### ISSUE THREAD

**Issue by zackaboyd** [makeplane/plane#3613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Issues are currently sorted with lowest priority on top, highest priority on bottom.

Correct sort order should have highest priority on top

### Steps to reproduce

View any table sorted by priority.

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hello @zackaboyd, thank you for reporting this. It will be fixed in our upcoming release.

**Comment by prateekshourya29** [comment]
Hi @zackaboyd, we've addressed this issue in the pull request #3627, where we've corrected the sorting order for priorities. Once the PR is merged, this problem will be resolved.
