### ISSUE TITLE
[bug]: Infinite "Waiting for database migrations to complete"

### ISSUE THREAD

**Issue by dmikushin** [makeplane/plane#3614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After upgrading to `v0.15-dev` migration can never be completed:

```
api            | Waiting for database migrations to complete...
api            | Waiting for database migrations to complete...
api            | Waiting for database migrations to complete...
beatworker     | Waiting for database...
beatworker     | Database available!
beatworker     | Waiting for database migrations to complete...
beatworker     | Waiting for database migrations to complete...
bgworker       | Waiting for database...
bgworker       | Database available!
bgworker       | Waiting for database migrations to complete...
bgworker       | Waiting for database migrations to complete...
bgworker       | Waiting for database migrations to complete...
bgworker       | Waiting for database migrations to complete...
bgworker       | Waiting for database migrations to complete...
```

However, the log contains no other errors.

Due to the pending migration, the instance never starts, therefore the Plane website is not available.

### Steps to reproduce

```
((v0.15-dev))> docker-compose up -d
```

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
@dmikushin, can you check if the migrator container ran ?

**Comment by dmikushin** [comment]
@pablohashescobar , thanks yes, the issue is resolved after I've added the following into `docker-compose.yml` in the root folder:

```
commit 74af988eec19fa001392d0a43bec785c4d4563cc (HEAD)
Author: Dmitry Mikushin <dmitry@kernelgen.org>
Date:   Sun Feb 11 01:27:06 2024 +0100

    Now we also need a 'migrator' to perform the database migration

diff --git a/docker-compose.yml b/docker-compose.yml
index e39f0d8d2..9fd2253a9 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -125,6 +125,21 @@ services:
       - api
       - space
 
+  migrator:
+    container_name: migrator
+    build:
+      context: ./apiserver
+      dockerfile: Dockerfile.api
+      args:
+        DOCKER_BUILDKIT: 1
+    restart: "no"
+    command: sh -c "python manage.py wait_for_db && python manage.py migrate"
+    env_file:
+      - ./apiserver/.env
+    depends_on:
+      - plane-db
+      - plane-redis
+
 volumes:
   pgdata:
   redisdata:
m
```

Please note: it is very misleading that there is a `docker-compose.yml` in the root folder, and `deploy/selfhost/docker-compose.yml`. Only the last one is getting updated, and the enclosed instruction is largely meant for new installations. Please consider removing `docker-compose.yml` and `Dockerfile` from the root folder, if it is indeed obsolete by the `deploy/selfhost/docker-compose.yml`.

**Comment by pablohashescobar** [comment]
@dmikushin yeah the `docker-compose.yml` outside is kept for the folks who build their own images. We will update the `docker-compose.yml` in the root and also make necessary changes to the documentation as well.
