### ISSUE TITLE
[feature]: Self-Hosted Change Terms and Conditions Link

### ISSUE THREAD

**Issue by ImperialKn** [makeplane/plane#3617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Would be great to be able to change the "terms and conditions of service" link shown on the login and any other pages.

### Why should this be worked on?

When self-hosting, users may have different terms and conditions for those who access their website. This may differ from plane's, which is currently hardcoded.

**Comment by srinivaspendem** [comment]
Hello @ImperialKn, thank you for your suggestion. We will try to implement this in our future releases.

**Comment by vihar** [comment]
We’ve added links to our terms and conditions when signing up for the hosted version of Plane. Thanks for flagging this.

**Comment by KimiyaMorozova** [comment]
Hi, 
If the Terms of Service and Privacy Policy are not Hardcoded anymore, where do i change them?
