### ISSUE TITLE
[bug]: page refresh opens sidebar

### ISSUE THREAD

**Issue by zackaboyd** [makeplane/plane#3636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

As of v0.15.1 (this morning), a page refresh opens the sidebar

This was not true of v0.15.0

### Steps to reproduce

Minimize Sidebar

Refresh page

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Thanks for letting us know @zackaboyd, apologies for this issue. We will fix it in our next release.
