### ISSUE TITLE
[bug]: getting error while setup local development in docker compose file

### ISSUE THREAD

**Issue by abidkhan484** [makeplane/plane#3641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It should start with the `docker-compose -f docker-compose-local.yml up -d` command. But it's returning error. The error is given below.

```sh
└─(10:44:04 on preview)──> docker-compose -f docker-compose-local.yml up -d                                                                     
ERROR: The Compose file './docker-compose-local.yml' is invalid because:
services.migrator.restart contains an invalid type, it should be a string
```

### Steps to reproduce

1. Try starting local development with docker compose up command (`docker-compose -f docker-compose-local.yml up -d`)
2. It will return error in `preview` branch

### Browser

Google Chrome

### Version

Local

**Comment by abidkhan484** [comment]
Can you please look into this PR? I have added the fix and the reason behind the issue. #3642

**Comment by srinivaspendem** [comment]
Hey @abidkhan484 thanks for raising the PR, we will get back to you tomorrow but we will need you to sign the CLA raised by the CLA bot in your PR. Only then can we actually proceed to evaluate your PR.

**Comment by abidkhan484** [comment]
> we will need you to sign the CLA raised by the CLA bot in your PR

Thanks for the information @srinivaspendem, I have accepted the CLA lisense.
