### ISSUE TITLE
all my coments disapeared from my projec :( (In issues) [bug]: 

### ISSUE THREAD

**Issue by kimx100** [makeplane/plane#3654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

all my coments disapeared from my projec :( (In issues)

### Steps to reproduce

i sadly dont know why it happened but i had a lot of issues commented with step by step instructions and all are now uncomented

### Browser

Other

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hi @kimx100, we tried to replicate this issue in multiple ways, but we could not reproduce it. Please let us know if there are any specific steps to reproduce; it would be easier for our team to identify the issue. Anyways, we are looking into the cause of this problem. I will keep you posted on the progress.

**Comment by srinivaspendem** [comment]
Hey @Jackzmc, sorry for the inconvenience you faced. We have resolved the issue and made it more stable.
