### ISSUE TITLE
[bug]: Pages code block not working

### ISSUE THREAD

**Issue by Tropaion** [makeplane/plane#3655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to add an codeblock with code to the page the tabs and comments of the code are deleted an there is no syntax highlighting.
It worked in v0.13.2:
![image](https://github.com/makeplane/plane/assets/6797663/0d47ddf6-a93e-4788-a2d1-1169c74b44eb)
I created a new installation with v0.14.0, now it looks like this:
![image](https://github.com/makeplane/plane/assets/6797663/fb071f5e-6d3c-4518-89a1-3b60e877e16a)

### Steps to reproduce

1. Create page
2. Create codeblock /code
3. Add code with tabs -> they are deleted and not syntax highlighting

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Palanikannan1437** [comment]
Hey @Tropaion, could you please create a new code block after upgrading to the latest version and check if this issue still persists?

**Comment by Tropaion** [comment]
Hi @Palanikannan1437,
I just tried it, the code block stays but there is still no syntax highlighting:
![image](https://github.com/makeplane/plane/assets/6797663/6e4e2131-5901-48ed-879e-6c8d1b2b7283)

**Comment by Palanikannan1437** [comment]
> Hi @Palanikannan1437,
> I just tried it, the code block stays but there is still no syntax highlighting:
> ![image](https://github.com/makeplane/plane/assets/6797663/6e4e2131-5901-48ed-879e-6c8d1b2b7283)
> 

By default the code block is in plaintext. Soon we'll have support for  syntax highlighting of multiple languages in which you can switch between things. 

Currently only typescript support is present, so you can do 

/```ts and hit space to get support for syntax highlighting in ts

**Comment by Tropaion** [comment]
Ok, didn't know that, didn't find any documentation about this, thanks.
