### ISSUE TITLE
[bug]: Sub-Issue status on parent not shown correctly

### ISSUE THREAD

**Issue by etaxi341** [makeplane/plane#3663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you have a parent issue and add children from different a different project to it, sometimes the states of the children are not correctly show.

It then shows "State" instead of "Todo" or "Done"
![image](https://github.com/makeplane/plane/assets/32163626/c0026b51-0ad5-489a-8df0-e42f2371ca74)

### Steps to reproduce

1. Create 2 Projects
2. Create Issue 1 in Project A
3. Create Issue 2 in Project B
4. Set Issue 2 as Sub-Issue of Issue 1
5. Open Issue 1 as Fullscreen.
6. Do a full refresh of page (STRG + F5)

Now the State of the Subissue from Project B will not be its correct state but will say ![image](https://github.com/makeplane/plane/assets/32163626/d736be01-553d-4e8f-9a10-366f90b21118)  instead.

The state will be correctly loaded once you open the "Issues" Tab of the Project B and reopen the Issue 1 of Project A

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hi @etaxi341, thanks for reporting this. It will be fixed in our upcoming release.

**Comment by pushya22** [comment]
This issue is resolved in 0.17 release
