### ISSUE TITLE
[bug]: Kanban View State Update Does not Change State

### ISSUE THREAD

**Issue by zackaboyd** [makeplane/plane#3669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Updating issue state directly from Kanban does not change state. This was working previously

### Steps to reproduce

1. View Issues in Kanban View
2. Update a State of an Issue directly from this view
3. Refresh Page 
4. The state reverts to previous state
5. Click on an issue to open expanded view
6. Update state in expanded view
7. Update state message received
8. State remains after page refresh

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hi @zackaboyd, we tried to recreate this issue but were not able to. Please do a hard reload and check if the issue still persists. Please let us know.
