### ISSUE TITLE
[bug]: When creating an Issue, if you've already added the title and switch tabs, the title you added gets deleted.

### ISSUE THREAD

**Issue by ErickFlores13** [makeplane/plane#3680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i start to create an issue and add the Title of the issue, when i'm writing the description if i change of tab when i return to plane to continue the report, the title get deleted:

https://github.com/makeplane/plane/assets/112999558/5925d853-61ee-4006-93d4-37078f962047

### Steps to reproduce

1. Go to a created project
2. Select a column 
3. Click on the '+' icon to create an Issue
4. Write the title of the issue
5. Change of tab
6. Return to plane

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
@ErickFlores13 i am unable to reproduce this, can you let me know the version you are on?

**Comment by pushya22** [comment]
Hi @ErickFlores13 this issue now resolved.

**Comment by ErickFlores13** [comment]
Thankss!!
