### ISSUE TITLE
[bug]: issue autosave sometimes lose current input focus on complete

### ISSUE THREAD

**Issue by nihauc12** [makeplane/plane#3684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On plane.so
When editing the description of an issue, a autosave feature runs with a debounce.
Sometimes when the save request goes through and finishes, the input lose its focus, you need to reclick on it to be able to type again.

### Steps to reproduce

1. open an issue
2. click on description
3. type something
4. wait for the autosave loader to finish
5. description textarea has lost focus

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hi @nihauc12, apologies for the inconvenience caused. We've identified the issue and have already begun working on it. It will be resolved very soon.

**Comment by pushya22** [comment]
Hi @nihauc12 this issue is now resolved.
