### ISSUE TITLE
[bug]: Childtickets disappearing in nowhere

### ISSUE THREAD

**Issue by etaxi341** [makeplane/plane#3699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This Bug happens on Cloud (plane.so) and selfhosted.

When you have a parent ticket that is assigned to noone and add a child ticket that is assigned to myself, I will not be able to see the childticket in my "Assigned" tickets.

Could you please have a look at this? This makes issues go into a blackhole where they won't ever be found again.

There are multiple cases where this happens. Look steps to reproduce:

### Steps to reproduce

Case 1:
1. Create Ticket A in Project
2. Assign Ticket A to no one or someone else
3. Create Ticket B in Project
4. Set Parent of Ticket B to Ticket A
5. Assign Ticket B to myself
6. Can't see Ticket B in "All Issues" -> "Assigned"

Case 2:
1. User 1 Creates Ticket A in Project
2. User 2 Creates Ticket B in Project
3. User 2 sets Parent of Ticket B to Ticket A
4. User 2 can't see Ticket B in "All Issues" --> "Created"

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hello @etaxi341 can you let me know if this was working in previous versions?

**Comment by etaxi341** [comment]
@srinivaspendem not sure. Only noticed it today when I searched for a ticket. I have only started to work with parents a few weeks ago.

**Comment by srinivaspendem** [comment]
Hey @etaxi341, we found the bug causing this issue. We are updating it and will keep you posted on the progress.

**Comment by pushya22** [comment]
This issue is resolved
