### ISSUE TITLE
[bug]: full name input field lacks input validation

### ISSUE THREAD

**Issue by teyim** [makeplane/plane#3713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The full name input field does not have any restriction to the length of the input string causing UI to break
![Screenshot from 2024-02-20 10-41-18](https://github.com/makeplane/plane/assets/48864977/9e5b20a7-b821-4d25-8da6-d6ea90a2a9f8)

### Steps to reproduce

1. Signup to plane
2. Enter a very long string in the full name input field during onboarding

### Browser

Google Chrome

### Version

Cloud

**Comment by teyim** [comment]
@srinivaspendem would like to work on this. The ideal max length for a full name could be 16-32 characters. also, I can add text truncation and wrapping to the UI where necessary for very long strings.

**Comment by srinivaspendem** [comment]
@teyim thanks for suggesting the issue and the fix, while we would like you to work on it. It's not a priority for us at the moment. We will let you know when you need to work on this.

**Comment by teyim** [comment]
ok @srinivaspendem

**Comment by vihar** [comment]
We've fixed this issue, thanks @teyim for flagging this.
