### ISSUE TITLE
[bug]: Error creating workspace when workspace name is 18 characters long

### ISSUE THREAD

**Issue by teyim** [makeplane/plane#3714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating a workspace with its name 18 characters long, an Error is thrown

![Screenshot from 2024-02-20 10-40-16](https://github.com/makeplane/plane/assets/48864977/3ba53fed-de55-4e06-a895-831eab45ff79)

### Steps to reproduce

1. Signup to plane 
2. On the Create workspace screen, enter an 18-character string in the workspace name input field18-character

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hi @teyim, thanks for letting us know about this bug. We will fix it in our upcoming release.

**Comment by vihar** [comment]
Thanks for flagging this, we've resolved this bug on our latest release.
