### ISSUE TITLE
[bug]: dashboard crashing on load

### ISSUE THREAD

**Issue by olivierlambert** [makeplane/plane#3747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Just after updating to the latest version, the home view of the workspace (ie the dashboard) displays for half a second and then being replaced by:

```
Exception Detected!

We're Sorry! An exception has been detected, and our engineering team has been notified. 
```

What's interesting: the rest of the app is working, eg if I use another URL in my history pointing to a specific project kanban or whatnot, it loads correctly. It's "just" the home/dashboard that is triggering this behavior.

### Steps to reproduce

1. Login into your plane
2. The error displays

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @olivierlambert, we are not able to reproduce this issue if you can attach logs of the error it will be helpful for your team to resolve the issue soon.

**Comment by etaxi341** [comment]
@olivierlambert this only happens in the current preview branch. It's already fixed yesterday in the dev branch

**Comment by etaxi341** [comment]
@olivierlambert see #3741

**Comment by olivierlambert** [comment]
Ah thanks! Indeed :+1:

**Comment by olivierlambert** [comment]
I can confirm it's fixed after updating the containers :+1:
