### ISSUE TITLE
[bug]: State filter dropdown on Issues spreadsheet layout is broken

### ISSUE THREAD

**Issue by Plorenzo** [makeplane/plane#3757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/makeplane/plane/assets/4695692/59c8c10b-4262-4910-915e-7e7633a3f4ac

### Steps to reproduce

(See video above)

Go to Project-> issues
Change the view to Spreadsheet layout
Try to sort by state

### Browser

Safari

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @Plorenzo, thank you for reporting this bug. We already stated fixing it will update you once it is resolved.

**Comment by vihar** [comment]
@Plorenzo, this issue is now pushed to the community edition with `0.16-dev` release.
