### ISSUE TITLE
[bug]: Can't edit issue that contains UL or Checkbox 

### ISSUE THREAD

**Issue by robson-koji** [makeplane/plane#3798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If a issue contains a To-do list or a bullet-list, I can not edit it.
When saving the edition, it says that it cannot create the issue. I am editing, not creating. 

### Steps to reproduce

1. Create a issue
2. Add elements (checkbox or unoreder list)
3. Save the issue
4. Edit the issue (go to the three dots and click Edit Issue) 
5. Click on the Update Issue button. It raises an error saying that the issue can not be created.  

If you just click on the issue and edit, it seems to be working

### Browser

Opera and Firefox. 

### Version

Self-hosted

**Comment by sriramveeraghanta** [comment]
Hello @robson-koji, 

Thank you for identifying the issue and reporting it. Looks like a bug, we are going to prioritise the fix it as soon as possible and push it in the next release.
