### ISSUE TITLE
[feature]: Show sub-issues in issue drawer

### ISSUE THREAD

**Issue by nishant2106** [makeplane/plane#3810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

when we are on main landing page, if we click any issue and that has sub issues, although issue open in right pane but sub issues are not shown there. 
It would be great to see sub-issues there as well along with other data. Right now it gives impression that it does not have child issue. Jira can be referenced for this , they show sub issues in summary and right pane.
<img width="636" alt="Screenshot 2024-02-27 at 4 29 33 PM" src="https://github.com/makeplane/plane/assets/59759332/6f49794e-a22e-4792-b0fc-ceed8d2e1f6f">

Now we have to click on issue again and open in full window to see sub issues. 

### Why should this be worked on?

It is very hard to track a issue with many sub-issues. And after opening an issue in detail breadcrumb is not showing the button to go back to existing cycle, it is redirecting to the main issues page. So it could save multiple clicks in experience.

**Comment by pushya22** [comment]
This issue resolved in PR #3956
