### ISSUE TITLE
[bug]: unable to attach images getting error always

### ISSUE THREAD

**Issue by SHUFIL** [makeplane/plane#3813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am not able to do attachment  , getting below error always,
`Something went wrong. please check file type & size (max 5 MB)` , for resolving tried different file format like JPG , PNG , size almost 104 KB , but still same error, 

In side the ENV file I have attached below configuration , and also I tried  and used this variable  alone AWS_S3_ENDPOINT_URL="http://plane-minio:9000" and AWS_S3_ENDPOINT_URL="https://s3.amazonaws.com"  but not worked. 

I have used docker makeplane/plane-backend:v0.13.2-dev version
 If I need change or add anything for resolve this issue , please let me know, I will try. Thanks

```
AWS_REGION=""
AWS_ACCESS_KEY_ID="access-key"
AWS_SECRET_ACCESS_KEY="secret-key"
AWS_S3_ENDPOINT_URL="http://plane-minio:9000"
AWS_S3_BUCKET_NAME="uploads"
# Maximum file upload limit
FILE_SIZE_LIMIT=5242880
```

### Steps to reproduce

1, Go to the home page , then from left side click on a project > then take one open case , then do attachment
![attachment](https://github.com/makeplane/plane/assets/22607542/ff6ae217-40b8-4e58-b794-7144b6430d00)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
@SHUFIL, can you enable `DEBUG` mode in the `.env` and check the error you are receiving in console.

**Comment by pushya22** [comment]
@SHUFIL closing this issue as there was no response, please re-open if the issue persists
