### ISSUE TITLE
[bug]: Dashboard reports all tasks as overdue

### ISSUE THREAD

**Issue by psi-chuffine** [makeplane/plane#3815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I view the dashboard, I am shown 26 issues overdue (all issues I have created)
![image](https://github.com/makeplane/plane/assets/76532245/73e25510-cba8-4926-ab52-dacea4438245)
Going to the assigned tab shows no issues overdue.
![image](https://github.com/makeplane/plane/assets/76532245/9c7cbacb-ee87-41e1-8a57-10dfaec481b6)

### Steps to reproduce

This issue is visible from the dashboard at all times.

I have tasks with no date and due dates in the future.
I am running v0.15.1 

### Browser

Google Chrome

### Version

Local

**Comment by NarayanBavisetti** [comment]
Thank you, @psi-chuffine , for bringing this to our attention. This will be addressed in our upcoming release.

**Comment by psi-chuffine** [comment]
Issue is resolved in v0.16, thanks!
