### ISSUE TITLE
[bug]: Sub tasks with different status than main task don't show up in Kanban layout

### ISSUE THREAD

**Issue by webmasterlv** [makeplane/plane#3839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I have a main task with status "Todo" and sub-task with status "In progress", only the main task shows up in "Todo" column, but not sub-task in column "In progress".

I expect sub tasks to show up in columns according to their status.

Version: v0.15.1

### Steps to reproduce

1. Create task
2. Create another task, assign "Parent" as first task.
3. Set different status for each task

![image](https://github.com/makeplane/plane/assets/2886170/53769b15-b181-4c21-bb3d-b1fbb4620849)
![image](https://github.com/makeplane/plane/assets/2886170/c143fea3-2a3e-4636-bbdc-40bbb1819808)

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @webmasterlv, I believe you need to toggle on the "Show sub-issues" option in the display properties to view the sub-issues. I think this will resolve your issue. If you're still facing problems, please let us know.

<img width="357" alt="image" src="https://github.com/makeplane/plane/assets/65014795/fdd67f0b-c513-410d-8e3f-e4fc897d4c5c">

**Comment by webmasterlv** [comment]
@srinivaspendem Hey, thanks! yes that solves the issue :)
