### ISSUE TITLE
[bug]:  Update from v0.14.2-dev to v0.15.4-dev demands database migration

### ISSUE THREAD

**Issue by gibso** [makeplane/plane#3861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I upgrade from v0.14.2-dev to v0.15.4-dev the services api, beat-worker and worker are logging
```
worker-1       | Waiting for database migrations to complete...
api-1          | Waiting for database migrations to complete...
beat-worker-1  | Waiting for database migrations to complete...
```
infinitely. The frontend is not accesssible, there is just an endless loading spinner. Restart, including recreation of all containers, did not solve anything. 

Does the migration need to be triggered manually by a command? How can I do that?

Thanks for any help, love your product!

### Steps to reproduce

1. setup self-hosted solution with version  v0.14.2-dev
2. start everything
3. replace image versions with v0.15.4-dev
4. start everything again

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
@gibso, a separate migrator service has been added to support migrations. You can upgrade if you are using the `setup.sh` or repull the `docker-compose.yml` file if you are running it manually.

**Comment by mmospanenko** [comment]
I don't see any migrator in docker-compose from v0.15.4-dev version. I use own Ansible config with docker-compose file, the template is identical.

**Comment by mmospanenko** [comment]
just because I use Django, I could run migrations manually:
<img width="898" alt="image" src="https://github.com/makeplane/plane/assets/2766211/c53d478a-fe31-484d-a993-f7058fadb6c7">
and services started then
<img width="1033" alt="image" src="https://github.com/makeplane/plane/assets/2766211/80c6e5b2-f199-4d57-8f75-44d18fbc2754">

**Comment by gibso** [comment]
Okay, so in my production environment I now ran
```bash
docker compose exec api python manage.py migrate
```
That did the trick for me. Might be worth adding this as a standard behaviour into the service on start in an entrypoint script.

**Comment by gibso** [comment]
Thanks guys, I'll close this issue then. 🙏

**Comment by mmospanenko** [comment]
It should be a part of entrypoint (image) logic, I don't this that it is solved...
