### ISSUE TITLE
[bug]: Ticket got renamed and description edited wrongly

### ISSUE THREAD

**Issue by etaxi341** [makeplane/plane#3876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Could not find any other ticket that describes this.

A user created a new ticket. After an hour he opened this ticket in his browser again. Suddenly the title and the description of his ticket was renamed by him. The content of the title is the exactly the same as the title and description of another issue that was created by another user 3 weeks ago.

The change is also in the log but was not made by the user himself:
![image](https://github.com/makeplane/plane/assets/32163626/fd56952e-b789-47c1-a6a8-27bf23cab8bf)

### Steps to reproduce

I sadly cannot really reproduce this.
This has only happened twice for us now. 1 month ago and a few minutes ago again.

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
@etaxi341 We need to learn more about this, will you be interested to talk to us? If yes, here's a link to our calendar, please book a slot which works for you - https://app.cal.com/srinivas-pendem/product-research

**Comment by pushya22** [comment]
@etaxi341 please re-open if you think the issue still persists.
