### ISSUE TITLE
[bug]: Dashboard displays server time, not local time

### ISSUE THREAD

**Issue by psi-chuffine** [makeplane/plane#3880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The dashboard shows the server time, not the local browser time.
![image](https://github.com/makeplane/plane/assets/76532245/056d0bca-a4dd-4e41-80f6-139913ef21ae)
![image](https://github.com/makeplane/plane/assets/76532245/bd50bfc9-ede3-4ff7-b104-faa55fb74237)

### Steps to reproduce

The local docker instance is running UTC time, while the local timezone is ET. 

### Environment

Production

### Browser

Google Chrome

### Version

Local

**Comment by srinivaspendem** [comment]
Hey @psi-chuffine, the time displayed on the dashboard depends on the timezone you've set in your profile. Please navigate to the /profile page, update your timezone, and then check again.
