### ISSUE TITLE
[bug]: Self hosting - Docker Compose : Plane.so fails to start on default install

### ISSUE THREAD

**Issue by radhakrisri** [makeplane/plane#3883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Followed the instructions here - https://docs.plane.so/self-hosting/docker-compose - to the dot. 

1. Downloaded latest stable release (https://docs.plane.so/self-hosting/docker-compose#downloading-latest-stable-release)
2. As described in https://docs.plane.so/self-hosting/docker-compose#proceed-with-setup, opted for 1 and then 2.

When I launch http://localhost, this is what shows up. 

![Screenshot from 2024-03-05 23-33-15](https://github.com/makeplane/plane/assets/125212515/398634db-adb7-4a17-a17a-a4a0d37a8584)

I digged around a bit - looks like https://github.com/makeplane/plane/issues/1516 is related. Sad that it is not reopened.

### Steps to reproduce

Nothing much, just follow instructions here: https://docs.plane.so/self-hosting/docker-compose. 

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @radhakrisri you have to go to `/god-mode` to continue your setup. You can find more details here- https://docs.plane.so/introduction/signup-signin#self-managed

**Comment by radhakrisri** [comment]
The documentation MUST be updated to say so. Nothing in this link - https://docs.plane.so/self-hosting/docker-compose - indicates that this must be performed. 

Please put yourself in an end user's shoes. And then imagine what documentation will help his usecase. 

@srinivaspendem : Please re-open this, till the documentation is updated accordingly.
