### ISSUE TITLE
[bug]: Setting Due Date ends up using the previous day

### ISSUE THREAD

**Issue by lars1273** [makeplane/plane#3903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On an issue, when i select a due date of March 12th, it sets the due date to March 11th.

I expect it to be March 12th

### Steps to reproduce

1. Go to an issue
2. Set the due date
3. The resulting due date will be the previous day

### Environment

Production

### Browser

Google Chrome

### Version

Cloud

**Comment by psi-chuffine** [comment]
There are several instances of this issue. #3074 #3305 #2204 #1992

It's most likely stemming from server/client TZ differences combined with use of the JS Date function.

**Comment by lars1273** [comment]
Do you need me to schedule a call or do you think it's server/client TZ differences combined with the use of the JS Date function?

**Comment by leonam-okajima** [comment]
I'm facing the same issue. I believe it happens when setting a different timezone in the Settings. In my case, I'm using GTM-3 (Brazil/East).

**Comment by apatterson2600** [comment]
Same issue here

**Comment by jake-ef** [comment]
Same here - On Firefox and Chrome, for every panel that allows a date picker. v0.16

**Comment by yepayepayepa** [comment]
I've been facing the same issue in the Cloud and self-hosted versions. I recorded a small video to show you, I agree that it might be a TZ issue
![plane](https://github.com/makeplane/plane/assets/70953970/012180d3-8e6b-4aab-9237-1bc8315d0784)

**Comment by srinivaspendem** [comment]
Hey, this issue has been resolved in the cloud version and will be addressed in the upcoming release for the self-hosted version.
