### ISSUE TITLE
[bug]: Upgrade from v0.14.2-dev to v0.15-dev gets stuck on "Waiting for database migrations to complete..."

### ISSUE THREAD

**Issue by marktopper** [makeplane/plane#3904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

So it seems that the migrations are no longer ran in v0.15-dev to v0.15.4-dev. Haven't tested v0.16-dev yet.

I would expect the migrations to run when I start the `makeplane/plane-backend` container.

### Steps to reproduce

Start `makeplane/plane-backend:v0.15.4-dev`
Watch the "Waiting for database migrations to complete..." loop.

I have rolled back to v0.14.2-dev, but I do wish to upgrade at some point.

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by mguptahub** [comment]
@marktopper 

Earlier we introduced the migrator service. So the backend service wait for migrator to get over. 

Can you the logs of migrator and share with me.

**Comment by marktopper** [comment]
> @marktopper
> 
> Earlier we introduced the migrator service. So the backend service wait for migrator to get over.
> 
> Can you the logs of migrator and share with me.

That makes sense. I don’t have setup that service on my environment yet. Thank you for the fast reply, I’ll take a look into that.
