### ISSUE TITLE
[bug]: Error: Cannot find module @rollup/rollup-darwin-x64. Mac M1

### ISSUE THREAD

**Issue by gHashTag** [makeplane/plane#3908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to run a web project locally, but I can't.

I'm running the project locally on M1 and getting the error: Error: Cannot find module @rollup/rollup-darwin-x64

Module installation
bun i @rollup/rollup-darwin-x64 

It doesn't solve the problem. What should I do?

bun 
"build": "turbo run build",

```bash
 bun dev
$ turbo run dev --concurrency=13
• Packages in scope: @plane/document-editor, @plane/editor-core, @plane/editor-extensions, @plane/lite-text-editor, @plane/rich-text-editor, @plane/types, @plane/ui, eslint-config-custom, space, tailwind-config-custom, tsconfig, web
• Running dev in 12 packages
• Remote caching disabled
@plane/editor-core:dev: cache bypass, force executing 12cdd2575432a0f7
@plane/ui:build: cache miss, executing 8c80657b67e09703
@plane/editor-core:build: cache miss, executing d1ad489f3ddd59c6
@plane/ui:dev: cache bypass, force executing 05c85e78a80d6814
@plane/editor-core:build: 
@plane/ui:build: 
yarn run v1.22.21
yarn run v1.22.21
yarn run v1.22.21
yarn run v1.22.21
$ tsup src/index.ts --format esm,cjs --dts --external react --minify
$ tsup --watch
$ tsup --minify
$ tsup src/index.ts --format esm,cjs --watch --dts --external react
@plane/ui:build: CLI Building entry: src/index.ts
@plane/ui:build: CLI Using tsconfig: tsconfig.json
@plane/ui:build: CLI tsup v5.12.9
@plane/ui:build: CLI Target: node12
@plane/editor-core:build: Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
@plane/editor-core:build:     at requireWithFriendlyError (/Users/playra/999-web3-plane/node_modules/tsup/node_modules/rollup/dist/native.js:87:9) bun dev
$ turbo run dev --concurrency=13
• Packages in scope: @plane/document-editor, @plane/editor-core, @plane/editor-extensions, @plane/lite-text-editor, @plane/rich-text-editor, @plane/types, @plane/ui, eslint-config-custom, space, tailwind-config-custom, tsconfig, web
• Running dev in 12 packages
• Remote caching disabled
@plane/editor-core:dev: cache bypass, force executing 12cdd2575432a0f7
@plane/ui:build: cache miss, executing 8c80657b67e09703
@plane/editor-core:build: cache miss, executing d1ad489f3ddd59c6
@plane/ui:dev: cache bypass, force executing 05c85e78a80d6814
@plane/editor-core:build: 
@plane/ui:build: 
yarn run v1.22.21
yarn run v1.22.21
yarn run v1.22.21
yarn run v1.22.21
$ tsup src/index.ts --format esm,cjs --dts --external react --minify
$ tsup --watch
$ tsup --minify
$ tsup src/index.ts --format esm,cjs --watch --dts --external react
@plane/ui:build: CLI Building entry: src/index.ts
@plane/ui:build: CLI Using tsconfig: tsconfig.json
@plane/ui:build: CLI tsup v5.12.9
@plane/ui:build: CLI Target: node12
@plane/editor-core:build: Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
@plane/editor-core:build:     at requireWithFriendlyError (/Users/playra/999-web3-plane/node_modules/tsup/node_modules/rollup/dist/native.js:87:9)

### Steps to reproduce

1. docker-compose up --build  
2. bun i 
3. bun dev

### Environment

Production

### Browser

Google Chrome

### Version

Local

**Comment by gHashTag** [comment]
I used the packaged bun manager and that's why I got this error. Works with yarn.

**Comment by nidekunji** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current behavior
> I want to run a web project locally, but I can't.
> 
> I'm running the project locally on M1 and getting the error: Error: Cannot find module @rollup/rollup-darwin-x64
> 
> Module installation bun i @rollup/rollup-darwin-x64
> 
> It doesn't solve the problem. What should I do?
> 
> bun "build": "turbo run build",
> 
> ```shell
>  bun dev
> $ turbo run dev --concurrency=13
> • Packages in scope: @plane/document-editor, @plane/editor-core, @plane/editor-extensions, @plane/lite-text-editor, @plane/rich-text-editor, @plane/types, @plane/ui, eslint-config-custom, space, tailwind-config-custom, tsconfig, web
> • Running dev in 12 packages
> • Remote caching disabled
> @plane/editor-core:dev: cache bypass, force executing 12cdd2575432a0f7
> @plane/ui:build: cache miss, executing 8c80657b67e09703
> @plane/editor-core:build: cache miss, executing d1ad489f3ddd59c6
> @plane/ui:dev: cache bypass, force executing 05c85e78a80d6814
> @plane/editor-core:build: 
> @plane/ui:build: 
> yarn run v1.22.21
> yarn run v1.22.21
> yarn run v1.22.21
> yarn run v1.22.21
> $ tsup src/index.ts --format esm,cjs --dts --external react --minify
> $ tsup --watch
> $ tsup --minify
> $ tsup src/index.ts --format esm,cjs --watch --dts --external react
> @plane/ui:build: CLI Building entry: src/index.ts
> @plane/ui:build: CLI Using tsconfig: tsconfig.json
> @plane/ui:build: CLI tsup v5.12.9
> @plane/ui:build: CLI Target: node12
> @plane/editor-core:build: Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
> @plane/editor-core:build:     at requireWithFriendlyError (/Users/playra/999-web3-plane/node_modules/tsup/node_modules/rollup/dist/native.js:87:9) bun dev
> $ turbo run dev --concurrency=13
> • Packages in scope: @plane/document-editor, @plane/editor-core, @plane/editor-extensions, @plane/lite-text-editor, @plane/rich-text-editor, @plane/types, @plane/ui, eslint-config-custom, space, tailwind-config-custom, tsconfig, web
> • Running dev in 12 packages
> • Remote caching disabled
> @plane/editor-core:dev: cache bypass, force executing 12cdd2575432a0f7
> @plane/ui:build: cache miss, executing 8c80657b67e09703
> @plane/editor-core:build: cache miss, executing d1ad489f3ddd59c6
> @plane/ui:dev: cache bypass, force executing 05c85e78a80d6814
> @plane/editor-core:build: 
> @plane/ui:build: 
> yarn run v1.22.21
> yarn run v1.22.21
> yarn run v1.22.21
> yarn run v1.22.21
> $ tsup src/index.ts --format esm,cjs --dts --external react --minify
> $ tsup --watch
> $ tsup --minify
> $ tsup src/index.ts --format esm,cjs --watch --dts --external react
> @plane/ui:build: CLI Building entry: src/index.ts
> @plane/ui:build: CLI Using tsconfig: tsconfig.json
> @plane/ui:build: CLI tsup v5.12.9
> @plane/ui:build: CLI Target: node12
> @plane/editor-core:build: Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
> @plane/editor-core:build:     at requireWithFriendlyError (/Users/playra/999-web3-plane/node_modules/tsup/node_modules/rollup/dist/native.js:87:9)
> 
> ### Steps to reproduce
> 
> 1. docker-compose up --build  
> 2. bun i 
> 3. bun dev
> 
> ### Environment
> 
> Production
> 
> ### Browser
> 
> Google Chrome
> 
> ### Version
> 
> Local
> ```

I encountered the same problem。。。
