### ISSUE TITLE
[bug]: Kanban Sub-Group Layout 

### ISSUE THREAD

**Issue by tillkoll** [makeplane/plane#3920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Issues are not mapped to the correct group if "Show empty groups" is deselected and the issues are grouped by assignee. 
The issues inside a sub-group are moving to the left if an assignee does not have an issue in that sub-group. Therefore an issue assigned to person B might be in the column of person A. This is quite confusing. 
I would assume that an issue should always be in the column of the assignee. 

If something other than assignee is selected as group, the problem also occurs. 

### Steps to reproduce

1. Open Kanban view in a project
2. Group by Assignee
3. Sub-Group by Module (or Label)
4. Deselect "Show empty groups"

This might only be reproducible if a person doesn't have any assigned issues in a module. 

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by mmospanenko** [comment]
also, it shows empty groups with subgroup grouping even if unselected Show empty
