### ISSUE TITLE
[bug]: CRITICAL - Documentation page crashes

### ISSUE THREAD

**Issue by likendev** [makeplane/plane#3922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I trying to go navigate around the [documentation page](https://docs.plane.so/introduction/home), however I got stuck and the page crashes when clicking on `About` under `Integration` on the side navigation menu.

![image](https://github.com/makeplane/plane/assets/15458805/40ff5c0a-8cc5-4a93-a42f-eaeb43d0b5b9)

OS: Fedora Linux 39 (Workstation Edition) x86_64
Browser: Brave v1.63.169

Tried with Firefox too. Noticed the same behaviour.

### Steps to reproduce

1. Go to [docs](https://docs.plane.so/introduction/home)
2. Click on side navigation item (Integration > About)
3. Monitor the page, it will be not responsive and crash the page.

### Environment

Production

### Browser

Other

### Version

Cloud

**Comment by srinivaspendem** [comment]
Thanks for bringing this to our attention @likendev we are investigating this

**Comment by srinivaspendem** [comment]
This is fixed now
