### ISSUE TITLE
[bug]: Installation does not work because of "unknown shorthand flag: 'f' in -f"

### ISSUE THREAD

**Issue by L4ma** [makeplane/plane#3924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I run the setup.sh script and select 1), an error is displayed immediately.

The following error is displayed: 
unknown shorthand flag: 'f' in -f

Here is another screenshot:
![Bildschirmfoto 2024-03-11 um 08 51 49](https://github.com/makeplane/plane/assets/26965333/47a7811e-a89f-4e2d-896a-22170654f949)

The whole thing happens on a root server from Hetzner with an Intel Core i7-6700 @ 3.40GHz x8, 64 GB RAM and 512 GB SSD

### Steps to reproduce

1. start the script.sh, if Plane is not yet installed.
2. enter 1 as the action
3. the error occurs

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hi @L4ma, it seems the issue might be related to your Docker setup. Could you please try using `docker compose up` and see if that resolves the problem? If it's still not working, I recommend reinstalling Docker and checking again.

**Comment by djo074** [comment]
Hello all,
Same problem to install plane on a synology with container manager.
Version of docker compose is :Docker Compose version v2.9.0-6413-g38f6acd
But for me this error appears when I try to start plane (choice 2)
Thanks for your help
Djo
