### ISSUE TITLE
chore: fix typo in docs

### ISSUE THREAD

**Issue by kyogesha** [makeplane/plane#3943]
In docs, quick start there is `Learn how to sue plane and ...`,
I'm guessing its meant to be `use plane`.

PS: I could open PR if someone would direct me

![Screenshot](https://github.com/makeplane/plane/assets/63769109/09b38cdf-05ed-4345-af74-6197d3147897)

**Comment by srinivaspendem** [comment]
Fixed, thanks for letting us know.
