### ISSUE TITLE
[bug]: Carriage return/new line in module description in side bar

### ISSUE THREAD

**Issue by tsbgarner** [makeplane/plane#3964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When carriage returns are added to the description field of a module, they are ignored in the module description in the pop out side panel.

When creating the module
![image](https://github.com/makeplane/plane/assets/5819118/0def5f0b-7b21-4ac6-a250-5f67c4e074a9)

and in the sidebar
![image](https://github.com/makeplane/plane/assets/5819118/4c9721f4-8a46-4fbc-bf22-5808ffdee09c)

The carriage returns are stored however, as when editing the description they remain
![image](https://github.com/makeplane/plane/assets/5819118/96d62809-37c4-473a-8308-906453df5a3f)

### Steps to reproduce

1. Start creating a new module
2. Enter some text with carriage returns
3. Create module
4. Click the "i" icon next to the module name in the module list
5. View the description that contains no line breaks.

### Environment

Production

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by srinivaspendem** [comment]
Hey @tsbgarner, we'll resolve this issue in our upcoming release.
