### ISSUE TITLE
[bug]: User still sees and can join a private project if they were once a member

### ISSUE THREAD

**Issue by benr77** [makeplane/plane#3967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Private projects should not be visible to members unless they are invited.

If I add a member to a private project, but then subsequently remove the member,  they should not then see the project any more because it is private.

However, I have found that the user continues to see the project and can join again at any time.

This means effectively that the project is no longer private for any users that have been a member historically, but have since been removed.

### Steps to reproduce

- Make a private project
- Invite another user
- Check the user can see the project and its contents
- As an admin, remove the user from the project
- Check and discover that the user continues to see the project and can join it again (even after a logout).

### Environment

Production

### Browser

Mozilla Firefox

### Version

Cloud - version 16.0

**Comment by srinivaspendem** [comment]
You are correct, this is a concern. Thanks for reporting this, we will get it fixed.

**Comment by srinivaspendem** [comment]
Hey @benr77, we've resolved this issue with PR #3971.
