### ISSUE TITLE
[bug]:  Starting local development of Plane fails

### ISSUE THREAD

**Issue by wassafshahzad** [makeplane/plane#3985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running the following command 
```
docker compose -f docker-compose-local.yml up -d
```
The proxy service seems to fail as it cant find the docker-entrypoint.sh

### Steps to reproduce

Follow the Local development guide.

### Environment

Deploy preview

### Browser

Google Chrome

### Version

Local

**Comment by pablohashescobar** [comment]
@wassafshahzad, what is the error you are getting can you send that error which would help us to debug this issue better.

**Comment by LeikoDmitry** [comment]
A also try to install project on my local machine and getting the page:

![Screenshot 2024-03-20 at 09 33 55](https://github.com/makeplane/plane/assets/9258971/7434c3d4-668f-44e2-a8e1-275c48d12bbc)

**Comment by wassafshahzad** [comment]
Issue was resolved
