### ISSUE TITLE
[bug]: Cannot use blocked by and relates to at the same time.

### ISSUE THREAD

**Issue by larrydewey** [makeplane/plane#4011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When modify an issue setting it as `Blocked by` you cannot also have it listed as `Related to`. This would be nice for when an issue is no longer blocked, you will no longer need to manually go and relate it.

### Steps to reproduce

1. Create `Issue A`
2. Create `Issue B`
3. Within `Issue A` click on `Blocked By` and select `Issue B`. 
4. Within `Issue A` click on `Related to` notice that `Issue B` is not available.

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pushya22** [comment]
Hi @larrydewey this is intended behaviour
