### ISSUE TITLE
[bug]: Duplication in spreadsheet view

### ISSUE THREAD

**Issue by larrydewey** [makeplane/plane#4012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When setting one issue as a parent to another issue, in the spreadsheet view, the item is duplicated.

![image](https://github.com/makeplane/plane/assets/41640198/c37f1ff5-2ab8-4131-8150-14f14305f21b)

### Steps to reproduce

1. Create `Issue A`
2. Create `Issue B`
3. Edit `Issue A` and set the parent as `Issue B`
4. Refresh the spreadsheet view (potentially a bug you have to do this manually)
5. Expand all of the issues.
6. See duplication.

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pushya22** [comment]
hi @larrydewey this is intended behaviour when sub-issues toggle is on in display properties.
