### ISSUE TITLE
[query]: how far are we from first stable release 

### ISSUE THREAD

**Issue by sarsony1** [makeplane/plane#4015]
Hello team, 
Your project looks like a really good open source alternative to JIRA. But at the moment I feel its is still missing some very basic things. May I know your targets for first stable release so that I can come back to this. I see only dev pre releases are happening right now

**Comment by srinivaspendem** [comment]
Hello, we are quite close to our stable release within the next few weeks. Please reach out to us on discord to know more - https://discord.com/invite/A92xrEGCge
