### ISSUE TITLE
[bug]: unable to select issue state when its bottom of the window .

### ISSUE THREAD

**Issue by codewithjk** [makeplane/plane#4019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I add some issues to a module of my project , the issues are listed and the list reached almost bottom of the window. Now  I can't  able to change  the issue state to "done" or "cancelled" . there is no scrolling option. This issue appears only for bottom issues. If it is solved by applying scroll for state dropdown or for full list of issue the UI will improve.

### Steps to reproduce

1. create a project
2. create some issues
3. issues list should reach almost bottom of the window , but not exceed.
4. click the state selecting button
5. a dopdown will show with some options (some options will be hidden )
<img width="1536" alt="Screenshot 2024-03-21 at 2 11 52 PM" src="https://github.com/makeplane/plane/assets/99420814/5f9f5566-4c91-4322-8223-d16fc8a7afb8">
<img width="1536" alt="Screenshot 2024-03-21 at 2 12 01 PM" src="https://github.com/makeplane/plane/assets/99420814/09febb3c-c731-4ed0-878a-f60d5e115894">

### Environment

Production

### Browser

Safari

### Version

Cloud

**Comment by pushya22** [comment]
Hi @codewithjk thanks for bringing this to our notice. This issue will be resolved in our next release.

**Comment by codewithjk** [comment]
issue is still there. 

browser details:
safari
Version 17.4 

https://github.com/makeplane/plane/assets/99420814/030612b8-a5bf-4876-ad0d-c69511761f60

**Comment by anmolsinghbhatia** [comment]
This issue is resolved.
<img width="1508" alt="Screenshot 2024-03-26 at 4 35 51 PM" src="https://github.com/makeplane/plane/assets/121005188/a3ba0dbd-e15c-4d18-b757-265af86b81ad">
