### ISSUE TITLE
[bug]: Stuck installl yarn for local installation

### ISSUE THREAD

**Issue by kmtcreator** [makeplane/plane#4036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After I run "docker compose -f docker-compose-local.yml up -d"
#51 [web 6/6] RUN yarn install
#51 6.039 yarn install v1.22.19
#51 7.067 [1/4] Resolving packages...
#51 11.19 [2/4] Fetching packages...
#51 11.24 warning Pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"] is trying to                                                                                                                 unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-strip-ansi-c                                                                                                                js-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-a                                                                                                                nsi-cjs" as pattern ["strip-ansi@^6.0.1"]. This could result in non-deterministi                                                                                                                c behavior, skipping.
#51 11.24 warning Pattern ["string-width@^4.1.0"] is trying to unpack in the sam                                                                                                                e destination "/usr/local/share/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c71                                                                                                                17d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as p                                                                                                                attern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-de                                                                                                                terministic behavior, skipping.
#51 11.24 warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same                                                                                                                 destination "/usr/local/share/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30                                                                                                                f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern                                                                                                                 ["strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skippin                                                                                                                g.
#51 147.3 info There appears to be trouble with your network connection. Retrying...

### Steps to reproduce

![image](https://github.com/makeplane/plane/assets/145428074/68c4c407-c0c0-423f-b9ce-3180fce28f28)

### Environment

Production

### Browser

Other

### Version

Local

**Comment by sriramveeraghanta** [comment]
Looks like a network connectivity issue can you try again @kmtcreator
