### ISSUE TITLE
[bug]: Uploaded media immediatly vanishes (RangeError: Position -1 out of range)

### ISSUE THREAD

**Issue by OfficialLambdax** [makeplane/plane#4051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i upload a image (jpg) to a issue it will immediatly vanish. I cannot locate any sort of error in any container log, all i see is
`172.30.0.11:52278 - "POST /api/workspaces/test-plane/file-assets/ HTTP/1.0" 201` which indicates a success

Looking into the browser console reveals the following error
`Upload error:  RangeError: Position -1 out of range`

I could confirm that the image was actually uploaded but it will not be shown in a issue or a comment of the issue, neither as a image box. It appears as if the image was never uploaded. Even after a full website reload or plane restart the issue persists.

.env files looks like this
[vars.env.txt](https://github.com/makeplane/plane/files/14734187/vars.env.txt)

### Steps to reproduce

1. Follow the instructions @ https://github.com/makeplane/plane/blob/preview/deploy/selfhost/README.md
2. Add the network ip of that machine inside the .env file
3. Install and Start the plane
4. Connect to the plane from a remote machine (same network)
5. Create an issue and try uploading any media

This issue is also present when i connect to the plane from localhost

### Environment

Production

### Browser

None

### Version

Self-hosted

**Comment by OfficialLambdax** [comment]
On another note, this is a beautifull tool, im used to using it in a community project and i find it this neat that i want to showcase it to others. So my plane is only ever going to be hosted on a test machine to showcase what this tool can do to others. But i cannot locate any error in my configuration

**Comment by aaryan610** [comment]
Hey @bartoszjuszczyk, this issue was recently fixed with #5585. It'll be made live with our next release soon.
