### ISSUE TITLE
[feature]: add more automations when issue statuses change

### ISSUE THREAD

**Issue by lars1273** [makeplane/plane#4089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Our previous tool allowed from a lot of automations when a status of an issue changed.  We think this would be a great feature for plane in order to save some of the manual steps needed after an issue moves into a new status.

### Why should this be worked on?

As a dev that works on multiple projects, it's not always known who is the QA user so having the automation of changing the assignee to the QA person when i move a ticket from in progress to ready for QA would eliminate a manual step and also some communication to figure out who it needs to go to.  Here is what our previous tool had setup
![image](https://github.com/makeplane/plane/assets/5789394/f1c0e393-4d2b-48c5-bb2e-7cfb71d5b49f)
![image (1)](https://github.com/makeplane/plane/assets/5789394/8959f290-3462-4c5b-a453-dec1f2588bb9)
![image (2)](https://github.com/makeplane/plane/assets/5789394/0bd1f5ae-4e31-497d-8286-ce97a195fa4c)

**Comment by vihar** [comment]
Automations are part of our Pro plan. We haven’t started working on this feature yet, but we’ll update you once it is available.
