### ISSUE TITLE
[bug]: Cycle Date Issue

### ISSUE THREAD

**Issue by athornfam2** [makeplane/plane#4118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When selecting a date after a cycles date range. The date after reverts to the last day of the cycle as the start date and then I get the attached error
![image](https://github.com/makeplane/plane/assets/74559383/0c63dd32-5dbb-4b68-9cc1-1f76684210b4)

### Steps to reproduce

Create a cycle with specified date range (April 1 to April 30 in my case), New cycle with start date of May 1 to Aug 1 and then you get an error.

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by pushya22** [comment]
Hi @athornfam2 We have resolved this issue in v0.17 release, could you please upgrade to v0.17 and check if you still facing the issue.

Thanks

**Comment by athornfam2** [comment]
I'm still having issues. I believe you can't have a cycle start date within an active cycle. I'm new to this as I'm not familiar with management part of projects just using it for personal use/maybe work. But when I select a start date for a second project after or in another active cycle it doesn't work.  @pushya22

**Comment by vihar** [comment]
@athornfam2, I understand now. This issue might be because you have used a different time zone under your profile settings. Please update your time zone, and this issue should be fixed. Closing this for now. If you are still seeing the issue, please re-open it.
