### ISSUE TITLE
[bug]: Jira import Problem in selfhosted

### ISSUE THREAD

**Issue by Muthu2602** [makeplane/plane#4136]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current behavior

![Screenshot (3)](https://github.com/makeplane/plane/assets/115365422/74afbcf1-c9be-4e26-a6b7-4271897febf8)
 While operating on my AWS server, I encountered difficulty importing a Jira file, which remains in a 'QUEUED' state.

### Steps to reproduce

First goto the import & click on Jira import and type all my project details correctly but still queued state.

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by ChandeepKhosa** [comment]
This works fine for me with the Cloud version, could you please rename the issue title to make it clear that it's happening for you on self-hosted please to make it easier for users looking for JIRA import issues? Thanks

**Comment by ishujais** [comment]
@ChandeepKhosa this isn't working for me on the cloud version of Plane, and I haven't seen any option for JIRA Import on the self-hosted version, it would be great if you help me to enable the import option for JIRA on self-hosted version & debug the issue that I'm facing while importing data from JIRA on the cloud version of Plane.

**Comment by ChandeepKhosa** [comment]
@ishujais unfortunately it's not possible on self-hosted yet, you will have to wait until it is. Read the comments on the 2nd link I posted please and you'll see for yourself

**Comment by Mo0rBy** [comment]
Sorry for being blunt here......but this is crazy.
This should be way more obvious to users.
I've had to dig to find this information and now I have to switch to GitLab.......I hate GitLab.
