### ISSUE TITLE
[bug]: I got invited to a workspace 

### ISSUE THREAD

**Issue by sebastian-ptz** [makeplane/plane#4166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I got invited to a workspace via e-mail I could not access the workspace. 

### Steps to reproduce

1. Registered with e-mail
2. Created own workspace
3. Got invited to a workspace via e-mail
4. Joined the workspace but still not having access
5. On the administration I am not visible in the workspace
6. When tried to get reinvited the admin got the message "the user is already a member of the workspace".

### Environment

Production

### Browser

Google Chrome

### Version

Cloud

**Comment by luis-cruzt** [comment]
Same issue here.

**Comment by moigagoo** [comment]
I'm having this issue right now. Literally blocking any usage of the product as I can't invite any coworkers.

**Comment by srinivaspendem** [comment]
Hi @moigagoo, We were unable to recreate the issue. Could you please ask your admin to resend the invite?

**Comment by moigagoo** [comment]
@srinivaspendem 

> We were unable to recreate the issue. Could you please ask your admin to resend the invite?

I'm the admin and I couldn't resend the invitation due to this error: "the user is already a member of the workspace."


> If you are still facing the issue please let us know.

I managed to work around the issue by inviting another member to the workspace. After I've invited the 3rd member, the 2nd one showed up. Then I removed the 3rd one.

**Comment by srinivaspendem** [comment]
To resend the invitation, please remove the member from the list first, then send the invitation again.
<img width="871" alt="image" src="https://github.com/makeplane/plane/assets/65014795/b3e42fb0-9751-4bfd-a6ad-82c3ef9319c7">


If you still face the issue, attaching a video or some images for reference will help our team resolve it more quickly.
