### ISSUE TITLE
[bug]: Unable to change the font style in the description  filed of issue.

### ISSUE THREAD

**Issue by codewithjk** [makeplane/plane#4174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to change the style of the text in description of  a issue , the menu list is  not working .

https://github.com/makeplane/plane/assets/99420814/0e80ee5d-d241-459a-b9c2-5f3fab6664c4

### Steps to reproduce

1. create a project
2. create a module 
3. create a issue  (save)
4. after issue is listed in  Modules issue list  click on that issue.
5. type something in description field .
6. change the text stye after selecting the text.

browser  :  safari 17.4.1

### Environment

Production

### Browser

Safari

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hello, this issue is fixed now. Can you check it once and let me know if we need to re-open?
