### ISSUE TITLE
[bug]: adding new members to workspace on hosted  https://plane.so/ doesnt work. Similar to  I got invited to a workspace #4166

### ISSUE THREAD

**Issue by fozak** [makeplane/plane#4176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

adding new members to workspace on hosted  https://plane.so/ doesnt work. 
 

### Steps to reproduce

1. Go to https://app.plane.so/testdww/settings/members
2. Add member by adding email
3. Member receives the invite, registering, can login with code, set up the password,
4. Admin doesnt see newly created member at https://app.plane.so/testdww/settings/members
5. Member sees both Admin and Member (himself), but can not do anything, including creating issues

### Environment

Production

### Browser

Google Chrome

### Version

Cloud

**Comment by dilippitchika** [comment]
Hey @fozak this issue is fixed in our cloud version. Please try doing a [hard refresh](https://faq.owlpractice.ca/how-to-do-a-hard-refresh-for-your-browser) and let me know if the issue persists.

**Comment by fozak** [comment]
Although I see the new member added, I can not assign any issue to him (he is not visible in asignees list) and there is no issues in his workspace. 
I wonder if this version has a working collaboration or we should wait for later release with working collaboration?
Please reopen the issue

**Comment by fozak** [comment]
Thanks, your were right, I should add members not only to workspace but to project, now it works. Again, thanks for support
