### ISSUE TITLE
[bug]: Project--Publish settings-- "Copy Link" button can not work(0.17-dev)

### ISSUE THREAD

**Issue by preswang** [makeplane/plane#4184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Project--Publish settings-- "Copy Link" button can not work

### Steps to reproduce

When I choose my Project
2. Scroll down to'Publish settings' 
3.click "Copy Link" button 
nothing copied 
and because of the URL is too long(not show all), I can not copy the address by myself.

### Environment

Production

### Browser

Safari

### Version

Self-hosted

**Comment by pushya22** [comment]
Hi @preswang Thank you for bringing this to our attention. We'll make sure to rectify it in our next release
