### ISSUE TITLE
[bug]:  django.db.utils.OperationalError: connection failed: FATAL:  database "plane" does not exist

### ISSUE THREAD

**Issue by CarlosPlasencia** [makeplane/plane#4197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to install plane on an EC2 (Ubuntu 22.04) and every time I try to install I get the error database "plane" does not exist in the logs, I tried to change the database and it gave me the error that the password does not match even though Just configure one for my user.

I did the same on my local (macbook) and it worked.

![image](https://github.com/makeplane/plane/assets/14086526/4c2c9484-f309-4402-b70a-60a697cdb64c)

### Steps to reproduce

1. excecute ./setup.sh
2. install
3. change plane.env (NGINX_PORT, WEB_URL, CORS_ALLOWED_ORIGINS)
4. excecute ./setup.sh again
5. option 2

### Environment

Production

### Browser

None

### Version

Self-hosted

**Comment by vihar** [comment]
@CarlosPlasencia, sorry for following up late. Are you still seeing this issue? Our self-hosting setup has been improved. Please follow our latest [docs for the upgrade](https://docs.plane.so/self-hosting/methods/docker-compose#upgrading-plane-version). Closing this issue for now, please re-open if you are having any trouble.
