### ISSUE TITLE
[feature]: GitHub Issue Importer

### ISSUE THREAD

**Issue by sphynxux** [makeplane/plane#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Adding a GitHub importer to Plane would be highly beneficial as an extension to the [GitHub sync integration](https://docs.plane.so/integrations#github). This would enable the transfer of existing issues from GitHub onto Plane.

### Why should this be worked on?

By utilizing this feature, users can manage their issue planning through Plane instead of doing so on GitHub.

**Comment by pablohashescobar** [comment]
We are expecting this soon, the backend logic for this issue is ready to be reviewed on #425.

**Comment by pablohashescobar** [comment]
This feature is already shipped on Plane v0.5-dev and is available on cloud version
