### ISSUE TITLE
[feature]: Customize the e-mail templates

### ISSUE THREAD

**Issue by LarsJaensch** [makeplane/plane#4272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be nice if you could customize the messages that the system sends to users. So the header, the footer and the content.

### Why should this be worked on?

This would move more in the direction of whitelabel and users could customize it according to their personal needs

https://discord.com/channels/1031547764020084846/1227262578955386950/1232598952596213760

**Comment by vihar** [comment]
@LarsJaensch, white labeling will be part of our Enterprise plan. Please see our [pricing page](https://plane.so/pricing) for more details.
