### ISSUE TITLE
[bug]: Some emojis are not rendered correctly

### ISSUE THREAD

**Issue by zvikarp** [makeplane/plane#4283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Some emojis are not rendered correctly for project icons, see the screenshot:

![image](https://github.com/makeplane/plane/assets/13397207/4fa8a0b3-d421-4e39-9447-93a23e9fb72b)

### Steps to reproduce

Create a project and give it the emoji 2️⃣

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

10.18.0

**Comment by mikecanann** [comment]
I can't duplicate this on the latest master branch

![image](https://github.com/makeplane/plane/assets/1325633/99ad9cc7-93a3-4918-b860-3eecab5cbe18)

**Comment by vihar** [comment]
Thanks for flagging this, @zvikarp. This issue was resolved a couple of releases back. I hope you’re on the latest version. If not, please upgrade to the latest version. Follow our [docs for upgrading](https://docs.plane.so/self-hosting/methods/docker-compose#upgrading-plane-version).
