### ISSUE TITLE
[bug]: issue embeded is not available on self hosted instance 

### ISSUE THREAD

**Issue by akarabach** [makeplane/plane#4290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

-

### Steps to reproduce

create new page and type `/`

<img width="871" alt="Screenshot 2024-04-25 at 18 57 12" src="https://github.com/makeplane/plane/assets/12261380/1489529d-6e94-4ecb-931e-643ba02bc73b">

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

Version: v0.18.0

**Comment by aaryan610** [comment]
Hey @akarabach, does this issue still persist for you?

**Comment by akarabach** [comment]
Hello @aaryan610 , still dont see this option on selfhosted instance

**Comment by aaryan610** [comment]
It is only available for Pro users. I guess you're using the community version, is this the case?

**Comment by akarabach** [comment]
Yes, I'm using community version

**Comment by aaryan610** [comment]
Thought so, you'll have to upgrade your workspace to use issue embeds. Let me know if I can help you out with anything else.
