### ISSUE TITLE
[feature]: Make it optional to set that first day of week is Monday

### ISSUE THREAD

**Issue by ronnyandre** [makeplane/plane#4356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In the calendar popups, the first day of week is default Sunday. This should be configurable

### Why should this be worked on?

Many countries of the world use Monday as first day of week, and this should be configurable.

**Comment by srinivaspendem** [comment]
Closing as duplicate of #4270. @ronnyandre we will figure out how to add this feature and get back on the other issue.
