### ISSUE TITLE
[bug]: drag 'n drop bugs in Firefox

### ISSUE THREAD

**Issue by ccrvlh** [makeplane/plane#4365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Not possible to drag & drop cards on Kanban view when using FIrefox - works fine in Brave.
Using Plane Version: v0.18.0 and FIrefox 125.0.3 (64-bit) (FWIW using Simple Tab Groups extension not sure if it has any effect).

https://github.com/makeplane/plane/assets/21188280/1bf6561d-22b3-40e6-8c73-297dd1db18fa

### Steps to reproduce

Try to drag and drop card on Kanban view

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.18.0

**Comment by pushya22** [comment]
Hi @ccrvlh, this is issue resolved in our latest release. Could you please upgrade to v0.19.0.

**Comment by ccrvlh** [comment]
@pushya22 just tested all seems to be working, thanks!
