### ISSUE TITLE
[feature]: Show issue id after create

### ISSUE THREAD

**Issue by yiiman-dev** [makeplane/plane#4368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

task will lost in list and we should search title for find that

### Why should this be worked on?

Please show issue id on success alert, when created new issue

**Comment by vihar** [comment]
@yiiman-dev, this is a good feature request. We will pick this up shortly and ship it. Apart from Issue ID, would you also like to see some shortcuts, like “copy link to issue” or “copy issue ID” as icons on the alert? More suggestions and feedback are welcome.
