### ISSUE TITLE
Issue: Inconsistent Icon Sizes in social media icons at the bottom of the website 

### ISSUE THREAD

**Issue by bro-maanii** [makeplane/plane#4378]
The social media icons at the bottom of the website exhibit inconsistent sizes. Some icons appear larger or smaller than others, leading to a visually unbalanced interface.

![image](https://github.com/makeplane/plane/assets/125199246/d30031a1-b131-4c25-af4b-4667a400f3a4)

**Comment by srinivaspendem** [comment]
Hey @bro-maanii, we've fixed the inconsistency with the sizes of the icons. Thank you for bringing it to our attention.

<img width="418" alt="image" src="https://github.com/makeplane/plane/assets/65014795/8e198a6b-fb68-4dad-b910-7fef1a901499">
