### ISSUE TITLE
[bug]: Website showing wrong information

### ISSUE THREAD

**Issue by etaxi341** [makeplane/plane#4380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

I found a Bug on your Website.
More then a Month ago this bug did not exist.

When selecting self-hosted and looking at the "free" Tier there is now a limit of 50 Users.
Before there was not User limit and it said free forever.

This surely must be a bug in your website right?
Because @theparthacus said in ticket #3364 that we do not have anything to worry about.

Could you please fix this to stop confusion? The people in the ticket #4095 are confused and this would help to clear this confusion.

This must be only an UI bug and should be easily fixed.

Thank you for the hard work!

### Steps to reproduce

1. Open the Website.
2. Click on Pricing
3. Click on Selfhost
4. There is suddenly a 50 Users limit.

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.17.0-dev

**Comment by theparthacus** [comment]
on it.

**Comment by theparthacus** [comment]
done.
![Hover text for number of users on pricing • Plane](https://github.com/makeplane/plane/assets/108609845/2e2b6070-6b4b-4c6d-96c2-194d377aae15)
