### ISSUE TITLE
[bug]: Invalid Email field validation

### ISSUE THREAD

**Issue by rahul-ymir** [makeplane/plane#4394]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

<img width="707" alt="image" src="https://github.com/makeplane/plane/assets/77712871/bb0d8a4f-9afe-46fa-abbd-43cca8650b6a">

Cannot invite team member with given email id: lars@drfasttrack.no which is valid email but it says invalid email.
Please refer screenshot attached.

### Steps to reproduce

1. Goto add team members section
2. Input email id 'lars@drfasttrack.no'
3. Click on submit

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

latest

**Comment by srinivaspendem** [comment]
Hi @rahul-ymir,

This issue has been resolved. If you're still experiencing any problems, please let us know.

**Comment by rahul-ymir** [comment]
Yes, the issue still exists. PFA image.
<img width="1439" alt="image" src="https://github.com/makeplane/plane/assets/77712871/6f199e64-42f1-47f0-8388-992d0431fcfb">
