### ISSUE TITLE
Suggestion: Add Toggle for Light and Dark Mode in Navbar

### ISSUE THREAD

**Issue by bro-maanii** [makeplane/plane#4395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I suggest adding a toggle for light and dark mode in the navbar. This toggle would allow users to switch between light and dark themes easily, enhancing the accessibility and customization options of the website. It's a feature many users appreciate for its ability to reduce eye strain and improve readability based on personal preferences. Including this toggle in the navbar would make it readily accessible and intuitive for users to control the display mode according to their needs.

### Why should this be worked on?

Adding a light and dark mode toggle in the navbar improves user experience, enhances accessibility, allows for customization, aligns with industry standards, and provides a competitive advantage.

**Comment by kohi9noor** [comment]
Sir I have 2 doubts the first can we use any external package for this and if it so then we will have to set images and some buttons for according to the condition of the toggle >?

**Comment by bro-maanii** [comment]
> Sir I have 2 doubts the first can we use any external package for this and if it so then we will have to set images and some buttons for according to the condition of the toggle >?
Yes, you can use Shadcn UI for the toggle effect. It's easy because Shadcn UI provides ready-made components, saving you time and effort.

With Shadcn UI, you won't need JavaScript to handle the toggle button's functionality; it's built-in. Just integrate the toggle button into your navbar and use Shadcn UI's classes to switch between light and dark modes.

Let me know if you need more help!

**Comment by pushya22** [comment]
Toggle themes are available at Profile settings > Preferences > Themes
