### ISSUE TITLE
[bug]: comment disappear from issues 

### ISSUE THREAD

**Issue by ERAS14D** [makeplane/plane#4412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Write a comment
Refresh tab
Comment disappear 

### Steps to reproduce

create issue
Comment it 
Refresh tab

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.19

**Comment by ERAS14D** [comment]
It's only occurring for issues created by copy

**Comment by pushya22** [comment]
hi @ERAS14D this issue is resolved. Please re-open in case of any further queries.
