### ISSUE TITLE
[bug]: ERROR: services.migrator.restart contains an invalid type, it should be a string

### ISSUE THREAD

**Issue by ilya4644** [makeplane/plane#4418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I install preview version got error because in docker-compose in service: migrator: restart value must be "no" but contain simply no

### Steps to reproduce

1. Get preview install on self-hosted
2. Start install

### Environment

Deploy preview

### Browser

None

### Variant

Self-hosted

### Version

v0.19-dev(?)

**Comment by mguptahub** [comment]
This has been resolved and not an issue anymore.
