### ISSUE TITLE
[bug]: Container plane-app-proxy-1 does not start after host restart (self hosted)

### ISSUE THREAD

**Issue by j3mu5** [makeplane/plane#4421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Plane is self-hosted in the latest version (0.19.0) and was installed according to the instructions for Docker: https://docs.plane.so/self-hosting/methods/docker-compose. 

When restarting the operating system (alpine linux), all containers start except plane-app-proxy-1 - this must be started manually.

It would be desirable if plane-app-proxy-1 also started.

### Steps to reproduce

Reboot

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

0.19.0

**Comment by mguptahub** [comment]
This has been taken care of in PR [5288](https://github.com/makeplane/plane/pull/5228)

**Comment by mguptahub** [comment]
Closing this issue.
