### ISSUE TITLE
[bug]: Plane web and space Container doesn't start after new deployment in preview version

### ISSUE THREAD

**Issue by sats268842** [makeplane/plane#4433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Error: container create failed: time="2024-05-10T11:51:42Z" level=error msg="runc create failed: unable to start container process: exec: \"/usr/local/bin/start.sh\": stat /usr/local/bin/start.sh: no such file or directory"

This message is shown in plane-web and plane-space

### Steps to reproduce

1. Try to deploy with preview tag in space and web image

### Environment

Deploy preview

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.19.0-dev

**Comment by KaraokeStu** [comment]
Update the docker-compose file from "/usr/local/bin/start.sh" to "node" and it'll work again
