### ISSUE TITLE
[feature]:Add Color Differentiation for Task Issues, Pages, etc. 

### ISSUE THREAD

**Issue by adamolnar** [makeplane/plane#4447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Introducing color coding to distinguish between different elements such as task issues, pages, and other components within the PLANE platform.

### Why should this be worked on?

 This visual enhancement will improve clarity and ease of navigation for users.

**Comment by vihar** [comment]
@adamolnar, issues can be differentiated using issue types (available as part of our Pro Plan). Pages can also have emojis, which will appear in the list view for differentiation. If you have more feedback, please feel free to re-open this issue. Closing it for now.
