### ISSUE TITLE
[feature]: Project Publish supports filtering by views, modules, or labels.

### ISSUE THREAD

**Issue by zhgchgli0718** [makeplane/plane#4453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, Project Publish only supports publishing all issues. We hope to only publish issues with specific conditions.

https://plane.sh/plane/459cfcdf-dc9c-49a6-9d4b-a89f91440189?board=kanban

### Why should this be worked on?

more flexible

**Comment by vihar** [comment]
@zhgchgli0718, publishing views, cycles, and modules is part of our [Pro plan](https://plane.so/pro), which will be available on both cloud and self-hosted versions. Please reach out to us on [Discord](https://discord.com/invite/A92xrEGCge) for more information on how this works.
