### ISSUE TITLE
[feature]: Open images in full screen mode without leaving issue window

### ISSUE THREAD

**Issue by mmakoto** [makeplane/plane#4458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Open images 🖼️  in full screen mode once one clicks on an attachment or - especially - when one clicks on images in the comments section. If I'm not mistaken, if nothing currently happens when we click on such images within comments.

### Why should this be worked on?

In order to properly see the images teammates leave on their Issues and I have to open them on a new screen. It would be great if the user could see attachments in full screen without leaving the Issue.

**Comment by rbouma** [comment]
upvote. This is really annoying right now when we need to post a image in the comment section.

**Comment by aaryan610** [comment]
This is definitely a great feature to have, we'll try to ship it soon.
