### ISSUE TITLE
[feature]: Should be able to filter issues with no cycles

### ISSUE THREAD

**Issue by frex-arup** [makeplane/plane#4496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently Filter is only there for Cycles Assigned. We should be able to filter issues with no cycles assigned.

### Why should this be worked on?

Currently Filter is only there for Cycles Assigned. We should be able to filter issues with no cycles assigned.

**Comment by pushya22** [comment]
Hi @frex-arup thanks for the suggestion, this feature is part of our roadmap and will be released soon.

**Comment by frex-arup** [comment]
ETA ?
