### ISSUE TITLE
[feature]: Jira Issue Importer

### ISSUE THREAD

**Issue by pablohashescobar** [makeplane/plane#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Build a new Jira issue importer that imports all issues from Jira to Plane. Additionally, migrate Epics from Jira to Plane modules along with other workflows such as states and labels.

### Why should this be worked on?

By doing this it will help existing Jira users to migrate from Jira to Plane

**Comment by pablohashescobar** [comment]
This Issue is shipped on v0.6-dev and is available on Plane Cloud.

**Comment by CybotTM** [comment]
Hi,

There is no commit, MR, documentation or anything at all linked to this issue.

Where do I find more information about this feature?

Thanks.

**Comment by peterhowe-adwanted** [comment]
Would love a response to this. We are running Jira Server v8.18.2 and migrating to Jira Cloud was going to be complicated and expensive - so we've become very interested in Plane, and knowing more about this importer would be a deciding factor.
