### ISSUE TITLE
[bug]: dark image not loading while adding parent in an issue

### ISSUE THREAD

**Issue by mobeenabdullah** [makeplane/plane#4510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I create an issue, there's a button called "Add parent", when I clicked on it, I can see a broken image in the dark mode. Light version of the image works fine.

Broken image URL:
https://app.plane.so/empty-state/search/issues-dark.webp

![Screenshot 2024-05-17 at 10 05 02 PM](https://github.com/makeplane/plane/assets/6951242/be839f5d-b98b-49e7-a37f-965603daaab1)

### Steps to reproduce

1. Create an Issue
2. Click on "Add parent" in the popup opened for creating the issue
3. Make sure to check in dark mode

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v0.17.0-dev

**Comment by srinivaspendem** [comment]
Hi @mobeenabdullah, We've resolved the issue in PR #4466. The fix will be included in our next release.
