### ISSUE TITLE
[bug]: login problem

### ISSUE THREAD

**Issue by alexodus** [makeplane/plane#4573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I login, after upgrade from 0.19.0-dev, and after change password, i receive  this message
<img width="511" alt="image" src="https://github.com/makeplane/plane/assets/2721510/5158288a-5bc6-43b7-b47e-387579d2a3cf">

### Steps to reproduce

1) change password
2) login with new password

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.20.0-dev

**Comment by alexodus** [comment]
same problem, when I create a new account.

**Comment by sriramveeraghanta** [comment]
You have to update your current domain in `CORS_ALLOWED_ORIGINS` env variable. Can you please try this out?

**Comment by alexodus** [comment]
> You have to update your current domain in `CORS_ALLOWED_ORIGINS` env variable. Can you please try this out?

It was set to http://localhost. Now it work like a charm! Thank you

**Comment by srinivaspendem** [comment]
Closing this, thanks for letting us know
