### ISSUE TITLE
[feature]: Enable special notification for direct mentions

### ISSUE THREAD

**Issue by mariliatostesdev** [makeplane/plane#4590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Enabling a different kind of notification for when a user is mentioned directly.

### Why should this be worked on?

This is specially useful in larger projects and/or when handling multiple projects at the same time.

Sometimes there is a large number of notifications and it would be very useful to be able to differentiate which notifications are most important (direct messages/mentions tend to be more urgent/of a priority)

**Comment by gchanchal** [comment]
Hi @mariliatostesdev , this is noted and we will bring it in. It makes sense

**Comment by vihar** [comment]
Thanks for the feature request, @mariliatostesdev! This feature has been shipped, and you can now view mentions under Inbox. We’re also revamping our entire notification engine and will share updates on our Discord shortly.

![CleanShot 2024-09-18 at 06 23 26@2x](https://github.com/user-attachments/assets/7bf7d426-a6ef-4ba1-902d-87f07db32c6e)
