### ISSUE TITLE
[feature]: Ordering projects inside projects dashboard

### ISSUE THREAD

**Issue by mariliatostesdev** [makeplane/plane#4593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Right now, when someone makes a new project, that goes automatically right to the bottom. The favorite/pinning feature would somehow fix that, but it would be great to not have to pin every project for it to appear on top.

To fix that, maybe we could have folders/stacks to contain all projects related to the same topic or the same department. (A folder for websites, a folder for our members journeys, a folder just for Project Management, etc).

Or maybe that could be made by adding a label feature to projects, so the user can filter on the basis of labels.

### Why should this be worked on?

This is essential for managing multiple projects and prioritizing key projects over others.

**Comment by srinivaspendem** [comment]
Hello @mariliatostesdev currently you should be able to rearrange projects as you like with the drag indicator we have. You need not use the favorite/pinning feature in this case.

**Comment by mariliatostesdev** [comment]
Thank you for your update, @srinivaspendem :)

However, I don't think that works. Let me know if I should be doing something different.

This is what happens when I try to drag projects:

![image](https://github.com/makeplane/plane/assets/133540781/5f07c6df-0bcb-4e77-8f1b-e030d7816190)

https://github.com/makeplane/plane/assets/133540781/9077569e-6e09-4ba8-9e33-a501e5ef8ed2

**Comment by srinivaspendem** [comment]
Hello @mariliatostesdev, you should see the drag handles on the left menu which help you re-arrange your projects. Please find the link to video attached showing the functionality. https://www.loom.com/share/38584dc5d471413baf608e2b7664ffce

**Comment by srinivaspendem** [comment]
No, you cannot re-arrange projects you haven't joined.

**Comment by gchanchal** [comment]
Hi @mariliatostesdev , we can bring in Labels for Projects, which will allow quick sorting and filtering
