### ISSUE TITLE
[feature]: Hability yo choose first day of week

### ISSUE THREAD

**Issue by emmgfx** [makeplane/plane#4600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It's necessary that users could choose the first day of week. 

### Why should this be worked on?

For a person which his first day of week is Monday, having it on the second position turns the UI very confusing. Actually, I put wrong dates on some tasks because of this.

**Comment by srinivaspendem** [comment]
Closing as duplicate of #4270
