### ISSUE TITLE
[feature]: Including an author field that is automatically populated when creating new pages

### ISSUE THREAD

**Issue by adamolnar** [makeplane/plane#4618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When creating new Pages: apart from Title and Privat and Public option, is needed an author field, and for it to be automatically populated so it is clear who made it. 

### Why should this be worked on?

Including an author field that is automatically populated when creating new pages is essential for several reasons:

1. **Accountability and Transparency**: Having a clear record of who created each page promotes accountability. It allows others to know who to contact for questions, updates, or feedback regarding the content. This transparency can improve trust within the organization or among users.

2. **Content Management**: In environments where multiple people contribute to content creation, knowing the author helps in managing and organizing content effectively. It makes it easier to track contributions, identify content owners, and manage permissions and responsibilities.

3. **Collaboration**: Automatically populating the author field fosters better collaboration. Team members can easily see who is responsible for specific pages, facilitating communication and coordination. This is particularly useful in projects requiring multiple contributors.

4. **Historical Record**: The author field provides a historical record of content creation. This can be important for auditing purposes, tracking changes over time, and understanding the evolution of content. It ensures that the origin of information is documented.

5. **Recognition and Attribution**: Giving proper credit to the content creators acknowledges their efforts and contributions. This can be motivating for authors and encourages high-quality content creation, as individuals are recognized for their work.

6. **User Experience**: For end-users or readers, knowing the author can add credibility to the content. It can also provide context, as understanding who wrote the content can sometimes help in interpreting it better.

By including an author field that is automatically populated, the system ensures that all these benefits are consistently realized without relying on manual entry, thereby enhancing efficiency and accuracy.

**Comment by aaryan610** [comment]
Hey @adamolnar, you can always see the author(creator) of a page by hovering over the last edited status. Let me know if this isn't what you meant by author.

https://github.com/user-attachments/assets/a1e5daf0-fd7e-4852-85ec-82d6effdbe45
