### ISSUE TITLE
[feature]: Pages revision history

### ISSUE THREAD

**Issue by adamolnar** [makeplane/plane#4619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A detailed record of all changes made to the page, including edits, deletions, and additions.

### Why should this be worked on?

- By implementing a robust revision history feature, users can enhance content management, collaboration, and overall document control.
- Accident Recovery: Easily recover lost or accidentally deleted information by reverting to previous versions.
- Accountability: Keep track of who made changes, ensuring transparency and responsibility among contributors.
- Collaboration: Facilitate collaborative work by allowing team members to see each other’s contributions and the evolution of the content.
- Audit Trail: Maintain a complete audit trail for compliance, quality control, or historical reference.
- Content Integrity: Ensure the integrity of the content by providing a clear history of modifications, helping to prevent unauthorized or harmful changes.
- Change Tracking: Monitor the development and changes in the content over time, aiding in project management and content strategy.

**Comment by aaryan610** [comment]
Hey @adamolnar, version history for pages was recently released, let us know how much you love it.
