### ISSUE TITLE
[bug]: Plane API: issues belonging to several modules are duplicated when fetching project issues.

### ISSUE THREAD

**Issue by Zebnastien** [makeplane/plane#4629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I fetch https://api.plane.so/api/v1/workspaces/{slug}/projects/{project_id}/issues...
...issues that belongs to several module are duplicated a corresponding time to modules count.

### Steps to reproduce

1) Create three modules
2) Create an issue
3) Assign the issue to all three modules
4) Fetch issues with plane API
=> Same issue appears 3 times.

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

v0.19.0-dev

**Comment by srinivaspendem** [comment]
Hi @Zebnastien,
Could you let me know what sorting method you are using? Additionally, if you are using sub-grouping, could you provide the details? This will help us understand the issue you're facing.

**Comment by sriramveeraghanta** [comment]
We have identified the issue, which is due to a recent change we made that allows issues to be attached to multiple modules. Thank you for pinpointing the problem. @pablohashescobar  is currently working on a fix, and we will include these changes in the next release.
