### ISSUE TITLE
[bug]: docker-entrypoint-migrator.sh & docker-entrypoint-beat.sh loss execute privilege in linux

### ISSUE THREAD

**Issue by xiaobaiwcc** [makeplane/plane#4630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I do docker compose in linux，I got such error:
[+] Running 13/15
 ✔ Network plane-master_dev_env          Created                                                    0.1s 
 ✔ Volume "plane-master_redisdata"       Created                                                    0.0s 
 ✔ Volume "plane-master_pgdata"          Created                                                    0.0s 
 ✔ Volume "plane-master_uploads"         Created                                                    0.0s 
 ✔ Container plane-master-plane-minio-1  Started                                                   23.8s 
 ✔ Container plane-master-plane-db-1     Started                                                   23.8s 
 ✔ Container plane-master-plane-redis-1  Started                                                   23.8s 
 ⠏ Container plane-master-migrator-1     Starting                                                  24.6s 
 ✔ Container plane-master-api-1          Started                                                   24.1s 
 ✔ Container plane-master-worker-1       Started                                                   24.5s 
 ⠦ Container plane-master-beat-worker-1  Starting                                                  24.6s 
 ✔ Container plane-master-web-1          Created                                                   11.3s 
 ✔ Container plane-master-space-1        Created                                                   12.1s 
 ✔ Container plane-master-admin-1        Created                                                   12.1s 
 ✔ Container plane-master-proxy-1        Created                                                    0.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/docker-entrypoint-migrator.sh": permission denied: unknown

I find that /apiserver/bin/docker-entrypoint-migrator.sh & /apiserver/bin/docker-entrypoint-beat.sh don't have execute privilege

### Steps to reproduce

1. ./setup.sh
2. docker compose -f docker-compose-local.yml up -d

### Environment

Production

### Browser

Google Chrome

### Variant

Local

### Version

master

**Comment by almereyda** [comment]
An example fix has been provided with 49fefd1ced23211ab9c0dc9d28d641908c0d0a88

**Comment by pablohashescobar** [comment]
closing the issue as the fix has been already pushed.
