### ISSUE TITLE
[bug]: Cannot open some issues in full screen after migrating to Plane v0.20 with Plane One Enterprise Edition

### ISSUE THREAD

**Issue by marcungeschikts** [makeplane/plane#4632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

---

After migrating to Plane v0.20 with Plane One Enterprise Edition, we have some tickets that we cannot open in full screen, receiving the error message "**Issue does not exist**".
![image](https://github.com/makeplane/plane/assets/74183327/ee72f6ea-cd4d-40bc-b26a-6f1997509a2f)

- These are mainly old tickets (3-4 months), although some of the old tickets have been migrated correctly.
- We can see the tickets in the list and on the right sidebar.
- These tickets no longer display any activities.

---

### Steps to reproduce

After migrating to Plane v0.20 with Plane One Enterprise Edition
1. Click on a ticket name to see it on the right sidebar
2. If there are no activities displayed, click on the top left "open issue fullscreen"
3. Then you should see the error message "**Issue does not exist**".

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.20 Plane One Entreprise Editon

**Comment by vihar** [comment]
@marcungeschikts, we moved this thread to a different channel, closing this here.
