### ISSUE TITLE
[bug]: Why can't I add a to do to an issue that I didn't create? I'm an admin and need this functionality to use plane effectively

### ISSUE THREAD

**Issue by t-verry** [makeplane/plane#4645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Why can't I add a to do to an issue that I didn't create? I'm an admin and need this functionality to use plane effectively

### Steps to reproduce

1. have a member else create an issue 
2. member adds a to-do to issue 
3. an admin tries to add another to-do and can't 

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v

**Comment by pushya22** [comment]
Hi @t-verry this issue now resolved
