### ISSUE TITLE
[bug]: "CSRF Verification Failed" error on login form using email with 1Password password manager

### ISSUE THREAD

**Issue by ChandeepKhosa** [makeplane/plane#4660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I login using the email method and let my password manager, 1Password, auto-fill my credentials, I get taken to the https://api.plane.so/auth/sign-in/ URL. 

"CSRF Verification Failed
It looks like your form submission has expired or there was a problem with your request.

Please try the following:

Refresh the page and try submitting the form again.
Ensure that cookies are enabled in your browser."

Usually I would do the same and successfully be able to login. This issue started approximately 1.5 weeks ago when 0.20 was released, which has some security changes as part of it.

I am able to successfully login if I don't use the password manager, but copy my username & password from it and manually paste each into the login fields.

For your reference, before this, I tried deleting cookies, cached images & files, auto-fill form data, and checked that allow third-party cookies was enabled in my Chrome settings, but none of that made a difference and was fine.

### Steps to reproduce

1. Go to Plane login page
2. click in username field and the 1Password app offers to auto-fill your credentials
3. Login
![Screenshot 2024-05-30 at 16 27 57](https://github.com/makeplane/plane/assets/705104/030b2132-e077-40a4-99c8-e110c349b876)

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v0.20

**Comment by pushya22** [comment]
HI @ChandeepKhosa we tried  multiple ways to recreate the issue but we were successfully able to log-in using 1-password. Could you please try sharing screen recording with network tab open.

**Comment by pushya22** [comment]
Closing this issue, please re-open if issue is not resolved

**Comment by ChandeepKhosa** [comment]
The video as requested https://drive.google.com/file/d/1DGmTmSTtkeGrI5jDO5Rvhvq-bwnNoMBu/view?usp=sharing
If you can't replicate, perhaps have a look if my account was restricted at some point after the first unsuccessful login for me please.

**Comment by candcdev** [comment]
I get the same issue with the latest version on a self hosted implementation (private GKE, helm chart known plane.so version asI cannot get past the login screen) and I see this in the logs for api:

```
INFO 2024-06-13 15:10:04,461 log 26 134766532070200 Forbidden (Origin checking failed - https://my.domain.private does not match any trusted origins.): /auth/sign-in/
```

in your case your third party tool may be messing with the trusted origin?

**Comment by candcdev** [comment]
@pablohashescobar I was missing `ingress.appHost` in my Helm deployment and now it works.

**Comment by loonglade** [comment]
It is also happening for me. Tried with 3 different browsers (Mullvad (firefox), Decentr (chromium) and Safari)
-I tried copy/pasting a password from keepass with numbers, letters and symbols.
-I also tried typing a simple password that meets the requirements

All efforts lead to the same message box that @ChandeepKhosa is also getting.

**Comment by ChandeepKhosa** [comment]
Update: I'm still having the same issue with the latest version of Cloud

**Comment by Bloodis94** [comment]
I'm too having the same issue with 1password when accessing from my domain. When doing the login via local ip (192.168.ecc) it works without problems.

**Comment by spreeni** [comment]
@pushya22 I am experiencing the same issue with 1password from our own deployment. Could it be a race condition, where `get-csrf-token/` does not complete before the call to `sign-in/`? I am only having the issue with the Autofill, not if I fill the login form slowlier manually.

**Comment by avimedi** [comment]
Same issue here. Since yesterday the api container service was not coming up. Today it started but get the same error as mentioned. All I did was select update from the menu.

**Comment by alex-whitney** [comment]
> @pushya22 I am experiencing the same issue with 1password from our own deployment. Could it be a race condition, where `get-csrf-token/` does not complete before the call to `sign-in/`? I am only having the issue with the Autofill, not if I fill the login form slowlier manually.

I agree -- disabling "log in automatically" avoids this problem for me on my self-hosted deployment as well.

**Comment by spmp** [comment]
FYI for plane self hosted, I have added listening to HTTPS to the `nginx.conf.template`, including certs and all on IP, so I can access via local IP on HTTPS and HTTP, and on my external IP on HTTPS, so I had to add all three origins as:
```
CORS_ALLOWED_ORIGINS=https://123.456.789.1122:443,https://192.168.1.x:443,http://192.168.1.x:12345,https://localhost:443,http://localhost:12345
```
Where `12345` is the `NGINX_PORT`

Note that the config file is parsed as:
```python
cors_origins_raw = os.environ.get("CORS_ALLOWED_ORIGINS", "")
# filter out empty strings
cors_allowed_origins = [
    origin.strip() for origin in cors_origins_raw.split(",") if origin.strip()
]
```
So no quotations and def. no list parenthesis. i.e `[orig1,orig2]` will not work, maybe fix this some time dev team 8)

**Comment by leandrogrupozani** [comment]
Great Solution I found:

Just configure your plane.conf at /etc/apache2/sites-available/

<VirtualHost *:80>
    ServerName yourdomain.com
    Redirect permanent / https:/yourdomain.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName plane.grupozani.com.br

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/yourdomain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/yourdomain.com/privkey.pem

    # API  
    ProxyPass /api http://localhost:8000/api
    ProxyPassReverse /api http://localhost:8000/api
    
    #auth
    ProxyPass /auth/get-csrf-token http://localhost:8000/auth/get-csrf-token
    ProxyPassReverse /auth/get-csrf-token http://localhost:8000/auth/get-csrf-token/
    
    # Admin
    ProxyPass /god-mode http://localhost:4001/god-mode
    ProxyPassReverse /god-mode http://localhost:4001/god-mode

    # Spaces
    ProxyPass /spaces http://localhost:4002/spaces
    ProxyPassReverse /spaces http://localhost:4002/spaces

    # Frontend – vem por último
    ProxyPass / http://localhost:4000/
    ProxyPassReverse / http://localhost:4000/

    # Headers e segurança
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "plane.grupozani.com.br"
    RequestHeader set Host "plane.grupozani.com.br"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always edit Set-Cookie "(?i)^((?!;\s?SameSite).*)$" "$1; HttpOnly; Secure; SameSite=Lax"
    ProxyTimeout 300
    Timeout 300

    ErrorLog ${APACHE_LOG_DIR}/plane_error.log
    CustomLog ${APACHE_LOG_DIR}/plane_access.log combined
</VirtualHost>

**Comment by leandrogrupozani** [comment]
Great Solution I found:

Just configure your plane.conf at /etc/apache2/sites-available/

`<VirtualHost *:80>
    ServerName yourdomain.com
    Redirect permanent / https:/yourdomain.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName plane.grupozani.com.br

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/yourdomain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/yourdomain.com/privkey.pem

    # API  
    ProxyPass /api http://localhost:8000/api
    ProxyPassReverse /api http://localhost:8000/api
    
    #auth
    ProxyPass /auth/get-csrf-token http://localhost:8000/auth/get-csrf-token
    ProxyPassReverse /auth/get-csrf-token http://localhost:8000/auth/get-csrf-token/
    
    # Admin
    ProxyPass /god-mode http://localhost:4001/god-mode
    ProxyPassReverse /god-mode http://localhost:4001/god-mode

    # Spaces
    ProxyPass /spaces http://localhost:4002/spaces
    ProxyPassReverse /spaces http://localhost:4002/spaces

    # Frontend – vem por último
    ProxyPass / http://localhost:4000/
    ProxyPassReverse / http://localhost:4000/

    # Headers e segurança
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "plane.grupozani.com.br"
    RequestHeader set Host "plane.grupozani.com.br"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always edit Set-Cookie "(?i)^((?!;\s?SameSite).*)$" "$1; HttpOnly; Secure; SameSite=Lax"
    ProxyTimeout 300
    Timeout 300

    ErrorLog ${APACHE_LOG_DIR}/plane_error.log
    CustomLog ${APACHE_LOG_DIR}/plane_access.log combined
</VirtualHost>`
