### ISSUE TITLE
[bug]:can't login via email.  

### ISSUE THREAD

**Issue by rzy1204** [makeplane/plane#4680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I login via email, there is no response.

method: POST
url is http://xx/auth/email-check
status code: 404 Not Found

![image](https://github.com/makeplane/plane/assets/50787785/dff4e9cc-11d3-4ece-8512-82f678b37765)

### Steps to reproduce

1. hosting an instance
2. login via email, there is no response.

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

Recent versions

**Comment by sriramveeraghanta** [comment]
Can you verify the Nginx conf file you are using? `/auth` location might be missing there.

**Comment by rzy1204** [comment]
> Can you verify the Nginx conf file you are using? `/auth` location might be missing there.

I don't feel like it's involved, I use the following command to do:
helm upgrade \
  --set ingress.appHost="x" \
  --set postgres.local_setup=false \
  --set env.pgdb_remote_url="x" \
  --set redis.local_setup=false \
  --set env.remote_redis_url="x" \
  --set smtp.host="x" \
  --set smtp.user="x" \
  --set smtp.password="x" \
  --set smtp.from="x" \
  --set smtp.port=x \
  zbyte-plane makeplane/plane-ce \
  --version 1.0.18 \
  -n plane

**Comment by sriramveeraghanta** [comment]
It appears that you are using Kubernetes to deploy the Plane Community Edition. I am including @mguptahub in this conversation to help resolve your issues.

**Comment by mguptahub** [comment]
@rzy1204 You may want to check the updated helm chart at https://artifacthub.io/packages/helm/makeplane/plane-ce

**Comment by rzy1204** [comment]
> @rzy1204 You may want to check the updated helm chart at https://artifacthub.io/packages/helm/makeplane/plane-ce

I don't use SSL, so I don't understand why it does need to do email check.

**Comment by rzy1204** [comment]
The document  I am referring to


> It appears that you are using Kubernetes to deploy the Plane Community Edition. I am including @mguptahub in this conversation to help resolve your issues.

The document I am referring to https://docs.plane.so/self-hosting/methods/kubernetes

**Comment by jordibeen** [comment]
I ran into the same issue hosting Plane with a custom helm chart on Kubernetes, but it was fixed once I pointed any traffic coming in on `/auth` to the API deployment as well.

So, just make sure your reverse proxy (we use Traefik) points any traffic to `/auth` to the API, and you're golden.

**Comment by rzy1204** [comment]
> I ran into the same issue hosting Plane with a custom helm chart on Kubernetes, but it was fixed once I pointed any traffic coming in on `/auth` to the API deployment as well.
> 
> So, just make sure your reverse proxy (we use Traefik) points any traffic to `/auth` to the API, and you're golden.

I tried it, but it didn't achieve the expected effect.
points any traffic to `/auth` to the API, can you provide a demo?

like this?
 /auth/email-check/  ——>  /api/email-check/

**Comment by tomerh2001** [comment]
For anyone encountering this, there's a table mapping the services to their paths:
<img width="672" alt="image" src="https://github.com/user-attachments/assets/131ed948-51b3-4df7-a911-6093b82d8525">
