### ISSUE TITLE
[bug]: Copying multiline code does not work

### ISSUE THREAD

**Issue by j3mu5** [makeplane/plane#4722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When formatting a multi-line code field, a copy button is displayed - this is a useful function that I would like to use. However, the code is not copied to the clipboard after clicking on the copy button (Google Chrome, Windows 10). After clicking on the copy button, the content of the code field should be copied. 

Additional idea: Ideally, this should also work for single-line code.

![image](https://github.com/makeplane/plane/assets/50756558/d562ff44-44ad-40e6-9e1f-8ceab53514ff)

### Steps to reproduce

1. Type multinie Text
2. Format as code
3. Klick on Copy Button
4. Try to paste somewhere elese (plane, Notepad, ...)

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.21.0

**Comment by codewithjk** [comment]
needs explanation  ;  which input field your talking about?

**Comment by aaryan610** [comment]
Hey @j3mu5, as you already mentioned, this issue has already been fixed. Thanks for reporting it, let us know if you find anymore.
