### ISSUE TITLE
[feature]: Click on project title in sidebar should open specific feature directly

### ISSUE THREAD

**Issue by j3mu5** [makeplane/plane#4737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

If you click on the project title in the left navigation, the possible features (Cycles, Modules, ...) currently open. For some projects, however, a specific feature is mostly desired, so that the optimal behaviour would be the direct opening of a feature. 

Suggestion: Provide an option for each project, which behaviour occurs when clicking on the project title in the left navigation (eg HomeAssistant as shown below): Expanding the list with features, issues and settings (current behaviour) or directly opening  issue view or one specific feature directly (issue or feature could be selected from a select list in the settings).

![image](https://github.com/makeplane/plane/assets/50756558/4cd17f7d-8f7f-4f8a-9b91-9dac0d6ed7f6)

### Why should this be worked on?

The ability to open the issue view directly, for example, saves one click and therefore increases efficiency and satisfaction.

**Comment by pushya22** [comment]
Hi @j3mu5 now clicking on the project name will redirect to issues  list page
