### ISSUE TITLE
[bug]: Ctrl+Enter to create new line in comments

### ISSUE THREAD

**Issue by mathaimon** [makeplane/plane#4772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Unable to create a new line in issue comments by pressing the `ctrl`+`enter` key, the shortcut creates a new line and publishes the comment instantly. I expect the `enter` key to publish the comment and `ctrl`+`enter` to create a new line.

https://github.com/makeplane/plane/assets/64730205/36f9c48b-13ca-4cca-8e49-8b688c670507

### Steps to reproduce

1. Open any issue
2. Type a comment
3. Press `ctrl`+`enter` to create new line in comments

### Environment

Production

### Browser

Other

### Variant

Cloud

### Version

v0.21.0

**Comment by sriramveeraghanta** [comment]
Hello @mathaimon, 

Currently, the comment editor supports `Shift+Enter` to add a new line. We have identified that `Ctrl+Enter` also adds a new line but submits the comment. We will fix this in our next release. Thank you for pointing this out.

**Comment by pushya22** [comment]
[This](https://github.com/makeplane/plane/pull/4986) PR has fixed this issue. Currently our editor support
shift+enter -> new line
cmd/ctrl+enter -> new line
enter -> submit

We have taken your suggestion into consideration and will try to come up with solution that helps all use cases.

**Comment by tcatlas** [comment]
I agree it should be more like:

shift+enter -> new line
cmd/ctrl+enter -> submit
enter -> new line (alternatively, enter should definitely not submit while working with certain formatted text, like bullets, and instead do a new bullet or a new row in a table, etc).

I've never personally encountered where cmd/ctrl+enter is a new line, it has always been a submit, so this change is quite odd to me.
