### ISSUE TITLE
[feature]: Add resizable columns to spreadsheet views

### ISSUE THREAD

**Issue by JS00001** [makeplane/plane#4809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

These columns should be resizable so two columns don't take up the entire screen real estate
![image](https://github.com/makeplane/plane/assets/49812749/f6d1ffbe-1967-4718-a5e6-e93b73a7d5e7)

### Why should this be worked on?

This is a pretty bad user experience, I understand the "Description" of the issue taking up a lot of space, but the 'State' should be resizable, or at least NOT take up half of the page when its a 10 char field. Thanks!

**Comment by pushya22** [comment]
Hi @JS00001 Thanks for bringing this to our notice it will be fixed in our upcoming release

**Comment by prateekshourya29** [comment]
Hey @JS00001, We've temporarily added a max width limit to the state column (refer #4859). Resizable spreadsheet layout coming soon!
