### ISSUE TITLE
[bug]: issue titles are not bold in light theme

### ISSUE THREAD

**Issue by jhdcruz** [makeplane/plane#4814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using dark theme, the issue title are bold and are easier to read.
Using light theme on the other hand, issue titles uses the same font weight with other texts.

| Dark Theme | Light Theme |
|------------|-------------|
| ![image](https://github.com/makeplane/plane/assets/28413338/7da9d0d8-2ed7-4091-90b3-9711e27ec598) | ![image](https://github.com/makeplane/plane/assets/28413338/785f4c44-2792-45ac-8f4a-955724e1fb6d) | 

### Steps to reproduce

1. Create a sample issue
2. Change interface theme using `Mod + K`.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v0.21.0

**Comment by pushya22** [comment]
Hi @jhdcruz we have made this consistent accorss the platform
