### ISSUE TITLE
[bug]: Can't visit /god-mode after upgrading from v0.19-dev to v0.21-dev

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#4865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I can't visit `/god-mode` anymore, after upgrading from `v0.19-dev` to `v0.21-dev`.
The `/god-mode` url says "Workspace not found". The button is also missing from my profile.

Because I am unable to visit /god-mode by starting on the newest version at all (#4864), I am unable to say if this occurs on upgrade only or if god mode is just completely broken on v21.

### Steps to reproduce

1. Create a new plane v19 instance.
2. Setup a user.
3. Upgrade to v21. 
4. Visit `/god-mode`.

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

stable (v0.21-dev)

**Comment by Quadrubo** [comment]
This was caused by my reverse proxy missing the new service.
However the button to visit `/god-mode` on the profile is still missing.
Did this move somewhere else?

This can be closed afterwards.

**Comment by ChenE2000** [comment]
> This was caused by my reverse proxy missing the new service. However the button to visit `/god-mode` on the profile is still missing. Did this move somewhere else?
> 
> This can be closed afterwards.

I encountered the same issue, the /god-mode url says "Workspace not found". Would you please share the way to solve this problem? Thanks so much. I might configure nginx the wrong way.

**Comment by Quadrubo** [comment]
@ChenE2000 have a look at the nginx config plane uses and adapt it to your setup.
https://github.com/makeplane/plane/blob/preview/nginx/nginx.conf.template

I am using traefik so I had to add these endpoints to my labels.
