### ISSUE TITLE
[bug]: Unexpected carret position change during edition (auto-save)

### ISSUE THREAD

**Issue by mm-edtake** [makeplane/plane#4907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While editing a rich field (issue or document), the auto-save process strip content and change the carret position.
This imply a really bad experience because you can't write an issue without stopping everytime to add spaces and so on.

https://github.com/makeplane/plane/assets/99755384/7a4f4cc0-5210-46c9-b7c5-ce922ef89509

### Steps to reproduce

1. edit an existing issue
2. write a space or new line
3. wait for 2s

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.21.0-dev

**Comment by Palanikannan1437** [comment]
Hey @mm-edtake, this issue has been fixed in https://github.com/makeplane/plane/pull/4700 and will be reflected in the upcoming release 🙌
