### ISSUE TITLE
[bug]: Kanban List and Login

### ISSUE THREAD

**Issue by Teresio** [makeplane/plane#4909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I select the Kanban layout and the page returns to the Layout list.

Furthermore, if I go to the login page, enter the email (teresio.sanfer@gmail.com) and click continue, nothing happens.

### Steps to reproduce

1. Login page - put e-mail teresio.sanfer@gmail.com. Clique continue. Nothing happens.
2. Open a project link, click a List Kanban, page return to List Layout.

### Environment

Production

### Browser

Google Chrome

### Variant

Local

### Version

site 23/06/2024

**Comment by vihar** [comment]
@Teresio, we are unable to reproduce this issue. Can you brief us more on the issue?

**Comment by pushya22** [comment]
@Teresio you should not be this facing but please re-open incase of the issue persists.
