### ISSUE TITLE
[bug]: Adding an issue does not update the UI

### ISSUE THREAD

**Issue by JS00001** [makeplane/plane#4925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Issue: Adding an issue does not live-update, you have to refresh the page
Expected: it gets added once the request is made, or even optomistically

### Steps to reproduce

Add an issue, see that it does not instantly show up on the screen/table. You have to refresh the page

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

Current

**Comment by pushya22** [comment]
Hi @JS00001 it seems to be working as intended at our end, could you specify if you are facing this issue in any specific layout or with any group/sub-group enabled in the display properties or filters applied

**Comment by pushya22** [comment]
hi @JS00001 please reopen the this if the issue still persists

**Comment by StreamlinedStartup** [comment]
Noticed this too in self-hosted. When adding a task via API the UI doesn't update and requires a refresh of the page.
