### ISSUE TITLE
[bug]: Dashboard collaboration card responsiveness issue

### ISSUE THREAD

**Issue by undefined-dev74** [makeplane/plane#4937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Collaboration input is overflow in when you open it in chrome mobile
![Screenshot_20240625_232344_Chrome](https://github.com/makeplane/plane/assets/45736218/74ee30b7-dfba-47cf-a2d0-f484e4ff6666)

### Steps to reproduce

Login into plane
Go to Home
Scroll down and see the collaboration section

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v0.17.0 prod

**Comment by dByler1** [comment]
Hi, I thought I would pick this one up if that's ok. I took the liberty to create a sketch of what I think the responsive view should look like. 

![Plane - Collaborators Responsive](https://github.com/makeplane/plane/assets/24251117/0708b9a5-984e-4166-a41f-9014738fad47)

**Comment by dByler1** [comment]
here is a pr for the issue: https://github.com/makeplane/plane/pull/4958
