### ISSUE TITLE
[bug]: Missing "Created by" and "Assignee" fields in exported file (CSV, Excel)

### ISSUE THREAD

**Issue by bennyocw** [makeplane/plane#4948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I export as csv or excel and I open the exported file, the values under column headers "Assignee" and "Created by" are empty. I should see the assignees and created by for each ticket created.

### Steps to reproduce

1. Go to Settings under workspace
2. Click on 'CSV' under exports
3. Download
4. Open downloaded csv

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

latest

**Comment by vihar** [comment]
@bennyocw, our export feature is still in the development stage. We will soon fix it and provide a robust experience with respect to export options. Also, curious why you are using exports—are you planning to migrate or taking data backups?
