### ISSUE TITLE
[bug]: Sub-Issues don't respect created order 

### ISSUE THREAD

**Issue by Plorenzo** [makeplane/plane#4967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you add sub-issues to a parent, I would expect (while custom order is not implemented) that the order is creation date. 

Currently, that is not the case, you add sub-issues and when you open the parent again, the order that they appear in is random.  

### Steps to reproduce

https://github.com/makeplane/plane/assets/4695692/5a0e4bc3-3371-447f-a80e-51ce783c3e11

Create parent task
open it and create sever sub-issues 
they look like they are nice and ordered by id which coincides by creation date
close parent task
open it again
sub-issues all messed up

### Environment

Deploy preview

### Browser

Safari

### Variant

Self-hosted

### Version

v0.21.0

**Comment by vihar** [comment]
Thanks for flagging this, @Plorenzo. I understand that ordering by created time would be easier for users in some use cases. Apart from this, do you think having filters under sub-issues makes sense? Just trying to think out loud to see if we can improve the experience. For now, we’ll try to show these sub-issues ordered by created time.

**Comment by Plorenzo** [comment]
What I would like ideally, is to sort them manually and that they keep the order. I think adding as many sorting options as the board column may be overkill, but at least manual and creation date, should be there. 

The second best thing is sorted by creation date because I can control

**Comment by vihar** [comment]
Thanks for the feedback, @Plorenzo. We will address this in the next release.

Solution:
• We will fix the sorting issue by setting the default to created_date.
• Later, we will explore options for issue states (e.g., completed sub-issues could be placed at the end, regardless of the created date).
