### ISSUE TITLE
[bug]: Api calls return 401 when called from different domains, despite domain added to .env

### ISSUE THREAD

**Issue by Plorenzo** [makeplane/plane#4969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to create issues via api in plane from my website. Despite adding my domain to `CORS_ALLOWED_ORIGINS=`  in .env file and restarting the services. The api returns 401. 

### Steps to reproduce

Use snippet from docs 
```
const options = {
  method: 'POST',
  headers: {
    'x-api-key': 'plane_api_my_api',
    'Content-Type': 'application/json'
  },
  body: '{"issue":{"name":"test"}}'
};

fetch('https://api.plane.so/api/v1/workspaces/{slug}/projects/{project_id}/inbox-issues/', options)
  .then(response => response.json())
  .then(response => console.log(response))
  .catch(err => console.error(err));
```

get 401 despite having a correct api key. 

It also happens when trying with curl. If I add CORS_ALLOWED_ORIGINS='*' the service restart fails with some django error. 

### Environment

Production

### Browser

Safari

### Variant

Local

### Version

v0.21.0

**Comment by pablohashescobar** [comment]
Hi @Plorenzo, thanks for reporting this issue. This has been already reported in #4928. The fix has been also created in #4929. 

Closing this issue as duplicate.
