### ISSUE TITLE
[bug]: Import settings not visible

### ISSUE THREAD

**Issue by chillpert** [makeplane/plane#4982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I navigate to my workspace settings (as instance admin), I cannot see the import button. The export button is visible however.

### Steps to reproduce

1. Set up fresh instance (Docker approach)
2. Create admin account
3. Create workspace
4. Go to workspace settings

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.21.0-dev

**Comment by chillpert** [comment]
Turns out, the import settings are still available if navigating to them via the URL. The button is simply missing.

**Comment by pushya22** [comment]
Hi @chillpert we are not supporting imports for self hosted version at this juncture.

**Comment by chillpert** [comment]
> Hi @chillpert we are not supporting imports for self hosted version at this juncture.

I understand. Perhaps consider removing 'Importers' from the community edition (self-hosted) on https://plane.so/pricing.
