### ISSUE TITLE
[bug]: Cannot export 

### ISSUE THREAD

**Issue by bettercoffee99** [makeplane/plane#5024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I got this problem when downloading from export on the self-hosted plane, I tried to backup and restore my data to the latest version plane, and got this error.
<img width="1440" alt="image" src="https://github.com/makeplane/plane/assets/79611746/3a4087e5-c4e0-4fea-adf9-19cb0c365d13">

### Steps to reproduce

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>84634677-4a39-4a82-9c59-26a2a4cd231c/export-busanid-7b3ad2-2024-07-03 06:17:01.904017+00:00.zip</Key>
<BucketName>uploads</BucketName>
<Resource>/uploads/84634677-4a39-4a82-9c59-26a2a4cd231c/export-busanid-7b3ad2-2024-07-03 06:17:01.904017+00:00.zip</Resource>
<RequestId>17DEA26916B22E84</RequestId>
<HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId>
</Error>

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

master

**Comment by pablohashescobar** [comment]
@bettercoffee99, this issue has been already pointed out and has been fixed in PR #4777. 

The fix would be available in the upcoming release.

**Comment by bettercoffee99** [comment]
@pablohashescobar wow, thanks. So I'm just waiting for the latest release right?

**Comment by pablohashescobar** [comment]
Yes @bettercoffee99, let us know if you are still facing the same issue.

**Comment by metalMajor** [comment]
Hello, I have the same issue, and the workaround is to remove the whole part after ".zip" so the part starting with a "?". And then you can download it anyways.

**Comment by pushya22** [comment]
This Fix is now part of the lastest release v0.22. Please re-open if the issue still persists
