### ISSUE TITLE
[bug]: Can't type question mark on Mac

### ISSUE THREAD

**Issue by moigagoo** [makeplane/plane#5035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Typing a question mark on a Mac requires pressing Shift + forward slash, which invokes a shortcut in Plain.

### Steps to reproduce

1. Open an issue.
2. Start typing a comment.
3. Type a question mark.

### Environment

Production

### Browser

Safari

### Variant

Cloud

### Version

Latest

**Comment by pushya22** [comment]
Hi @moigagoo this issue is now resolved. Please let us know if the issue still persists at your end.
