### ISSUE TITLE
[bug]: minimized kanban columns keep re-opening

### ISSUE THREAD

**Issue by axelrindle** [makeplane/plane#5048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We habe a kanban where i like to minimize the last columns as they're usually empty, like in the following image:

![Bildschirmfoto vom 2024-07-04 18-23-48](https://github.com/makeplane/plane/assets/7105632/372e2fb5-b916-4868-8ecb-cecd78829af4)

After a couple of minutes they automagically maximize themselves again.

The columns should maintain their state until I decide to maximize or minimize it again.

### Steps to reproduce

1. Create Kanban board
2. Minimize a column
3. Wait

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.21.0

**Comment by pushya22** [comment]
Hi @axelrindle We've resolved this issue in our latest release. Could you please upgrade to version v0.22.

Please re-open if you are still facing the issue.
