### ISSUE TITLE
[feature]: Issue types property (Bug, User Story, Task, etc.)

### ISSUE THREAD

**Issue by mmospanenko** [makeplane/plane#5060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have no idea why, but this is the most confusing decision - why you don't have issue types like Bug, User Story, Tech Story, Epic, Task, etc.? :)

Yes, we can use labels for this, but then we don't have labels :)

This is very important functionality for any PM systems, will be great to have different workflows (stages) for each issue type, different templates, colors, integrations, etc.

OpenProject has cool customization by types, very useful and important basic functionality for any teams I believe

### Why should this be worked on?

1. Different workflows (stages)
Bug - more about QA and Dev (without design or UAT)
User Story - about business value, functionality
Task - just work, part of User Story for example
Feature Request - for BA, Designers

These types should be fully customizable

2. Different colors
Red for bugs :)

3. Templates for new issues
Predefined form will be great for Bug reports

4. Filtering for views
For example, we can see only product related types on some PO views, etc.

5. Integrations
Only particular type should be posted in updates channel.
Or for syncs with other systems where we have issue types - how to map it?

**Comment by pushya22** [comment]
Hi @mmospanenko, issue types are part of our feature raodmap and will coming to plane  pretty soon.

**Comment by ch-ar-vi** [comment]
Unfortunately not for the Community Edition ...
