### ISSUE TITLE
[bug]: Tapping on a notification in Notifications from mobile doesn't work

### ISSUE THREAD

**Issue by moigagoo** [makeplane/plane#5070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I tap on a notification in Notifications, the issue page doesn't open.

### Steps to reproduce

1. Open Plane on mobile.
2. Go to Notifications.
3. Tap on a notification.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

Latest

**Comment by vihar** [comment]
@moigagoo, thanks for reporting this issue, we've fixed this in #5074.
