### ISSUE TITLE
[bug]: Emails not sending with SMTP configurations (self-host)

### ISSUE THREAD

**Issue by ktw1016** [makeplane/plane#5114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm setting up self-hosted Plane with Kubernetes
My company has internal SMTP Relay and they provided me with host, port, and also told me email security is not necessary (no TLS/SSL required)
However, they said that they need to allow the sender's server address and port number. I took a guess that it would be plane-app-api service endpoint which is 10.163.67.228:8000. However my email is still not being sent. Are my configurations correct? 

I am getting code 400 bad request

It may be helpful to understand how Plane sends the email and where I can find more info on endpoint /api/instances/email-credentials-check/

### Steps to reproduce

1. Go to god-mode
2. Fill out host, port, sender email address, no email security, tried with/without authentication
3. Receiver email to be internal email address
4. Test email
5. Get code 400 bad request, "Could not send email. Please check your configuration"

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.22-dev

**Comment by ahen2305** [comment]
could anyone can pls share steps for fix this bug?
