### ISSUE TITLE
[feature]: Add full support for LDAP

### ISSUE THREAD

**Issue by fraenki** [makeplane/plane#5124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

*PLEASE NOTE:* The previous feature request was closed, although the feature is not implemented yet. Besides that a proper timeline for when this feature will be available was not provided. So before closing this issue again, I ask the Plane folks to communicate their strategy clearly to regain some trust.

LDAP should be fully supported in Plane:
* LDAP authentication
* nested LDAP groups
* restrict login to certain groups
* user/group synchronisation
* user state synchronisation (locked/not locked)

### Why should this be worked on?

LDAP support is especially useful for self-hosted setups and environments with increased security requirements.

LDAP support is one of the TOP 10 most requested features. Without proper support for LDAP, Plane cannot be considered a viable replacement for Jira.

Refs #916, #1296 and #1446.

**Comment by theparthacus** [comment]
per [this](https://github.com/makeplane/plane/issues/916#issuecomment-2219977836), @fraenki, i did say which tier LDAP will come to and likely when. it's a little misleading to say we offered neither. to respond to [this question from you](https://github.com/makeplane/plane/issues/916#issuecomment-2219977836), we close issues on the Community repo when a feature isn't coming to it. this is standard GitHub practice.

we don't use GtiHub anymore for ongoing discussions for paid features. for discussions about this and other paid features, [please use our Discord](https://discord.com/invite/A92xrEGCge).

**Comment by fraenki** [comment]
@theparthacus So you're doing it in the exact same way as Atlassian. I was expecting more from an "Open Source JIRA".

**Comment by theparthacus** [comment]
> @theparthacus So you're doing it in the exact same way as Atlassian. I was expecting more from an "Open Source JIRA".

exactly the same as Atlassian? no. not at all. it will be on the highest plan, but it will come bundled with other features on the plan, not in a separate product that's charged independently of the core product.

you are maybe confusing us with FOSS. we aren't that. we are commercial open source AKA COSS. we will continue to ship an open-source version of the product, but we will also ship paid versions of the software and depending on the size of the market, keep features on paid tiers or move them higher and lower as the case may be.

**Comment by fraenki** [comment]
The point is: the community suggests features, the feature request remains open for an extended period of time (everyone expecting that it will be implemented someday), there's even a PR implementing the feature which gets closed, and then out of sudden the feature is declared "premium". Sure, one _can_ do it this way. But more transparency and a clear roadmap would be required to really distinguish Plane from Atlassian.

Like I said, I was expecting too much. Nevermind.

**Comment by theparthacus** [comment]
you are bringing up something that [we have apologized for several times](https://github.com/makeplane/plane/pull/3341#issuecomment-1889086950). once again, we weren't sure just how much work the feature would be and how much it would cost us. that's the one SNAFU from us. since then, we have communicated exclusively what's coming to the Community Edition and what will be paid. as for a public roadmap, that's coming soon, too.

the call for transparency is legit and we are focusing on honoring it. we didn't mean to be less transparent. we just didn't know better. we learnt more when we looked through the implementation and worked with our Security consultants to unravel the net work on the feature.

we are sorry again to disappoint about this, but we are doing better now.

**Comment by centuryx476** [comment]
> > @theparthacus So you're doing it in the exact same way as Atlassian. I was expecting more from an "Open Source JIRA".
> 
> exactly the same as Atlassian? no. not at all. it will be on the highest plan, but it will come bundled with other features on the plan, not in a separate product that's charged independently of the core product.
> 
> you are maybe confusing us with FOSS. we aren't that. we are commercial open source AKA COSS. we will continue to ship an open-source version of the product, but we will also ship paid plans of the software and depending on the size of the market, keep features on paid tiers and move them higher and lower as the case may be.

I was looking for a good alternative that I can self-Host for my team that has LDAP support. But this "we are commercial open source AKA COSS" made that decision easy for this product. 
LDAP should be a given for self-host. Even gitlab self-host offers LDAP support out of the box...

**Comment by andreas-bulling** [comment]
Which software did you settle on instead in the end @centuryx476 ?
