### ISSUE TITLE
[feature]: Add font color & highlighters in pages.

### ISSUE THREAD

**Issue by itaaya** [makeplane/plane#5136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add font color palette & text highlights to the text to better visualize lengthy texts and document things more better. 

### Why should this be worked on?

When dealing with a large amount of text, readability can be challenging, making it hard to absorb all the information efficiently. To enhance comprehension, utilizing highlighters and font colors can significantly improve text segregation, making it visually distinct. This approach not only enhances the overall visual appeal but also facilitates a more effective skimming process, aiding in better data retention and understanding.

**Comment by vihar** [comment]
Thanks, @itaaya, for creating this feature request. Pages will be one of the core offerings on Plane, and we have an extensive roadmap for improving this feature. One of the enhancements we plan to support includes various formatting options like colors, highlights, fonts, columns, uploads, and more. We’ll be picking this up shortly. Meanwhile, your feedback or any bugs related to Pages will greatly help improve this feature.

**Comment by JMOCARRO** [comment]
The ability to track changes, show markup/comments would make it a powerful multiuser editing tool. Not sure if this is beyond the scope of what you had in mind as a roadmap.

**Comment by aaryan610** [comment]
We listened to you all, text color and highlighting will be added to Pages with #5653.

Check the demo here-

https://github.com/user-attachments/assets/058870e1-eb3f-49bb-bd64-979ee4a617d3
