### ISSUE TITLE
[bug]: "Toggle peek view layout" button setting does not stick 

### ISSUE THREAD

**Issue by jasonvanhattum** [makeplane/plane#5167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I select to toggle peek view layout, e.g. to Modal, I expect that setting to stay set for the next time I open an issue. Currently it reverts to side view.

### Steps to reproduce

[Self-hosted, Firefox latest]

1. Open peek view for an issue. 
2. Select toggle peek view layout. 
3. Set to Modal. 
4. Close peek view.
5. Open peek view for an issue. Expected result: Setting is modal. Actual result: Setting has reverted to sidebar.

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.22.0

**Comment by pushya22** [comment]
Hi @jasonvanhattum, Thank you for bringing this matter to our attention. After careful review, we can confirm that the behaviour you've noticed is actually part of the platform's current design. However, your feedback is extremely valuable to us and will consider your suggestion for future platform updates.

**Comment by jasonvanhattum** [comment]
Thanks. This defintely makes sense to me as something I can set as a global preference.

**Comment by pushya22** [comment]
Thanks @jasonvanhattum We've noted your request and will track it internally for future consideration. For now, we're closing this issue.
