### ISSUE TITLE
[bug]: Latest Preview release breaks detail issue view 

### ISSUE THREAD

**Issue by Plorenzo** [makeplane/plane#5178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

App crashes when trying to open a issue

`TypeError: undefined is not an object (evaluating 'this.getActivitiesByIssueId'`

### Steps to reproduce

https://github.com/user-attachments/assets/de744fba-2c63-4b2c-b982-9d52273cf2cd

### Environment

Production

### Browser

Safari

### Variant

Self-hosted

### Version

v0.22.0

**Comment by pushya22** [comment]
@Plorenzo, thanks for flagging this issue. We identified that it was present in our preview environment, and the issue has been resolved. Please pull from the master branch to deploy the stable version of Plane.
