### ISSUE TITLE
[bug]: docker-compose.yaml validation error

### ISSUE THREAD

**Issue by gauravagnihotristla** [makeplane/plane#5202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

fails to start 
validating /home/<USERID>/<path>/plane-selfhost/plane-app/docker-compose.yaml: services.worker.pull_policy services.worker.pull_policy must be one of the following: "always", "never", "if_not_present", "build", "missing"

Checking log file for Web and Space returns - service 'web'/'space' is not running

### Steps to reproduce

Following the installation method from `https://docs.plane.so/self-hosting/methods/docker-compose`

### Environment

Production

### Browser

Google Chrome

### Variant

Local

### Version

v0.22-dev

**Comment by ferdinandkeller** [comment]
I am getting the same bug. Removing `pull_policy` from every single line in the docker compose file seems to work as a temporary fix.

**Comment by pushya22** [comment]
Hi @ferdinandkeller. Thank you for your request. We're currently upgrading our external APIs and will aim to incorporate the relations as part of this feature enhancement.

**Comment by blackat** [comment]
Hello,
got the same issue with Docker Compose 2.29.0:
```yaml
# Not working
pull_policy: ${IMAGE_PULL_POLICY:-missing}

# Working
pull_policy: missing
```

**Comment by blackat** [comment]
Docker Compose version 2.29.1 seems solving the issue.
I have updated and values are correctly interpolated now.

**Comment by mguptahub** [comment]
this has been taken care in PR #5228

**Comment by mguptahub** [comment]
This has been resolved and released.
