### ISSUE TITLE
[feature]: Migrate projects into another workspace

### ISSUE THREAD

**Issue by nnh09290** [makeplane/plane#5214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be advantageous to be able to migrate a project into a different workspace.  As the workspace becomes heavily utilized re-organization sometimes makes sense.  

### Why should this be worked on?

here are a few reasons moving projects between workspaces might be appropriate:
The composition of a team working in plane can change, workspaces might be created as a logical way to organize teams
incomplete discovery - a project might be created and have details filled in before realizing it is more appropriate to have in another workspace

**Comment by MuhmdAjeer** [comment]
hey @vihar, i would like to work on this feature!

**Comment by vihar** [comment]
Duplicate of, #4866.

**Comment by gainggs** [comment]
@vihar - This has been marked as completed, but is it available as a feature yet? I can't find any documentation or posts about how to move projects between workspaces.

**Comment by Sleepful** [comment]
@gainggs https://github.com/makeplane/plane/issues/4866

**Comment by sipamungkas** [comment]
I am also curious about this feature, where can i found it
