### ISSUE TITLE
[bug]: when selecting first icon for the cycle view, tab closes :(

### ISSUE THREAD

**Issue by antoniusupov** [makeplane/plane#5294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When selecting icon for the cycle view, the whole tab closes

### Steps to reproduce

1. click on creating cycle view
2. choose icon for it
3. tab closes

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

latest

**Comment by pushya22** [comment]
hi @antoniusupov We attempted to recreate the issue on our end but were unsuccessful. Could you please provide us with screenshots or screen recordings of the problem? This will greatly aid us in debugging the issue.

**Comment by ShrootBuck** [comment]
Same thing happened to me but when I tried to reproduce it was fine. very weird bug

**Comment by ShrootBuck** [comment]
Managed to repro
https://github.com/user-attachments/assets/3c8bddd1-15ae-40b3-a07f-9a5d03dd11f1

**Comment by pushya22** [comment]
@ShrootBuck thanks for sharing, The issue appears to be intermittent. We'll aim to include a fix in our next release.

**Comment by pushya22** [comment]
@ShrootBuck This issue has been resolved in one of our latest releases. If you are still experiencing it, please feel free to reopen the issue.
