### ISSUE TITLE
[bug]: Incorrect `Project ID` tool tip example

### ISSUE THREAD

**Issue by nikkuexe** [makeplane/plane#5308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating a project, or checking the project's setting, the tool tip for the project id shows conflicting information. It uses the example "APP-123" as an example project ID, but states the max character limit is 5.

<img width="408" alt="image" src="https://github.com/user-attachments/assets/c436b095-dab5-48e8-a903-2446d76096f3">

Expected behavior for the example to adhere to the max character limit.

### Steps to reproduce

1. Go to a project and click on `Settings`
2. In General, find `Project ID` and hover over the tool tip icon.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

Latest

**Comment by sbaamoha** [comment]
i can fix that, just give it to me.
but what you want to change it ? either reduce the example characters or increase the max characters

**Comment by pushya22** [comment]
Hi @nikkuexe, Thanks for bringing this up,  we already have a fix in place and will be part of our next release.

**Comment by pushya22** [comment]
Hi @nikkuexe This issue is now resolved
