### ISSUE TITLE
[bug]: Unable to add links whose domain does not finish with .xxx to issue

### ISSUE THREAD

**Issue by Zebnastien** [makeplane/plane#5362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, if you try to add a link to an issue, you cannot use a link whose domain does not end in .xxx

![image](https://github.com/user-attachments/assets/9bd04bc0-0561-4adc-bff4-e77fcc0ff97c)
Result in...
![image](https://github.com/user-attachments/assets/9fa191b5-8696-4074-a4a9-7149269797c4)

For example, here are working and not working links :
🆗 http://google.com/...
🆗 http://google.uk/...
🆗 http://google.whatever/...
❌ http://google/...
❌ http://whatever/...

This is a problem for our dev env because our dev servers adresses are http://dev-x:port/dev/...

### Steps to reproduce

1) Go to whatever issue.
2) Click "add link" button.
3) Add a link whose domain does not finish with .xxx like "http://test/"
4) Notice the error message and no link creation.

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

v0.22.0-dev

**Comment by pushya22** [comment]
Hi @Zebnastien thanks for bringing this to our attention. We'll include a fix for this in our next release.

**Comment by aaryan610** [comment]
Hey @Zebnastien, new improvements to adding links have been made, you'll have a better experience with the next release.
