### ISSUE TITLE
[bug]: Comment is published to the wrong Intake issue 

### ISSUE THREAD

**Issue by moigagoo** [makeplane/plane#5365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I post a comment to an Intake issue, it is published to another seemingly random Intake issue, not the one opened.

This is extremely frustrating and basically makes Intake unusable.

### Steps to reproduce

1. Go to Intake.
2. Open issue.
3. Add a comment.

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

Latest

**Comment by pushya22** [comment]
Hi @moigagoo This issue is now resolved.
