### ISSUE TITLE
[bug]: Keeping page open overwrites changes from other team member

### ISSUE THREAD

**Issue by StefanFabian** [makeplane/plane#5370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I forget to close a page, and someone else modifies it, my open page will overwrite these changes at some point, and there is no way of restoring it.
In 2024, if not live collaboration, I expect it to merge changes or print a warning and not just overwrite.
Thank you for your work on this, we are using it to manage the tasks in our student team and we like it a lot.

### Steps to reproduce

1. Open Page
2. Have someone else open it, modify it and close it again
3. Still have the page open
4. Changes by the other person are overwritten

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

v0.22.0

**Comment by pushya22** [comment]
Hi @StefanFabian Thanks for reporting this issue—we're actively investigating it. It seems like this could be a rare edge case where the second user made changes and closed the page within the 10-second auto-save window. Rest assured, real-time pages are coming soon to Plane.

**Comment by StefanFabian** [comment]
Thank you for the quick reply!
Might also be relevant that I had put my PC to sleep and the page was still open when it resumed.

**Comment by pushya22** [comment]
Thanks for sharing @StefanFabian it will help us to debug better.

**Comment by aaryan610** [comment]
Hey @StefanFabian, we heard you. Lossless realtime collaboration will be made live with our upcoming release soon. It was recently merged with #5493.
