### ISSUE TITLE
[bug]: Intake issue's title is randomly overwritten by other issue's title

### ISSUE THREAD

**Issue by moigagoo** [makeplane/plane#5380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Our Intake issues' titles are randomly replaced with other issues' titles. Not only is this extremely annoying, but also leads to data loss as we're losing the original titles forever.

### Steps to reproduce

1. Create a bunch of issues in Intake.
2. Create a new one.

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

Latest

**Comment by pushya22** [comment]
Hi @moigagoo Thank you for reporting this issue. However, we are currently unable to recreate it on our end. We are continuing to investigate further, and it would be extremely helpful if you could share additional evidence, such as a screen recording.

**Comment by moigagoo** [comment]
@pushya22 it's extremely hard to reproduce consistently because it just happens from time to time. Like, an old issue would get updated out of the blue with another issue's title.

It feels like it could be related to another bug I reported earlier, the one regarding comments.

**Comment by moigagoo** [comment]
This just happened again but this time one issue's description overwrote another one's description. The original description was lost :-(

This is such a destructive bug.

**Comment by pushya22** [comment]
@moigagoo This is definitely concerning, we will look into this more seriously and resolve it at the earliest.

**Comment by lngsx** [comment]
This happened to me too, many times. I thought it was my fault at first. 

I can't reproduce it either, but it mostly happens just after I accept the intake issue to the project. One of the remaining intakes was replaced with content from the one that got accepted.

**Comment by moigagoo** [comment]
@pushya22 I think I know how to reproduce this.

The bug is caused by the fact that you catch keypresses on the page incorrectly. While I'm editing the issue text, I move my cursor with UP and DOWN arrows. By these keypresses are also caught and handled as MOVE UP and MOVE DOWN in the issue list.

So, if you press UP or DOWN while editing an issue, you'll switch to another issue, and the issue body will be replaced.

**Comment by pushya22** [comment]
@moigagoo this is really helpful we will fix it.

**Comment by pushya22** [comment]
@moigagoo Thank you for reporting the issue and sharing the reproduction steps. It has now been resolved.

**Comment by moigagoo** [comment]
@pushya22 when will it be deployed?

**Comment by pushya22** [comment]
Hi @moigagoo this is already deployed to cloud. Please hard refresh if issue still persists.

**Comment by moigagoo** [comment]
@pushya22 the problem seems to be fixed in Intake but it's still present in the issue list.

**Comment by Bilge** [comment]
I have this issue but in self-hosted. It is bizarre, because the option to rename the title of intake issues does not seem to exist, so I cannot even fix the title, now that it has been duplicated.
