### ISSUE TITLE
[feature]: don't strike through todo items which are done

### ISSUE THREAD

**Issue by robstoll** [makeplane/plane#5394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I still want to be able to see what was already done and striking the text through hinders readability

### Why should this be worked on?

Because we want the TODO feature to be as useable as possible.
Intuitively I would assume something which is stroke through was not done (skipped if you like)

**Comment by aaryan610** [comment]
Hey @robstoll, we listened to you, here's #5659 to remove the strikethrough decoration from checked todo list items. It'll be shipped soon. Let us know of more such improvements that can enhance your experience. Cheers 🥂
