### ISSUE TITLE
[bug]: Cannot resize pasted images

### ISSUE THREAD

**Issue by ari-party** [makeplane/plane#5397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I paste the following image in an issue:
![image](https://github.com/user-attachments/assets/f9a08788-8813-4208-9481-34bb03e661d0)
I am unable to resize the image.
![chrome_fKxhDRHX7y](https://github.com/user-attachments/assets/9ec3bfa5-6231-46ca-9a32-76ba8ba98193)

I'm using the cloud version but I'm unable to see the exact version. 
![chrome_lO5ATDAfxv](https://github.com/user-attachments/assets/a1cf8953-4935-4485-91bb-c54dd0d8cf61)

### Steps to reproduce

See above.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

Latest

**Comment by aaryan610** [comment]
Hey @ari-party, we have recently optimized the images' experience across all of our editors with #5585. You'll see the changes with our upcoming release real soon.
