### ISSUE TITLE
[feature]: Improve vertical spacing for heading elements in Pages and Issues

### ISSUE THREAD

**Issue by benr77** [makeplane/plane#5399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When creating content on Pages, or inside Issues, there is not enough space around heading elements. I end up putting additional empty paragraphs around headings example, to increase the spacing. However, this empty paragraph is both semantically wrong, and _too much_ spacing.

### Why should this be worked on?

It is a quick and easy fix to improve the `margin-top` and `margin-bottom` of the various headings, and this will greatly improve the appearance of textual content, which is what users are looking at the whole time they use the platform.
Thanks!

**Comment by dev13-suthar** [comment]
@benr77  can u provide ss for this, so i can have better idea

**Comment by benr77** [comment]
Here are two screenshots, one with paragraph style content, and another with lists. Neither of these has any additional empty paragraphs added, which is my workaround for increasing the spacing, but as I said in my original post this created _too much_ spacing.

In my opinion, it would be better if the padding above and below the H2, H3 and H4 elements was increased a little. The H1 is pretty much fine as it is. I realise this is quite subjective, but it's been bugging me for a long time and is one of the only gripes I have with an otherwise wonderful text-editing experience.

![plane-typography-lists](https://github.com/user-attachments/assets/66c3d287-1204-402a-bfc3-82f8e1c8ab6d)
![plane-typography-paragraphs](https://github.com/user-attachments/assets/2281f078-c580-4931-bb04-252c4139f443)

**Comment by aaryan610** [comment]
Hey @benr77, we recently pushed improvements on typography of all the rich-text editors, including Pages, with #5978 making them much more visually appealing.
