### ISSUE TITLE
Mobile usage

### ISSUE THREAD

**Issue by tomerh2001** [makeplane/plane#5457]
Is there any recommended way to use plane on mobile? I can't find a proper solution to this. The app project seems to be abandoned.

**Comment by theparthacus** [comment]
not at all. mobile is almost ready. if you are interested, we will have you beta test in two week's time.

**Comment by tomerh2001** [comment]
> not at all. mobile is almost ready. if you are interested, we will have you beta test in two week's time.

Good to know! I would happily beta test it

**Comment by spencerwongfeilong** [comment]
Me too!

**Comment by tomerh2001** [comment]
> not at all. mobile is almost ready. if you are interested, we will have you beta test in two week's time.

Hi! Any updates? 🙃

**Comment by tomerh2001** [comment]
> not at all. mobile is almost ready. if you are interested, we will have you beta test in two week's time.

@theparthacus Hi :) Any updates? Can we start beta testing?

**Comment by vihar** [comment]
Plane Mobile is now available on the App Store and the Play Store for Plane Cloud users. Links ↓

- App Store: https://apps.apple.com/us/app/plane/id6657986465
- Play Store: https://play.google.com/store/apps/details?id=com.plane.so

We’ll soon be working on a separate app that lets self-hosted users connect to their instance. Stay tuned—closing this issue now. For more updates, join our Discord.

**Comment by tomerh2001** [comment]
> Plane Mobile is now available on the App Store and the Play Store for Plane Cloud users. Links ↓
> 
> - App Store: https://apps.apple.com/us/app/plane/id6657986465
> - Play Store: https://play.google.com/store/apps/details?id=com.plane.so
> 
> We’ll soon be working on a separate app that lets self-hosted users connect to their instance. Stay tuned—closing this issue now. For more updates, join our Discord.
> 

Woho! Looking forward to the self hosted version 🙏

If you need beta testers I'm still down
