### ISSUE TITLE
[bug]: calendar not sync with current date 

### ISSUE THREAD

**Issue by TimotheDavid** [makeplane/plane#5473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

the calendar is not sync with date

today we are the 30th august it's friday : in the calendar it's thursday ... oups 

![image](https://github.com/user-attachments/assets/c8c08b8c-ac5d-4e0b-8a3b-45247e846ee3)

### Steps to reproduce

just go to the calendar 

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Cloud

### Version

v0.17.0-dev

**Comment by pushya22** [comment]
Hi @TimotheDavid in the screen shot share i see 30th is on a Friday, am I missing something? Could you please provide more details so we can understand the issue and work on a fix?

**Comment by TimotheDavid** [comment]
It's Tuesday on 30th 

It should be Friday 


I don't know how to solve it ... If you want I can deep dive in the code :)

**Comment by pushya22** [comment]
Hi @TimotheDavid, The 30th you’re referring to is actually from the previous month, while the current day is highlighted in blue. The 30th of this month is located at the bottom right of the calendar, also highlighted in blue.

**Comment by TimotheDavid** [comment]
Ha oups .... My fault 

Sorry I close the ticket
