### ISSUE TITLE
[bug]: Error Updating Issues

### ISSUE THREAD

**Issue by ChrisDeardeuff** [makeplane/plane#5476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to move an issue from one status to another I get an error toast "error while updating issue". 
In the developer tools -> console, I see this being logged: ```useIssueType: typeId is not provided```

### Steps to reproduce

1. Go to Cycles
2. Go to Active Cycle
3. Move issue from "In Progress" column of Kanban layout, to "In QA" column.
4. Toast is displayed - 
![image](https://github.com/user-attachments/assets/53790abb-8f80-4e10-b41d-e7f892102e64)
and this is the console - 
![image](https://github.com/user-attachments/assets/cabb0a48-6f04-4e35-a904-f5df0e28d13c)

### Environment

Production

### Browser

Other

### Variant

Cloud

### Version

Latest

**Comment by NarayanBavisetti** [comment]
@ChrisDeardeuff, Could you please check your role in the specific project that the active cycle belongs to? You can find your role by going to the project settings and viewing the members.

**Comment by ChrisDeardeuff** [comment]
I am listed as an admin.
![image](https://github.com/user-attachments/assets/c585886b-1da9-40ca-88af-16c6bae2a485)
Another colleague also has the same problem and is listed as member.

**Comment by NarayanBavisetti** [comment]
@ChrisDeardeuf, Thank you for sharing this information. However, we are unable to reproduce the issue. If possible, could you please provide the network logs and the error message from the failed request?

**Comment by ChrisDeardeuff** [comment]
@NarayanBavisetti console logs attached below 😸 
[app.plane.so-1725064683247.log](https://github.com/user-attachments/files/16822940/app.plane.so-1725064683247.log)
What is the best way to share network logs?
Thanks for your help!

**Comment by NarayanBavisetti** [comment]
@ChrisDeardeuff You can open the Developer Tools, go to the Network tab, and click on the failed request to view the response.
<img width="712" alt="Screenshot 2024-08-31 at 6 20 43 AM" src="https://github.com/user-attachments/assets/ac0e42a9-b42a-4caf-8f85-10d1eb9b733c">

**Comment by ChrisDeardeuff** [comment]
There seem to be no failed responses... 
![image](https://github.com/user-attachments/assets/3a2ba11e-1eb6-4020-bc94-6c514df292fb)

**Comment by NarayanBavisetti** [comment]
Try replicating the issue you reported, and then check the network logs.

**Comment by ChrisDeardeuff** [comment]
Nevermind! Just did a refresh and got this:

![image](https://github.com/user-attachments/assets/615bf3e2-cd0c-4bec-91ac-ec15d4b70738)

I then cleared the network log, and tried to move the issue again. It only had a few network requests when I clicked back into the window and none when I tried to move it:
![image](https://github.com/user-attachments/assets/e2023ed4-170f-489b-a2ec-16e15d36f2b7)

**Comment by zeeshanibnali** [comment]
I am facing the same issue when trying to assign a task to someone in the team.

**Comment by richardcardoso198** [comment]
Facing the same issue, any updates on this?

**Comment by davialano** [comment]
Facing tha same issue, any updates?

**Comment by pushya22** [comment]
This issue is resolved and deployed to cloud.
