### ISSUE TITLE
[bug]: Gantt View data not loading and mixes data across projects

### ISSUE THREAD

**Issue by madukan** [makeplane/plane#5483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

##### Summary
When I view the data under a pre-defined View, they tend to either 
1. Not show the data (Issues/tasks) at all
2. Or show the data (tasks/issues) from a different project

##### Steps to reproduce
1. Create a list of `Issues`, have some of them assigned `Backlog` state; and some others `Todo` state (We will use only Backlog state issues, others are there only to validate what we see.
2. Lets create two views (one view is just for checking). First view with `List` view and state filter `Backlog`. 
3. Next view, create it  with `Gantt` view and state filter `Backlog`.

Now, visit the Gantt view having Backlog items.

##### Expected result
Display the backlog state items in a Gantt view so that I can start allocating dates for issues.

##### Actual Result
Either blank (no tasks, loading views stuck forever) or displays tasks from a different random project. 

##### Workaround
Change the view from Gantt to List and back to Gantt. Then it seem to work again. 

##### Ramarks
It would be great if this can be fixed as it may otherwise give the user a wrong perception about the tasks at hand for the project. 

##### Steps to reproduce
1. Create a list of `Issues`, have some of them assigned `Backlog` state; and some others `Todo` state (We will use only Backlog state issues, others are there only to validate what we see.
2. Lets create two views (one view is just for checking). First view with `List` view and state filter `Backlog`. 
3. Next view, create it  with `Gantt` view and state filter `Backlog`.

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.22-dev

**Comment by pushya22** [comment]
@madukan This is fixed in our latest release. Please upgrade to v0.23.1
