### ISSUE TITLE
[bug]: Discard and then save as draft does not save as draft

### ISSUE THREAD

**Issue by cendyne** [makeplane/plane#5484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, it only stores drafts which are clicked out of in the modal state.

I expect that when I save a draft in the discard dialog, and the toast notification says draft saved successfully, that the draft can be restored.

### Steps to reproduce

1. In a project, click add issue, a modal box comes up
2. Enter a title and description
3. Click Discard
4. In the next modal "Would you like to save this issue in drafts", click "Save draft"
5. Observe the toast notification saying it was successful
6. Observe that `draftedIssue` in local storage has not been changed

### Environment

Deploy preview

### Browser

Google Chrome

### Variant

Self-hosted

### Version

stable

**Comment by pushya22** [comment]
Hi @cendyne could you please check in drafts under project settings it will be saved there.

**Comment by cendyne** [comment]
Hi @pushya22 
Thank you for your guidance, I did find the discard -> draft issue preserved by going to "..." and then to Draft issues. I was not aware of this dropdown before. It was not visible within project settings.

![image](https://github.com/user-attachments/assets/6b6dde50-7fee-4db4-8f1e-e7f4bd9f0249)

Given that the functionality exists to restore a drafted issue, I believe closing this issue is the appropriate action. Though, I think the usability could be improved.
