### ISSUE TITLE
[bug]: Transfer Issue button disappears

### ISSUE THREAD

**Issue by karimul** [makeplane/plane#5490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is no Transfer Issue button on Completed cycle. 

### Steps to reproduce

1. Go to Cycles menu
2. Select completed cycle
3. Transfer Issue button disappears

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

latest

**Comment by pushya22** [comment]
Hi @karimul The "Transfer Issues" action in a cycle is a one-time operation. Once used, the button disappears, and a cycle snapshot is saved in the backend, which can be viewed in Cycle Analytics.

**Comment by karimul** [comment]
@pushya22 the "Transfer Issues" action disappears in the first time I opened completed cycle without used it.

**Comment by pushya22** [comment]
Hi @karimul Could you please share screen shot of network response

**Comment by karimul** [comment]
here is the capture of network responses @pushya22 
![image](https://github.com/user-attachments/assets/0394e32e-7800-4a10-851d-1762ecbe68c6)

**Comment by pushya22** [comment]
@karimul Thanks, will look into it and get back.

**Comment by pushya22** [comment]
Hi @karimul thanks for reporting this issue is now resolved, please re-open if there are any further questions
