### ISSUE TITLE
[bug]: Comment image resize issue

### ISSUE THREAD

**Issue by sasha-id** [makeplane/plane#5500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/user-attachments/assets/b9468d28-0318-45b6-8800-69debd3b35c3

### Steps to reproduce

1. Go to any issue comment, add 1st comment with embedded image
2. Add second comment with embedded image and try to resize

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.22

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by pushya22** [comment]
Hi @sasha-id alredy fix is in place and will be part of our next release

**Comment by aaryan610** [comment]
Hey @sasha-id, all issues related to images across all the editors have been fixed with #5585. You should see those changes live with our next release.
