### ISSUE TITLE
[bug]: Unable to remove comment attachment

### ISSUE THREAD

**Issue by sasha-id** [makeplane/plane#5501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/user-attachments/assets/015c7bc3-b053-4b82-b815-48c3e6a2b5ce

### Steps to reproduce

1. Go to any issue comment and add attachment
2. Try to remove it, it will just redirect to issue index page

No console errors

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.22

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by shubhankartrivedi** [comment]
The issue still persists!

**Comment by pushya22** [comment]
Hi @sasha-id the fix is available in our latest release. Please upgrade to v0.23.1. Please not that only admins will have access to edit intake issues.
