### ISSUE TITLE
[bug]: Files larger than 5mb are not uploaded (self host)

### ISSUE THREAD

**Issue by hfzi** [makeplane/plane#5525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I tried everything, I increased all FILE_SIZE_LIMITs, I made 5242880000, I made MAX_FILE_SIZE = 5000 * 1024 * 1024, but I cannot upload files over 5mb. I solved the 5mb error in the frontend, but in the backend I get an error, it returns 400

### Steps to reproduce

1. Click attach button
2. Select file
3. 400 error backend

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

0.22

**Comment by lucas-strummer** [comment]
Same here, I changed values on the docker-compose, apiserver/.env, apiserver/plane/settings/common.py and even the nginx.conf container but still can't upload files bigger than 5MB.

Same version as OP.

**Comment by hfzi** [comment]
> Same here, I changed values on the docker-compose, apiserver/.env, apiserver/plane/settings/common.py and even the nginx.conf container but still can't upload files bigger than 5MB.
> 
> Same version as OP.

Did you find a solution dude?

**Comment by shubhankartrivedi** [comment]
Any update on this?

**Comment by gabe3886** [comment]
I thought this would be a fun one to dig through. The short version of resolving this is to set the filesize in the `.env` and the `apiserver/.env` files ahead of running the `docker compose -f docker-compose-local.yml up -d` command. Doing that has let me upload larger files consistently.

It doesn't look like the values in `packages/editor/src/core/plugins/image/utils/validate-file.ts` or `web/core/constants/common.ts` are used for anything other than showing the error when Plane is run using the default values.

I was running the `preview` branch when digging through this.

**Comment by aaryan610** [comment]
Hi @hfzi, this issue has now been fixed and is live in both, cloud and self-hosted versions. I am closing this issue for now, but feel free to re-open it in case there's something more you'd like to discuss.
