### ISSUE TITLE
[bug]: Fix draft history when moving from draft

### ISSUE THREAD

**Issue by omarin-disco** [makeplane/plane#5528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you've created a draft ticket and finalize it by clicking "Move from draft", the history of the ticket then incorrectly shows `<user> deleted an issue.`. This is misleading since the ticket isn't deleted, but moved out of draft status.

### Steps to reproduce

1. Click "Add issue"
2. Enter some data
3. Click "Discard"
4. Click "Save draft"
5. Click "..." next to your project name on the side nav
6. Click "Draft issues"
7. Click "..." next to a draft issue
8. Click "Edit"
9. Click "Move from draft"
10. View issue history and see "deleted an issue."

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

v0.22-dev

**Comment by aaryan610** [comment]
Hey @omarin-disco, this issue has been fixed and is live in production.
