### ISSUE TITLE
[bug]: When a view is created to show Kanban it does not display the Kanban view correctly

### ISSUE THREAD

**Issue by muazrakin** [makeplane/plane#5552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create a view to show my issues as a Kanban, it does not display the Kanban view correctly. It shows the Kanban view as a list.

![image](https://github.com/user-attachments/assets/3ed27c76-1a77-4a50-aa89-6b6ed906ac67)

Under "Display>Group by" nothing is selected.

![image](https://github.com/user-attachments/assets/3902a9d0-c71c-4491-80ce-3a51d6866fe2)

However, if I click on Group by> States the Kanban view is now correct.

![image](https://github.com/user-attachments/assets/53f02f72-2b70-4995-81ae-ec540f0bb967)

![image](https://github.com/user-attachments/assets/de214171-5238-43eb-a64b-89b617e68093)

**Clicking on Lists or any other view and then going back to Kanban also renders the Kanban view correctly**

### Steps to reproduce

![image](https://github.com/user-attachments/assets/6ae7dca7-cd81-46c7-9a83-7a483585ea27)

![image](https://github.com/user-attachments/assets/5cc7f157-0878-46f9-b5cf-248af590866f)

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.22.0

**Comment by pushya22** [comment]
Hi @muazrakin this issues is already fixed and will be part of our next release.
