### ISSUE TITLE
🚀 Feature: Add "Copy to Clipboard" Button for Task ID

### ISSUE THREAD

**Issue by nicholaslhoest** [makeplane/plane#5610]
## Feature Request:

As a developer, I frequently include task IDs in my Git commit messages for traceability. I would appreciate a "Copy to Clipboard" button next to the task ID on the task board and ticket detail page.

## Use Case:

As a developer, I want to copy the task ID from the task board quickly,
So that I can paste it into my Git commit message without having to select and copy the ID manually.

## Proposed Solution:

On both the task board and ticket detail page, add a "Copy to Clipboard" button adjacent to the task ID.
When clicked, the task ID is copied to the clipboard, making it easier to include in commit messages or other documentation.

## Example Format:
**Without button**
![Screenshot 2024-09-14 112952](https://github.com/user-attachments/assets/20cd500a-d103-4fc9-aded-0bd4cb868ae3)

**With Copy to Clipboard button**
![Screenshot 2024-09-14 112952 v2](https://github.com/user-attachments/assets/4d374265-0c59-45a4-9d6b-0d89a9aaf992)

Thank you for considering this feature. Have a great day.

**Comment by gaurisharma1122** [comment]
Hey, I wanna work on this. Can you please assign this to me?

**Comment by nicholaslhoest** [comment]
Issue was moved because it did not have a feature label attached to it.
