### ISSUE TITLE
[feature]: Public Roadmap - no new release for quite some time 

### ISSUE THREAD

**Issue by mnbro** [makeplane/plane#5611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Public Roadmap

### Why should this be worked on?

The pace of releases was around 1-2/month until 0.22-dev. There is no release for more than 2 months.

1. Do you have a public roadmap?
2. Do you have a scheduled date for the next release?

**Comment by nickproud** [comment]
Id also love to hear more about release cadence. I love the app but want to see development continue as it has so much potential

**Comment by ShaonPro** [comment]
Join the Discord To Know more, they said, this week they will release new update.

**Comment by vihar** [comment]
This repo is actively maintained, with major performance improvements and reliability updates coming in our next community release, along with exciting new features. We’re aiming to ship either this week or next, and our engineering team is confident. We’ll also run thorough tests to ensure a smooth migration for all community instances.

Everything is already in the `preview` branch, and we’ll share updates on Discord soon. Over 500 commits squashed—there’s a lot coming, so hang tight!

![CleanShot 2024-09-17 at 03 36 13@2x](https://github.com/user-attachments/assets/39e39890-6a09-4951-9794-366e89733e2c)

Sneak peek of what’s coming:

	•	Real-time sync and version history to Pages
	•	Issue layouts UI and API performance improvements, tested on over 10,000+ issues
	•	Role management improvements
	•	Favorites management across the workspace
	•	And many more

**Comment by vihar** [comment]
Closing this issue. The roadmap will be made public soon, and our community release is scheduled for early next week.
