### ISSUE TITLE
[feature]: Add Plane to OpenCollective

### ISSUE THREAD

**Issue by kdhaka94** [makeplane/plane#5633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Why have you guys not added plane to OpenCollective by now, there are a lot of people I think already ready to contribute with money and gives you a big platform to get more users 

### Why should this be worked on?

This seems like a no-brainer

**Comment by vihar** [comment]
@kdhaka94, thank you for sharing your thoughts. At this time, we are not planning to raise any funds.
