### ISSUE TITLE
[bug]: Docker container naming convention create malfunction in setup script

### ISSUE THREAD

**Issue by ldbglobe** [makeplane/plane#5655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. Starting the app with the setup script would end with :

```
API Service started successfully ✅
Plane Server started successfully ✅
You can access the application at $WEB_URL
``` 

This error seems to be induce by a naming convention change on the docker compose engine using underscore instead of hyphen. So before we used to have ``plane-app-plane-db-1`` as container name and now we have ``plane-app_plane-db_1``

### Steps to reproduce

With a fresh install of the community version :

1. I start the app with sur setup script
2. Services start and the app is quickly functionnal
3. The script get stuck at step ">> Waiting for API Service to Start...... (endless)"

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

v0.22.0-dev

**Comment by akshat5302** [comment]
Hey @ldbglobe, could you please share your `docker-compose` version

**Comment by ldbglobe** [comment]
Sorry, The problem was solved by updating docker version

I work on windows with WSL and I had install a custom version of Docker in my Linux Subsystem distribution causing inconsistent behavior.

Note for my passed me ... keep it simple and do not build tools mashup !!!
