### ISSUE TITLE
[bug]: Remove attachment in issue (panel view) closes the issue panel and does not remove attachment

### ISSUE THREAD

**Issue by arihan01** [makeplane/plane#5677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to remove an attachment from an issue (panel view) it closes the panel and does not remove the attachment. Removing attachment works when the issue is in expanded view.

### Steps to reproduce

- Open and issue in panel view
- Add an attachment
- Click on the remove attachment (x icon)
- Confirm Delete in the popup

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v0.22.0

**Comment by shubhankartrivedi** [comment]
Why is this closed? The issue's still there

**Comment by genomedicsmarzoli** [comment]
There are no commits related to this bug fix. Is it fixed? I am having this issue too.
