### ISSUE TITLE
What is the unit of estimate? （day?hour?）

### ISSUE THREAD

**Issue by njuptlzf** [makeplane/plane#5684]
What is the unit of estimate? Can it be changed? It is not obvious on the web, which confuses me
![image](https://github.com/user-attachments/assets/32f79f05-8744-4fee-867f-1b03c1fdecbe)

**Comment by StefanFabian** [comment]
In project planning, you usually work with something more abstract, like story points, because it is incredibly difficult, not to say pointless, to give an exact estimate of hours/days.

**Comment by vihar** [comment]
Find more details in our docs here: https://docs.plane.so/core-concepts/issues/estimates
