### ISSUE TITLE
[bug]: when adding an attachment to a task, the list of collapsed. 

### ISSUE THREAD

**Issue by jamesrusso** [makeplane/plane#5700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I click the + item on the attachment window to add an attachment the attachment list is minimized and then the select file dialog shows up. 

<img width="1737" alt="Screenshot 2024-09-25 at 3 09 42 PM" src="https://github.com/user-attachments/assets/e0e7d2f3-9e83-4461-892a-5fd92dc06ae6">

### Steps to reproduce

Create a task, add an attachment. 
Expand list to show attachment.
Click + to add another attachment it will be closed.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

LATEST?

**Comment by jamesrusso** [comment]
Basically only the chevron or the blank row space should cause toggle. The plus should only do add attachment and stop propagation of the event to the underlying element.

**Comment by pushya22** [comment]
@jamesrusso this issue is fixed and will be part of our next release

**Comment by pushya22** [comment]
Hi @jamesrusso this is issue is resolved in our latest release. Please feel free to reach out in case of further queries.
