### ISSUE TITLE
[feature]: Move "Mark all as read"

### ISSUE THREAD

**Issue by ari-party** [makeplane/plane#5701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![chrome_w8rVTN3NZ6](https://github.com/user-attachments/assets/f87c8a33-619c-4b0a-89be-a4f4ff177ac0)
Requesting that the mark all as read button be moved next to refresh.

### Why should this be worked on?

Enhances accessibility for one of the most used buttons in the inbox.

**Comment by vihar** [comment]
We now have a fully revamped Inbox UI. Thanks for sharing the feedback.

![CleanShot 2024-12-01 at 15 36 14@2x](https://github.com/user-attachments/assets/6ebe3cdb-8ee1-4cc7-ab2c-cdffd1184d8a)
