### ISSUE TITLE
[bug]: Filename size limited to 100 characters 💥

### ISSUE THREAD

**Issue by sasha-id** [makeplane/plane#5702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to upload file with filename > 100 chars will fail with popup error:

<img width="512" alt="Screenshot 2024-09-26 at 10 09 28" src="https://github.com/user-attachments/assets/7b753c15-64bd-4bd2-941f-3d43093476cc">

1. This is very limiting, make it 255 at least
2. The only way to find what went wrong is to debug http requests, no logs or meaningful error

Response from api
```json
{"asset":["Ensure this filename has at most 100 characters (it has 104)."]}
```

### Steps to reproduce

upload images with filename >100chars

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.22

**Comment by pushya22** [comment]
@sasha-id this issue is already fixed and will part of our next release

**Comment by pushya22** [comment]
@sasha-id this issue is resolved in our latest release. Feel free to reach out in case of any further queries
