### ISSUE TITLE
[feature]: Markdown/Text Editor

### ISSUE THREAD

**Issue by ach5948** [makeplane/plane#5735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

WYSIWG editors can be a pain to get the formatting right. Since plane supports markdown, it would useful to have a Markdown or Text view in description fields (or any field that's longer than a single line). This view would just show plain text with no formatting. Toggling back to a "Visual" view would show the text with any rendered formatting.

This would make it much easier to do formatting for anyone familiar with writing Markdown.

### Why should this be worked on?

Many existing services support this model, such as github, gitlab, jira. In my experience it is popular among developers (who frequently use task/ticketing software like plane) without taking away from the experience of more typical users.

**Comment by MuhmdAjeer** [comment]
@vihar can i work on this please ?

**Comment by eughcus** [comment]
hi, 

I second this request, it would also be nice to have a syntax highlighting in code blocks.

thank you!

**Comment by aaryan610** [comment]
Hey @ach5948, Thank you for suggesting this feature. After careful consideration, we’ve decided not to pursue this feature as it doesn’t align with our current roadmap or focus areas.

That shouldn't stop you from writing in markdown format as we support markdown end to end for all of our editors, you can also paste markdown content from anywhere.

**Comment by vihar** [comment]
@NatoBoram, plane supports markdown formats.

**Comment by NatoBoram** [comment]
I don't think we're taking about the same thing. Can you show a screenshot of how to disable WYSIWYG?

**Comment by rzr** [comment]
> I don't think we're taking about the same thing. Can you show a screenshot of how to disable WYSIWYG?

yes this would be welcome, also a way to open pages are read only would be helpful because I hate when "out of control" changes are done in my name.
