### ISSUE TITLE
[bug]: Creating a draft issue with no project is allowed but doesn't actually save

### ISSUE THREAD

**Issue by nikkuexe** [makeplane/plane#5841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When in the top-level 'Drafts' and click the 'Draft issue' button to create a draft issue, I am able to click 'create draft issue' without a project defined, which will result in a toast message saying the draft issue is saved but the draft issue doesn't show in the draft list.

The expected result is either (a) requiring the project to save the draft, or (b) actually creating a draft without a project defined.

---

I think there is value in not requiring a project when creating a draft issue. This would allow less friction in making a draft issue, appropriate if you do not yet know which project would handle the issue. However, this might be beyond the scope of this bug request and instead be a new feature.

### Steps to reproduce

1. Click on the top-level Drafts in the sidebar
2. Click on 'Draft issue' on the top-right
3. Write an draft issue without selecting a project
4. Click the 'create draft issue'
5. See the toast message saying the draft has been saved.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

latest

**Comment by pushya22** [comment]
Hi @nikkuexe thanks for notifying this, will look into it and get back.

**Comment by pushya22** [comment]
Hi @nikkuexe, there’s no scenario where a draft issue can be created, as the last active project is always selected as the default. Could you please share more details, such as a screen recording, so we can investigate further?

**Comment by nikkuexe** [comment]
Hello @pushya22  You'll see that no last active project was selected by default:

[Screen Recording 2024-10-16 at 1.07.17 AM.webm](https://github.com/user-attachments/assets/d9430d3d-786a-433c-bfa3-8538b0aa7069)
