### ISSUE TITLE
Inconsistent versioning

### ISSUE THREAD

**Issue by axelrindle** [makeplane/plane#5862]
We're running a Plane Pro instance (which is working fine), but I noticed some very inconsistent versioning.

- The Plane containers are tagged as `v1.3.1`
- The latest release in this repository is `v0.23.1`
- The Web UI tells me I'm running `0.15.1`

I'd like to know if this is intended and if yes, how to understand this scheme.

**Comment by leedsjb** [comment]
Different editions have different versions. You can find more details here: https://plane.so/changelog
