### ISSUE TITLE
[bug]: Unable to change project settings

### ISSUE THREAD

**Issue by echoes95** [makeplane/plane#5870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to change project settings, i get the error - key does not exist.

### Steps to reproduce

1. Go to Project Settings
2. Change project description
3. Face error
![Screenshot 2024-10-18 165431](https://github.com/user-attachments/assets/39de2d8a-2a05-405f-a86b-f083a78e5415)

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.23.0

**Comment by talibraath** [comment]
Please assign me.

**Comment by pushya22** [comment]
Hi @echoes95 this issue is resolved in v0.23.1 release.

**Comment by echoes95** [comment]
Thank you! @pushya22
