### ISSUE TITLE
[bug]: Different view - Different results

### ISSUE THREAD

**Issue by tranminhnhanchinh** [makeplane/plane#5895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In List view, the result is different from in Kanban view

List view: https://prnt.sc/BuVD_AojXR2H
Kanban: https://prnt.sc/uVz8EHrZiGIm

### Steps to reproduce

1- Click List view

2- Click Kanban view

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

lastest

**Comment by pushya22** [comment]
@tranminhnhanchinh The difference in issue counts occurs because the sub-issue toggle is disabled in the display properties. Please enable it, and the issue counts will match in both layouts.
