### ISSUE TITLE
[bug]: The required key does not exist when updating the project settings

### ISSUE THREAD

**Issue by johhnry** [makeplane/plane#5914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I go to a Project settings, click the `Update project` button then it shows this error: `The required key does not exist.`

It sends this PATCH request:

```json
{
  "name": "WTL Pipeline",
  "network": 2,
  "identifier": "PIP",
  "description": "Pipeline @ Welcome To Love",
  "cover_image": "https://images.unsplash.com/photo-1693868769698-6c7440636a09?auto=format&fit=crop&q=80&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=870&q=80",
  "logo_props": {
    "in_use": "emoji",
    "emoji": {
      "value": "128140",
      "url": "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f48c.png"
    }
  }
}
```

And the response is: 

```json
{"error":"The required key does not exist."}
```

### Steps to reproduce

1. Go to project settings
2. Click the `Update project` button

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.23.0

**Comment by pushya22** [comment]
@johhnry This issue has already been resolved. Please upgrade to version 0.23.1, and if the issue persists, feel free to reopen it.
