### ISSUE TITLE
[bug]: Project Issues list is blank/empty, even though there are multiple issues open

### ISSUE THREAD

**Issue by smonksi** [makeplane/plane#5956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- When I try to list all issues in a project, the screen is completely blank. 

- Conversely, all modules within the project display the issues they contain, as expected. 

- This is a recent issue I have only become aware of since upgrading to v0.23.1

Project Issues: Blank 
![2024-11-05](https://github.com/user-attachments/assets/8e11dbdf-fb1d-4296-a796-4833c35d048b)

Module Issues: Populated 
![2024-11-05 (1)](https://github.com/user-attachments/assets/4d7990fb-21b7-4cac-9550-bd53dcddb09f)

### Steps to reproduce

1. Go to the issues page in a project. No issues are listed.
2. Go to any of the modules for the project. Issues are correctly listed.

Problem manifests both in Chrome and Firefox. Other browsers not tested.

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v.0.23.1

**Comment by aaryan610** [comment]
Hey @smonksi, I see that you have not selected any layout(Board, List, etc.). It seems like a bug as we display the issues in the list layout when none is selected, we'll check on this from our end.

Meanwhile, can you please try selecting from any one of them once?

**Comment by pushya22** [comment]
@smonksi could you please upgrade to our latest version v0.24.1.

**Comment by smonksi** [comment]
> @smonksi could you please upgrade to our latest version v0.24.1.

I have recently upgraded to v0.24.1 and now the isssue is resolved. Thanks for all your help.

**Comment by smonksi** [comment]
Resolved in latest version v0.24.1
