### ISSUE TITLE
[feature]: Support GIFs in Issue description

### ISSUE THREAD

**Issue by thelegend09** [makeplane/plane#5996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In the same way that I can upload a picture (currently supported: JPEG, JPG, PNG. WEBP, SVG), in the Issue description, I'd like to be able to upload GIFs.

### Why should this be worked on?

Sometimes, it's much easier to explain something by SHOWING it rather than explaining. And often it's easier to show by using a video or GIF than via still images. 

(I'm using a tool on Windows that makes recording GIFs very easy and straightforward, and I use it all the time to show things to my developer colleagues.)

**Comment by pushya22** [comment]
@thelegend09 Gif's are already supported in our cloud version, will be shipping to self hosted versions soon.

**Comment by thelegend09** [comment]
Awesome, and thanks for this amazing piece of software!

**Comment by pushya22** [comment]
thanks @thelegend09 closing the issue. Do let us know if you have any further queries.
