### ISSUE TITLE
[bug]: Broken Link to Profile Image in Notification Emails

### ISSUE THREAD

**Issue by leedsjb** [makeplane/plane#5999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I receive a notification email the users profile photo does not appear. The link to the image is broken. The image src tag reads: `<img src="https://[self-hosted-plane-instance-url]None"/>` and therefore <img src="https://[self-hosted-plane-instance-url]None"/> is shown. 

I expect the users profile photo to appear in the email or, if the user has no profile photo, a circle w/ the first letter of their name inside it.

<img width="118" alt="Screenshot 2024-11-14 at 12 39 13 PM" src="https://github.com/user-attachments/assets/54012b08-864f-4960-8bce-17d21e39a1b7">

### Steps to reproduce

1. Received a Plane notification email

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.4.0

**Comment by aaryan610** [comment]
Hey @leedsjb, thanks for pointing out this bug, we'll look into the issue and fix it with our upcoming release.

**Comment by leedsjb** [comment]
@aaryan610 v1.6.0 made progress towards resolving this issue - but we're not all the way there. May I DM you the raw content of the email for further debugging?

**Comment by leedsjb** [comment]
@aaryan610 I figured out the problem - it has to do with Gmail's image proxy service. Because the profile photos are hosted in our Plane self-hosted instance and this instances is not accessible on the internet Google has no way to retrieve the images and display them. The solution to this for companies using Google Workspace is disable image proxying in Gmail for images that are hosted in Plane by providing the URL. 

I suggest you add this to the Plane documentation here: https://developers.plane.so/self-hosting/govern/communication

The relevant Google documentation is here: https://support.google.com/a/answer/3299041?hl=en
