### ISSUE TITLE
[feature]: Ability to move issue from one project to another

### ISSUE THREAD

**Issue by ivorynoise** [makeplane/plane#6039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great to allow moving issues to right teams/projects. 

### Why should this be worked on?

This would allow project managers to distribute workload better. Requirements raised in one team can be routed to right project without creating further tickets.

**Comment by vihar** [comment]
@ivorynoise, thanks for your feedback. this feature is already available on our Pro plan. see [pricing](https://plane.so/pricing) for more details. Thank you.
