### ISSUE TITLE
[bug]: URL is Invalid error in Add Link modal

### ISSUE THREAD

**Issue by leedsjb** [makeplane/plane#6070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to add a link to a Google Drive item in the Issue -> Add Link modal the URL does not pass validation and the "URL is invalid" error message is shown:

<img width="264" alt="Screenshot 2024-11-18 at 10 59 41 PM" src="https://github.com/user-attachments/assets/51bd9a7a-0c9f-4f24-a4b1-022a2c50a7c6">

I would expect any link generated by Google Drive to be accepted by Plane.

The error specifically is related to the `=` at the end of the URL. If this character is removed the URL passes validation. However, the `=` character is necessary to paste a link to a specific slide in a Google Slides presentation.

Example URL: https://docs.google.com/presentation/d/16j0_wRP5MyS4uBXUFDa48CIxrPd5_t1W4ybzIlq6nPM/edit#slide=id.p

### Steps to reproduce

1. Copy link to a Google Slide file
2. Open Plane issue
3. Click "Add link"
4. Past Google Slide link into URL field
5. Click "Add link" -> URL is invalid error appears

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.4.0

**Comment by leedsjb** [comment]
*Might* be addressed by: https://github.com/makeplane/plane/pull/5994

**Comment by pushya22** [comment]
@leedsjb This issue has alredy been fixed. Will shipped to self hosted in our next release.

**Comment by leedsjb** [comment]
@pushya22 confirming this issue has been fixed in v1.5.0. Thanks!
