### ISSUE TITLE
[bug]: UI bug. the "workspace level toggle" has almost no padding in right side.

### ISSUE THREAD

**Issue by giteshsarvaiya** [makeplane/plane#6103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when I click any issue in "created by you, pending issues" section and then click on "parent issue", a modal opens and that modal has a toggle named as workspace level. it has very little padding at the right side. 
![Screenshot 2024-11-27 142646](https://github.com/user-attachments/assets/70c35d80-b1b8-40f6-8832-3950c0275c57)
 
 
 I have created some versions of it. 
 version 1.  reversed the flex-row
![Screenshot 2024-11-27 143242](https://github.com/user-attachments/assets/525e2f18-2340-4745-b7f5-4d7f6a29704b)

version 2. reversed the flex row + gave 5% padding at the right side
![Screenshot 2024-11-27 143305](https://github.com/user-attachments/assets/0308b651-9d05-4799-b934-4af5e3a9fecf)

version 3. just gave 5% padding at the right side.
![Screenshot 2024-11-27 143316](https://github.com/user-attachments/assets/5cbcbce5-34ae-41a9-bbc8-155979bc546b)

If you allow me. I can produce any of the version that you choose from above and raise a PR.

### Steps to reproduce

1. Go to the home page. i.e. "plane.so/:workspaceName/"
2. Click any of the issues from "created by you and pending section"
3. Click on "parent issue"

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v.0.23.1

**Comment by pushya22** [comment]
@giteshsarvaiya This issue has beed addressed in our lates release, please upgrade to v0.24.1. If the issue persists, feel free to re-open it.
