### ISSUE TITLE
[bug]: UI Bug: "already have and account?" is center aligned in signup page

### ISSUE THREAD

**Issue by giteshsarvaiya** [makeplane/plane#6105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is how it the "Already have an account?" button looks in my phone
![Screenshot 2024-11-27 161048](https://github.com/user-attachments/assets/1740c788-fe51-4751-8dac-79530a9f142f)

this is how it should look like
![Screenshot 2024-11-27 162524](https://github.com/user-attachments/assets/26b8055a-a9d5-460b-a923-8266078e8f58)

### Steps to reproduce

1. Go to the "app.plane.so/sign-up/" route.
2. Observe the "Already have an account?" in mobile screen. (Samsung S21FE or Samsung S8)

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v0.23.1

**Comment by aaryan610** [comment]
Hey @giteshsarvaiya, thanks for pointing out this inconsistency in the UI, we'll fix it with our upcoming release.

**Comment by pushya22** [comment]
Hi @giteshsarvaiya,This issue has been addressed in our latest release. Please upgrade to v0.24.1. If the issue persists, feel free to re-open it.
