### ISSUE TITLE
[bug]: Incorrect Version Number in UI in Plane Pro v1.5.0

### ISSUE THREAD

**Issue by leedsjb** [makeplane/plane#6127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I look at the version number for Plane by clicking the ? in the bottom left corner the version number should be v1.5.0. It is v1.4.0. 

There is no doubt the server is still accidentally running v1.4.0 because the Local Cache option introduced in v1.5.0 is available.

<img width="184" alt="Screenshot 2024-11-29 at 5 29 34 PM" src="https://github.com/user-attachments/assets/eee2364a-4079-471d-963e-9a4696e52820">

### Steps to reproduce

1. Go to Plane
2. Click the ? in the bottom left corner
3. View Version Number

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.5.0

**Comment by leedsjb** [comment]
The version now reads as v1.5.1. Perhaps the previous version was cached in my browser. **However** I have not yet deployed v1.5.1, the install is on v1.5.0 so the version number is still incorrect.

<img width="193" alt="Screenshot 2024-12-01 at 5 16 49 PM" src="https://github.com/user-attachments/assets/b32445d4-c66b-4a41-8c56-a714d0fa2e71">

**Comment by sriramveeraghanta** [comment]
Hey @leedsjb 

Thank you for reporting the issue. We have identified an issues with application version recorded on Plane Instance while using Kubernetes as a deployment strategy. We are working towards fixing the issue. This will be fixed as a part of v1.6.0 version.

**Comment by leedsjb** [comment]
Confirming this is fixed now in v1.6.0. Thanks!
