### ISSUE TITLE
[feature]: Ability to Subscribe other users to an issue

### ISSUE THREAD

**Issue by leedsjb** [makeplane/plane#6148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the ability to add Subscribers (other than oneself) to an issue to keep them informed of the status. 

### Why should this be worked on?

The ability to subscribe others to an issue allows users to keep stakeholders for an issue automatically informed of the issue's progress via email and in-app updates. Users always have the option to unsubscribe themself if they wish to be removed from future updates for a given issue.

Right now, if you want to keep someone up to date on an issue's progress you need to send them a link to the issue and tell them to click Subscribe or manually tag them in comments w/ updates. This is an awkward UX.

**Comment by leedsjb** [comment]
Relates to #4795 but at the issue level as opposed to the Project or Module level.

**Comment by aaryan610** [comment]
Hey @leedsjb, this indeed is a good feature request. We’ll discuss it internally and prioritize it accordingly.

Thanks you!

**Comment by aaryan610** [comment]
Also, forgot to mention, you can currently make other users subscribe to an issue by mentioning them in the comments or description of the issue using `@`.

**Comment by leedsjb** [comment]
Thanks! Great to know @ mentioning someone automatically subscribes them as well. I will try this. 

Recommend you add detail of that functionality here: https://docs.plane.so/core-concepts/issues/overview#subscribe-to-notifications

**Comment by aaryan610** [comment]
Yup, thanks for the recommendation. We'll do that.

**Comment by vihar** [comment]
we updated our docs. thanks, @leedsjb.

https://docs.plane.so/core-concepts/issues/overview#subscribe-to-notifications
