### ISSUE TITLE
[bug]: Unable to Modify Project Settings: Error "The Required Key Does Not Exist"

### ISSUE THREAD

**Issue by Lokanadha-SRE** [makeplane/plane#6155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am encountering an issue while trying to modify the network mode in a project under the workspace settings. Specifically, I am unable to change the network mode from Public to Private. The system throws the following error:

### Steps to reproduce

Navigate to Workspace → Project → Settings.
Attempt to change the network mode from Public to Private. or any settings like updating the description or anything updates getting issues. 
Observe the error message.
Expected Behavior: The network mode should update from Public to Private without errors.

Actual Behavior: The following error is displayed: "The Required Key Does Not Exist."

Can anyone help me resolve this issue? Any guidance or workaround would be greatly appreciated.. 

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.14.x

**Comment by pushya22** [comment]
HI @Lokanadha-SRE this issue has been addressed in our latest release. Kindly upgrade!

**Comment by Lokanadha-SRE** [comment]
Great!!.. Thank you so much for your prompt support. now the issue has been fixed.

**Comment by pushya22** [comment]
@Lokanadha-SRE Thanks.
