### ISSUE TITLE
[bug]: Unable to Join Project by clicking Join

### ISSUE THREAD

**Issue by leedsjb** [makeplane/plane#6157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I click Join on a project I am not a member of on the project page I expect to be able to do so. However, after clicking "Join Project" in the Join Project? modal the modal does not close and nothing happens.

<img width="559" alt="Screenshot 2024-12-04 at 9 43 09 PM" src="https://github.com/user-attachments/assets/89e4fa79-da95-48f9-a472-45098dee0434">

The front-end sends a request to /api/users/me/workspaces/[workspace-name]/projects/invitations and the API returns HTTP response code 403 Forbidden. 

I am a Workspace admin so I should have permissions however I expect this to work for workspace members as well not just admins.

### Steps to reproduce

1. Go To /projects
2. Click "Join" on the tile for the project you wish to Join
3. Click "Join Project" in the Join Project? modal pop-up

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.5.0

**Comment by pushya22** [comment]
Hi Benjamin, this issue has been resolved in our 1.5.1 release. Please
upgrade.

**Comment by leedsjb** [comment]
Thanks @pushya22! Excellent. The Helm chart has not been updated to reflect v1.5.1 yet.

https://github.com/makeplane/helm-charts/blob/plane-enterprise-1.1.0/charts/plane-enterprise/README.md

May I just apply the existing helm chart (v1.1.0) w/ planeVersion=v1.5.1?

**Comment by pushya22** [comment]
@leedsjb We have updated the Helm chart to reflect the latest app version. Please proceed with the upgrade and let us know if you encounter any further challenges.

**Comment by leedsjb** [comment]
Resolved - thanks!
