### ISSUE TITLE
[bug]: default project of the sub issue in inbox that cannot be changed

### ISSUE THREAD

**Issue by vikulikov** [makeplane/plane#6166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to create a sub issue for an issue in inbox the creation dialog opens with some predetermined project that is not a project of the parent issue and it can not be changed in this dialog.
It would be convenient if default selected project to such sub issue would be a parent's one and it should be changeable

### Steps to reproduce

1. Go to Inbox
2. Click on any notification for an issue
3. Click on `Add sub-issue` -> `Create new`
4. Try to change project to another one

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Cloud

### Version

Latest

**Comment by pranjalsh99** [comment]
Hey @vikulikov ,This issue has already been reported and will be fixed in the next release.

**Comment by vikulikov** [comment]
Ok, thank you! Then I will close the issue

**Comment by pushya22** [comment]
@vikulikov this issue has been resolved in our latest release.
