### ISSUE TITLE
[bug]: ISSUE PATCH API Does Nothing

### ISSUE THREAD

**Issue by jvilalta** [makeplane/plane#6173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I attempt to add assignees or labels to an issue via the PATCH method, I get a success response code (200), but the issue is not updated.

### Steps to reproduce

curl --location --request PATCH 'https://api.plane.so/api/v1/workspaces/{my-slug}/projects/{projectId}/issues/{IssueId}' \
--header 'x-api-key: mykey' \
--header 'Content-Type: application/json' \
--data '{
    "labels":["{labelID}"]
}'

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

Latest

**Comment by NarayanBavisetti** [comment]
Hey @jvilalta, I just tried to replicate the issue mentioned above. I was able to create the labels successfully, and they are being attached correctly. Can you please check it again?

**Comment by jvilalta** [comment]
I see what the issue is now, the API is returning a 301 when I make a patch request, redirecting the same url with GET as the method.
When I do a post, it works, fine.
