### ISSUE TITLE
[bug]: Email notifications checkboxes difficult to see

### ISSUE THREAD

**Issue by leedsjb** [makeplane/plane#6174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I visit the Email notifications settings page (https://app.plane.so/profile/notifications/) the checkboxes to set email notification preferences are very difficult to see. Multiple users have not been able to find them upon first visit to the page. 

The following screenshot is with the Plane default theme set:

<img width="1523" alt="Screenshot 2024-12-09 at 9 09 06 AM" src="https://github.com/user-attachments/assets/42faf4d3-c102-4bae-aff7-a672a74e55a1">
 

### Steps to reproduce

1. Visit https://app.plane.so/profile/notifications/ in cloud or self-hosted equivalent

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.5.1

**Comment by vihar** [comment]
Thanks @leedsjb for the feedback! I did a quick mockup based on your suggestions - we'll implement these improvements in our next release.

![CleanShot 2024-12-09 at 23 13 31@2x](https://github.com/user-attachments/assets/75931dee-7ee1-4c83-8f0e-90941e17143a)

**Comment by megluedke** [comment]
@vihar This design is a lot better but I'm not sure it will solve the problem users will have on wider screens, If the buttons are contained to the edges of that box it will get lost. Could you try the buttons on the left or adding a Max Width to the box so it doesn't hug the edges of the screen. 

<img width="2538" alt="Screenshot 2024-12-09 at 10 00 51 AM" src="https://github.com/user-attachments/assets/f50ba37e-5fe9-4af9-8a5a-9c42b3ee2e68">

**Comment by leedsjb** [comment]
Wow that was so fast - thanks Plane team!
