### ISSUE TITLE
[bug]: View create new issue cant select project

### ISSUE THREAD

**Issue by elmagnificogi** [makeplane/plane#6176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In workspace view ,select any issue, then create new sub-issue, you cant select project

no matter which issue you select， you could only create a issue in same project

0.23 no this problem

![image](https://github.com/user-attachments/assets/494eeaff-b158-4e27-acd7-0fb5e67749c7)

### Steps to reproduce

same as above

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.24

**Comment by aaryan610** [comment]
Hey @elmagnificogi, this is a product design choice. Sub-issues can only belong to the same project as their parent issue.

Previously, we allowed creating sub-issues in a different project than the parent’s, but based on internal discussions, we decided to remove that functionality.

**Comment by elmagnificogi** [comment]
> Hey @elmagnificogi, this is a product design choice. Sub-issues can only belong to the same project as their parent issue.
> 
> Previously, we allowed creating sub-issues in a different project than the parent’s, but based on internal discussions, we decided to remove that functionality.

You didnt konw my means. 

No matter whitch issue you select, such as it is a A project issue，you could only create a sub issue in B not A in View .
If you go to project A you could create a sub issue in A

**Comment by elmagnificogi** [comment]
see my picture, 456 is "123" project,but create sub issue in "project", it's not right. and use cant select the right project

**Comment by aaryan610** [comment]
I get your problem. This issue is similar to #6166. And will be fixed with #6169.

**Comment by pushya22** [comment]
HI @elmagnificogi this is issue is released in 0.24.1, please upgrade. Please re-open the issue if issue still persists.
