### ISSUE TITLE
[bug]: 24.1 > Images lost in version 24, unable to add new ones

### ISSUE THREAD

**Issue by Cousclou** [makeplane/plane#6184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, 

I lost all the images, and even when I restore to revert to version 24.0, the same problem persists.

![image](https://github.com/user-attachments/assets/bfe5900b-ebc0-4c49-b3b8-7dc2600ca01c)

### Steps to reproduce

update to 24.1

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v.0.24.1

**Comment by pablohashescobar** [comment]
@Cousclou please share the logs for the api container.

**Comment by sypion** [comment]
Hey there! I'm also experiencing a similar issue on my workspaces after upgrading to v0.24.1:

```
plane-api  | 172.18.0.13:49812 - "GET /api/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/ HTTP/1.1" 200
plane-api  | 172.18.0.13:55818 - "GET /api/workspaces/demo/users/notifications/unread/ HTTP/1.1" 200
plane-api  | ERROR 2024-12-11 21:47:18,404 exception_logger 3751 140023704755000 Provided region_name '""' doesn't match a supported format.
plane-api  | 172.18.0.13:55804 - "GET /api/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/v2/issues/?cursor=500:0:0&description=true&updated_at__gt=2024-12-10T13:17:26.813007-08:00 HTTP/1.1" 200
plane-api  | 172.18.0.13:55834 - "GET /api/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/project-members/me/ HTTP/1.1" 200
plane-api  | 172.18.0.13:55796 - "GET /api/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/ HTTP/1.1" 200
plane-api  | ERROR 2024-12-11 21:47:18,426 log 3751 140023711132472 Internal Server Error: /api/assets/v2/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/issues/2468e6e6-4dbb-49ab-bc0a-eaf84bf699db/attachments/
plane-api  | 172.18.0.13:55822 - "POST /api/assets/v2/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/issues/2468e6e6-4dbb-49ab-bc0a-eaf84bf699db/attachments/ HTTP/1.1" 500
plane-api  | 172.18.0.13:55848 - "GET /api/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/deleted-issues/?updated_at__gt=2024-12-10T13:17:26.813007-08:00 HTTP/1.1" 200
plane-api  | 172.18.0.13:55858 - "GET /api/workspaces/demo/projects/f3d17be4-f7e0-4d2e-904f-22535e959d8b/issues/2468e6e6-4dbb-49ab-bc0a-eaf84bf699db/history/?activity_type=issue-property&created_at__gt=2024-12-11T13:47:07.402570-08:00 HTTP/1.1" 200
```

**Comment by akarabach** [comment]
I also can not upload new images 
<img width="1305" alt="Screenshot 2024-12-17 at 13 57 59" src="https://github.com/user-attachments/assets/1c123491-f6b0-48fd-979b-b153c7eaa1b2" />

**Comment by pablohashescobar** [comment]
@Cousclou @sypion, looks like the region name went as `'""'` can you update the `plane.env` and remove any value from the `AWS_REGION`.

@akarabach @isrealbm are you using AWS or the included minio ?

**Comment by sypion** [comment]
> @Cousclou @sypion, looks like the region name went as `'""'` can you update the `plane.env` and remove any value from the `AWS_REGION`.
> 
> @akarabach @isrealbm are you using AWS or the included minio ?

Hey there! I added the region just the other day and that resolved the problem. Thank you for reminding me to update everyone here. Take care!
