### ISSUE TITLE
[bug]: Issue creation box does not go away after clicking out of it

### ISSUE THREAD

**Issue by Peasniped** [makeplane/plane#6225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In KANBAN or List views, when I click on the "+ New Issue" button, a box appears, where I can enter the title of a new issue. When I click away from the box without entering anything, I would expect the box to disappear, but it hangs around. The only way to get rid of the boxes are by reloading, or by collapsing then expanding the section. 

### Steps to reproduce
![plane add issue](https://github.com/user-attachments/assets/83c809dd-0487-483f-8d82-5fe2a4c2efc3)

1. Goto the KANBAN view
2. Click "+ New Issue"
3. Click on something else

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.23.1

**Comment by pushya22** [comment]
Hi @Peasniped, we appreciate your feedback. This design choice was made to avoid accidental clicks that could lead to data loss. As an alternative, pressing the ESC key provides the same functionality.

**Comment by Peasniped** [comment]
Hi @pushya22! Thanks for getting back to me. Fair enough, i'm happy to hear that this is a design feature and not a bug.
I would expect the box to disappear only, when clicking outside of it, if nothing had been entered in it, as such to not lose data.

Happy with your software, i think you guys are doing a great job. Cheers!
