### ISSUE TITLE
[bug]: "Make a Copy" creates an issue with empty description unless you open the source issue just before copying 

### ISSUE THREAD

**Issue by henriquelatorre** [makeplane/plane#6239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The current workflow for copying issues drops the description most of the time: The copy will inherit the Name, Labels, Modules and all other properties from the source issue except the description. If the source issue is opened just before copying the description is correctly filled.

My current workflow relies on frequent issue duplication and this bug makes the process quite frustrating.

The bug hapens with or without the Hyper mode enabled.

Bonus improvement: Add the "Make a Copy" option to the issue visualization interface, it will greatly improve workflows involving issue duplication.

### Steps to reproduce

1. Reload any view with existing issues and use the option "Make a Copy" of issue EG-123 whithout opening issue EG-123
2. Observe the description on the edit dialog will be blank

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.24.1

**Comment by pushya22** [comment]
Hi, @henriquelatorre Thanks for reporting this issue. We are actively working on fix and will part of our next release

**Comment by prateekshourya29** [comment]
Hey @henriquelatorre, we have fixed the issue. It will be available in our next release!
