### ISSUE TITLE
[bug]: API Service not starting - going in a loop

### ISSUE THREAD

**Issue by shiginbhaskar** [makeplane/plane#6261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The API service is not starting, it's going in a loop...

WARN[0000] The "ADMIN_BASE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACE_BASE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_BASE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "ADMIN_BASE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACE_BASE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_BASE_URL" variable is not set. Defaulting to a blank string.
[+] Running 8/8
 ✔ beat-worker Pulled                                                                                                                                 22.2s
 ✔ migrator Pulled                                                                                                                                    22.1s
 ✔ admin Pulled                                                                                                                                       22.1s
 ✔ api Pulled                                                                                                                                         22.1s
 ✔ proxy Pulled                                                                                                                                       22.1s
 ✔ web Pulled                                                                                                                                         22.1s
 ✔ space Pulled                                                                                                                                       21.9s
 ✔ worker Pulled                                                                                                                                      22.2s
[+] Running 12/12
 ✔ Network plane-app_default          Created                                                                                                          0.1s
 ✔ Container plane-app-plane-db-1     Started                                                                                                          0.7s
 ✔ Container plane-app-plane-redis-1  Started                                                                                                          0.7s
 ✔ Container plane-app-plane-minio-1  Started                                                                                                          0.8s
 ✔ Container plane-app-api-1          Started                                                                                                          1.0s
 ✔ Container plane-app-migrator-1     Started                                                                                                          1.3s
 ✔ Container plane-app-beat-worker-1  Started                                                                                                          1.5s
 ✔ Container plane-app-worker-1       Started                                                                                                          1.5s
 ✔ Container plane-app-web-1          Started                                                                                                          1.8s
 ✔ Container plane-app-admin-1        Started                                                                                                          2.7s
 ✔ Container plane-app-space-1        Started                                                                                                          2.8s
 ✔ Container plane-app-proxy-1        Started                                                                                                          3.5s

   Data Migration completed successfully ✅
>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start.........................................................................................................................>> Waiting for API Service to Start...........................................

### Steps to reproduce

--------------------------------------------
 ____  _                          /////////
|  _ \| | __ _ _ __   ___         /////////
| |_) | |/ _` | '_ \ / _ \   /////    /////
|  __/| | (_| | | | |  __/   /////    /////
|_|   |_|\__,_|_| |_|\___|        ////
                                  ////
--------------------------------------------
Project management tool from the future
--------------------------------------------

Select a Action you want to perform:
   1) Install (x86_64)
   2) Start
   3) Stop
   4) Restart
   5) Upgrade
   6) View Logs
   7) Backup Data
   8) Exit

Action [2]: 2

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.6.0

**Comment by shiginbhaskar** [comment]
API Log shows the following:

api-1  | Waiting for database...
api-1  | Database available!
api-1  | No migrations Pending. Starting processes ...
api-1  | Instance already registered
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/functional.py", line 32, in __call__
api-1  |     return self.__value__
api-1  |            ^^^^^^^^^^^^^^
api-1  | AttributeError: 'ChannelPromise' object has no attribute '__value__'. Did you mean: '__call__'?
api-1  |
api-1  | During handling of the above exception, another exception occurred:
api-1  |
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
api-1  |     yield
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 459, in _ensure_connection
api-1  |     return retry_over_time(
api-1  |            ^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
api-1  |     return fun(*args, **kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 934, in _connection_factory
api-1  |     self._connection = self._establish_connection()
api-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 860, in _establish_connection
api-1  |     conn = self.transport.establish_connection()
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/transport/pyamqp.py", line 203, in establish_connection
api-1  |     conn.connect()
api-1  |   File "/usr/local/lib/python3.12/site-packages/amqp/connection.py", line 324, in connect
api-1  |     self.transport.connect()
api-1  |   File "/usr/local/lib/python3.12/site-packages/amqp/transport.py", line 132, in connect
api-1  |     self._connect(self.host, self.port, self.connect_timeout)
api-1  |   File "/usr/local/lib/python3.12/site-packages/amqp/transport.py", line 187, in _connect
api-1  |     self.sock.connect(sa)
api-1  | ConnectionRefusedError: [Errno 111] Connection refused
api-1  |
api-1  | The above exception was the direct cause of the following exception:
api-1  |
api-1  | Traceback (most recent call last):
api-1  |   File "/code/manage.py", line 15, in <module>
api-1  |     execute_from_command_line(sys.argv)
api-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
api-1  |     utility.execute()
api-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
api-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
api-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
api-1  |     self.execute(*args, **cmd_options)
api-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
api-1  |     output = self.handle(*args, **options)
api-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/code/plane/license/management/commands/register_instance.py", line 70, in handle
api-1  |     instance_traces.delay()
api-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/task.py", line 444, in delay
api-1  |     return self.apply_async(args, kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/task.py", line 594, in apply_async
api-1  |     return app.send_task(
api-1  |            ^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/base.py", line 801, in send_task
api-1  |     amqp.send_task_message(P, name, message, **options)
api-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/amqp.py", line 518, in send_task_message
api-1  |     ret = producer.publish(
api-1  |           ^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 186, in publish
api-1  |     return _publish(
api-1  |            ^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 556, in _ensured
api-1  |     return fun(*args, **kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 195, in _publish
api-1  |     channel = self.channel
api-1  |               ^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 218, in _get_channel
api-1  |     channel = self._channel = channel()
api-1  |                               ^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/functional.py", line 34, in __call__
api-1  |     value = self.__value__ = self.__contract__()
api-1  |                              ^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 234, in <lambda>
api-1  |     channel = ChannelPromise(lambda: connection.default_channel)
api-1  |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 953, in default_channel
api-1  |     self._ensure_connection(**conn_opts)
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 458, in _ensure_connection
api-1  |     with ctx():
api-1  |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
api-1  |     self.gen.throw(value)
api-1  |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
api-1  |     raise ConnectionError(str(exc)) from exc
api-1  | kombu.exceptions.OperationalError: [Errno 111] Connection refused
api-1 exited with code 1
api-1  | Waiting for database...
api-1  | Database available!
api-1  | No migrations Pending. Starting processes ...

**Comment by akshat5302** [comment]
Are you on the plane community or commercial edition? @shiginbhaskar

**Comment by shiginbhaskar** [comment]
Plane community edition.

**Comment by akshat5302** [comment]
Could you please share your plane version?

**Comment by akshat5302** [comment]
We have introduced the Rabbitmq service in our recent releases, please upgrade your plane to the newest version by running  `./setup.sh` upgrade in your Plane installation directory

**Comment by shiginbhaskar** [comment]
Thanks. Looks like the upgrade to the latest version worked!!

**Comment by akshat5302** [comment]
This issue is resolved, closing it now.

**Comment by mgn-nikey** [comment]
Have same issue, when I try to build API container, I get this error. I'm on v0.24.1 (latest) and my RabbitMQ service working.
Could you please help, what could it be?

`api             | Instance already registered
api             | Traceback (most recent call last):
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/functional.py", line 32, in __call__
api             |     return self.__value__
api             |            ^^^^^^^^^^^^^^
api             | AttributeError: 'ChannelPromise' object has no attribute '__value__'. Did you mean: '__call__'?
api             | 
api             | During handling of the above exception, another exception occurred:
api             | 
api             | Traceback (most recent call last):
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
api             |     yield
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 459, in _ensure_connection
api             |     return retry_over_time(
api             |            ^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
api             |     return fun(*args, **kwargs)
api             |            ^^^^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 934, in _connection_factory
api             |     self._connection = self._establish_connection()
api             |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 860, in _establish_connection
api             |     conn = self.transport.establish_connection()
api             |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/transport/pyamqp.py", line 203, in establish_connection
api             |     conn.connect()
api             |   File "/usr/local/lib/python3.12/site-packages/amqp/connection.py", line 324, in connect
api             |     self.transport.connect()
api             |   File "/usr/local/lib/python3.12/site-packages/amqp/transport.py", line 132, in connect
api             |     self._connect(self.host, self.port, self.connect_timeout)
api             |   File "/usr/local/lib/python3.12/site-packages/amqp/transport.py", line 187, in _connect
api             |     self.sock.connect(sa)
api             | ConnectionRefusedError: [Errno 111] Connection refused
api             | 
api             | The above exception was the direct cause of the following exception:
api             | 
api             | Traceback (most recent call last):
api             |   File "/code/manage.py", line 15, in <module>
api             |     execute_from_command_line(sys.argv)
api             |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
api             |     utility.execute()
api             |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
api             |     self.fetch_command(subcommand).run_from_argv(self.argv)
api             |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
api             |     self.execute(*args, **cmd_options)
api             |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
api             |     output = self.handle(*args, **options)
api             |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api             |   File "/code/plane/license/management/commands/register_instance.py", line 70, in handle
api             |     instance_traces.delay()
api             |   File "/usr/local/lib/python3.12/site-packages/celery/app/task.py", line 444, in delay
api             |     return self.apply_async(args, kwargs)
api             |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/celery/app/task.py", line 594, in apply_async
api             |     return app.send_task(
api             |            ^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/celery/app/base.py", line 801, in send_task
api             |     amqp.send_task_message(P, name, message, **options)
api             |   File "/usr/local/lib/python3.12/site-packages/celery/app/amqp.py", line 518, in send_task_message
api             |     ret = producer.publish(
api             |           ^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 186, in publish
api             |     return _publish(
api             |            ^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 556, in _ensured
api             |     return fun(*args, **kwargs)
api             |            ^^^^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 195, in _publish
api             |     channel = self.channel
api             |               ^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 218, in _get_channel
api             |     channel = self._channel = channel()
api             |                               ^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/functional.py", line 34, in __call__
api             |     value = self.__value__ = self.__contract__()
api             |                              ^^^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 234, in <lambda>
api             |     channel = ChannelPromise(lambda: connection.default_channel)
api             |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 953, in default_channel
api             |     self._ensure_connection(**conn_opts)
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 458, in _ensure_connection
api             |     with ctx():
api             |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
api             |     self.gen.throw(value)
api             |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
api             |     raise ConnectionError(str(exc)) from exc
api             | kombu.exceptions.OperationalError: [Errno 111] Connection refused
api exited with code 0`
