### ISSUE TITLE
[bug]: Unable to Search Issues for Re-linking After Relationship Removal

### ISSUE THREAD

**Issue by shaolin-tw** [makeplane/plane#6288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

**Description**
When an issue relationship is established and then removed, the issue can no longer be found in the search bar for re-linking. This seems to happen because the search logic excludes issues with deleted relationships.

**Expected Behavior**
Issues with previously deleted relationships should still be searchable and selectable for re-linking.

**Possible Cause**
The search logic likely filters out relationships where deleted_at is not NULL.
Relevant code:
[apiserver/plane/app/views/search/issue.py#L55](https://github.com/makeplane/plane/blob/preview/apiserver/plane/app/views/search/issue.py#L55)

### Steps to reproduce

1. Create a relationship between two issues (e.g., Issue A and Issue B).
2. Remove the relationship between Issue A and Issue B.
3. Try to search for Issue B in the "Relates to" search bar for Issue A.
4. Observe that Issue B does not appear in the search results.

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.24.1

**Comment by pushya22** [comment]
HI @shaolin-tw Thank you for reporting this. We will investigate further and resolve it as soon as possible.

**Comment by pushya22** [comment]
HI @shaolin-tw We have identified the issue and are actively addressing it, the fix will be part of the next release.

**Comment by shaolin-tw** [comment]
Thank you for the quick response and for addressing the issue so promptly! Plane is an amazing project, and I really appreciate all the effort you put into it! 🙌
