### ISSUE TITLE
[feature]: Dark mode and custom theming

### ISSUE THREAD

**Issue by sphynxux** [makeplane/plane#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As Plane gains more popularity, we have received requests from users for a dark mode option to reduce eye strain and provide a more comfortable viewing experience. Additionally, custom theming would allow users to personalize the app to their preferences and potentially increase the app's usability.

To implement dark mode and custom theming, we may need to work on the following tasks:

- Identify the key design elements that need to be changed for dark mode
- Create a new color palette and design guidelines for custom theming
- Implement the necessary changes to the codebase and user interface

Our current target for shipment is the final week of April 2023.

### Why should this be worked on?

Better user experience.

**Comment by vihar** [comment]
Hey @Igorgro, yes it's on the development branch. We will make it live coming Tuesday. We will close the issue after we push this to the master branch.

**Comment by Igorgro** [comment]
I've found a bug already: this input have different text colors in dark mode:

![image](https://user-images.githubusercontent.com/22894169/233477093-6bde46a2-abe6-4bfd-a59b-cc1224c09f88.png)

**Comment by vihar** [comment]
Hey @Igorgro, we are still testing this feature. Our engineer @aaryan610 is working on this issue. I'm sure he's aware of this. But thanks for reporting :) Just curious, did you test this on your self-hosted version?

**Comment by Igorgro** [comment]
Yes, I'm running personal instance right from develop branch)

**Comment by vihar** [comment]
Awesome, thanks for testing this feature out. Do let us know, how it looks, and improvements if any. Soon, we are also launching custom themes, inspired from Slack.

**Comment by vihar** [comment]
Got it, we'll fix this as well.

**Comment by Szymek887** [comment]
Also font in text inputs in dark mode has color pretty similar to background and it is pretty hard to read. I spotted it on delete workspace form

**Comment by vihar** [comment]
Thanks for the feedback @Szymek887, we will fix this.

**Comment by rhea0110** [comment]
Hey @sphynxux, We are pleased to inform you that both the features, Dark Mode and Custom Theming, are now available on the platform for your use.
