### ISSUE TITLE
[feature]: Ability to add attachments to Issues

### ISSUE THREAD

**Issue by sphynxux** [makeplane/plane#710]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

One of the most frequently requested features from our Alpha-launch users has been the ability to add attachments to issues within the issue detail page.

For Plane Cloud users, the free account comes with a file upload limit of 5MB. However, for users who self-host Plane, there is the option to set up unlimited file hosting either locally or on AWS.

![Attachments design](https://user-images.githubusercontent.com/122926002/230024443-246e1e59-b7f2-4b36-b96b-83db2403e8e2.png)

### Why should this be worked on?

This provides greater flexibility for users who need to manage larger files and attachments.

**Comment by pablohashescobar** [comment]
This is already shipped on v0.5-dev and is available on Plane Cloud.
