### ISSUE TITLE
[feature]: Estimations as a sub-property to Issue

### ISSUE THREAD

**Issue by sphynxux** [makeplane/plane#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This feature allows users to set estimations for their issues, providing a more structured approach to planning and tracking their progress on a particular issue.

In addition to setting estimations, users can filter their issues based on estimations, allowing them to easily prioritize tasks and manage their workload. Issues can also be grouped by estimation, providing a more organized view of all issues.

### Why should this be worked on?

Helps plan better.

**Comment by pablohashescobar** [comment]
This feature is already shipped in 0.5-dev and is available on Plane Cloud.
