### ISSUE TITLE
[bug]: First run fails on docker-compose because port 80 is in use

### ISSUE THREAD

**Issue by andy47** [makeplane/plane#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I run `docker-compose up` some of the containers, and in particular nginx, fail to start because ports are already in use.

The provided docker-compose.yml file from the Github repository has `ports: - 80:80` defined which is not going to work on most development machines and will only reliably work on new hosts/servers that are not running any other services.

### Steps to reproduce

1. Follow the install and start instructions from this project web site
2. Attempt to run the application with `docker-compose up`

### Environment

Deploy preview

### Version

Self-hosted

**Comment by vihar** [comment]
It seems that another application may already be using port 80, which is causing the nginx container to fail when running `docker-compose up`. To resolve this issue, please check if any other application is running on port 80 and terminate that process before retrying docker-compose up. Once the conflicting application is stopped, you should be able to successfully start the nginx container and the rest of the application. Let us know if you have any further questions or concerns. Closing this issue for now. Please re-open in case of any issues.

**Comment by andy47** [comment]
It would be preferable if it was possible to define custom ports for this application. Rather than it assuming that it can take over standard ports on a machine which may be running multiple applications and services.

**Comment by markskram** [comment]
yes please, let us specify a different port

**Comment by mkeida** [comment]
Why is this closed? It's still a BIG issue!

**Comment by keymetaphore** [comment]
I think it is not very reasonable to shut down my reverse proxy in order to install this. It will not run on port 80 anyway, so why would the setup need to take up the port?

**Comment by karthik1915** [comment]
I am already running traefik as my reverse proxy, and now i can't install plane and asks me for specify different port, but where?
