### ISSUE TITLE
[bug]: The initial run with docker compose failed

### ISSUE THREAD

**Issue by ajnasaboobacker** [makeplane/plane#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
[3/4] Linking dependencies...
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > recharts@2.4.3" has unmet peer dependency "prop-types@^15.6.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > @blueprintjs/core > react-popper@1.3.11" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0 || ^17.0.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > next-pwa > babel-loader@8.3.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > next-pwa > babel-loader@8.3.0" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > next-pwa > clean-webpack-plugin@4.0.0" has unmet peer dependency "webpack@>=4.0.0 <6.0.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > next-pwa > terser-webpack-plugin@5.3.6" has unmet peer dependency "webpack@^5.1.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > next-pwa > workbox-webpack-plugin@6.5.4" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > recharts > react-smooth@2.0.2" has unmet peer dependency "prop-types@^15.6.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > @remirror/extension-react-tables > @emotion/css > @emotion/babel-plugin@11.10.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > remirror > @remirror/extension-yjs > y-prosemirror@1.2.0" has unmet peer dependency "prosemirror-model@^1.7.1".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > remirror > @remirror/extension-yjs > y-prosemirror@1.2.0" has unmet peer dependency "prosemirror-state@^1.2.3".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > remirror > @remirror/extension-yjs > y-prosemirror@1.2.0" has unmet peer dependency "prosemirror-view@^1.9.10".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > @remirror/extension-react-tables > @emotion/css > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > @remirror/extension-react-tables > @remirror/react-components > multishift > @reach/auto-id@0.16.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > @remirror/extension-react-tables > @remirror/react-components > multishift > @reach/auto-id@0.16.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > @remirror/extension-react-tables > @remirror/react-components > multishift > @reach/auto-id > @reach/utils@0.16.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning "workspace-aggregator-3b7daf84-f8e7-4836-81de-ab25764bb7f7 > app > @remirror/extension-react-tables > @remirror/react-components > multishift > @reach/auto-id > @reach/utils@0.16.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
[4/4] Building fresh packages...
error /app/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node ./scripts/install.js
Arguments:
Directory: /app/node_modules/@sentry/cli
Output:
info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.74.6/sentry-cli-Linux-aarch64
Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.74.6/sentry-cli-Linux-aarch64.
Error code: ECONNREFUSED
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
1 error occurred:
        * Status: The command '/bin/sh -c yarn install' returned a non-zero code: 1, Code: 1

### Steps to reproduce

Just followed the instruction from the github readme.

Additionally i edited the docker-compose to change the 80 port, to 8013 since my 80 port is already used.

Run the docker-compose up -d and this is what i see on the terminal.

### Environment

Production

### Version

Self-hosted

**Comment by vihar** [comment]
Hey @ajnasaboobacker, we have fixed this in our develop branch and it should be fairly stable we are still testing it and fixing. This issue is also related to #477.

**Comment by LoudSoftware** [comment]
I am running into the same issue with both the latest tag and commit on the develop branch.
```
[...]
#0 47.32 [4/4] Building fresh packages...
#0 47.45 error /app/node_modules/@sentry/cli: Command failed.
#0 47.45 Exit code: 1
#0 47.45 Command: node ./scripts/install.js
#0 47.45 Arguments: 
#0 47.45 Directory: /app/node_modules/@sentry/cli
#0 47.45 Output:
#0 47.45 [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.75.2/sentry-cli-Linux-x86_64
#0 47.45 Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.75.2/sentry-cli-Linux-x86_64.
#0 47.45 Error code: ECONNREFUSED
#0 47.45 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1
```

**Comment by hansklepitko** [comment]
Same error with me:

```
 => ERROR [plane-web installer  7/13] RUN yarn install --network-timeout 500000                                                                                                                           37.6s
------                                                                                                                                                                                                          
 > [plane-web installer  7/13] RUN yarn install --network-timeout 500000:                                                                                                                                       
0.409 yarn install v1.22.19                                                                                                                                                                                     
0.491 [1/4] Resolving packages...                                                                                                                                                                               
0.824 [2/4] Fetching packages...                                                                                                                                                                                
25.23 [3/4] Linking dependencies...                                                                                                                                                                             
25.23 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > @nivo/core@0.80.0" has unmet peer dependency "@nivo/tooltip@0.80.0".
25.23 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > @nivo/core@0.80.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
25.23 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > @nivo/legends@0.80.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
25.23 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > @nivo/line@0.80.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
25.23 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > @blueprintjs/core > react-popper@1.3.11" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0 || ^17.0.0".
25.23 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > @nivo/bar > @nivo/axes@0.80.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
25.23 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > @nivo/bar > @nivo/colors@0.80.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
25.24 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > next-pwa > babel-loader@8.3.0" has unmet peer dependency "@babel/core@^7.0.0".
25.24 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > next-pwa > babel-loader@8.3.0" has unmet peer dependency "webpack@>=2".
25.24 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > next-pwa > clean-webpack-plugin@4.0.0" has unmet peer dependency "webpack@>=4.0.0 <6.0.0".
25.24 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > next-pwa > terser-webpack-plugin@5.3.7" has unmet peer dependency "webpack@^5.1.0".
25.24 warning "workspace-aggregator-736655cb-b543-44b0-8902-16c10cde72c6 > app > next-pwa > workbox-webpack-plugin@6.5.4" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
36.81 [4/4] Building fresh packages...
36.96 error /app/node_modules/@sentry/cli: Command failed.
36.96 Exit code: 1
36.96 Command: node ./scripts/install.js
36.96 Arguments: 
36.96 Directory: /app/node_modules/@sentry/cli
36.96 Output:
36.96 [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.75.2/sentry-cli-Linux-x86_64
36.96 Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.75.2/sentry-cli-Linux-x86_64.
36.96 Error code: ECONNREFUSED
36.96 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install --network-timeout 500000" did not complete successfully: exit code: 1
```

I checked my DNS sinkhole just to make sure. I am able to properly resolve `https://yarnpkg.org`
