### ISSUE TITLE
[feature]: Provide pre-build docker images for all components (or mono image)

### ISSUE THREAD

**Issue by TheZoker** [makeplane/plane#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently when a user uses the docker compose setup, all images need to be build. It would be nice if the images are pre build and pushed to dockerhub or github docker packages. 

Maybe even a single docker image could be provided for API, frontend and worker. 

### Why should this be worked on?

To simplify the setup and remove the need to build the images on the users system.

**Comment by vihar** [comment]
Hey @TheZoker, thank you for your interest in our product. I am writing to inform you that we are currently in the process of creating a new image, which we plan to release with our next update. We will keep you informed of any developments

**Comment by pablohashescobar** [comment]
Hi @TheZoker, 

We have upgraded our docker setup and pushed pre-built images to DockerHub and also updated have a compose file to setup this `docker-compose-hub.yml` currently this is available on our develop branch and we are still testing it.

**Comment by TheZoker** [comment]
Thanks for the heads up! I will try it out. 
Is there a chance, that there will be a unified docker package for all the components (maybe except database)?
Similar to how bitwarden does it:
https://github.com/bitwarden/server/blob/master/docker-unified/docker-compose.yml

**Comment by pablohashescobar** [comment]
We're happy to announce that this issue is now resolved and we have successfully pushed all the required images to Docker Hub. As a result, we are closing this issue. If you have any further questions or concerns, please don't hesitate to reach out. Thank you for your cooperation and patience throughout this process!

**Comment by leikoilja** [comment]
took a minute to find the registry since it's not quite a "unique" name: 
https://hub.docker.com/u/makeplane

**Comment by vihar** [comment]
thanks for sharing this here, @leikoilja 🙏🏻.
