### ISSUE TITLE
[feature]: API?

### ISSUE THREAD

**Issue by mikhailnov** [makeplane/plane#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Does Plane have an API or a cli interface? It would be useful for such scenario: users commit to git with refenrence to task, a script automatically posts information about the commit into Plane.

### Why should this be worked on?

.

**Comment by pablohashescobar** [comment]
Hi @mikhailnov, This feature has been shipped in the [0.14-dev](https://github.com/makeplane/plane/releases/tag/v0.14-dev) release. For more reference on APIs usage you can follow [docs](https://docs.plane.so/apis/introduction).
