### ISSUE TITLE
[feature]: ghcr or docker hub container release

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Would it be possible for plane to be released as a ghcr or docker hub container?

### Why should this be worked on?

This would allow plane to be more easily deployed on services that let users deploy with just a docker compose file or for example unraid.

**Comment by vihar** [comment]
Thanks for raising this PR, we'll work on this. Related to, #736

**Comment by Quadrubo** [comment]
Ah okay, sorry for the duplicate then, gonna close this.
