### ISSUE TITLE
Email login broken on Firefox & Firefox Mobile

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to sign up or login into the application results in a short lived error message "Oops" in the top right corner followed by a page reload.

I tested this in both Firefox developer version on endeavourOS Linux and Android. I also tested it using the bormal Firefox Version on Linux. On chrome everything seems to be working.

### Steps to reproduce

1. Navigate to the sign-up page using Firefox
2. Enter your email address

### Environment

Production

### Version

Cloud

**Comment by vihar** [comment]
We are testing this issue, we'll resolve this soon. Thanks for bringing this to our attention.

**Comment by sphynxux** [comment]
This issue is fixed on #802. We'll promote this to production soon.
