### ISSUE TITLE
[feature]: Password authentication in the cloud version

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I think it would be a good idea to add password authentication to the cloud version. The feature should of course be made optional so people who prefer magic links can use those.

### Why should this be worked on?

Advantages of Passwords over Magic Links:

1. Passwords are quicker to enter and require fewer steps. With magic links i need to request a link, login to the email, open the link from the email. A password can be easily remembered or autofilled.
2. On a device that doesn't have access to the email inbox of the plane account, it is hard to use magic links. I have to either send the magic link over an insecure channel or type the link manually which is clunky.

**Comment by vihar** [comment]
Thank you for raising this feature request. We should definitely add password-based authentication to make the sign-up process smoother on both cloud and self-hosted platforms. We'll pick this up very soon.

**Comment by pablohashescobar** [comment]
Hi @Quadrubo, password authentication has been added to Plane cloud you can check the new flow in the [app](https://app.plane.so). More reference [here](https://docs.plane.so/sign-up-sign-in). Closing this issue.
