### ISSUE TITLE
[feature]: allow exporting issues list to CSV or Open Document Spreadsheet

### ISSUE THREAD

**Issue by eth0OS** [makeplane/plane#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Inserting a single button on the issues view allowing exporting the issues list to an open format as CSV or ODS.

### Why should this be worked on?

This would allow for some interchangeably since the information about the issues dealt in a period could be pasted in some kind of presentation or document.

**Comment by srinivaspendem** [comment]
Hello @eth0OS, this feature has been developed. You can find it [here](https://github.com/makeplane/plane/pull/1781).
