### ISSUE TITLE
[feature]: Allow to run on alternate ports

### ISSUE THREAD

**Issue by jontstaz** [makeplane/plane#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have a home server on which I run a wide variety of apps. I tend to avoid using port 80, 3000, etc. for any apps that aren't my server management dashboard and portainer. I tried changing the port assignments in the docker-compose.yml file directly but it appears the ports are hardcoded elsewhere. For reference I changed the `nginx` port mapping to `3137:80`, the `plane-web` mapping to `3005:3000` and the `plane-api` mapping to `8005:8000`.

### Why should this be worked on?

It's best-practice to allow users to specify what ports they prefer for containerised applications. It gives more flexibility and allows multiple apps to run side-by-side on the same server/machine without interfering with each other.

**Comment by andy47** [comment]
+1

**Comment by HuyNguyenAu** [comment]
I have managed to change the port by doing the following:
```
$ ./setup.sh localhost:8000 # <--- Make sure this matches the `plane-api` port defined in `docker-compose.yml`.
```

**Comment by pablohashescobar** [comment]
Hello @jontstaz! We wanted to inform you that in the current setup, we have made it possible for you to specify the `NGINX_PORT` of your choice. This allows you to run the application on an alternate port instead of the default port 80.
