### ISSUE TITLE
[bug]: Missing error feedback on onboarding form

### ISSUE THREAD

**Issue by luc122c** [makeplane/plane#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating a new workspace, if you enter an invalid slug, no error message is shown on the frontend. 

### Steps to reproduce

1. Create a new account and get to https://app.plane.so/onboarding to create a new workspace
2. Enter an 'invalid' workspace name, such as `one.two` or `three?four`, see that it populates the slug with invalid characters
3. Click 'Create Workspace' 
4. See that no error message is displayed to the user. In the console, there is an error message: `Enter a valid "slug" consisting of letters, numbers, underscores or hyphens.`

### Environment

Production

### Version

Cloud

### Screenshot
![Screenshot 2023-04-13 at 12 20 50](https://user-images.githubusercontent.com/7257092/231743486-9f48b51c-ec10-481a-a119-7d53b5520642.png)

**Comment by anmolsinghbhatia** [comment]
Thank you for reporting this issue, we have raised a PR (#809) to fix this and it will be live with our next release soon.
Thank you for your patience.
