### ISSUE TITLE
[bug]: Cannot upload file on self-hosted

### ISSUE THREAD

**Issue by letieu** [makeplane/plane#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running self-hosted version, I cannot upload file to s3. I was add aws config to .env file and try rebuild image. I was check my AWS config detail and it work on another project.

- My codebase in this commit: 657241c9c1133de8d995c2e2e614dd42d7875cac 

### Steps to reproduce

- Add AWS config to .env file
- Rebuild docker image with: docker-compose build
- Run app with docker-compose up
- Try upload image ( change avatar, upload file to issue) -> server error 400.

```
{ error : "Something went wrong please try again later" }
```

### Environment

Deploy preview

### Version

Self-hosted

**Comment by vihar** [comment]
Hello @letieu, we've tried reproducing the bug, but haven't had any issues. Can you share us any logs?

**Comment by letieu** [comment]
I don't see any error log on server

**Comment by letieu** [comment]
> Hello @letieu, we've tried reproducing the bug, but haven't had any issues. Can you share us any logs?

Only have this log:

planebackend   | 167.172.70.214:45696 - "POST /api/workspaces/soinmedia/projects/04b0d163-706b-481f-989a-9ed9d47af09d/issues/f5b186f2-b259-446a-9b51-82c3ed6ddbf6/issue-attachments/ HTTP/1.1" 400

**Comment by pablohashescobar** [comment]
Hey @letieu, we were unable to replicate this issue at our end, we have pushed the latest changes to `master` branch please try rebuilding the container on the master branch and let us know if you still face this issue.

**Comment by pablohashescobar** [comment]
Hello @letieu! The issue you reported has been successfully resolved. We appreciate your patience and understanding throughout the process. If you encounter the same issue, please don't hesitate to reach out or reopen the issue. Thank you for your valuable feedback and cooperation!
