### ISSUE TITLE
[feature]: Audit Logs

### ISSUE THREAD

**Issue by Pdzly** [makeplane/plane#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would suggest a Audit Log for Projects and Single Pages, where actions like create issues, delete issues, moving issues etc. like all actions that is possible to log.

With the attributes: Action Name, Action Time, User that triggered it.

### Why should this be worked on?

This could improve the auditability of actions user of that board made.

**Comment by aaryan610** [comment]
Hello @Pdzly, thank you for suggesting this feature. Project activity is a good feature to have. Our team will brainstorm on it and try to ship it in the near future.

**Comment by vihar** [comment]
Audit Logs are part of our enterprise plan. Please reach out to support@plane.so for more details. You can find feature packaging on our [pricing page](https://plane.so/pricing).
