### ISSUE TITLE
[bug]: Error while following self-hosting guide on Windows

### ISSUE THREAD

**Issue by Chris-Greaves** [makeplane/plane#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Following the self-host guide using docker-compose, planebackend errors on a loop.
The error is `exec ./bin/takeoff: no such file or directory`

### Steps to reproduce

Follow these steps on windows https://github.com/makeplane/plane#docker-compose-setup
(git clone pulled the `develop` branch)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by Chris-Greaves** [comment]
Tried on both develop and master and both don't work with the same error.
![image](https://user-images.githubusercontent.com/28542943/232662666-d13b4c34-ed41-4c1d-bc5e-7e593df2bf02.png)

**Comment by dakshesh14** [comment]
Hello @Chris-Greaves, we have conducted some tests on the docker self-host feature in our Windows machine and were able to replicate the issue you reported. However, we have found a solution to this problem. By running the following command in Powershell, we were able to get rid of the errors:

```
(Get-Content apiserver/bin/takeoff -Raw) -replace "rn", "n" | Set-Content apiserver/bin/takeoff -NoNewline
(Get-Content apiserver/bin/worker -Raw) -replace "rn", "n" | Set-Content apiserver/bin/worker -NoNewline
```

**Comment by Chris-Greaves** [comment]
Hello, your scripts were missing the backticks ( ` ) although I'm guessing that was Github's fault. I saw what you were trying to do tho so thank you. 

For anyone else finding this, there is a backtick before the `r` and `n` in the replace arguments.

I've uploaded a text file with the commands (I couldn't upload it as a ps1, but you could just change the extension to ps1 and I'll be a valid powershell script)
[windows-lineendings-fix.txt](https://github.com/makeplane/plane/files/11267991/windows-lineendings-fix.txt)

**Comment by Chris-Greaves** [comment]
The question is, does this need documenting? 
Should this issue be closed as we have solved it, or leave it open until the docs are updated or a script is added just for Windows users?

I leave that up to you guys!

**Comment by vihar** [comment]
@Chris-Greaves, my apologies for the delayed follow-up. We've implemented some substantial modifications to our self-hosting setup. Kindly refer to the instructions provided in our documentation at https://docs.plane.so/self-hosting/docker-compose. If you're still facing issue, let us know.
