### ISSUE TITLE
[bug]: only single workspace image possible

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the workspace switcher on the top left, the workspaces all get the same randomly generated image with a letter depending on the currently open project, not the letter of the actual workspace. This issue appears both in cloud and self hosted.

![Screenshot from 2023-04-18 17-42-54](https://user-images.githubusercontent.com/71718414/232831142-9c11f6f6-b9a4-49b5-880f-57f94c19051d.png)
![Screenshot from 2023-04-18 17-43-00](https://user-images.githubusercontent.com/71718414/232831145-920b0dac-33cc-40c6-adf7-59512119245e.png)

### Steps to reproduce

1. Add 2 workspaces with different letters at the beginning of their name.
2. Open the workspace switcher in the top left corner.

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by rhea0110** [comment]
Hey @Quadrubo, thank you for reporting this bug to us. Our engineers will address it and fix it in our next release. We will keep you updated with our releases.

**Comment by aaryan610** [comment]
Hey @Quadrubo, this issue has been resolved in PR #903. It's currently in the develop branch, and will be pushed into master with the next release. Thank you.

**Comment by Quadrubo** [comment]
This is now fixed on the selfhosted and cloud version
