### ISSUE TITLE
[bug]: docker-compose-hub.yml broken with domain other than localhost

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The docker-compose-hub.yml file is broken for domains other than localhost. The frontend doesn't respect the NEXT_PUBLIC_API_BASE_URL and tries to make the API calls to localhost:8000 which obviously fails.

### Steps to reproduce

1. Follow the installation but use the docker-compose-hub.yml file
2. Use a domain other than localhost

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by gcarrarom** [comment]
Big issue here is related to https://github.com/makeplane/plane/issues/884

I will share my work in progress tomorrow as an example of what could be used.

**Comment by moquito64** [comment]
Was looking at this a bit today cause I ran into this issue as well. I went through all the files that mention localhost and adjusted it to the ip address of the vm I was using. It still seems to fail with a http://localhost:8000/api/users/me/ 
![image](https://user-images.githubusercontent.com/6897956/233805636-1e6e233c-d55f-46bc-94f2-079b64b2d784.png)

**Comment by Quadrubo** [comment]
> Was looking at this a bit today cause I ran into this issue as well. I went through all the files that mention localhost and adjusted it to the ip address of the vm I was using. It still seems to fail with a http://localhost:8000/api/users/me/ ![image](https://user-images.githubusercontent.com/6897956/233805636-1e6e233c-d55f-46bc-94f2-079b64b2d784.png)

Yeah I also tried this myself, not deep enough within the codebase to figure out why this happens so I decided to make this issue.

**Comment by Quadrubo** [comment]
I can confirm this issue being fixed on the newest version #994

**Comment by gcarrarom** [comment]
Trying the new image version from dockerhub (https://hub.docker.com/r/makeplane/plane-backend/tags) it still uses localhost on 0.6. 

@Quadrubo , did you have to build the images yourself?

**Comment by Quadrubo** [comment]
To migrate i needed to pull the new changes, copy my key into the new general .env file and rebuild the container.
