### ISSUE TITLE
[feature]: Add story points

### ISSUE THREAD

**Issue by Igorgro** [makeplane/plane#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Implement story points - they help to measure how hard the specific task relatively to other tasks

### Why should this be worked on?

Story points are one of core concepts of Agile methodology  and should be supported in such Agile software as Plane is.

**Comment by vihar** [comment]
Hey @Igorgro, we have a feature called **Estimates** that was shipped recently. This could used to add points to issues in a more custom way. Do check it out, the docs for this feature will be out soon. 

Please check the [release notes](https://github.com/makeplane/plane/releases/tag/v0.5-dev) to learn more about this feature. If there's anything that we could do on Estimates, do let us know and keep the issue open :)

**Comment by Igorgro** [comment]
Sorry didn't noticed them 😅. I see the only problem with them is that there is hardcoded number of 6 points, which cannot be canged somehow

**Comment by vihar** [comment]
No problem :) Here's some info about the estimate points:

- You can create any kind of estimates, and upto 8 points that you can customise any time.
- You can switch between estimates anytime, the point will be directly mapped from the order based on the last estimates.

Of course, we should have more docs on this. We'll add this soon.

**Comment by Igorgro** [comment]
I'm sorry, maybe I'm blind, but I don't see, how I can change the number of points:

![image](https://user-images.githubusercontent.com/22894169/232901954-94b97273-a7c1-43a9-a4d7-b3ee6796a225.png)

If I left some of fields empty, I get the following error:

![image](https://user-images.githubusercontent.com/22894169/232902139-df747244-7151-450d-9ea6-9825b1280685.png)

**Comment by vihar** [comment]
Ahh, my bad. We only support 6. So sorry. 

And we'll need to add all six points. This feature is still in beta, and we are taking as much feedback as possible.

Here are somethings we can improve on,
- Have a easy UX to create, add and update issue points.
- Remove validation for estimates, we can have atleast 2 estimate points by default. Rest is upto user's choice. 

Is there anything that you would like to add on?

**Comment by Igorgro** [comment]
Maybe to improve switching between estimates: currently you should press "disable estimates" and the select an estimate and click "use estimate". It would be better. if ue can just select an estimate and activate it without need to press "disable"

**Comment by vihar** [comment]
understood, we'll make this update for the next release. thanks for the feedback.

**Comment by rhea0110** [comment]
Hey @Igorgro, We are delighted to inform you that this feature, along with its related issues, has been resolved and is now available for use in the app.plane.so.

**Comment by Igorgro** [comment]
@rhea0110 I'm sorry,but I cannot consider this issue as fixed, because I can't still change the number of estimate points. If I type less than 6 points I get the following error:

![image](https://github.com/makeplane/plane/assets/22894169/cf9924c9-f729-4559-9833-b2027df7e227)
