### ISSUE TITLE
[feature]: Internal and public issues

### ISSUE THREAD

**Issue by Igorgro** [makeplane/plane#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Let's imagine the following situation (I'm sure this is not uncommon among teams): my team wants to keep it's work planning private, but to allow external people to create issues in separate public zone. If someone from team wants to work on user request, they copies public user request to pivate issues, split it into sub-issues, etc. When the internal issue is closed, the public one is closed also, providing feedback to users.

### Why should this be worked on?

This will allow to use plane not only as task tracker, but also as a tool to handle user requests

**Comment by vihar** [comment]
Thanks for raising this PR, @Igorgro. We are working on a feature called "INBOX", which lets you take issue requests from external users. Since, you've already created this FR, we'll continue the conversation about this here.

Thanks again :)

**Comment by docimin** [comment]
This is something I need as well, however I would not like to manually accept issues via the INBOX. This should then at least be a setting. We have a lot of issues a week for bug reports our users have for us.

I think the best practice for this is more advanced role management. For example public (anonymous users) can create issues and see the workspace, but not delete or do anything else. :)

**Comment by dennisrahmen** [comment]
@docimin there is a topic "Automation" on the roadmap, I would imagine that you could then add automations for the items in the INBOX to automtically create issues.

**Comment by vihar** [comment]
Thanks, @Igorgro, for all the feedback and conversation on this thread. We shipped Inbox a few months back, and now it’s stable and free on the community edition. More documentation [here](https://docs.plane.so/core-concepts/inbox).

You can enable this feature when creating a project, or by navigating to `Project > Settings > Features > Toggle Inbox`.
