### ISSUE TITLE
[feature]: Add markdown tasks

### ISSUE THREAD

**Issue by Igorgro** [makeplane/plane#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add suport for markdown tasks lists (`- [ ] Some task`) with a counter of opened/done tasks on issues overview page and boards (like it is done here on GitHub).

### Why should this be worked on?

Tasks are useful when the issue can be divided into small steps, which are too small themself to become a separate issues.

**Comment by Quadrubo** [comment]
I'd suggest to instead of working on this feature seperately, just to work on supporting the complete markdown syntax in general. I don't really know what Plane currently uses but I had a few things from Markdown which didn't work for me. What do you guys think about that?

**Comment by Igorgro** [comment]
I can recommend TipTap editor https://tiptap.dev/installation/react

**Comment by Quadrubo** [comment]
TipTap is just an editor, one should work on a general markdown spec that will be implemented across the application.

**Comment by vihar** [comment]
this issue is fixed on our latest release, `v0.14-dev`.
