### ISSUE TITLE
[feature]: Notifications

### ISSUE THREAD

**Issue by Quadrubo** [makeplane/plane#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Notifications could be used to send reminders on issue's (by due date maybe?), cycles, etc.
I think plane should support multiple drivers for notifications such as email, ntfy, etc. for maximum compatibility. 

Id be interested in [ntfy](https://ntfy.sh/) as that is a standardized cross platform solution.

### Why should this be worked on?

Notifications are an integral part of project management, especially for managing deadlines.

**Comment by vihar** [comment]
Hey @Quadrubo, we are already working on this feature. We'll keep you posted once this is out.

**Comment by Quadrubo** [comment]
Ah okay that's great news. I didn't see an issue for it yet.

**Comment by vihar** [comment]
Absolutely, let's keep the issue open so that the community can subscribe to it and stay informed about the progress of this feature.

**Comment by kirtan403** [comment]
Would love to see the progress on this

**Comment by vihar** [comment]
**Notifications Phase - I** is now available on Production. Refer, https://github.com/orgs/makeplane/discussions/1667 to see all the supported features. If there are any enhancements, please open an new issue. Thanks 🙏🏻.
