### ISSUE TITLE
[bug]: Creating multiple Issues without ticking "Create more" clears the 2nd popup

### ISSUE THREAD

**Issue by Pdzly** [makeplane/plane#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After i created a issue and try to create after few seconds another issue the modal gets cleared and i have to retype everything.

Of course it is already a workaround with "Create more" Slider and because of that it could be a low prio issue.

### Steps to reproduce

1. Go to Projects
2. Create Issue and finish it
3. Try to create a issue withing 2-3 seconds
4. ( The new Modal gets cleared of any content )

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @Pdzly, thank you for reporting this bug. We acknowledge the issue and assure you that we are actively working on it. We plan to have it resolved and included in one of our upcoming releases.

Thank you!

**Comment by yaikohi** [comment]
I was about to make an issue report for this as well; glad it's already been noted!

**Comment by rhea0110** [comment]
Hey @Pdzly, this issue has already been fixed and is live on app.plane.so.

Thanks!
