### ISSUE TITLE
[feature]: ldap support

### ISSUE THREAD

**Issue by guos** [makeplane/plane#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

is there any plan for integration ldap for user management.?

### Why should this be worked on?

then, we can use LDAP to manage user like JIRA

**Comment by a1batross** [comment]
Looking for LDAP support as well!

**Comment by Shauno-DUG** [comment]
+ 1 for ldap 👍

**Comment by jaavid** [comment]
also we Looking for LDAP !

**Comment by andjoye** [comment]
1 for ldap

**Comment by theparthacus** [comment]
LDAP will come to our highest-tier plan when it does come. we are thinking more than six months out.

**Comment by fraenki** [comment]
> LDAP will come to our highest-tier plan when it does come. we are thinking more than six months out.

So you're closing this issue, although the feature was not implemented yet? :open_mouth:

**Comment by fraenki** [comment]
Since this is one of the TOP 10 most requested features, I ask you to re-open this issue.

**Comment by a1batross** [comment]
>highest-tier plan 

That's it guys, nothing to see here anymore.
