### ISSUE TITLE
[bug]: Can't delete workspace

### ISSUE THREAD

**Issue by Szymek887** [makeplane/plane#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I created test workspace and when trying to delete it nothing happens. After looking at the network card of Safari inspector it shows error 500 Internal Server Error. I deployed app using the docker-compose.yml on development branch. I run setup.sh script with https://local.domain parameter but it failed with error broken pipe. I manually changed API URL in application .env to https://local.domain.

My app is running behind a traefik reverse proxy with let's encrypt certs, this is why I changed the url to https.

### Steps to reproduce

1. Deploy app with docker-compose.yml
2. Run setup.sh script with https://local.domain parameter
3. Manually change the app .env, because it now has http://https://local.domain
4. Login and create test workspace
5. Try to delete workspace

### Browser

Safari

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hello @Szymek887,

We wanted to let you know that we have made updates to our Docker setup, and have pushed several commits to our development branch. This should resolve the issues you were experiencing.
