### ISSUE TITLE
[bug]: Creating Cycles fails on self hosted

### ISSUE THREAD

**Issue by heromiyo** [makeplane/plane#947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i click create Cycle i get an error 
![image](https://user-images.githubusercontent.com/39757927/233959812-68876c70-780d-421e-8c19-707cb3ea5768.png)

![image](https://user-images.githubusercontent.com/39757927/233960039-18e9491d-1c1b-447a-bf3a-477b28a6d308.png)

I expect the cycle to be created

### Steps to reproduce

1. Clone the latest version on develop branch 
2. Deploy
3. Login and create Cycle on a project

### Browser

Google Chrome

### Version

Local

**Comment by necrogami** [comment]
```
planebackend   | 172.19.0.7:55860 - "POST /api/workspaces/c4/projects/4b52ac88-db2a-4496-b86e-ea4f2533c37f/cycles/date-check/ HTTP/1.0" 200
nginx          | 172.19.0.1 - - [09/May/2023:20:41:50 +0000] "POST /api/workspaces/c4/projects/4b52ac88-db2a-4496-b86e-ea4f2533c37f/cycles/date-check/ HTTP/1.1" 200 15 "http://localhost/c4/projects/4b52ac88-db2a-4496-b86e-ea4f2533c37f/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
db             | 2023-05-09 20:41:51.548 UTC [265] ERROR:  column "view_props" of relation "cycles" does not exist at character 185
db             | 2023-05-09 20:41:51.548 UTC [265] STATEMENT:  INSERT INTO "cycles" ("created_at", "updated_at", "created_by_id", "updated_by_id", "id", "project_id", "workspace_id", "name", "description", "start_date", "end_date", "owned_by_id", "view_props") VALUES ('2023-05-09T20:41:51.547929+00:00'::timestamptz, '2023-05-09T20:41:51.547941+00:00'::timestamptz, 'd0e92e85-eb16-45b0-941a-3629f89c11bf'::uuid, 'd0e92e85-eb16-45b0-941a-3629f89c11bf'::uuid, '46824c0f-981e-4348-a9b0-f7c1a1c7ade0'::uuid, '4b52ac88-db2a-4496-b86e-ea4f2533c37f'::uuid, '6f9c29e0-90d4-41c6-b786-44ddb02ee5d8'::uuid, 'Sprint1', 'Sprint1', '2023-05-15'::date, '2023-05-21'::date, 'd0e92e85-eb16-45b0-941a-3629f89c11bf'::uuid, '{}')
```

**Comment by pablohashescobar** [comment]
Hello @heromiyo! The issue has been successfully resolved in the latest Docker setup. We sincerely appreciate you bringing this matter to our attention. If you encounter any further difficulties or if the issue persists, please don't hesitate to reopen the issue.
