### ISSUE TITLE
[bug]: setup.sh always uses http://, which breaks things when trying to host the API over https.

### ISSUE THREAD

**Issue by Chris-Greaves** [makeplane/plane#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you run `setup.sh my.domain.dev` it'll add the `NEXT_PUBLIC_API_BASE_URL` variable into the .env file. 

```sh

echo -e "\nNEXT_PUBLIC_API_BASE_URL=http://$1"  >> ./apps/app/.env

```
As you can see, it forces `http` with no option for `https`. Some top-level domains (like, .dev) require all traffic to go across https, which this breaks. I noticed it was doing this when I got mine hosted and I couldn't log in due to the following error.
![image](https://user-images.githubusercontent.com/28542943/234162748-407e7578-2cfe-4b93-b03b-674c7e927d96.png)

### Steps to reproduce

1. Run the `setup.sh` script
2. Build the images using `docker compose build`
3. Host the frontend and backend on https domains
4. Try and log in

### Browser

Google Chrome

### Version

Self-hosted

**Comment by itsOnly1Jah** [comment]
Experiencing this problem as well

**Comment by pablohashescobar** [comment]
Hi, this will be fixed in the upcoming release (already on `develop` branch).

**Comment by pablohashescobar** [comment]
Hello @Chris-Greaves! We're pleased to inform you that the issue you reported has been successfully resolved in the new `./setup.sh script`. The updated version now requires the protocol as well when executing the command. You can use `./setup.sh https|http://<IP|Domain>` for proper configuration. We would appreciate it if you could test this new setup and let us know if you encounter any further difficulties. If the issue persists or if you have any additional concerns, please don't hesitate to reopen the issue. We're here to assist you further. Thank you for your patience and cooperation!
