### ISSUE TITLE
[bug]: User assignment icons are invalid when user leaves

### ISSUE THREAD

**Issue by Pdzly** [makeplane/plane#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i assign someone to a issue and he leaves the icon gets cleared of the issue.

![grafik](https://user-images.githubusercontent.com/34943569/235310880-e0ab2ded-acb4-4d04-91c9-364974fb1d64.png)

It should either behave like: 

It gets removed cleanly from all issues or his icon or a default icon should be shown. ( my opinion )

### Steps to reproduce

1. Assign a Issue to a user
2. the user leaves
3. the icon doesnt show it anymore but it is still assigned.

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by rhea0110** [comment]
Hey @Pdzly, we are delighted to inform you that we have already fixed this issue, and it is now live on our website.

Thank you!
