### ISSUE TITLE
[bug]: Unsplash proxy API inaccessible

### ISSUE THREAD

**Issue by Web-eWorks** [makeplane/plane#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When loading the project settings page or attempting to make a new project on the current `develop` branch (160b4a4), the image picker tries to load `<host>/api/unsplash` to proxy the actual Unsplash API call. This endpoint returns 404 because it's attempting to read from the Django `apiserver` service on port 8000 rather than the web service on port 3000 (where the `/api/unsplash` handler appears to be served from).

This prevents the project image from being able to be changed.

### Steps to reproduce

1. Self-host Plane `develop` branch on localhost
2. Create a new project in your workspace
3. Go to the workspace settings
4. Observe an XHR GET error in the console
5. Unable to change the workspace splash image

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by piyushgarg-dev** [comment]
Please Check PR #1176 
@rhea0110

**Comment by vihar** [comment]
@Web-eWorks, I apologize for the tardy response. The issue has been resolved in v0.13-dev. If you encounter any further difficulties, please don't hesitate to inform us.
