### ISSUE TITLE
[bug]: Uploaded files not accessible on self-hosted version

### ISSUE THREAD

**Issue by Web-eWorks** [makeplane/plane#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When not using AWS S3 bucket storage for uploaded files, the `https://<host>/uploads/<asset>` path is not served by any Plane components. I've confirmed uploaded files are being created in the (transient) `plane-api` container, but attempting to access the uploaded files fails with a 404 error.

This impacts project logos, user avatars, and issue attachments.

I believe I've seen official communication from the Plane team that Plane intends to support serving files from disk for self-hosted instances, as S3 is significantly more operational overhead than needed for a small self-hosted Plane instance. I expect that a self-hosted instance should work "out of the box" when serving uploaded assets without S3 storage.

### Steps to reproduce

1. Self-host Plane without an AWS S3 configuration
2. Create a Workspace, Project, and Issue
3. Upload an asset (image file) to the issue
4. Attempt to open the attached image file
5. Observe 404 page

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @Web-eWorks thanks for reporting this issue we are still working on improving our self-hosted setup. We will picking up this issue in our upcoming releases.

**Comment by pablohashescobar** [comment]
Hi @Web-eWorks, this issue has been fixed in the current Docker setup and now the image uploads should be reflected in the self-hosted version. Thanks for your patience and support if you are still facing any issue feel free to reopen this issue.

**Comment by MFYDev** [comment]
I just installed the latest version and still have this issue. Could you please tell me how to solve? All my uploaded image url will be localhost/uploads instead of the real url @pablohashescobar

**Comment by pablohashescobar** [comment]
HI @MFYDev, can you try configuring `WEB_URL` variable in `apiserver/.env` to your current hosted url `http://{app_domain}`.
