### ISSUE TITLE
[bug]: Forgot password link treated as workspace slug

### ISSUE THREAD

**Issue by Web-eWorks** [makeplane/plane#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using password-based authentication, the Forgot Password link on the signin page does not lead to a password reset form, but rather is treated as a workspace slug and Plane displays a page showing I do not have access to the (non-existent) forgot-password workspace.

### Steps to reproduce

1. Self-host plane without OAuth authentication
2. Click the Forgot Password link on the signin page

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hey @Web-eWorks, 
Thanks for reporting this issue we will fix this in upcoming releases.

**Comment by pablohashescobar** [comment]
Hello @Web-eWorks! We have successfully addressed the problem in the latest Docker setup update. The fix has been implemented, thanks to your valuable feedback. We appreciate your patience. If you have any further questions or encounter any other concerns, please don't hesitate to reach out. Thank you once again for helping us improve Plane.
