### ISSUE TITLE
[bug]: New users cannot be added when not using OAuth

### ISSUE THREAD

**Issue by Web-eWorks** [makeplane/plane#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When not using OAuth-based authentication methods while self-hosting Plane, users cannot create a new email+password based account.

When inviting a user who does not have an account on the running Plane instance, accepting the invite internally marks the invite link as "accepted", but takes them to the signin page rather than allowing them to create a new account. This results in a member entry on the workspace settings page marked as "activated", but which no person can actually log into.

I expect that at the very least, specifically-invited users can create a new email+password based account as part of the join-workspace flow.

### Steps to reproduce

1. Self-host Plane without OAuth-based authentication
2. Observe no way to create new account from the `/signin` page
3. Invite a user via email who has no account on the Plane instance
4. User clicks through the invite and clicks accept
5. Redirected to `/signin` page, invite cannot be used again
6. No way to create an account to accept the invite

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hello @Web-eWorks! Thank you for bringing this to our attention. We want to assure you that we are actively working on updating the onboarding setup specifically for self-hosted users. Our team is dedicated to resolving this issue promptly, and we anticipate having a fix in place soon. We appreciate your patience and understanding during this process. If you have any further questions or concerns, please feel free to reach out. Thank you for your valuable feedback!

**Comment by pablohashescobar** [comment]
Hi there! In the current version of Plane, you have the ability to invite users to your workspace. When you invite a user, a User account is created with a random dummy password. Upon receiving the invitation, the user will need to reset their password and log in to Plane. This process is facilitated through the 'forgot password' workflow.

It's important to note that this functionality is designed to work when signups are disabled using the ENABLE_SIGNUP environment variable. If signups are enabled, the invited user can join the workspace during the onboarding process while signing up.

We consider this issue resolved based on the recent fix. However, if you encounter any further difficulties during the onboarding process or have additional concerns, please feel free to reopen the issue. We'll be more than happy to assist you further. Thank you!
